@testitem "007_filter_by_substring_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "007_filter_by_substring.jl"))
    @test filter_by_substring(["banana", "apple", "kiwi", "peach"],"a") == ["banana", "apple", "peach"]
    @test filter_by_substring(["hello", "world", "python", "numpy", "pandas"],"py") == ["python", "numpy"]
    @test filter_by_substring(String[],"") == String[]
    @test filter_by_substring(["abc", "bcd", "cbd", "dbc", "cda"],"bc") == ["abc", "bcd", "dbc"]
    @test filter_by_substring(["a", "ab", "abc", "abcd", "abcde", "bcde", "cde"],"cd") == ["abcd", "abcde", "bcde", "cde"]
    @test filter_by_substring(["123", "456", "789", "101112"],"12") == ["123", "101112"]
    @test filter_by_substring(["cat", "dog", "elephant", "rhinoceros", "seagull"],"e") == ["elephant", "rhinoceros", "seagull"]
    @test filter_by_substring(["supercalifragilisticexpialidocious", "antidisestablishmentarianism", "floccinaucinihilipilification"],"ili") == ["supercalifragilisticexpialidocious", "floccinaucinihilipilification"]
    @test filter_by_substring(["moon", "stars", "sun", "planets"],"s") == ["stars", "sun", "planets"]
    @test filter_by_substring(["earth", "mars", "jupiter", "saturn", "uranus"],"s") == ["mars", "saturn", "uranus"]
    @test filter_by_substring(["hello", "world", "python", "numpy", "pandas", "numpy"],"py") == ["python", "numpy", "numpy"]
    @test filter_by_substring(["supercalifragilisticexpialidocious", "antidisestablishmentarianism", "floccinaucinihilipilification", "floccinaucinihilipilificatnion"],"ili") == ["supercalifragilisticexpialidocious", "floccinaucinihilipilification", "floccinaucinihilipilificatnion"]
    @test filter_by_substring(["hello", "world", "python", "numpy", "pandas"],"antidisestablishmentarianismpy") == String[]
    @test filter_by_substring(["supercalifragilisticexpialidocious", "antidisestablishmentarianism", "floccinaucinihilipilification", "floccinaucinihilipilificatnion"],"ili12") == String[]
    @test filter_by_substring(["supercalifragilisticexpialidocious", "antidisesshmentarianism", "floccinaucinihilipilification", "floccinaucinihilipilificatnion", "floccinaucinihilipilificatilinion"],"ili") == ["supercalifragilisticexpialidocious", "floccinaucinihilipilification", "floccinaucinihilipilificatnion", "floccinaucinihilipilificatilinion"]
    @test filter_by_substring(["supercalifragilisticexpialidocious", "sun", "floccinaucinihilipilificatioearthn"],"ili") == ["supercalifragilisticexpialidocious", "floccinaucinihilipilificatioearthn"]
    @test filter_by_substring(["123", "456", "789", "101112"],"122") == String[]
    @test filter_by_substring(["supercalifragilisticexpialidocious", "antidisestablishementarianism", "floccinaucinihilipilification"],"ili") == ["supercalifragilisticexpialidocious", "floccinaucinihilipilification"]
    @test filter_by_substring(["abc", "bcd", "cbd", "dbc", "cda", "cfloccinaucinihilipilificatilinionda"],"bc") == ["abc", "bcd", "dbc"]
    @test filter_by_substring(["earth", "mars", "jupiter", "saturn", "uranus"],"numpuranusys") == String[]
    @test filter_by_substring(["supercalifragilisticexpialidocious", "antidisestablishementarianism", "floccinaucinihilipilification", "supercalifragilisticexpialidocious"],"ili") == ["supercalifragilisticexpialidocious", "floccinaucinihilipilification", "supercalifragilisticexpialidocious"]
    @test filter_by_substring(["hello", "world", "python", "numpy", "pandas"],"antidisestablishmentariasaturnnismpy") == String[]
    @test filter_by_substring(["supercalifragilisticexpialidocious", "antidisesshmentarianism", "floccinaucinihilipilification", "floccinaucinihilipilificatnion", "floccinaucinihilipilificatilinion", "floccinaucinihilipilifi101112cation"],"ili") == ["supercalifragilisticexpialidocious", "floccinaucinihilipilification", "floccinaucinihilipilificatnion", "floccinaucinihilipilificatilinion", "floccinaucinihilipilifi101112cation"]
    @test filter_by_substring(["supercalifragilisticexpialidocious", "antidisestablishmentarianism", "floccinaucinihilipilification", "floccinaucinihilipilificatnion"],"floccinaucinihilipilificatioearthn") == String[]
    @test filter_by_substring(["hello", "world", "python", "numpy", "s"],"antidisestablishmentariasaturnnismpy") == String[]
    @test filter_by_substring(["hello", "world", "python", "numpy"],"antidisestablishmentarianismpy") == String[]
    @test filter_by_substring(["antidisesshmentarianism", "floccinaucinihilipilification", "floccinaucinihilipilificatnion", "floccinaucinihilipilificatilinion"],"ili") == ["floccinaucinihilipilification", "floccinaucinihilipilificatnion", "floccinaucinihilipilificatilinion"]
    @test filter_by_substring(["hello", "world", "python", "numpy", "pandas", "numpy"],"antidisestablishmentarianismpy") == String[]
    @test filter_by_substring(["abc", "bcd", "cbd", "dbc", "cda", "cfloccinaucinihilipilificatilinionda", "dcbd"],"bbc") == String[]
    @test filter_by_substring(["abc", "bcd", "cbd", "dbc", "cda", "cfloccinaucinihilipilificatilinionda", "dcbd", "cfloaccinaucinihilipilificatilinionda"],"bbc") == String[]
    @test filter_by_substring(["123", "456", "789", "101112", "456"],"12") == ["123", "101112"]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami"],"an") == ["San Francisco"]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"ox") == ["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs"]
    @test filter_by_substring(["The cat in the hat", "Green eggs and ham", "One fish two fish", "Red fish blue fish"],"fish") == ["One fish two fish", "Red fish blue fish"]
    @test filter_by_substring(["The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Lord of the Rings", "Star Wars", "Inception", "Forrest Gump"],"he") == ["The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Lord of the Rings"]
    @test filter_by_substring(["abcdefg"],"") == ["abcdefg"]
    @test filter_by_substring(["abc(d)e", "ba%cd", "cde", "array", "12345"],"(d)") == ["abc(d)e"]
    @test filter_by_substring(["wsrefgtrh", "zxyvtru", "asxwaqzx", "kjbncxz"],"tr") == ["wsrefgtrh", "zxyvtru"]
    @test filter_by_substring(["The Shawshank Redemption", " The Godfather ", "The Dark Knight", "  The Lord of the Rings   ", "   Star Wars", " Inception     ", "Forrest Gump"]," ") == ["The Shawshank Redemption", " The Godfather ", "The Dark Knight", "  The Lord of the Rings   ", "   Star Wars", " Inception     ", "Forrest Gump"]
    @test filter_by_substring(["The Shawshank Redemption", " The Godfather ", "The Dark Knight", "  The Lord of the Rings   ", "   Star Wars", " Inception     ", "Forrest Gump", " Inception     "]," ") == ["The Shawshank Redemption", " The Godfather ", "The Dark Knight", "  The Lord of the Rings   ", "   Star Wars", " Inception     ", "Forrest Gump", " Inception     "]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"an") == ["San Francisco"]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami"],"York") == ["New York City"]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"oConstitutionx") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz"],"created") == String[]
    @test filter_by_substring(["Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz"],"creeated") == String[]
    @test filter_by_substring(["abcdefg"],"universally") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz"],"creataed") == String[]
    @test filter_by_substring(["abcdefg", "abcdefg"],"universally") == String[]
    @test filter_by_substring(["Washington", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"nan") == String[]
    @test filter_by_substring(["Washington", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"nan") == String[]
    @test filter_by_substring(["Washington", "The cat in the hat", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"nation,") == String[]
    @test filter_by_substring(["Washington", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"nabc(d)e") == String[]
    @test filter_by_substring(["abcdeits"],"universally") == String[]
    @test filter_by_substring(["abcdefg", "abcdefg"],"upromoteniversally") == String[]
    @test filter_by_substring(["The cat in the hat", "Green eggs and ham", "One fish two fish", "Red fish blue fish"],"ffis") == String[]
    @test filter_by_substring(["Washington", "New York City", "Los Angeles", "San Francisco", "Miami", "Washington"],"nabc(d)e") == String[]
    @test filter_by_substring(["abcdefg", "abcdefg", "abcdefg"],"universally") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"oConstituti") == String[]
    @test filter_by_substring(["Washington", "New York Ciity", "The cat in the hat", "New York City", "Boston", "Los Angeles", "Miami", "Washington"],"nation,") == String[]
    @test filter_by_substring(["Pack my box with five dozen liqugor jugs", "The quick brown fox jumps ove  zy dog", "The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz"],"created") == String[]
    @test filter_by_substring(["Washington", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"want") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Pack my box with five dozen lisevenquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"ox") == ["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Pack my box with five dozen lisevenquor jugs"]
    @test filter_by_substring(["The q uick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"oConstitutionx") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "San Francisco", "Pack my box with five dozen liquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"oConstitutionx") == String[]
    @test filter_by_substring(String[],"It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Pack my box with five dozen lisevenquor jugs", "forth", "Jackdaws love my big sphinx of quartz"],"ox") == ["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Pack my box with five dozen lisevenquor jugs"]
    @test filter_by_substring(["Washington", "New York City", "Los Angeles", "San Francisco", "zebras", "Washington"],"nabc(d)e") == String[]
    @test filter_by_substring(String[],"universally") == String[]
    @test filter_by_substring(["Washington", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington", "Miami"],"want") == String[]
    @test filter_by_substring(["Washington", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"New York Citywant") == String[]
    @test filter_by_substring(String[],"Star") == String[]
    @test filter_by_substring(["The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Lord of the Rings", "Star Wars", "Inception", "universally"],"he") == ["The Shawshank Redemption", "The Godfather", "The Dark Knight", "The Lord of the Rings"]
    @test filter_by_substring(["Washington", "cRedemptionread", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"nation,") == String[]
    @test filter_by_substring(["abcgdefg", "aasxwaqzxbcdefg", "want", "abcdefg", "abcdefg", "abcdefg"],"universally") == String[]
    @test filter_by_substring(["Washington", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"New York Citywan") == String[]
    @test filter_by_substring(["Washington", "New York City", "nWashington", "Los Angeles", "San Francisco", "zebras", "Washington"],"nabc(d)e") == String[]
    @test filter_by_substring(["abcdeits"],"fortune,") == String[]
    @test filter_by_substring(["B\"Weoston", "Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami"],"York") == ["New York City"]
    @test filter_by_substring(["abcgdefg", "aasxwaqzxbcdefg", "want", "abcdefg", "abcdefg", "abcdefg"],"box") == String[]
    @test filter_by_substring(["peoplbige", "abcdefg", "abcdefg"],"universally") == String[]
    @test filter_by_substring(["Pack my box with five dozen liqugor jugs", "The quick brown fkjbncxzox jumps ove  zy dog", "The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz", "Jackdaws love my big sphinx of quartz"],"createdd") == String[]
    @test filter_by_substring(["We the people of the United States of America, in order to form a more perfect union, establish justice, insure domestic tranquility, provide for the common defense, promote the general welfare, and secure the blessings of liberty to ourselves and our posterity, do ordain and establish this Constitution for the United States of America.", "To be or not to be, that is the question.", "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", "I have a dream that one day this nation will rise up and live out the true meaning of its creed: \"We hold these truths to be self-evident, that all men are created equal.\"", "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal."],"Citywan") == String[]
    @test filter_by_substring(["The Shawshank Redemption", " The Godfather ", "The Dark Knight", "  The Lord of the Rings   ", "   Star Wars", " Inception     ", "Forrest Gump"],"nation") == String[]
    @test filter_by_substring(["Washington", "DC", "New York City", "ton", "Boston", "Los Angeles", "San Francisco", "Miami"],"York") == ["New York City"]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz"],"tthese") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "San Francisco", "Pack my box with five dozen liquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"oConstitStar Warsutionx") == String[]
    @test filter_by_substring(["Washington", "New York City", "Los Angeles", "San Francisco", "Miami", "Washington"],"nab(((The Dark Knightdthese)cc(d)e") == String[]
    @test filter_by_substring(["Washington", "New York City", "San Francisco", "Miami", "New York Cicreateddty", "Washington", "New York Cicreateddty"],"nabc(d)e") == String[]
    @test filter_by_substring(["Washington", "MMiami", "New York City", "San Francisco", "Miami", "New York Cicreateddty", "Washington", "New York Cicreateddty"],"nabc(d)e") == String[]
    @test filter_by_substring(["an", "abcdeits"],"universally") == String[]
    @test filter_by_substring(["The Shawshank Redemption", " The Godfather ", "The Dark Knight", "  The Lord of the Rings   ", "   Star Wars", " Inception     ", "Forrest Gump"]," l.") == String[]
    @test filter_by_substring(["We the people of the United States of America, in order to form a more perfect union, establish justice, insure domestic tranquility, provide for the common defense, promote the general welfare, and secure the blessings of liberty to ourselves and our posterity, do ordain and establish this Constitution for the United States oef America.", "To be or not to be, that is the question.", "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", "I have a dream that one day this nation will rise up and live out the true meaning of its creed: \"We hold these truths to be self-evident, that all men are created equal.\"", "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal."],"City") == String[]
    @test filter_by_substring(["th"],"(((The Dark Knightdtmeaninghese)") == String[]
    @test filter_by_substring(["abcdefg", "abcdefg", "abcdefg"],"univerhavely") == String[]
    @test filter_by_substring(["daft", "UEZ", "(((The Dark Knightdthese)", "of", "New York Ciitypcerfefct"],"RRed fish blue fish") == String[]
    @test filter_by_substring(["Pack my box with five dozen liqugor jugs", "The quick brown fkjbncxzox jumps ove  zy dog", "The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz"],"The quick b over the lazy dog") == String[]
    @test filter_by_substring(["The quick brown fox jumps ove  zy dog", "The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz", "The quick brown fox jumps ove  zy dog"],"oxx") == String[]
    @test filter_by_substring(["Washington", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington", "Miami"],"daft") == String[]
    @test filter_by_substring(["Pack my box with five dozen liqugor jugs", "The quick brown fox jumps ove  zy dog", "The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Redemption"],"created") == String[]
    @test filter_by_substring(["Washington", "Boston", "Los Angeles", "San Francisco", "Miami", "Washington"],"nann") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz", "Pack my box with five dozen liquor jugs"],"createt") == String[]
    @test filter_by_substring(["Washington", "MMiami", "New York City", "San Francisco", "Miami", "New York Cicreateddty", "Washington", "New York Cicreateddty"],"nabc)e") == String[]
    @test filter_by_substring(["The Shawshank Redemption", "The Godfather", "The Lord of the Rings", "Star Wars", "Inception", "Forrest Gump"],"he") == ["The Shawshank Redemption", "The Godfather", "The Lord of the Rings"]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Pack my box with five dozen lisevenquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"quiickox") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz"],"propmtr") == String[]
    @test filter_by_substring(["The quick brown fox jumps over tPacFour score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are crzyeated equal.he lazy dog", "San Francisco", "Pack my box with five dozen liquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"oConstittutionx") == String[]
    @test filter_by_substring(["Thee quick brown fox jumps ove  zy dog", "The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "Jackdaws love my big sphinx of quartz", "The quick brown fox jumps ove  zy dog"],"oxxNew York Citywan") == String[]
    @test filter_by_substring(String[],"abc") == String[]
    @test filter_by_substring(String[],"substring") == String[]
    @test filter_by_substring(["", "", ""],"substring") == String[]
    @test filter_by_substring(["substring", "substring", "substring"],"substring") == ["substring", "substring", "substring"]
    @test filter_by_substring(["string", "bingo", "frost", "parka"],"substring") == String[]
    @test filter_by_substring(["", "", ""],"") == ["", "", ""]
    @test filter_by_substring(["", "a", "", "b"],"") == ["", "a", "", "b"]
    @test filter_by_substring([""],"") == [""]
    @test filter_by_substring(["abc", "bcd", "cde", "def"],"a") == ["abc"]
    @test filter_by_substring(["The Godfather", "The Dark Knight", "The Lord of the Rings", "Star Wars", "posterity,", "Forrest Gump"],"he") == ["The Godfather", "The Dark Knight", "The Lord of the Rings"]
    @test filter_by_substring(["abcdefg"],"form") == String[]
    @test filter_by_substring(String[],"Green") == String[]
    @test filter_by_substring(["The quick brown fox jumps over the lazy dog", "Pack my box with five dozen liquor jugs", "How vexingly quick daft zebras jump", "Jackdaws love my big sphinx of quartz"],"tranquility,ox") == String[]
    @test filter_by_substring(["abcdefg"],"fom") == String[]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami"],"liberty") == String[]
    @test filter_by_substring(["The Godfather", "The Dark Knight", "The Lord of the Rings", "union,", "posterity,", "Forrest Gump", "union,"],"h") == ["The Godfather", "The Dark Knight", "The Lord of the Rings"]
    @test filter_by_substring(["abcdefg", "abcdefg"],"m") == String[]
    @test filter_by_substring(["fom", "abcdefg"],"fom") == ["fom"]
    @test filter_by_substring(["We the people of the United States of America, in order to form a more perfect union, establish justice, insure domestic tranquility, provide for the common defense, promote the general welfare, and secure the blessings of liberty to ourselves and our posterity, do ordain and establish this Constitution for the United States of America.", "To be or not to be, that is the question.", "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", "I have a dream that one day this nation will rise up and live out the true meaning of its creed: \"We hold these truths to be self-evident, that all men are created equal.\"", "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal."],"eqal.") == String[]
    @test filter_by_substring(["abcdbefg"],"form") == String[]
    @test filter_by_substring(["abbcdefg", "fom", "abcdefg"],"fom") == ["fom"]
    @test filter_by_substring(["The Shawshank Redemption", "The Godfather", "The Dark Knight", "Star Wars", "Inception", "Forrest Gump"],"he") == ["The Shawshank Redemption", "The Godfather", "The Dark Knight"]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami"],"libertequal.y") == String[]
    @test filter_by_substring(["The Shawshank Redemption", " The Godfather ", "The Dark Knight", "  The Lord of the Rings   ", "   Star Wars", " Inception     ", "Forrest Gump"],"Angeles") == String[]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "New York City"],"an") == ["San Francisco"]
    @test filter_by_substring(["The Godfather", "The Dark Knight", "The Lord of the Rings", "Star Wars", "posterity,", "Forrest Gump"],"h") == ["The Godfather", "The Dark Knight", "The Lord of the Rings"]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "San Francisco", "Miami"],"libertequal.y") == String[]
    @test filter_by_substring(["abcdefg"],"fofm") == String[]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "New York City"],"aan") == String[]
    @test filter_by_substring(["The Shawshank Redemption", "The Godfather", "The Dark Knight", "Star Wars", "Inception", "Forrest Gump"],"hhe") == String[]
    @test filter_by_substring(["abbcdefg", "fom", "abcdefg", "abbcdefg"],"fom") == ["fom"]
    @test filter_by_substring(["abcdefg", "abcdefg"],"To be or not to be, that is the question.") == String[]
    @test filter_by_substring(["The Godfatosacknowlledged,phinxxher", "The Dark Knight", "The Lord of the Rings", "union,", "tranquility,oxunion,", "posterity,", "Forrest Gump", "union,"],"h") == ["The Godfatosacknowlledged,phinxxher", "The Dark Knight", "The Lord of the Rings"]
    @test filter_by_substring(["osafortune,cknowlledged,p", "abcdefg", "abcdefg"],"fom") == String[]
    @test filter_by_substring(["The Shawshank Redemption", "The Godfather", "justice,The Dark Knight", "The Lord of the Rings", "and", "Inception", "Forrest Gump"],"he") == ["The Shawshank Redemption", "The Godfather", "justice,The Dark Knight", "The Lord of the Rings"]
    @test filter_by_substring(["abc(d)e", "ba%cd", "cde", "array", "12345"],"dozen") == String[]
    @test filter_by_substring(["The Godfather", "The Dark Knight", "DCt", "The Lord of the Rings", "union,", "posterity,", "Forrest Gump", "union,"],"h") == ["The Godfather", "The Dark Knight", "The Lord of the Rings"]
    @test filter_by_substring(["osafortune,cknowlledged,p", "abcdefg"],"fom") == String[]
    @test filter_by_substring(["wsrefgtrh", "zxyvtru", "asxwaqzx", "zxyvtConstitutionru", "kjbncxz"],"tr") == ["wsrefgtrh", "zxyvtru"]
    @test filter_by_substring(["kQEHdzw", "for", "asxwaqzx", "  The Lord of the Rings   ", "Mi", "its", "kZWuN"],"Green") == String[]
    @test filter_by_substring(["abc(d)e", "ba%cd", "cde", "array", "12345", "12345"],"Saabc(d)en") == String[]
    @test filter_by_substring(["abc(d)e", "ba%cd", "cde", "array", "dog"],"doquartuzzen") == String[]
    @test filter_by_substring(["The Shawshank Redemption", "The Godfather", "justice,The Dark Knight", "The Lord of the Rings", "and", "Inception", "Forrest Gump"],"hhate") == String[]
    @test filter_by_substring(["Washinestablishon", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "New York City"],"an") == ["San Francisco"]
    @test filter_by_substring(["abcdefg"],"rtr") == String[]
    @test filter_by_substring(["The Dark Knight", "The Lord of the Rings", "union,", "posterity,", "Forrest Gump", "union,"],"h") == ["The Dark Knight", "The Lord of the Rings"]
    @test filter_by_substring(["The Godfatosacknowlledged,phinxxher", "The Dark Knight", "The Lord of the Rings", "union,", "tranquility,oxunion,", "posterity,", "Forrest Gump", "union,"],"ourselvesh") == String[]
    @test filter_by_substring(["Washinestablishon", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "New York City"],"aan") == String[]
    @test filter_by_substring(["We the people of the United States of America, in order to form a more perfect union, establish justice, insure domestic tranquility, provide for the common defense, promote the general welfare, and secure the blessings of liberty to ourselves and our posterity, do ordain and establish this Constitution for the United States of America.", "To be or not to be, that is the question.", "It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.", "I have a dream that one day this nation will rise up and live out the true meaning of its creed: \"We hold these truths to be self-evident, that all men are created equal.\"", "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal."],"eqal.osacknsowlledged,phinxx") == String[]
    @test filter_by_substring(["Washinestablishon", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "DCC", "New York City"],"an") == ["San Francisco"]
    @test filter_by_substring(["fI have a dream that one day this nation will rise up and live out the true meaning of its creed: \"We hold these truths to be self-evident, that all men are created equal.\"om", "abcdefg"],"fom") == String[]
    @test filter_by_substring(["We the people of the United States of America, in order to form a more perfect union, establish justice, insure domestic tranquility, provide for the common defense, promote the general welfare, and secure the blessings of liberty to ourselves and our posterity, do ordain and establish this Constitution for the United States of America.", "To be or not to be, that is the question.", "I have a dream that one day this nation will rise up and live out the true meaning of its creed: \"We hold these truths to be self-evident, that all men are created equal.\"", "Four score and seven years ago our fathers brought forth on this continent, a new nation, conceived in Liberty, and dedicated to the proposition that all men are created equal."],"eqal.") == String[]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami"],"nan") == String[]
    @test filter_by_substring(["Washinestablishon", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami", "DCC", "New York City"],"Guoxxplibertequal.yan") == String[]
    @test filter_by_substring(String[],"form") == String[]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami"],"tranquility,oxunion,doquartuzzen") == String[]
    @test filter_by_substring(["Washington", "DC", "New York CitYy", "Boston", "Los Angeles", "San Francisco", "Miami"],"liberty") == String[]
    @test filter_by_substring(["abcdefg", "abcdefg"],"To be or not to be,  that is the question.") == String[]
    @test filter_by_substring(["The Godfather", "The Dark Knight", "The Lord of the Rings", "union,", "pyeathesersrity,", "Forrest Gump", "union,"],"h") == ["The Godfather", "The Dark Knight", "The Lord of the Rings", "pyeathesersrity,"]
    @test filter_by_substring(["The Shawshank Redemption", "The Godfather", "justice,The Dark Knight", "The Lord of the Rings", "and", "Inception", "Forrest Gump"],"hhatethThe") == String[]
    @test filter_by_substring(["The Shawshank Redemption", "To be or not to be, that is the quesetion. Godfather", "The Godfather", "justice,The Dark Knight", "The Lord of the Rings", "and", "Inception", "Forrest Gump"],"hhatetmyhThe") == String[]
    @test filter_by_substring(["osafortune,cknowlledged,p", "abcdefg", "orm", "abcdefg"],"fom") == String[]
    @test filter_by_substring(["Washington", "DC", "New York City", "Boston", "Los Angeles", "San Francisco", "Miami"],"tranquility,oxunion,doquartuzLoszen") == String[]
end
