@testitem "019_sort_numbers_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "019_sort_numbers.jl"))
    @test sort_numbers("four eight two") == "two four eight"
    @test sort_numbers("nine") == "nine"
    @test sort_numbers("one six two four nine") == "one two four six nine"
    @test sort_numbers("two seven eight zero five") == "zero two five seven eight"
    @test sort_numbers("nine zero") == "zero nine"
    @test sort_numbers("seven three one") == "one three seven"
    @test sort_numbers("two two three three four five six") == "two two three three four five six"
    @test sort_numbers("zero five four one seven eight two six") == "zero one two four five six seven eight"
    @test sort_numbers("nine eight seven six five four three two one zero") == "zero one two three four five six seven eight nine"
    @test sort_numbers("two zero nine four five six") == "zero two four five six nine"
    @test sort_numbers("nine eight seven six five four one zero") == "zero one four five six seven eight nine"
    @test sort_numbers("two zero nine") == "zero two nine"
    @test sort_numbers("four eight") == "four eight"
    @test sort_numbers("") == ""
    @test sort_numbers("zero five four one seven") == "zero one four five seven"
    @test sort_numbers("six") == "six"
    @test sort_numbers("two two four five six") == "two two four five six"
    @test sort_numbers("zero five four one") == "zero one four five"
    @test sort_numbers("zero five seven") == "zero five seven"
    @test sort_numbers("four two") == "two four"
    @test sort_numbers("four") == "four"
    @test sort_numbers("two six") == "two six"
    @test sort_numbers("two two five six") == "two two five six"
    @test sort_numbers("seven") == "seven"
    @test sort_numbers("zero five four zero five four one seven eight two six") == "zero zero one two four four five five six seven eight"
    @test sort_numbers("zero five one seven eight two six") == "zero one two five six seven eight"
    @test sort_numbers("four four eight two") == "two four four eight"
    @test sort_numbers("seven three") == "three seven"
    @test sort_numbers("nine eight seven five four three two one zero") == "zero one two three four five seven eight nine"
    @test sort_numbers("two four five six") == "two four five six"
    @test sort_numbers("zero four one") == "zero one four"
    @test sort_numbers("zero seven eight two six") == "zero two six seven eight"
    @test sort_numbers("zero five eight two six") == "zero two five six eight"
    @test sort_numbers("zero") == "zero"
    @test sort_numbers("three") == "three"
    @test sort_numbers("one six") == "one six"
    @test sort_numbers("nine six") == "six nine"
    @test sort_numbers("two seven eight five") == "two five seven eight"
    @test sort_numbers("two") == "two"
    @test sort_numbers("two three three four five six") == "two three three four five six"
    @test sort_numbers("zero five four seven") == "zero four five seven"
    @test sort_numbers("nine eight seven one zero") == "zero one seven eight nine"
    @test sort_numbers("four five six") == "four five six"
    @test sort_numbers("two nine") == "two nine"
    @test sort_numbers("two two three") == "two two three"
    @test sort_numbers("nine eight seven six five two one zero") == "zero one two five six seven eight nine"
    @test sort_numbers("zero five six") == "zero five six"
    @test sort_numbers("zero five") == "zero five"
    @test sort_numbers("zero five two six") == "zero two five six"
    @test sort_numbers("zero five four zero four one seven eight two six") == "zero zero one two four four five six seven eight"
    @test sort_numbers("four eight two two three") == "two two three four eight"
    @test sort_numbers("five four one seven eight two six") == "one two four five six seven eight"
    @test sort_numbers("nine seven six five two one zero") == "zero one two five six seven nine"
    @test sort_numbers("nine eight seven six zero") == "zero six seven eight nine"
    @test sort_numbers("two nine seven six five two one zero") == "zero one two two five six seven nine"
    @test sort_numbers("two four six") == "two four six"
    @test sort_numbers("nine one zero") == "zero one nine"
    @test sort_numbers("four six") == "four six"
    @test sort_numbers("zero five four") == "zero four five"
    @test sort_numbers("zero two six") == "zero two six"
    @test sort_numbers("zero five one") == "zero one five"
    @test sort_numbers("nine six five two one zero") == "zero one two five six nine"
    @test sort_numbers("two nine eight seven six five four one zero") == "zero one two four five six seven eight nine"
    @test sort_numbers("zero four one seven") == "zero one four seven"
    @test sort_numbers("two zero nine four zero four one") == "zero zero one two four four nine"
    @test sort_numbers("one zero five six") == "zero one five six"
    @test sort_numbers("nine seven six five two zero") == "zero two five six seven nine"
    @test sort_numbers("two nine eight seven six five four one zero one zero") == "zero zero one one two four five six seven eight nine"
    @test sort_numbers("two nine seven six five two one zero five two six") == "zero one two two two five five six six seven nine"
    @test sort_numbers("one") == "one"
    @test sort_numbers("nine eight seven five four three two one") == "one two three four five seven eight nine"
    @test sort_numbers("two seven") == "two seven"
    @test sort_numbers("nine eight seven six") == "six seven eight nine"
    @test sort_numbers("zero five one seven six") == "zero one five six seven"
    @test sort_numbers("nine one zero five four one seven eight two six") == "zero one one two four five six seven eight nine"
    @test sort_numbers("zero two") == "zero two"
    @test sort_numbers("two four zero four one") == "zero one two four four"
    @test sort_numbers("zero five four zero five four one seven") == "zero zero one four four five five seven"
    @test sort_numbers("two two four five") == "two two four five"
    @test sort_numbers("zero one seven eight two six") == "zero one two six seven eight"
    @test sort_numbers("nine two six") == "two six nine"
    @test sort_numbers("nine one zero five four one six") == "zero one one four five six nine"
    @test sort_numbers("two two seven eight zero five four five six") == "zero two two four five five six seven eight"
    @test sort_numbers("two four zero four") == "zero two four four"
    @test sort_numbers("two zero six") == "zero two six"
    @test sort_numbers("two three") == "two three"
    @test sort_numbers("two nine seven six five two one zero four five six") == "zero one two two four five five six six seven nine"
    @test sort_numbers("nine six five two three three four five six one zero") == "zero one two three three four five five six six nine"
    @test sort_numbers("nine eight one zero") == "zero one eight nine"
    @test sort_numbers("two four") == "two four"
    @test sort_numbers("four two nine eight seven six five four one zero") == "zero one two four four five six seven eight nine"
    @test sort_numbers("two two") == "two two"
    @test sort_numbers("nine seven six five two one") == "one two five six seven nine"
    @test sort_numbers("one six two nine") == "one two six nine"
    @test sort_numbers("zero five four one seven eight six") == "zero one four five six seven eight"
    @test sort_numbers("nine seven four six") == "four six seven nine"
    @test sort_numbers("five six") == "five six"
    @test sort_numbers("two zero nine four one") == "zero one two four nine"
    @test sort_numbers("zero five four one eight two six") == "zero one two four five six eight"
    @test sort_numbers("nine one zero five four one") == "zero one one four five nine"
    @test sort_numbers("one two three four five six seven eight nine") == "one two three four five six seven eight nine"
    @test sort_numbers("nine eight seven six five four three two one") == "one two three four five six seven eight nine"
    @test sort_numbers("five seven eight six nine four zero two one three") == "zero one two three four five six seven eight nine"
    @test sort_numbers("four six nine eight seven one five zero two three") == "zero one two three four five six seven eight nine"
    @test sort_numbers("seven one zero five two four eight six nine three") == "zero one two three four five six seven eight nine"
    @test sort_numbers("zero one two three four five six seven eight nine") == "zero one two three four five six seven eight nine"
    @test sort_numbers("two four six eight zero one three five seven nine") == "zero one two three four five six seven eight nine"
    @test sort_numbers("nine seven five three one eight six four two zero") == "zero one two three four five six seven eight nine"
    @test sort_numbers("one zero three four two six five seven eight nine") == "zero one two three four five six seven eight nine"
    @test sort_numbers("seven five zero four nine eight two six one three") == "zero one two three four five six seven eight nine"
    @test sort_numbers("five") == "five"
    @test sort_numbers("eight") == "eight"
    @test sort_numbers("four six nine eight five zero two three") == "zero two three four five six eight nine"
    @test sort_numbers("one two three three") == "one two three three"
    @test sort_numbers("two nine eight seven six five four three two one seven nine") == "one two two three four five six seven seven eight nine nine"
    @test sort_numbers("zero one two five six seven eight nine") == "zero one two five six seven eight nine"
    @test sort_numbers("five four six nine eight seven one five zero two three two one three") == "zero one one two two three three four five five six seven eight nine"
    @test sort_numbers("nine eight seven six five four two one") == "one two four five six seven eight nine"
    @test sort_numbers("one two one four") == "one one two four"
    @test sort_numbers("one one one one one") == "one one one one one"
    @test sort_numbers("one two") == "one two"
    @test sort_numbers("four four two six nine two zero") == "zero two two four four six nine"
    @test sort_numbers("nine eight seven six five two three two one") == "one two two three five six seven eight nine"
    @test sort_numbers("nine eight seven two one") == "one two seven eight nine"
    @test sort_numbers("one zero three nine") == "zero one three nine"
    @test sort_numbers("nine eight") == "eight nine"
    @test sort_numbers("seven one zero five three") == "zero one three five seven"
    @test sort_numbers("zero two three") == "zero two three"
end
