@testitem "029_filter_by_prefix_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "029_filter_by_prefix.jl"))
    @test filter_by_prefix(String[],"") == String[]
    @test filter_by_prefix(["abc", "abcd", "abcde"],"abc") == ["abc", "abcd", "abcde"]
    @test filter_by_prefix(["xyz", "efg", "hij"],"a") == String[]
    @test filter_by_prefix(["cat", "dog", "bat"],"elephant") == String[]
    @test filter_by_prefix(["apple", "banana", "orange", "apricot", "kiwi"],"ap") == ["apple", "apricot"]
    @test filter_by_prefix(["a", "ab", "abc", "ba", "bb", "bc"],"a") == ["a", "ab", "abc"]
    @test filter_by_prefix(["zzz", "zzz", "zzz"],"z") == ["zzz", "zzz", "zzz"]
    @test filter_by_prefix(["hello", "world", "house"],"h") == ["hello", "house"]
    @test filter_by_prefix(["apple", "orange", "banana"],"b") == ["banana"]
    @test filter_by_prefix(["python", "java", "javascript", "c++"],"java") == ["java", "javascript"]
    @test filter_by_prefix(["hello", "world", "heworldlo", "house"],"h") == ["hello", "heworldlo", "house"]
    @test filter_by_prefix(["cat", "dog"],"apricot") == String[]
    @test filter_by_prefix(["hello", "world", "heworldlo", "house"],"hh") == String[]
    @test filter_by_prefix(["hah"],"hah") == ["hah"]
    @test filter_by_prefix(["world", "heworldlo", "house"],"h") == ["heworldlo", "house"]
    @test filter_by_prefix(["apple", "banana", "orange", "apricot", "kiwi"],"a") == ["apple", "apricot"]
    @test filter_by_prefix(["apricot"],"apricot") == ["apricot"]
    @test filter_by_prefix(["orange"],"apicapot") == String[]
    @test filter_by_prefix(["aa"],"a") == ["aa"]
    @test filter_by_prefix(["aaa"],"heworldlo") == String[]
    @test filter_by_prefix(["hello", "world", "house"],"") == ["hello", "world", "house"]
    @test filter_by_prefix(["kiwi"],"z") == String[]
    @test filter_by_prefix(["hello", "world"],"") == ["hello", "world"]
    @test filter_by_prefix(["zz"],"z") == ["zz"]
    @test filter_by_prefix(["oapricot"],"apricot") == String[]
    @test filter_by_prefix(["hello", "world", "house"],"hh") == String[]
    @test filter_by_prefix(["apple", "orange", "hello"],"bananab") == String[]
    @test filter_by_prefix(["aaaajavascript"],"aaaa") == ["aaaajavascript"]
    @test filter_by_prefix([""],"") == [""]
    @test filter_by_prefix(["apriccot"],"apricot") == String[]
    @test filter_by_prefix(["xyz", "efg", "hij", "hij"],"aaaajavascript") == String[]
    @test filter_by_prefix(["apple", "orange", "banana"],"heworldlo") == String[]
    @test filter_by_prefix([""],"aa") == String[]
    @test filter_by_prefix(["aaaajavascript"],"aaaajavascript") == ["aaaajavascript"]
    @test filter_by_prefix(["zzbb"],"zz") == ["zzbb"]
    @test filter_by_prefix(["a", "ab", "abc", "ba", "bb", "bc"],"banana") == String[]
    @test filter_by_prefix(["aboapricot"],"boapricot") == String[]
    @test filter_by_prefix(["kiwwi"],"z") == String[]
    @test filter_by_prefix(["aboapricot"],"aboapricot") == ["aboapricot"]
    @test filter_by_prefix(["boaprictot"],"boapricot") == String[]
    @test filter_by_prefix(["java"],"java") == ["java"]
    @test filter_by_prefix(["apple", "orange", "baanana"],"z") == String[]
    @test filter_by_prefix(["zzbbb"],"zjavascriptz") == String[]
    @test filter_by_prefix(["zzz"],"apicapoot") == String[]
    @test filter_by_prefix(["oapricot"],"appricott") == String[]
    @test filter_by_prefix(["world", "hello", "world", "house"],"") == ["world", "hello", "world", "house"]
    @test filter_by_prefix(["jaava"],"java") == String[]
    @test filter_by_prefix(["world", "hello", "world"],"") == ["world", "hello", "world"]
    @test filter_by_prefix(["a", "ab", "abc", "ba", "bb", "aa", "bc"],"banana") == String[]
    @test filter_by_prefix(["hello", "heworldlo", "house"],"h") == ["hello", "heworldlo", "house"]
    @test filter_by_prefix(["a"],"a") == ["a"]
    @test filter_by_prefix(["python", "java", "javascript", "c++"],"javakiwwi") == String[]
    @test filter_by_prefix(["world", "house"],"h") == ["house"]
    @test filter_by_prefix(["hah"],"bc") == String[]
    @test filter_by_prefix(["aboapricot"],"boaipricot") == String[]
    @test filter_by_prefix(["jjava"],"java") == String[]
    @test filter_by_prefix(["hello", "worlwd", "worldwd", "world"],"orange") == String[]
    @test filter_by_prefix(["kiwi"],"kiwapriccotibanana") == String[]
    @test filter_by_prefix(["jaava"],"jaava") == ["jaava"]
    @test filter_by_prefix(["hahworldwd"],"hahworlhhdwd") == String[]
    @test filter_by_prefix(["elephant"],"hhh") == String[]
    @test filter_by_prefix(["boaprictotbb", "a", "ab", "abc", "ba", "bb", "aa", "bc"],"banana") == String[]
    @test filter_by_prefix(["world"],"apric") == String[]
    @test filter_by_prefix(["hello", "world"],"apriccot") == String[]
    @test filter_by_prefix(["hello", "bc", "world"],"") == ["hello", "bc", "world"]
    @test filter_by_prefix(["hhh"],"") == ["hhh"]
    @test filter_by_prefix(["hello", "aworlwdbcdworld"],"apriccot") == String[]
    @test filter_by_prefix(["bkiwirt"],"boaiprt") == String[]
    @test filter_by_prefix(["apple", "orange", "aboapricot", "banana"],"") == ["apple", "orange", "aboapricot", "banana"]
    @test filter_by_prefix(["world"],"java") == String[]
    @test filter_by_prefix(["oapricoelepohantt"],"apricot") == String[]
    @test filter_by_prefix(["b"],"b") == ["b"]
    @test filter_by_prefix(["zzbb"],"jaava") == String[]
    @test filter_by_prefix(["aboapricot"],"rboapricot") == String[]
    @test filter_by_prefix(["hello", "wdorld", "house"],"") == ["hello", "wdorld", "house"]
    @test filter_by_prefix(["hahoerange"],"bc") == String[]
    @test filter_by_prefix(["bopaprictot"],"boaprictot") == String[]
    @test filter_by_prefix(["harboapricothh"],"harboapricothh") == ["harboapricothh"]
    @test filter_by_prefix(["hhah"],"bc") == String[]
    @test filter_by_prefix(["orange"],"apicaptot") == String[]
    @test filter_by_prefix(["aboaprpythonicot"],"boaipricot") == String[]
    @test filter_by_prefix(["world"],"wworlwdorld") == String[]
    @test filter_by_prefix(["apriccot"],"") == ["apriccot"]
    @test filter_by_prefix(["house"],"zjavascriptz") == String[]
    @test filter_by_prefix(["zjavascriptz"],"house") == String[]
    @test filter_by_prefix(["kiwapcriccotibanana"],"kiwapriccotibanana") == String[]
    @test filter_by_prefix(["bananna"],"aboaprpythonicot") == String[]
    @test filter_by_prefix(["hahlworldwd"],"hahlworldwd") == ["hahlworldwd"]
    @test filter_by_prefix(["kiwapcriccotibanana"],"javva") == String[]
    @test filter_by_prefix(["zzz"],"apicaopoot") == String[]
    @test filter_by_prefix(["hello", "world", "heworldlo"],"h") == ["hello", "heworldlo"]
    @test filter_by_prefix(["aaa"],"aaaajavascript") == String[]
    @test filter_by_prefix(["h"],"h") == ["h"]
    @test filter_by_prefix(["apple"],"kiwapriccotibanana") == String[]
    @test filter_by_prefix(["zzbbb"],"hhah") == String[]
    @test filter_by_prefix(["aboapriczzbbbt"],"rboapricot") == String[]
    @test filter_by_prefix(["boaipricot"],"boaipricot") == ["boaipricot"]
    @test filter_by_prefix(["ap"],"aap") == String[]
    @test filter_by_prefix(["amy", "apple", "pams", "alligator", "maple", "mops"],"a") == ["amy", "apple", "alligator"]
    @test filter_by_prefix(["batman"],"superman") == String[]
    @test filter_by_prefix(["电影", "电子", "电话", "邮件"],"电") == ["电影", "电子", "电话"]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH"],"qwe") == ["qwerty", "qwertyuiop"]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"],"bu") == ["butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"]
    @test filter_by_prefix(["fgh", "Kilometer", "Gigabyte", "Kiwi", "jinx", "jujitsu", "Joyride", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "favicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forward", "forgive", "foliage"],"fi") == ["filter", "fiduciary", "fidelity", "film"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"],"a") == ["abc", "ab1c", "abc_", "abc1"]
    @test filter_by_prefix(["", " ", "\n", "\t", "a", "ab", "abc", "abcde"],"") == ["", " ", "\n", "\t", "a", "ab", "abc", "abcde"]
    @test filter_by_prefix(["apple", "banana", "cherry", "durian", "elderberry", "fig", "grape", "honeydew", "jujube", "kiwi", "lemon"],"e") == ["elderberry"]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa"],"c") == ["coffee", "cocoa"]
    @test filter_by_prefix(["qwe"],"qwe") == ["qwe"]
    @test filter_by_prefix(["qe"],"qwe") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock", "bulldog"],"buu") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa"],"") == ["water", "wine", "coffee", "tea", "beer", "cocoa"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "alphabet", "abc1", "1abc"],"a") == ["abc", "ab1c", "alphabet", "abc1"]
    @test filter_by_prefix(["", " ", "\n", "\t", "ab", "abc", "abcde"],"") == ["", " ", "\n", "\t", "ab", "abc", "abcde"]
    @test filter_by_prefix(["facetious"],"facetious") == ["facetious"]
    @test filter_by_prefix(["apple", "banana", "cherry", "durian", "elderberry", "fig", "applpe", "honeydew", "jujube", "kiwi", "lemon"],"e") == ["elderberry"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "电"],"a") == ["abc", "ab1c", "abc_", "abc1"]
    @test filter_by_prefix(["电影", "电子", "电话", "邮件", "电影"],"电") == ["电影", "电子", "电话", "电影"]
    @test filter_by_prefix(["bu"],"电影") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa"],"cfidelity") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc", "abc_"],"a") == ["abc", "ab1c", "abc_", "abc1", "abc_"]
    @test filter_by_prefix(["fgKilometerh"],"fgh") == String[]
    @test filter_by_prefix(["电影", "电子", "电话", "burdock", "电影"],"") == ["电影", "电子", "电话", "burdock", "电影"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电"],"a") == ["abc", "ab1c", "abc_", "abc1"]
    @test filter_by_prefix(["apple", "banana", "durian", "elderberry", "fig", "applpe", "honeydew", "jujube", "kiwi", "lemon", "durian"],"e") == ["elderberry"]
    @test filter_by_prefix(["Kilometfaulter"],"Kilometer") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "faceless", "bulge", "bulb", "bulldog", "burdock"],"bu") == ["butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"]
    @test filter_by_prefix(["Kilometer"],"Kilometer") == ["Kilometer"]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH"],"ASDFGH") == ["ASDFGH"]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampABCersand", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "faceless", "bulge", "bulb", "bulldog", "burdock"],"bu") == ["butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"]
    @test filter_by_prefix(["", "\n", "\t", "a", "ab", "abc", "abcde"],"ampABCersand") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "fiburgher", "business", "burrow", "build", "bully", "faceless", "bulge", "bulb", "bulldog", "burdock", "butter"],"bu") == ["butter", "budget", "buds", "bureaucracy", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock", "butter"]
    @test filter_by_prefix(["电子"],"aa") == String[]
    @test filter_by_prefix(["cfidelity"],"cfidelity") == ["cfidelity"]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa"],"apple") == String[]
    @test filter_by_prefix(["A SD FGH", "qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH", "ASDFGH"],"faceless") == String[]
    @test filter_by_prefix(["电子"],"mops") == String[]
    @test filter_by_prefix(["fgKilomkwieterh"],"fgKamputeeilomkiwieterh") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电"],"aa") == String[]
    @test filter_by_prefix(["", " ", "\nelderberry", "\t\t", "a", "ab", "abc", "abcde"],"") == ["", " ", "\nelderberry", "\t\t", "a", "ab", "abc", "abcde"]
    @test filter_by_prefix(["fgKilomkwieterh"],"fgKilomkwieterh") == ["fgKilomkwieterh"]
    @test filter_by_prefix(["buufaceless"],"buu") == ["buufaceless"]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock", "bulldog", "burdock"],"buu") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "as fgh", "ASD FGH"],"qwe") == ["qwerty", "qwertyuiop"]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH"],"ABC") == String[]
    @test filter_by_prefix(["qwe"],"qwwe") == String[]
    @test filter_by_prefix(["buamputeeu"],"buamputeeu") == ["buamputeeu"]
    @test filter_by_prefix(["qwwe"],"qwe") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa"],"cfacetious") == String[]
    @test filter_by_prefix(["qwe"],"elderberryqwe") == String[]
    @test filter_by_prefix(["qwetea"],"qamiablee") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电", "abc_"],"aa") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "application123", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电"],"aa") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "fiburgher", "business", "burrow", "build", "bully", "faceless", "bulge", "bulb", "bulldog", "burdock", "butter"],"cfidelity") == String[]
    @test filter_by_prefix(["amy", "apple", "pams", "applQWERTYUIOPe", "alligator", "maple", "mops"],"a") == ["amy", "apple", "applQWERTYUIOPe", "alligator"]
    @test filter_by_prefix(["abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc", "abc_"],"a") == ["abc", "ab1c", "abc_", "abc1", "abc_"]
    @test filter_by_prefix(["", " ", "\n", "\t", "ab", "abc", "abcde", " "],"") == ["", " ", "\n", "\t", "ab", "abc", "abcde", " "]
    @test filter_by_prefix(["f"],"f") == ["f"]
    @test filter_by_prefix(["", " ", "\n", "\t", "ab", "abc", "abcde", " ", "\t"],"") == ["", " ", "\n", "\t", "ab", "abc", "abcde", " ", "\t"]
    @test filter_by_prefix(["jujitsu"],"bully") == String[]
    @test filter_by_prefix(["f"]," ") == String[]
    @test filter_by_prefix(["abc1"],"abc1") == ["abc1"]
    @test filter_by_prefix(["foothills"],"jujitsu") == String[]
    @test filter_by_prefix(["fiburgher"],"facetious") == String[]
    @test filter_by_prefix(["电电话"],"电电话") == ["电电话"]
    @test filter_by_prefix(["电facetious"],"电") == ["电facetious"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电", "budget", "abc_"],"facade") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "asdfgh", "ASDFGH", "as fgh", "ASD FGH"],"AASDFGH") == String[]
    @test filter_by_prefix(["", "\n", "\t", "a", "ab", "abc", "abcde"],"buds") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc", "abc", "ab1c"],"QWERTYUIOP") == String[]
    @test filter_by_prefix(["abc1"],"abfanfare") == String[]
    @test filter_by_prefix(["123", "aabc1", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"],"a") == ["aabc1", "abc", "ab1c", "abc_", "abc1"]
    @test filter_by_prefix(["facade"],"facade") == ["facade"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "teea", "电"],"a") == ["abc", "ab1c", "abc_", "abc1"]
    @test filter_by_prefix(["cfacetious"],"") == ["cfacetious"]
    @test filter_by_prefix(["fgKilomkwieterhABC"],"fgKilofmkwieterhABC") == String[]
    @test filter_by_prefix(["qwbulldogetea"],"qwbulldogetea") == ["qwbulldogetea"]
    @test filter_by_prefix(["abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc", "abc_"],"aa") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1cabc", "abc", "ab1c"],"QWERTYUIOflabbergastedP") == String[]
    @test filter_by_prefix(["e"],"e") == ["e"]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh"],"ASDFGH") == ["ASDFGH"]
    @test filter_by_prefix(["", "\n", "\t", "a", "abbatman", "ab", "abc", "abcde"],"a电电话mpABCersand") == String[]
    @test filter_by_prefix(["Kilometer"],"pams") == String[]
    @test filter_by_prefix(["fgh", "Kilometer", "Gigabyte", "Kiwi", "jinx", "jujitsu", "Joyride", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "favicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forward", "forgive", "foliage"],"f") == ["fgh", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "favicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forward", "forgive", "foliage"]
    @test filter_by_prefix(["filmbu"],"bu") == String[]
    @test filter_by_prefix(["filmbu"],"") == ["filmbu"]
    @test filter_by_prefix(["alphabet"],"wPwhchT") == String[]
    @test filter_by_prefix(["qwe"],"buamputefaulteu") == String[]
    @test filter_by_prefix(["elderberryqwe"],"burgher") == String[]
    @test filter_by_prefix(["fgh", "Kilometer", "Gigabyte", "Kiwi", "jinx", "jujitsu", "Joyride", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "favicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forgive", "foliage", "foothills"],"f") == ["fgh", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "favicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forgive", "foliage", "foothills"]
    @test filter_by_prefix(["amy", "apple", "pams", "applQWERTYUIOPe", "alligator", "maple", "mops"],"") == ["amy", "apple", "pams", "applQWERTYUIOPe", "alligator", "maple", "mops"]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH"],"amy") == String[]
    @test filter_by_prefix(["qwertyuiop"],"") == ["qwertyuiop"]
    @test filter_by_prefix(["电电话"],"电foliage电话") == String[]
    @test filter_by_prefix(["电子"],"fgKilomkwieterh") == String[]
    @test filter_by_prefix(["QWERTYURIOP"],"QWERTYUIOP") == String[]
    @test filter_by_prefix(["ampoule"],"qwe") == String[]
    @test filter_by_prefix(["abbananac1"],"aabc1") == String[]
    @test filter_by_prefix(["forwaard"],"ambulance") == String[]
    @test filter_by_prefix(["", "\n", "\t", "a", "abbatman", "ab", "abc", "abcde", "abbatman"],"a电电话mpABCersand") == String[]
    @test filter_by_prefix(["asdfgh"],"abfanfare") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH"],"qwefacetious") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "application123", "amaze", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电"],"aa") == String[]
    @test filter_by_prefix(["电电话话"],"电电话") == ["电电话话"]
    @test filter_by_prefix(["aa"],"aa") == ["aa"]
    @test filter_by_prefix(["burghber"],"bur") == ["burghber"]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "wwine", "cocoa", "cocoa"],"film") == String[]
    @test filter_by_prefix(["bfilterurghber"],"buambulancer") == String[]
    @test filter_by_prefix(["c"],"c") == ["c"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1cabc", "abc", "ab1c"],"QWERTYUIOflabberrgastedP") == String[]
    @test filter_by_prefix(["abc1buds"],"buds") == String[]
    @test filter_by_prefix(["buufaceless"],"bu") == ["buufaceless"]
    @test filter_by_prefix(["", " ", "\nelderberry", "a", "ab", "abc", "abcde"],"s fgh") == String[]
    @test filter_by_prefix(["alphabet"],"pams") == String[]
    @test filter_by_prefix(["ab1c"],"aa") == String[]
    @test filter_by_prefix(["faceless"],"faceless") == ["faceless"]
    @test filter_by_prefix(["amy"],"yamy") == String[]
    @test filter_by_prefix(["子"],"子") == ["子"]
    @test filter_by_prefix(["f"],"faa") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc", "ABC"],"amazoamputeen") == String[]
    @test filter_by_prefix(["f"],"") == ["f"]
    @test filter_by_prefix(["foot\t\thiills"],"foothills") == String[]
    @test filter_by_prefix(["qwwe"],"cfidelity") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "faceless", "bulge", "bulb", "bulldog", "burdock"],"b") == ["butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"]
    @test filter_by_prefix(["forwaard"],"banana") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "application123", "amaze", "ab1c", "_amaple_bc", "filmabc_", "abc1", "tea"],"aabuu") == String[]
    @test filter_by_prefix(["电影"],"电") == ["电影"]
    @test filter_by_prefix(["build"],"bluild") == String[]
    @test filter_by_prefix(["abuu1"],"ab1caabc1") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "asdfgh", "ASDFGH", "as fgh", "ASD FGH", "qwerty"],"AASDFGH") == String[]
    @test filter_by_prefix(["qforwardwwe"],"qforwardwwe") == ["qforwardwwe"]
    @test filter_by_prefix(["dsflabbergasted"],"b") == String[]
    @test filter_by_prefix(["abfanfare"],"abfanfare") == ["abfanfare"]
    @test filter_by_prefix(["abbatmanABC"],"ABC") == String[]
    @test filter_by_prefix(["", " ", "\n", "\t", "ab", "abc", "abcde"],"ampoule") == String[]
    @test filter_by_prefix(["bcocoa"],"figb") == String[]
    @test filter_by_prefix(["电电"],"电facetious") == String[]
    @test filter_by_prefix(["abc", "ABC", "ab1c", "_abc", "1cabc", "abc_", "abc1", "1abc", "abc_"],"aa") == String[]
    @test filter_by_prefix(["aabccqwertyuiop1"],"alphabet") == String[]
    @test filter_by_prefix([""],"ab1caabc1") == String[]
    @test filter_by_prefix(["Joyride", "batman"],"superman") == String[]
    @test filter_by_prefix(["ampoule"],"qqwe") == String[]
    @test filter_by_prefix(["faapplicationcade"],"facade") == String[]
    @test filter_by_prefix(["1bcabc"],"1cabc") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "wwine", "cocoa", "cocoa"],"fillm") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH"],"qwe") == ["qwerty"]
    @test filter_by_prefix(["QWERTYURIPOP"],"QWERTYUIOP") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc", "ABC", "ABC"],"aa") == String[]
    @test filter_by_prefix(["fgKilomkwieterh"],"wwine") == String[]
    @test filter_by_prefix(["alaphabet"],"pams") == String[]
    @test filter_by_prefix(["foolish"],"a电电话mpABCersand") == String[]
    @test filter_by_prefix(["bur"],"fgKilomkwieterhABC") == String[]
    @test filter_by_prefix(["taea"],"tea") == String[]
    @test filter_by_prefix(["Kilometer"],"电子") == String[]
    @test filter_by_prefix(["bfirllterurghber"],"bfillterurghber") == String[]
    @test filter_by_prefix(["ampoule"],"wqqwqe") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "application123", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电"],"aaa") == String[]
    @test filter_by_prefix(["电子"],"fgrKilofmkwieterh") == String[]
    @test filter_by_prefix(["fiburgher"],"qwe") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "as fgh", "asdforwardfgh", "ASD FGH"],"qwe") == ["qwerty", "qwertyuiop"]
    @test filter_by_prefix(["123", "abc", "ab1c", "_a_bc", "abc_", "abc1", "电"],"a") == ["abc", "ab1c", "abc_", "abc1"]
    @test filter_by_prefix(["amy", "apple", "pams", "alligator", "foot\t\thiills", "mops"],"a") == ["amy", "apple", "alligator"]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa"],"jinx") == String[]
    @test filter_by_prefix(["fgh", "Kilometer", "Gigabyte", "Kiwi", "jinx", "jujitsu", "Joyride", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "favicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forward", "forgive", "foliage", "faceless"],"") == ["fgh", "Kilometer", "Gigabyte", "Kiwi", "jinx", "jujitsu", "Joyride", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "favicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forward", "forgive", "foliage", "faceless"]
    @test filter_by_prefix(["yamy"],"burrow") == String[]
    @test filter_by_prefix(["a"],"aa") == String[]
    @test filter_by_prefix(["dsfldabbergasted"],"dsflabbergasted") == String[]
    @test filter_by_prefix(["yamy"],"qwwe") == String[]
    @test filter_by_prefix(["elderberryqwe"],"burgcherryher") == String[]
    @test filter_by_prefix(["qwetea"],"qamiaablee") == String[]
    @test filter_by_prefix(["taea"],"bu") == String[]
    @test filter_by_prefix(["abcfidelityc1"],"abfanfare") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa"],"burgcherryher") == String[]
    @test filter_by_prefix(["burdoforgiveck"],"burdock") == String[]
    @test filter_by_prefix(["burrow"],"yamy") == String[]
    @test filter_by_prefix(["bfirll"],"befillterurgfhber") == String[]
    @test filter_by_prefix(["water", "tea", "beer", "wwine", "cocoa", "cocoa", "wwine"],"fillm") == String[]
    @test filter_by_prefix(["1bcabc"],"1bcabc") == ["1bcabc"]
    @test filter_by_prefix(["", "\n", "\t", "a", "abbatman", "ab", "foolish", "abc", "abcde"],"a电电话mprABCersand") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "ebeer", "wwine", "cocoa", "cocoa"],"fillm") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock", "build"],"bfootf\t\thiills") == String[]
    @test filter_by_prefix(["电子"],"电ASDFGH子") == String[]
    @test filter_by_prefix(["qewee"],"qqwe") == String[]
    @test filter_by_prefix(["Joyride"],"qaabccqwertyuiop1qwe") == String[]
    @test filter_by_prefix(["abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc", "abc_"],"foothills") == String[]
    @test filter_by_prefix(["f"],"kiwi") == String[]
    @test filter_by_prefix(["ASDFGH"],"ASDFGH") == ["ASDFGH"]
    @test filter_by_prefix(["a电facetiouslaphabet"],"alaphabet") == String[]
    @test filter_by_prefix(["bureaucracy"],"cfacetious") == String[]
    @test filter_by_prefix(["elderberryqwe"],"ab1caabc1") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "\n", "ASD FGH", "ASD FGH"],"qwefacetious") == String[]
    @test filter_by_prefix(["aabc1"],"bu") == String[]
    @test filter_by_prefix(["batman", "batman"],"superman") == String[]
    @test filter_by_prefix(["jujisu"],"bbullby") == String[]
    @test filter_by_prefix(["abfanrfare"],"abfanfare") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "fgh", "tea", "电", "abc_"],"aa") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampABCersand", "ampersand", "amputee", "ambulance", "amiable", "buttter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "faceless", "bulge", "bulb", "bulldog", "burdock"],"buforgive") == String[]
    @test filter_by_prefix(["QWERTYURIPOP"],"durian") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "fgh", "tea", "电", "1cabc"],"aa") == String[]
    @test filter_by_prefix(["amy"],"yam") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "QWERTYUIOP", "ASDFGH", "as fgh", "ASD FGH"],"qwwe") == String[]
    @test filter_by_prefix(["电子"],"电子") == ["电子"]
    @test filter_by_prefix(["amy", "apple", "pams", "alligator", "1bcabc", "mops"],"") == ["amy", "apple", "pams", "alligator", "1bcabc", "mops"]
    @test filter_by_prefix(["dsfldabbergasted"],"电影") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "businsess", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "faceless", "bulge", "bulb", "bulldog", "burdock"],"bu") == ["butter", "budget", "businsess", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"]
    @test filter_by_prefix(["bbuly"],"jujisu") == String[]
    @test filter_by_prefix(["jujitsu"],"fgh") == String[]
    @test filter_by_prefix(["faapplicationcade"],"facadee") == String[]
    @test filter_by_prefix(["电子"],"favicon") == String[]
    @test filter_by_prefix(["fgh"],"faapplicationcade") == String[]
    @test filter_by_prefix(["forgive"],"dsflabbergasted") == String[]
    @test filter_by_prefix(["1bcabc"],"1bcabeerbamazec") == String[]
    @test filter_by_prefix(["cocoa"],"wPwhchT") == String[]
    @test filter_by_prefix(["ococoa"],"wPwhchT") == String[]
    @test filter_by_prefix(["dsfldabbergasted"],"\n") == String[]
    @test filter_by_prefix(["jujisu"],"faa") == String[]
    @test filter_by_prefix(["fgKilometerh"],"fabric") == String[]
    @test filter_by_prefix(["fiamaze"],"amaze") == String[]
    @test filter_by_prefix(["ampoumle"],"ampoule") == String[]
    @test filter_by_prefix(["qwefacetious"],"qwefacetious") == ["qwefacetious"]
    @test filter_by_prefix(["AASDFGH"],"ab1caabc1") == String[]
    @test filter_by_prefix(["aburrowmaze"],"wwine") == String[]
    @test filter_by_prefix(["aaa"],"aa") == ["aaa"]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa", "coffee"],"cfidelity") == String[]
    @test filter_by_prefix(["blluild"],"bluild") == String[]
    @test filter_by_prefix(["abc1电"],"电") == String[]
    @test filter_by_prefix(["e"],"qaabccqwertyuiop1qwe") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "1cabc", "abc", "ab1c"],"QWERTYUIOflabbergastedP") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "asdfgh", "ASDFGH", "as fgh", "ASD FGH", "qwerty", "ASD FGH"],"b") == String[]
    @test filter_by_prefix(["ABC"],"ABC") == ["ABC"]
    @test filter_by_prefix(["amaze"],"amaze") == ["amaze"]
    @test filter_by_prefix(["fantajinxsy"],"fantasy") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "as fgh", "asdforwardfgh", "ASD FGH"],"qwqe") == String[]
    @test filter_by_prefix(["ambulance"],"qqwewe") == String[]
    @test filter_by_prefix(["qwerty"],"cfidelity") == String[]
    @test filter_by_prefix(["cfacetious"],"b") == String[]
    @test filter_by_prefix(["\t\talligator"],"alligator") == String[]
    @test filter_by_prefix(["amwPwhchTle"],"ampoule") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "businsess", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "ffaceless", "bulge", "bulb", "bulldog", "burdock"],"bu") == ["butter", "budget", "businsess", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"]
    @test filter_by_prefix(["A SD FGH"],"ab1c") == String[]
    @test filter_by_prefix(["qforwardwwe"],"c") == String[]
    @test filter_by_prefix(["fantajinxsyab"],"ab") == String[]
    @test filter_by_prefix(["qwefacetious"],"qampersandwefacetious") == String[]
    @test filter_by_prefix(["fiburgher"],"fiburgher") == ["fiburgher"]
    @test filter_by_prefix(["amy", "apple", "pams", "1bcabc", "mops"],"ccocoa") == String[]
    @test filter_by_prefix(["QWERTYURIPOP"],"QWERTYURIPOP") == ["QWERTYURIPOP"]
    @test filter_by_prefix(["fasacA SD FGHade"],"facade") == String[]
    @test filter_by_prefix(["A SD FGH", "qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH", "ASDFGH"],"faceleamazess") == String[]
    @test filter_by_prefix(["FGHade"],"qwwqe") == String[]
    @test filter_by_prefix(["fidelity"],"babc1电u") == String[]
    @test filter_by_prefix(["", "\n", "\t", "a", "abbatman", "ab", "abc", "bur", "_a_bca", "abcde", "a"],"a电电话mpABCersand") == String[]
    @test filter_by_prefix(["br"],"br") == ["br"]
    @test filter_by_prefix(["faapplicactioencade"],"faapplicationcade") == String[]
    @test filter_by_prefix(["", " ", "\nelderberry", "a", "ab", "abc", "abcde", "a"],"s fgh") == String[]
    @test filter_by_prefix(["buforgive"],"buforgive") == ["buforgive"]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock", "bulldog"],"amazoamputeen") == String[]
    @test filter_by_prefix(["fiburgher"],"faqaabccqwertyuiop1qwecetious") == String[]
    @test filter_by_prefix(["durian"],"ab1caabc1") == String[]
    @test filter_by_prefix(["a"],"Gigabyte") == String[]
    @test filter_by_prefix(["alligator"],"facade") == String[]
    @test filter_by_prefix(["a电电话mprABCersand"],"a电电话mprABCersand") == ["a电电话mprABCersand"]
    @test filter_by_prefix(["电facetious"],"电facetious") == ["电facetious"]
    @test filter_by_prefix(["电影", "电子", "电话", "burdock", "电影"],"fabric") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH"],"ASDFGebeerH") == String[]
    @test filter_by_prefix(["forwaard"],"dsflabbergasted") == String[]
    @test filter_by_prefix(["1bbullbybcabc"],"1c") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "ASDFGH", "as fgh", "ASD FGH"],"qwe") == ["qwerty", "qwertyuiop"]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa"],"facadee") == String[]
    @test filter_by_prefix(["s电asdforwardfgherman"],"superman") == String[]
    @test filter_by_prefix(["1bcabeerbamazec"],"1cabc") == String[]
    @test filter_by_prefix(["", "\n", "\t", "a", "ab", "abc", "abcde", "\t"],"ampABCersand") == String[]
    @test filter_by_prefix(["", "\n", "\t", "a", "abbatman", "ab", "abc", "abcde", ""],"a电电话mpABCersand") == String[]
    @test filter_by_prefix(["burghber"],"burghber") == ["burghber"]
    @test filter_by_prefix(["forwaard"],"amazon") == String[]
    @test filter_by_prefix(["fgKilometerh"],"\nelderberry") == String[]
    @test filter_by_prefix(["ABAC"],"AC") == String[]
    @test filter_by_prefix(["1babc1电bullbybcabc"],"1c") == String[]
    @test filter_by_prefix(["ubu"],"1bbullbybcabc") == String[]
    @test filter_by_prefix(["", "\n", "\t", "a", "ab", "abc", "abcde", "\n"],"ampABCersafaand") == String[]
    @test filter_by_prefix(["bbuu"],"ai") == String[]
    @test filter_by_prefix(["bully"],"bully") == ["bully"]
    @test filter_by_prefix(["ffaapplicationcade"],"ffaapplicationcade") == ["ffaapplicationcade"]
    @test filter_by_prefix(["buufaceless"],"wPwhchT") == String[]
    @test filter_by_prefix(["电子"],"wwine") == String[]
    @test filter_by_prefix(["电电"],"电电") == ["电电"]
    @test filter_by_prefix(["dsflabberfillmgasted"],"dsflabberfillmgasted") == ["dsflabberfillmgasted"]
    @test filter_by_prefix([""],"f") == String[]
    @test filter_by_prefix(["Kilometfaulter"],"1cabc") == String[]
    @test filter_by_prefix(["fabric"],"alaphabet") == String[]
    @test filter_by_prefix(["qforwardwwe"],"1abc") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "asdfgh", "ASDFGH", "as fgh", "ASD FGH", "qwerty", "ASD FGH"],"bubu") == String[]
    @test filter_by_prefix(["fgrKilofmkwieterh"],"电ASDFGH子") == String[]
    @test filter_by_prefix(["fghqwertyuio"],"fgh") == ["fghqwertyuio"]
    @test filter_by_prefix(["filmbu"],"filmbu") == ["filmbu"]
    @test filter_by_prefix(["applQWERTYUIOPe"],"f") == String[]
    @test filter_by_prefix(["ffaapplicationcade"],"ffaappliocationcade") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock", "build"],"bfootf\t\thiills") == String[]
    @test filter_by_prefix(["fig"],"abfanfare") == String[]
    @test filter_by_prefix(["yam"],"qwe") == String[]
    @test filter_by_prefix(["1bc1abc"],"1bcabc") == String[]
    @test filter_by_prefix(["abcfidelifacadeetyc1"],"abfanfare") == String[]
    @test filter_by_prefix(["abuilda"],"jujube") == String[]
    @test filter_by_prefix(["ab1cabc1电facetious"],"ab1cabc1电facetious") == ["ab1cabc1电facetious"]
    @test filter_by_prefix(["bfootf"],"wPwhchT") == String[]
    @test filter_by_prefix(["Kilometer"],"电电") == String[]
    @test filter_by_prefix(["abfanrfare"],"foliage") == String[]
    @test filter_by_prefix(["amy", "apple", "pams", "applQWERTYUIOPe", "alligator", "maple", "applQWERTUYUIOPe", "mops", "maple"],"a") == ["amy", "apple", "applQWERTYUIOPe", "alligator", "applQWERTUYUIOPe"]
    @test filter_by_prefix(["emon"],"lemon") == String[]
    @test filter_by_prefix(["a电电话mpABCersand"],"a电电话mpABCersand") == ["a电电话mpABCersand"]
    @test filter_by_prefix(["", " ", "\n", "\t", "a", "ab", "abc", "abcde"],"fgrKilofmkwieterh") == String[]
    @test filter_by_prefix(["fgKilomkwieterh"],"fgrapegKamputeeilomkiwieterh") == String[]
    @test filter_by_prefix(["fgh"],"fgh") == ["fgh"]
    @test filter_by_prefix(["forgyamive"],"dsflabbergasted") == String[]
    @test filter_by_prefix(["abc", "ABC", "ab1c", "_abc", "1cabc", "abc_", "A", "abc1", "1abc", "abc_"],"aa") == String[]
    @test filter_by_prefix(["butter"],"faqaabccqwertyuiop1qwecetious") == String[]
    @test filter_by_prefix(["babc1电bur"],"babc1电u") == String[]
    @test filter_by_prefix(["ffaa"],"fgKilomkwieterh") == String[]
    @test filter_by_prefix(["bu"],"QWERTYUIOP") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "ebeer", "wwine", "cocoa", "cocoa"],"qwwqe") == String[]
    @test filter_by_prefix(["afgKilofmkwieterhABCi"],"ai") == String[]
    @test filter_by_prefix(["Kilomete"],"Kilometer") == String[]
    @test filter_by_prefix(["ampoule"],"ampoule") == ["ampoule"]
    @test filter_by_prefix(["yamy"],"yamy") == ["yamy"]
    @test filter_by_prefix(["buamputefaulteuive"],"forgive") == String[]
    @test filter_by_prefix(["fgh", "Kilometer", "Gigabyte", "Kiwi", "jinx", "jujitsu", "Joyride", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "cfacetiousfavicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forward", "forgive", "foliage", "faceless"],"") == ["fgh", "Kilometer", "Gigabyte", "Kiwi", "jinx", "jujitsu", "Joyride", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "cfacetiousfavicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forward", "forgive", "foliage", "faceless"]
    @test filter_by_prefix(["ddsfldabbergasted"],"dsfldabbergasted") == String[]
    @test filter_by_prefix(["qwertyuiop"],"facadee") == String[]
    @test filter_by_prefix(["abc1"],"bu") == String[]
    @test filter_by_prefix(["buforgive"],"bufgKamputeeilomkiwieterhforfiggive") == String[]
    @test filter_by_prefix(["abc_"],"fantasy") == String[]
    @test filter_by_prefix(["durian"],"babc1电bur") == String[]
    @test filter_by_prefix(["abfanffare"],"bfootf\t\thiills") == String[]
    @test filter_by_prefix(["qwqe"],"") == ["qwqe"]
    @test filter_by_prefix(["ab1caabc1"],"abuu1") == String[]
    @test filter_by_prefix(["wPwhchT"],"wPwhchT") == ["wPwhchT"]
    @test filter_by_prefix(["foliage"],"bufgKamputeeilomkiwieterhforfiggive") == String[]
    @test filter_by_prefix(["fi"],"abbananac1") == String[]
    @test filter_by_prefix(["ampAaBCersand"],"a") == ["ampAaBCersand"]
    @test filter_by_prefix(["buuu"],"jujube") == String[]
    @test filter_by_prefix(["bfilterurghber"],"cbuambulancer") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa", "cocoa"],"coffee") == ["coffee"]
    @test filter_by_prefix(["1bcabACc"],"1bcabACc") == ["1bcabACc"]
    @test filter_by_prefix(["电子"],"abfanrfare") == String[]
    @test filter_by_prefix(["facade"],"facadefacade") == String[]
    @test filter_by_prefix(["d1abcsfldabbergastedamiable"],"dsabuu1fldabbergastedamiable") == String[]
    @test filter_by_prefix([" "],"abc1") == String[]
    @test filter_by_prefix(["filmbu"],"QWERTYURIPOP") == String[]
    @test filter_by_prefix(["aa"],"aABC") == String[]
    @test filter_by_prefix(["Kfilometfaulr"],"Kilometfaulr") == String[]
    @test filter_by_prefix(["bfilterurghber"],"bfilterurghber") == ["bfilterurghber"]
    @test filter_by_prefix(["1bcacbc"],"1cabc") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电"],"") == ["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电"]
    @test filter_by_prefix([""],"电") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "as fgh", "asdforwardfgh", "ASD FGH"],"fiduciary") == String[]
    @test filter_by_prefix(["aoambfirllterurghberputeen"],"aoamputeen") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "tea", "abc"],"aa") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "application123", "ab1c", "_a_bc", "abcab", "abc1", "tea", "电"],"aa") == String[]
    @test filter_by_prefix(["buamputeeu"],"fgfh") == String[]
    @test filter_by_prefix(["fantajinxsyab"],"fantajinxsyab") == ["fantajinxsyab"]
    @test filter_by_prefix(["cfacus"],"") == ["cfacus"]
    @test filter_by_prefix(["m"],"qwe") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "fgh", "m", "电", "abc_"],"akiwi") == String[]
    @test filter_by_prefix(["abbanananc1"],"buttteraabc1") == String[]
    @test filter_by_prefix(["amnbulance"],"qqwewe") == String[]
    @test filter_by_prefix(["bampersanduamputeeu"],"buamputeeu") == String[]
    @test filter_by_prefix(["jujitsu"],"build") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "cocoa", "coffee"],"abcfidelityc1") == String[]
    @test filter_by_prefix(["forgyamfive"],"dsflabbergasteburdoforgiveckd") == String[]
    @test filter_by_prefix(["fgrKilofmkwietKerh"],"fgrKilofmkwieterh") == String[]
    @test filter_by_prefix(["AASDFGH"],"AASDFGH") == ["AASDFGH"]
    @test filter_by_prefix(["电电话"],"cfidelity") == String[]
    @test filter_by_prefix(["cocoajujitsu"],"cocoajujitsu") == ["cocoajujitsu"]
    @test filter_by_prefix(["qQWERTYUIOPwe"],"qwe") == String[]
    @test filter_by_prefix(["QWERTYURIOP"],"QWERTYURIOP") == ["QWERTYURIOP"]
    @test filter_by_prefix([""],"1abc") == String[]
    @test filter_by_prefix(["bbuu"],"bbuu") == ["bbuu"]
    @test filter_by_prefix(["facadee"],"facadee") == ["facadee"]
    @test filter_by_prefix(["bbu"],"bu") == String[]
    @test filter_by_prefix(["abare"],"abfanfare") == String[]
    @test filter_by_prefix([""],"qe") == String[]
    @test filter_by_prefix(["qqwe"],"asdforwardfgh") == String[]
    @test filter_by_prefix(["apple", "banana", "durian", "elderberry", "fig", "applpe", "honeydew", "jujube", "ABC", "kiwi", "lemon", "durian"],"fantajinxsy") == String[]
    @test filter_by_prefix(["fgh", "Kilometer", "Gigabyte", "Kiwi", "jinx", "jujitsu", "Joyride", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "favicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forgive", "foliage", "foothills"],"ff") == String[]
    @test filter_by_prefix(["applpe"],"qwwe") == String[]
    @test filter_by_prefix(["bureaucracy"],"buuu") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc__", "1cabc", "abc", "ab1c", "abc", "ABC"],"QWERTYUIOflabbergastedP") == String[]
    @test filter_by_prefix(["ffaa"],"电") == String[]
    @test filter_by_prefix(["fidelaABCity"],"babc1电u") == String[]
    @test filter_by_prefix([" alphabet"]," alphabet") == [" alphabet"]
    @test filter_by_prefix(["qforwardwwe", "abc", "ABC", "ab1c", "_abc", "abc_", "bbullby", "1abc", "abc_", "abc_"],"aa") == String[]
    @test filter_by_prefix(["jujisu"],"ai") == String[]
    @test filter_by_prefix(["bfootf\t\thiills"],"bfootf\t\thiills") == ["bfootf\t\thiills"]
    @test filter_by_prefix(["abc1"],"afgKilofmkwieterhABCi") == String[]
    @test filter_by_prefix(["Kilometfacadefacader"],"电子") == String[]
    @test filter_by_prefix(["电"],"abcab") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_a_bc", "abc_", "abc1", "tea", "电"],"ampAaBCersand") == String[]
    @test filter_by_prefix(["buufaceless"],"a") == String[]
    @test filter_by_prefix(["blluild"],"123") == String[]
    @test filter_by_prefix(["pams"],"ab1caabc1") == String[]
    @test filter_by_prefix(["电影"],"电电") == String[]
    @test filter_by_prefix(["abare"],"abare") == ["abare"]
    @test filter_by_prefix(["bfillterurghber"],"forgyamfive") == String[]
    @test filter_by_prefix(["jujisu"],"jujisu") == ["jujisu"]
    @test filter_by_prefix(["abfanfare"],"abcab") == String[]
    @test filter_by_prefix(["QWERTYUIOflabbergastedemon"],"QWERTYUIOflabbergastedP") == String[]
    @test filter_by_prefix(["ab1burgcherryherc"],"aa") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "asdfgh", "as fgh", "asdforwardfgh", "ASD FGH"],"qwe") == ["qwerty", "qwertyuiop"]
    @test filter_by_prefix(["amy", "pams", "applQWERTYUIOPe", "alligator", "maple", "applQWERTUYUIOPe", "mops", "maple"],"a") == ["amy", "applQWERTYUIOPe", "alligator", "applQWERTUYUIOPe"]
    @test filter_by_prefix(["forgive"],"dsffaultlabbergast子ed") == String[]
    @test filter_by_prefix(["aabc1"],"QWERTYURIPOforwaardP") == String[]
    @test filter_by_prefix(["qwefacetious"],"forgive") == String[]
    @test filter_by_prefix(["burgcherryher"],"burgcherryher") == ["burgcherryher"]
    @test filter_by_prefix(["电foliage电话"],"电foliage电话") == ["电foliage电话"]
    @test filter_by_prefix(["qweetea"],"qamiablee") == String[]
    @test filter_by_prefix(["aoampputeen"],"allaigator") == String[]
    @test filter_by_prefix(["AASDFGH"],"ASDFGH") == String[]
    @test filter_by_prefix(["aaa"],"buforgive") == String[]
    @test filter_by_prefix(["wqqewqe"],"wqqwqe") == String[]
    @test filter_by_prefix(["ubu"],"") == ["ubu"]
    @test filter_by_prefix(["bud电电话s"],"buds") == String[]
    @test filter_by_prefix(["\nelderberryaffaa"],"电") == String[]
    @test filter_by_prefix(["123", "aabc1", "abc", "ab1c", "_abc", "abc_", "abc1", "1abc", "aabc1"],"qeaabcab") == String[]
    @test filter_by_prefix(["电电话"],"电fo话") == String[]
    @test filter_by_prefix(["alligatqQWERTYUIOPweor"],"alligator") == String[]
    @test filter_by_prefix(["buttter"],"batman") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "faceless", "bulge", "bulb", "bulldog", "burdock"],"ffacelessb") == String[]
    @test filter_by_prefix(["apple", "buforgivecherry", "banana", "cherry", "durian", "elderberry", "fig", "grape", "honeydew", "jujube", "kiwi", "lemon"],"e") == ["elderberry"]
    @test filter_by_prefix(["buforgivechherry"],"buforgivecherry") == String[]
    @test filter_by_prefix(["电ffoliage电话"],"电ffoliagASDFGebeerHe电话") == String[]
    @test filter_by_prefix(["fabric"],"fabric") == ["fabric"]
    @test filter_by_prefix(["fgh", "Kilometer", "Gigabyte", "Kiwi", "jinx", "jujitsu", "Joyride", "foothills", "filter", "fiduciary", "fidelity", "film", "fault", "fantasy", "fanfare", "favicon", "fabric", "facetious", "facade", "faceless", "flabbergasted", "foolish", "forgive", "foliage", "foothills"],"ABC") == String[]
    @test filter_by_prefix(["faceless"],"facealphabetless") == String[]
    @test filter_by_prefix(["ABC"],"abfanffare") == String[]
    @test filter_by_prefix(["amazon"],"ABAC") == String[]
    @test filter_by_prefix(["", "\n", "\t", "a", "abbatman", "ab", "abc", "bur", "_a_bca", "abcde", "a"],"ebeer") == String[]
    @test filter_by_prefix(["apWplQWERTYUbfootfIOPe"],"f") == String[]
    @test filter_by_prefix(["apple"],"apple") == ["apple"]
    @test filter_by_prefix(["jubuforgivecherryjitsu"],"bully") == String[]
    @test filter_by_prefix(["aa"],"aaa") == String[]
    @test filter_by_prefix(["fgrKilotfmkrwieterh"],"电ASDFGH子") == String[]
    @test filter_by_prefix(["Kilometer"],"Kilomeer") == String[]
    @test filter_by_prefix(["oocoa"],"wPwhchT") == String[]
    @test filter_by_prefix(["电子batmtan"],"电子batmtan") == ["电子batmtan"]
    @test filter_by_prefix(["qwQWERTYURIPOPefacetious"],"qwefacetious") == String[]
    @test filter_by_prefix(["1bbullbybcabc"],"1bbullbybcabc") == ["1bbullbybcabc"]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "businsess", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "faceless", "bulge", "bulb", "bulldog", "burdock"],"b\nelderberry") == String[]
    @test filter_by_prefix(["bur"],"qwwqe") == String[]
    @test filter_by_prefix(["ABC"],"ABAC") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc", "abc_"],"abuuu") == String[]
    @test filter_by_prefix(["Kilometdsffaultlabbergast子eder"],"1cabc") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer"],"facadee") == String[]
    @test filter_by_prefix(["ubu"],"qqwqewe") == String[]
    @test filter_by_prefix(["jujitsu"],"bulluy") == String[]
    @test filter_by_prefix(["hiills"],"burdock") == String[]
    @test filter_by_prefix(["sapplication123 fgh"],"s fgh") == String[]
    @test filter_by_prefix(["burgcherryher"],"bbbuher") == String[]
    @test filter_by_prefix(["qwwe"],"qwwe") == ["qwwe"]
    @test filter_by_prefix(["fasacA"],"dsfldabbergasted") == String[]
    @test filter_by_prefix(["m"],"m") == ["m"]
    @test filter_by_prefix(["elderberryaffaa"],"a电电话mpaABCersand") == String[]
    @test filter_by_prefix(["电子batmmtan"],"电子batmtan") == String[]
    @test filter_by_prefix(["bbu"],"buufaceless") == String[]
    @test filter_by_prefix(["_a_bc"],"fgrKilofmkwieterh") == String[]
    @test filter_by_prefix(["bbu"],"bb子u") == String[]
    @test filter_by_prefix(["ampAaBCersand电电话话"],"电电话") == String[]
    @test filter_by_prefix(["water", "wine", "ccoffee", "tea", "beer", "cocoa"],"cfidelity") == String[]
    @test filter_by_prefix(["电电话"],"Kfilometfaulr") == String[]
    @test filter_by_prefix(["filmbqwQWERTYURIPOPefacetiousu"],"fiu") == String[]
    @test filter_by_prefix(["1cabc"],"b") == String[]
    @test filter_by_prefix(["1bcacbc"],"bcocoa") == String[]
    @test filter_by_prefix(["ab11caabc1"],"ab1burghber1caabc1") == String[]
    @test filter_by_prefix(["abare"],"aebare") == String[]
    @test filter_by_prefix(["aabccfgfhqwertyuiop1"],"allphfabet") == String[]
    @test filter_by_prefix(["bureaucracy"],"电子batmtan") == String[]
    @test filter_by_prefix(["burghber"],"buamputeeu") == String[]
    @test filter_by_prefix(["qwwqe1cabc"],"1cabc") == String[]
    @test filter_by_prefix(["abcfidelityc1"],"ab") == ["abcfidelityc1"]
    @test filter_by_prefix(["amazon"],"amazon") == ["amazon"]
    @test filter_by_prefix(["oocab1coa"],"oocab1coa") == ["oocab1coa"]
    @test filter_by_prefix(["s电asdforwardfgherman"],"spuperman") == String[]
    @test filter_by_prefix(["wqqwqe"],"ai") == String[]
    @test filter_by_prefix(["A SD FGH"],"A SD FGH") == ["A SD FGH"]
    @test filter_by_prefix(["afgKilofmkwieterhABCi"],"afgKilofmkwieterhABCi") == ["afgKilofmkwieterhABCi"]
    @test filter_by_prefix(["aallphfabet"],"abfanrfare") == String[]
    @test filter_by_prefix(["water", "wine", "coffee", "tea", "beer", "tea"],"facadee") == String[]
    @test filter_by_prefix(["abqweteacfidelifacadeetyyc1"],"abcfidelifacadeetyyc1") == String[]
    @test filter_by_prefix(["qfdwwe"],"c") == String[]
    @test filter_by_prefix(["fafaa"],"fafaa") == ["fafaa"]
    @test filter_by_prefix(["foothills"],"foothills") == ["foothills"]
    @test filter_by_prefix(["forgive"],"forgive") == ["forgive"]
    @test filter_by_prefix(["bbullfasacA SD FGHadeby"],"bbullby") == String[]
    @test filter_by_prefix(["A SD FGH", "qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH", "ASDFGH", "ASDFGH"],"fmazes") == String[]
    @test filter_by_prefix(["bureaucracy"],"bu") == ["bureaucracy"]
    @test filter_by_prefix(["forward"],"f") == ["forward"]
    @test filter_by_prefix(["dsflbbergasted"],"dsfldabbergasted") == String[]
    @test filter_by_prefix(["1bcacbc"],"1bcacbc") == ["1bcacbc"]
    @test filter_by_prefix(["wqqewqe"],"qwwe") == String[]
    @test filter_by_prefix(["", " ", "\nelderberry", "a", "ab", "abc", "abcde", ""],"s fgh") == String[]
    @test filter_by_prefix(["aabet"],"pams") == String[]
    @test filter_by_prefix(["电电"],"电face电tious") == String[]
    @test filter_by_prefix(["burgjujisucherryher"],"yher") == String[]
    @test filter_by_prefix([""],"a") == String[]
    @test filter_by_prefix(String[],"xyz") == String[]
    @test filter_by_prefix(["a", "ab", "abc"],"") == ["a", "ab", "abc"]
    @test filter_by_prefix(["", "", ""],"") == ["", "", ""]
    @test filter_by_prefix(["asdf", "b", "04", "as df", "as-df"],"-") == String[]
    @test filter_by_prefix(["", "21", "abc", "", "", "asdf"]," ") == String[]
    @test filter_by_prefix(String[],"a") == String[]
    @test filter_by_prefix(["a", "aa", "ab", "abc", "aba"],"a") == ["a", "aa", "ab", "abc", "aba"]
    @test filter_by_prefix(["bcdef", "efgh", "hijk"],"a") == String[]
    @test filter_by_prefix(["fii"],"fi") == ["fii"]
    @test filter_by_prefix(["apple", "banana", "cherry", "durian", "elderberry", "fig", "honeydew", "jujube", "kiwi", "lemon"],"e") == ["elderberry"]
    @test filter_by_prefix(["fgh"],"电") == String[]
    @test filter_by_prefix(["fhgh"],"电") == String[]
    @test filter_by_prefix(["电影", "电话", "邮件"],"电superman") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"],"") == ["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"]
    @test filter_by_prefix(["fcoffeeii"],"fi") == String[]
    @test filter_by_prefix(["fghJoyride"],"fgh") == ["fghJoyride"]
    @test filter_by_prefix(["honeydew"],"电电") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "ab1", "1abc"],"a") == ["abc", "ab1c", "abc_", "ab1"]
    @test filter_by_prefix(["alligator"],"fgh") == String[]
    @test filter_by_prefix(["电"],"电") == ["电"]
    @test filter_by_prefix(["f"],"fgh") == String[]
    @test filter_by_prefix(["fii"],"cocoa") == String[]
    @test filter_by_prefix(["faceless"],"电") == String[]
    @test filter_by_prefix(["f电电gh"],"fgh") == String[]
    @test filter_by_prefix(["abc_"],"QWERTYUIO") == String[]
    @test filter_by_prefix(["gh"],"fgh") == String[]
    @test filter_by_prefix(["a"],"application") == String[]
    @test filter_by_prefix(["fampersandghJoyride"],"fgh") == String[]
    @test filter_by_prefix(["\t"],"fgh") == String[]
    @test filter_by_prefix(["honeydew"],"电honeydew") == String[]
    @test filter_by_prefix(["apple", "banana", "cherry", "durian", "elderberry", "fig", "honeydew", "jujube", "kiwi", "lemon"],"") == ["apple", "banana", "cherry", "durian", "elderberry", "fig", "honeydew", "jujube", "kiwi", "lemon"]
    @test filter_by_prefix(["123"],"fgh") == String[]
    @test filter_by_prefix(["abc", "ABC", "ab1c", "_abc", "abc_", "ab1", "1abc"],"a") == ["abc", "ab1c", "abc_", "ab1"]
    @test filter_by_prefix(["qwecherry"],"qwe") == ["qwecherry"]
    @test filter_by_prefix(["honeydeww"],"burgher") == String[]
    @test filter_by_prefix(["fii"],"tea") == String[]
    @test filter_by_prefix(["fampegrsandghJoyride"],"fgh") == String[]
    @test filter_by_prefix(["电影", "电子", "电话", "邮件"],"forward") == String[]
    @test filter_by_prefix(["abelderrberry"],"abelderberry") == String[]
    @test filter_by_prefix(["hfiduciaryew"],"hfiduciaryew") == ["hfiduciaryew"]
    @test filter_by_prefix(["fghh"],"forgive") == String[]
    @test filter_by_prefix(["fii"],"jujube") == String[]
    @test filter_by_prefix(["bulb"],"电") == String[]
    @test filter_by_prefix(["banana"],"banana") == ["banana"]
    @test filter_by_prefix(["abc_"],"QWERTYUIUO") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"],"fanfare") == String[]
    @test filter_by_prefix(["fampegrsandghJoyride"],"fampegrsandghJoyride") == ["fampegrsandghJoyride"]
    @test filter_by_prefix(["电影", "电子", "邮kiwi件", "电话", "邮件"],"forward") == String[]
    @test filter_by_prefix(["hfiduciaryew"],"tea") == String[]
    @test filter_by_prefix(["facelaess"],"电") == String[]
    @test filter_by_prefix(["fii", "123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"],"") == ["fii", "123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "ab1", "1abc"],"aa") == String[]
    @test filter_by_prefix(["qwecherry"],"we") == String[]
    @test filter_by_prefix(["电影", "电子", "电话", "电电子", "邮件"],"电") == ["电影", "电子", "电话", "电电子"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"],"电话a") == String[]
    @test filter_by_prefix(["foliage"],"ab") == String[]
    @test filter_by_prefix(["honeydGigabyteew"],"电电") == String[]
    @test filter_by_prefix(["honeydew"],"1abc") == String[]
    @test filter_by_prefix(["burdocdk"],"fgh") == String[]
    @test filter_by_prefix(["fii"],"jjujube") == String[]
    @test filter_by_prefix(["jjujubeaa"],"a") == String[]
    @test filter_by_prefix(["bbfacelaessu"],"bbu") == String[]
    @test filter_by_prefix(["电影", "电话"],"电superman") == String[]
    @test filter_by_prefix(["forgive"],"a") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH", "QwertY"],"qwwe") == String[]
    @test filter_by_prefix(["hqwertyuioponeydew"],"honeydew") == String[]
    @test filter_by_prefix(["a"],"burdocdk") == String[]
    @test filter_by_prefix(["fhghh"],"forgfcoffeeiiive") == String[]
    @test filter_by_prefix(["fii"],"jujubealphabet") == String[]
    @test filter_by_prefix(["fcoffeeii"],"fgh") == String[]
    @test filter_by_prefix(["bulb"],"fighoneydGigabyteew") == String[]
    @test filter_by_prefix(["wine"],"qwwe电") == String[]
    @test filter_by_prefix(["mops"],"qwertyuiop") == String[]
    @test filter_by_prefix(["fii", "123", "abc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"],"qwwe电") == String[]
    @test filter_by_prefix(["123", "abc", "ab1c", "_abc", "abc_", "ab1", "1abc"],"aqwecherry") == String[]
    @test filter_by_prefix(["fii"],"facetious") == String[]
    @test filter_by_prefix(["fiburdocki"],"a") == String[]
    @test filter_by_prefix(["abelderrberry"],"abelderrberry") == ["abelderrberry"]
    @test filter_by_prefix(["hfiduciaryew"],"qwe") == String[]
    @test filter_by_prefix(["apple", "banana", "cherry", "durian", "honeydewburgher", "elderberry", "fig", "grape", "honeydew", "jujube", "kiwi", "lemon"],"e") == ["elderberry"]
    @test filter_by_prefix(["facelaessbatmanh"],"fgh") == String[]
    @test filter_by_prefix(["fii"],"jujubue") == String[]
    @test filter_by_prefix(["fanfare"],"电") == String[]
    @test filter_by_prefix(["jjinx"],"jinx") == String[]
    @test filter_by_prefix(["kiwi"],"邮kiwi件") == String[]
    @test filter_by_prefix(["apple", "banana", "cherry", "durian", "elderberry", "fig", "honeydew", "jujube", "kiwi", "lemon"],"honeydewburgher") == String[]
    @test filter_by_prefix(["honeydewburgher"],"honeydewburgher") == ["honeydewburgher"]
    @test filter_by_prefix(["bbfacelaessu"],"ubbu") == String[]
    @test filter_by_prefix(["fhgfhh"],"fhghh") == String[]
    @test filter_by_prefix(["f"],"ABC") == String[]
    @test filter_by_prefix(["facwineeless"],"forgive") == String[]
    @test filter_by_prefix(["QWERTYUIO"],"qwe") == String[]
    @test filter_by_prefix(["jjujubeaa"],"ASD FGH") == String[]
    @test filter_by_prefix(["abeldery"],"abelderrberry") == String[]
    @test filter_by_prefix(["fanfare"],"f电电gh") == String[]
    @test filter_by_prefix(["cocofghh"],"cocoa") == String[]
    @test filter_by_prefix(["we电"],"电") == String[]
    @test filter_by_prefix(["邮"],"foliage") == String[]
    @test filter_by_prefix(["abc_"],"abc_") == ["abc_"]
    @test filter_by_prefix(["f电电gh"],"f电电gh") == ["f电电gh"]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "_abc", "durian", "abc_", "1abc"],"amorous") == String[]
    @test filter_by_prefix(["burdocd邮件k"],"fgh") == String[]
    @test filter_by_prefix(["pamsfii"],"jjujube") == String[]
    @test filter_by_prefix(["fcoffeeii"],"电话a") == String[]
    @test filter_by_prefix(["邮件"],"fiduciary") == String[]
    @test filter_by_prefix(["honeydew"],"oneydew") == String[]
    @test filter_by_prefix(["qwecherwghry"],"qabcwecherwry") == String[]
    @test filter_by_prefix(["cocofghh"],"fi") == String[]
    @test filter_by_prefix(["电影", "电子", "电话", "邮件", "电子"],"hqwertyuioponeydew") == String[]
    @test filter_by_prefix(["f电电gh"],"f电电ghfavicon") == String[]
    @test filter_by_prefix(["f电电gh"],"f电电ghfaon") == String[]
    @test filter_by_prefix(["f"],"maple") == String[]
    @test filter_by_prefix(["facelaessbatmanh"],"电电") == String[]
    @test filter_by_prefix(["amazon"],"电superman") == String[]
    @test filter_by_prefix(["fantasy"],"jinx") == String[]
    @test filter_by_prefix(["fii"],"fii") == ["fii"]
    @test filter_by_prefix(["fiif"],"fi") == ["fiif"]
    @test filter_by_prefix(["qwecdurianherry"],"we") == String[]
    @test filter_by_prefix(["\n"],"superman") == String[]
    @test filter_by_prefix(["SffUs"],"BOY") == String[]
    @test filter_by_prefix(["winne"],"winnfoolish") == String[]
    @test filter_by_prefix(["amazon"],"a") == ["amazon"]
    @test filter_by_prefix(["ffii"],"fi") == String[]
    @test filter_by_prefix(["amazon"],"fighoneydGigabyteew") == String[]
    @test filter_by_prefix(["amy", "apple", "pams", "amputee", "maple", "mops", "apple"],"a") == ["amy", "apple", "amputee", "apple"]
    @test filter_by_prefix(["cocofghh"],"fijujubealphabet") == String[]
    @test filter_by_prefix(["1abc"],"fhghh") == String[]
    @test filter_by_prefix(["hfiduciaryew"],"foliage") == String[]
    @test filter_by_prefix(["fhghh"],"fhghh") == ["fhghh"]
    @test filter_by_prefix(["abc_"],"QWERTYUIRO") == String[]
    @test filter_by_prefix(["azmazon"],"amazon") == String[]
    @test filter_by_prefix(["yfampegrsandghJoyride"],"abcfgh") == String[]
    @test filter_by_prefix(["fhgfilterh"],"电") == String[]
    @test filter_by_prefix(["fhghh"],"电话a") == String[]
    @test filter_by_prefix(["amazolemonn"],"amazoon") == String[]
    @test filter_by_prefix(["foothills"],"fhgfilterh") == String[]
    @test filter_by_prefix(["SffUs"],"电") == String[]
    @test filter_by_prefix(["ejjujube"],"jjujube") == String[]
    @test filter_by_prefix(["123", "abc", "ABC", "ab1c", "abc_", "abc1", "1abc"],"fanfare") == String[]
    @test filter_by_prefix(["QwertY"],"fii") == String[]
    @test filter_by_prefix(["fcoffeeifi"],"burgher") == String[]
    @test filter_by_prefix(["ifii"],"jujubfhghe") == String[]
    @test filter_by_prefix(["honeydew"],"ohqwertyuioponeydewew") == String[]
    @test filter_by_prefix(["fi"],"fi") == ["fi"]
    @test filter_by_prefix(["SffUs"],"SfffUs") == String[]
    @test filter_by_prefix(["jiinx邮i件"],"fantasy") == String[]
    @test filter_by_prefix(["ASD FGH"],"电电") == String[]
    @test filter_by_prefix(["bbefacelaessu"],"bbuubbu") == String[]
    @test filter_by_prefix(["jjinx"],"jxinx") == String[]
    @test filter_by_prefix(["maplp"],"maplpe") == String[]
    @test filter_by_prefix(["babc_"],"abc_") == String[]
    @test filter_by_prefix(["abac_"],"abc_") == String[]
    @test filter_by_prefix(["azmazon"],"SfffUs") == String[]
    @test filter_by_prefix(["honeydew"],"howneydew") == String[]
    @test filter_by_prefix(["电影", "电话"],"电supesrman") == String[]
    @test filter_by_prefix(["电影", "电子", "邮kiwi件", "电话"],"forward") == String[]
    @test filter_by_prefix(["batman"],"电") == String[]
    @test filter_by_prefix(["facade"],"jjujube") == String[]
    @test filter_by_prefix(["f电电gh"],"application") == String[]
    @test filter_by_prefix(["电影", "电话", "邮件"],"电") == ["电影", "电话"]
    @test filter_by_prefix(["honeydew"],"电电forward") == String[]
    @test filter_by_prefix(["\t"],"\t") == ["\t"]
    @test filter_by_prefix(["wwe"],"we") == String[]
    @test filter_by_prefix(["fi"],"电") == String[]
    @test filter_by_prefix(["abc1"],"fighoneydGigabytfhghyeew") == String[]
    @test filter_by_prefix(["mops"],"mops") == ["mops"]
    @test filter_by_prefix(["foliage"],"foliage") == ["foliage"]
    @test filter_by_prefix(["fiif"],"ifi") == String[]
    @test filter_by_prefix(["abeldberrberry"],"abelderrberry") == String[]
    @test filter_by_prefix(["qwerty", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH", "ASDFGH"],"qwe") == ["qwerty", "qwertyuiop"]
    @test filter_by_prefix(["burdocddk"],"burdocddk") == ["burdocddk"]
    @test filter_by_prefix(["abac_"],"burGigabytedocodkfgh") == String[]
    @test filter_by_prefix(["foothills"],"qwecdurianherry") == String[]
    @test filter_by_prefix(["fcoffebureaucuracyeiSfffUsi"],"fcoffeeii") == String[]
    @test filter_by_prefix(["amazolemonn"],"bbuubbu") == String[]
    @test filter_by_prefix(["mapl"],"maplpe") == String[]
    @test filter_by_prefix(["bman"],"superman") == String[]
    @test filter_by_prefix(["f"],"fiduciary") == String[]
    @test filter_by_prefix(["apple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"],"bbu") == String[]
    @test filter_by_prefix(["bman"],"suhowneydewpefhghrman") == String[]
    @test filter_by_prefix(["\t"],"facelaess") == String[]
    @test filter_by_prefix(["bu"],"qabcwecherwry") == String[]
    @test filter_by_prefix(["fhgh"],"1abc") == String[]
    @test filter_by_prefix(["fighoneforwarddGigabytfhghyeew"],"fighoneforwarddGigabytfhghyeew") == ["fighoneforwarddGigabytfhghyeew"]
    @test filter_by_prefix(["bbbuubbu"],"bbbuubbu") == ["bbbuubbu"]
    @test filter_by_prefix(["a"],"cocoa") == String[]
    @test filter_by_prefix(["apple", "banana", "cherry", "durian", "honeydewburgher", "elderberry", "fig", "grape", "honeydew", "jujube", "kiwi", "lemon"],"ambulance") == String[]
    @test filter_by_prefix(["fhgfhh"],"电电") == String[]
    @test filter_by_prefix(["qwertyuiop"],"fghazmazon") == String[]
    @test filter_by_prefix(["fiburcki"],"a") == String[]
    @test filter_by_prefix(["f1ab"],"facetious") == String[]
    @test filter_by_prefix(["amperabeldberrberryand"],"foiburdocki") == String[]
    @test filter_by_prefix(["qwecdurjinxry"],"we") == String[]
    @test filter_by_prefix(["fhghhfacelaessbhatmanh"],"afijujubealphabet电话a") == String[]
    @test filter_by_prefix(["apple", "banana", "cherry", "durian", "elderberry", "fig", "kiapplicationwi", "honeydew", "jujube", "kiwi", "lemon"],"honeydewburgher") == String[]
    @test filter_by_prefix(["fgifiih"],"f") == ["fgifiih"]
    @test filter_by_prefix(["winne"],"abelderberry") == String[]
    @test filter_by_prefix(["ccocofghhocofghh"],"fi") == String[]
    @test filter_by_prefix(["ASD"],"abelderberry") == String[]
    @test filter_by_prefix(["fhjujubfhghegh"],"fhgh") == String[]
    @test filter_by_prefix(["bu"],"邮kiwi件") == String[]
    @test filter_by_prefix(["abc_"],"jinx") == String[]
    @test filter_by_prefix(["SffUs"],"SfsfUs") == String[]
    @test filter_by_prefix(["SffUUs"],"SffUUs") == ["SffUUs"]
    @test filter_by_prefix(["电电"],"电a话a") == String[]
    @test filter_by_prefix(["fbananaary"],"fbananaary") == ["fbananaary"]
    @test filter_by_prefix(["电电电"],"电电") == ["电电电"]
    @test filter_by_prefix(["azmazaon"],"qwecdurianherry") == String[]
    @test filter_by_prefix(["ampersand"],"ampersand") == ["ampersand"]
    @test filter_by_prefix(["amfbananaaryperabeldberrberryand"],"ubbu") == String[]
    @test filter_by_prefix(["\tpamsfii"],"fghh") == String[]
    @test filter_by_prefix(["fhgfhh"],"电wqwe电") == String[]
    @test filter_by_prefix(["电影", "电子", "电话", "邮件", "电子"],"amperabeldberrberryand") == String[]
    @test filter_by_prefix(["bbulb"],"ASDFGH") == String[]
    @test filter_by_prefix(["f电电gh"],"f电电ghfaflabbergastedon") == String[]
    @test filter_by_prefix(["123"],"电") == String[]
    @test filter_by_prefix(["电honeydew"],"fii") == String[]
    @test filter_by_prefix(["mapl"],"a") == String[]
    @test filter_by_prefix(["f1ab"],"邮kiwi件") == String[]
    @test filter_by_prefix(["banana"],"fampegrsandghJoyride") == String[]
    @test filter_by_prefix(["qwerty", "asdfgh", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "as fgh", "ASD FGH"],"qwe") == ["qwerty", "qwertyuiop"]
    @test filter_by_prefix(["QwertY"],"QwertY") == ["QwertY"]
    @test filter_by_prefix(["ifi"],"fi") == String[]
    @test filter_by_prefix(["\n"],"\n") == ["\n"]
    @test filter_by_prefix(["123", "ab", "abc", "ABC", "ab1c", "abc_", "abc1", "1abc", "abc_"],"lemon") == String[]
    @test filter_by_prefix(["SffUUs"],"fhgh") == String[]
    @test filter_by_prefix(["SUfsfUs"],"SUfsfUs") == ["SUfsfUs"]
    @test filter_by_prefix(["f电电gh"],"f电电ghh") == String[]
    @test filter_by_prefix(["fghazmazon"],"fighoneydGigabyteew") == String[]
    @test filter_by_prefix(["qwerty", "asdfgh", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "favicon", "ASD FGH"],"qbatmanwne") == String[]
    @test filter_by_prefix(["fabric"],"fhghh") == String[]
    @test filter_by_prefix(["fgh"],"bbbuubbu") == String[]
    @test filter_by_prefix(["fiburddocki"],"a") == String[]
    @test filter_by_prefix(["honeydew"],"abc_") == String[]
    @test filter_by_prefix(["hfiduew"],"hfiduciaryew") == String[]
    @test filter_by_prefix(["fii"],"fiii") == String[]
    @test filter_by_prefix(["fantasy"],"fatasy") == String[]
    @test filter_by_prefix(["abelrderberry"],"abelrderberry") == ["abelrderberry"]
    @test filter_by_prefix(["电影", "电子", "电话", "邮件"],"电电") == String[]
    @test filter_by_prefix(["amazolemonn"],"amazzoon") == String[]
    @test filter_by_prefix(["appple", "application", "airport", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"],"bbu") == String[]
    @test filter_by_prefix(["qwehoneydewburgher"],"qwe") == ["qwehoneydewburgher"]
    @test filter_by_prefix(["fii", "123", "abc", "ABC", "ab1c", "bbulb", "abc_", "abc1", "1abc"],"qwwe电") == String[]
    @test filter_by_prefix(["fb1ab"],"邮kiwi件") == String[]
    @test filter_by_prefix(["fii"],"ju电wqwe电jube") == String[]
    @test filter_by_prefix(["bcoffeebulb"],"ASDFGH") == String[]
    @test filter_by_prefix(["qfwecdurianher电电电ry"],"foothills") == String[]
    @test filter_by_prefix(["f电电gh"],"Kilometer") == String[]
    @test filter_by_prefix(["fighoneydGigabytfhghyeew"],"fighoneydGigabytfhghyeew") == ["fighoneydGigabytfhghyeew"]
    @test filter_by_prefix(["tea"],"tea") == ["tea"]
    @test filter_by_prefix(["Kilometer"],"ifi") == String[]
    @test filter_by_prefix(["efacelaessburdocddk"],"facelaessburdocddk") == String[]
    @test filter_by_prefix(["电honapplicationeydew"],"电honeydew") == String[]
    @test filter_by_prefix(["bbuuubbu"],"gh") == String[]
    @test filter_by_prefix(["cherrybanana"],"banana") == String[]
    @test filter_by_prefix(["batmabn"],"batman") == String[]
    @test filter_by_prefix(["coocofampegrsandghJoyridefghhwine"],"coocofghhwine") == String[]
    @test filter_by_prefix(["fhgh"],"fh") == ["fhgh"]
    @test filter_by_prefix(["amazolemonn"],"amaazoon") == String[]
    @test filter_by_prefix(["fhgh"],"1ab") == String[]
    @test filter_by_prefix(["fantfhgfilterhasy"],"fantasy") == String[]
    @test filter_by_prefix(["jiinx邮i件"],"jiinx邮i件") == ["jiinx邮i件"]
    @test filter_by_prefix(["fiig"],"fig") == String[]
    @test filter_by_prefix(["fggh"],"bbbuubbhoneydewu") == String[]
    @test filter_by_prefix(["电SffUs电"],"电电") == String[]
    @test filter_by_prefix(["ampersand"],"abelderberry") == String[]
    @test filter_by_prefix(["A"],"ASDFGH") == String[]
    @test filter_by_prefix(["\t"],"forgfcoffeeiiivefg") == String[]
    @test filter_by_prefix(["jjin电SffUs电x"],"jxinx") == String[]
    @test filter_by_prefix(["电superman"],"电superman") == ["电superman"]
    @test filter_by_prefix(["alligator\t"],"\t") == String[]
    @test filter_by_prefix(["amperabeldberrberryandjujubfhghe"],"jujubfhghe") == String[]
    @test filter_by_prefix(["电coffee影", "电话"],"电supesrman") == String[]
    @test filter_by_prefix(["fighoneydGigabytfhghyeamazolemonnew"],"fighoneydGigabytfhghyeew") == String[]
    @test filter_by_prefix(["fbanyanaary"],"fbananaary") == String[]
    @test filter_by_prefix(["fighoneydGigabytfhghyeama邮zolemonnew"],"fighoneydGigabytfhghyeew") == String[]
    @test filter_by_prefix(["bu"],"qabecwbbuy") == String[]
    @test filter_by_prefix(["jujube"],"1ab") == String[]
    @test filter_by_prefix(["hfiduciaryew"],"fiii") == String[]
    @test filter_by_prefix(["mops"],"12fgifiih3") == String[]
    @test filter_by_prefix(["oneydew"],"oneydew") == ["oneydew"]
    @test filter_by_prefix(["ASD FGH"],"ASD FGH") == ["ASD FGH"]
    @test filter_by_prefix(["cocofghh"],"f电电ghfaflabbergastedon") == String[]
    @test filter_by_prefix(["honeydew"],"电") == String[]
    @test filter_by_prefix(["bappleman"],"fatasy") == String[]
    @test filter_by_prefix(["hqwertyuioponeydew"],"hqwertyuioponeydew") == ["hqwertyuioponeydew"]
    @test filter_by_prefix(["bb电coffee影uuubbu邮jjinx"],"gh") == String[]
    @test filter_by_prefix(["qwecdurianherry"],"qwecdurianheramiablery") == String[]
    @test filter_by_prefix(["ccocofghhocofghh"],"fantfhgfilterhasy") == String[]
    @test filter_by_prefix(["jujubue"],"jiinx邮i件") == String[]
    @test filter_by_prefix(["facelaess"],"facelaess") == ["facelaess"]
    @test filter_by_prefix(["foiburdockia"],"foiburdockia") == ["foiburdockia"]
    @test filter_by_prefix(["a"],"applicaburdocktabcion") == String[]
    @test filter_by_prefix(["faecelaess"],"fgghh") == String[]
    @test filter_by_prefix(["alphabet"],"邮kiwi件") == String[]
    @test filter_by_prefix(["hqwertyuioponeydew"],"hqwerty电supesrmanuioponeydew") == String[]
    @test filter_by_prefix(["jjujubeaa"],"bbu") == String[]
    @test filter_by_prefix(["fabelderrberrygh"],"fabelderrberrygh") == ["fabelderrberrygh"]
    @test filter_by_prefix(["电电子burrow"],"burrow") == String[]
    @test filter_by_prefix(["ftoothills"],"qwecdurianherry") == String[]
    @test filter_by_prefix(["jiinx邮i件"],"fbbuuubby") == String[]
    @test filter_by_prefix(["ba\nbc_"],"abc_") == String[]
    @test filter_by_prefix(["电suuperman"],"电superman") == String[]
    @test filter_by_prefix(["qwerty"],"电电话a") == String[]
    @test filter_by_prefix(["电supean"],"电superman") == String[]
    @test filter_by_prefix(["电电"],"电ifiiju电wqwe电jube") == String[]
    @test filter_by_prefix(["fantfhgfilterhasy"],"fantasay") == String[]
    @test filter_by_prefix(["burdocdk"],"oneydew") == String[]
    @test filter_by_prefix(["abelerbry"],"abelerry") == String[]
    @test filter_by_prefix(["fii", "123", "aabc", "ABC", "ab1c", "_abc", "abc_", "abc1", "1abc"],"qwwe电") == String[]
    @test filter_by_prefix(["fighoneydGigabytfhghyeew"],"\n") == String[]
    @test filter_by_prefix(["bb电coffee影uuubbu邮jojinx"],"bb电coffee影uuubbu邮jjinx") == String[]
    @test filter_by_prefix(["ae"],"a") == ["ae"]
    @test filter_by_prefix(["电影", "电子", "邮kiwi件", "电话"],"forwardburGigabytedocodkfgh") == String[]
    @test filter_by_prefix(["电fhgh"],"电") == ["电fhgh"]
    @test filter_by_prefix(["abelerbry"],"alligator\t") == String[]
    @test filter_by_prefix(["gfhgfhh"],"gfhgfhh") == ["gfhgfhh"]
    @test filter_by_prefix(["appple", "application", "alligator", "alphabet", "ampoule", "amazon", "amorous", "amaze", "ampersand", "amputee", "ambulance", "amiable", "butter", "budget", "buds", "bureaucracy", "burgher", "business", "burrow", "build", "bully", "bulge", "bulb", "bulldog", "burdock"],"bbu") == String[]
    @test filter_by_prefix(["maplp"],"suhowneydewpefhghrman") == String[]
    @test filter_by_prefix(["amperabefoothillsldberhqwertyuioponeydewrberryand"],"amperabeldberrberryand") == String[]
    @test filter_by_prefix(["fcoffeeii"],"fcoffeeii") == ["fcoffeeii"]
    @test filter_by_prefix(["电电forward"],"abelderberry") == String[]
    @test filter_by_prefix(["bannana"],"banana") == String[]
    @test filter_by_prefix(["qfwecdurianher电电电ry"],"qfwecdurianher电电电ry") == ["qfwecdurianher电电电ry"]
    @test filter_by_prefix(["ejjujube"],"amiable") == String[]
    @test filter_by_prefix(["电"],"电电") == String[]
    @test filter_by_prefix(["fhwine"],"fhwine") == ["fhwine"]
    @test filter_by_prefix(["qwwe电"],"电qwwe电") == String[]
    @test filter_by_prefix(["qwecdurianheramiableryfoothills"],"qwecdurianherry") == String[]
    @test filter_by_prefix(["fighoneydGigabw"],"fighoneydGigabyteew") == String[]
    @test filter_by_prefix(["mopss"],"mops") == ["mopss"]
    @test filter_by_prefix(["fh"],"bbuu") == String[]
    @test filter_by_prefix(["acade"],"efacelaessburdocddk") == String[]
    @test filter_by_prefix(["lalligator\t"],"lalligator\t") == ["lalligator\t"]
    @test filter_by_prefix(["a"],"aforgive") == String[]
    @test filter_by_prefix(["burgher"],"burgher") == ["burgher"]
    @test filter_by_prefix(["alligator\t"],"\tffb1abault") == String[]
    @test filter_by_prefix(["fighoneydGijjujubeaagabyteew"],"fighoneydGigabyteew") == String[]
    @test filter_by_prefix(["abcc_"],"abc_") == String[]
    @test filter_by_prefix(["jjinx"],"fabelderrberryi") == String[]
    @test filter_by_prefix(["abelderberry"],"abelderberry") == ["abelderberry"]
    @test filter_by_prefix(["burGigabytedocodkfgh"],"burGigabytedocodkfgh") == ["burGigabytedocodkfgh"]
    @test filter_by_prefix(["foigve"],"forgigve") == String[]
    @test filter_by_prefix(["fhjujubfhghegh"],"bbu") == String[]
    @test filter_by_prefix(["ASADFGH"],"ASDFGH") == String[]
    @test filter_by_prefix(["f电电ghfaviconabc_"],"f电电ghfaviconabc_") == ["f电电ghfaviconabc_"]
    @test filter_by_prefix(["abelrderemopssberry"],"abelrderberry") == String[]
    @test filter_by_prefix(["ffii"],"fiburddocki") == String[]
    @test filter_by_prefix(["filter"],"fhghapplicaburdocktabcionhfacelaessbhatmanh") == String[]
    @test filter_by_prefix(["jujubealphabet"],"电") == String[]
    @test filter_by_prefix(["QWERTYUIOP"],"QWERTYUIOP") == ["QWERTYUIOP"]
    @test filter_by_prefix(["honeydew"],"honeydew") == ["honeydew"]
    @test filter_by_prefix(["honeyde"],"1abc") == String[]
    @test filter_by_prefix(["bu"],"电superman") == String[]
    @test filter_by_prefix(["Kilometemapl"],"azmazon") == String[]
    @test filter_by_prefix(["\tpamsfii"],"gh") == String[]
    @test filter_by_prefix(["bb电coffee影uuubbu邮jojinx"],"fabelderrberryi") == String[]
    @test filter_by_prefix(["FGH"],"bbuu") == String[]
    @test filter_by_prefix(["fbbuuubby"],"QWERTbuYUIOP") == String[]
    @test filter_by_prefix(["jujubealphabet"],"film") == String[]
    @test filter_by_prefix(["fggh"],"bbbuubbu") == String[]
    @test filter_by_prefix(["电电forwardKilometemapl"],"电电forward") == ["电电forwardKilometemapl"]
    @test filter_by_prefix(["fiigh"],"fiigh") == ["fiigh"]
    @test filter_by_prefix(["fcoffebureaucuracyeiSfffsi"],"fcoffeeii") == String[]
    @test filter_by_prefix(["eQwertaY"],"电话a") == String[]
    @test filter_by_prefix(["ccocofghhocofghh"],"电superman") == String[]
    @test filter_by_prefix(["babc_"],"qabecwbbuy") == String[]
    @test filter_by_prefix(["ab"],"ftoothills") == String[]
    @test filter_by_prefix(["fcoffeeii"],"facelaessbatmanh") == String[]
    @test filter_by_prefix(["fcoffeeii电superman"],"电话a") == String[]
    @test filter_by_prefix(["howneydewfghJghoyride"],"fghJoyride") == String[]
    @test filter_by_prefix(["fighoneydGigabyteew"],"电话a") == String[]
    @test filter_by_prefix(["watreer"],"water") == String[]
    @test filter_by_prefix(["apple", "banana", "cherry", "durian", "honeydewburgher", "elderberry", "fig", "grape", "honeydew", "jujube", "kiwi", "cocofghh", "lemon"],"ambulance") == String[]
    @test filter_by_prefix(["efacelaessburdocd"],"facelaessburdocddk") == String[]
    @test filter_by_prefix(["qabcwecherwry"],"hfidrew") == String[]
    @test filter_by_prefix(["kiwi"],"kiwi") == ["kiwi"]
    @test filter_by_prefix(["amaazflabbergastedoon"],"amazolemonn") == String[]
    @test filter_by_prefix(["电honeydew"],"fi") == String[]
    @test filter_by_prefix(["bulance"],"ambulance") == String[]
    @test filter_by_prefix(["fggh"],"buds") == String[]
    @test filter_by_prefix(["fiburcki"],"fiburcki") == ["fiburcki"]
    @test filter_by_prefix(["apple"],"efacelaessburdocd") == String[]
    @test filter_by_prefix(["qwerty", "asdfgh", "电a话a", "QwertY", "qwertyuiop", "QWERTYUIOP", "asdfgh", "ASDFGH", "favicon", "ASD FGH"],"qbatmanwne") == String[]
    @test filter_by_prefix(["f电电gh"],"bulge") == String[]
    @test filter_by_prefix(["heoneydew"],"heoneydew") == ["heoneydew"]
    @test filter_by_prefix(["fijujubealphabet"],"bbbuubbu") == String[]
    @test filter_by_prefix(["bb电coffee影uuubbu邮jojinx"],"winne") == String[]
    @test filter_by_prefix(["honeydGigabyteew\t"],"honeydGigabyteew\t") == ["honeydGigabyteew\t"]
    @test filter_by_prefix(["电电子"],"FGH电电子") == String[]
    @test filter_by_prefix(["Joyride"],"电") == String[]
    @test filter_by_prefix(["jujubue电"],"jujubue电") == ["jujubue电"]
    @test filter_by_prefix(["fgh"],"bbbu电电ubbu") == String[]
    @test filter_by_prefix(["123", "fabric", "ab1c", "_abc", "abc_", "ab1", "1abc"],"aqwecherry") == String[]
end
