@testitem "051_remove_vowels_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "051_remove_vowels.jl"))
    @test remove_vowels("hello") == "hll"
    @test remove_vowels("This is a Test!") == "Ths s  Tst!"
    @test remove_vowels("i am using python") == " m sng pythn"
    @test remove_vowels("The quick brown fox jumps over the lazy dog.") == "Th qck brwn fx jmps vr th lzy dg."
    @test remove_vowels("This sentence has vowels: aeiou") == "Ths sntnc hs vwls: "
    @test remove_vowels("strawberries and cream") == "strwbrrs nd crm"
    @test remove_vowels("Programming is fun") == "Prgrmmng s fn"
    @test remove_vowels("1234567890") == "1234567890"
    @test remove_vowels("Python is awesome!") == "Pythn s wsm!"
    @test remove_vowels("How are you today?") == "Hw r y tdy?"
    @test remove_vowels("This is ai am using python Test!") == "Ths s  m sng pythn Tst!"
    @test remove_vowels("1234561207890") == "1234561207890"
    @test remove_vowels("1234561207890This is ai am using python Test!") == "1234561207890Ths s  m sng pythn Tst!"
    @test remove_vowels("Thise sentence haaei:ou") == "Ths sntnc h:"
    @test remove_vowels("The quick over the This sentence has vowels: aeioulazy dog.") == "Th qck vr th Ths sntnc hs vwls: lzy dg."
    @test remove_vowels("1234567890This sentence has vowels: aeiou") == "1234567890Ths sntnc hs vwls: "
    @test remove_vowels("st1234567890m") == "st1234567890m"
    @test remove_vowels("123456789The quick over the This sentence has vowels: aeioulazy dog.0") == "123456789Th qck vr th Ths sntnc hs vwls: lzy dg.0"
    @test remove_vowels("Pyt hon is awesome!") == "Pyt hn s wsm!"
    @test remove_vowels("1234567890This sesntence has vowels: aeiou") == "1234567890Ths ssntnc hs vwls: "
    @test remove_vowels("hel") == "hl"
    @test remove_vowels("hellhelloo") == "hllhll"
    @test remove_vowels("hel12344567890This sesntence has vowels: aeiou") == "hl12344567890Ths ssntnc hs vwls: "
    @test remove_vowels("strawberries and creaPyt hon is awesome!m") == "strwbrrs nd crPyt hn s wsm!m"
    @test remove_vowels("This is ahellhellooi am using python Test!") == "Ths s hllhll m sng pythn Tst!"
    @test remove_vowels("This is a T1234561207890This is ai am using python Test!est!") == "Ths s  T1234561207890Ths s  m sng pythn Tst!st!"
    @test remove_vowels("This sentence has vowels: a") == "Ths sntnc hs vwls: "
    @test remove_vowels("How are youy today?") == "Hw r yy tdy?"
    @test remove_vowels("12345687890") == "12345687890"
    @test remove_vowels("123456789The quick over the This sentence has vowels: aeioulazy dogThis is ai am using python Test!.0") == "123456789Th qck vr th Ths sntnc hs vwls: lzy dgThs s  m sng pythn Tst!.0"
    @test remove_vowels("hel1234567890l") == "hl1234567890l"
    @test remove_vowels("12345629890") == "12345629890"
    @test remove_vowels("This sentt!: a") == "Ths sntt!: "
    @test remove_vowels("123465687890") == "123465687890"
    @test remove_vowels("123456789The quicThis sentence has vowels: areiouk over t he This sentence has vowels: aeioulazy dog.0") == "123456789Th qcThs sntnc hs vwls: rk vr t h Ths sntnc hs vwls: lzy dg.0"
    @test remove_vowels("Pyt hon is awmesome!") == "Pyt hn s wmsm!"
    @test remove_vowels("hel12344567890This sesntehellhelloonce has vowels: aeiou") == "hl12344567890Ths ssnthllhllnc hs vwls: "
    @test remove_vowels("helloThis is ai am using python Test!") == "hllThs s  m sng pythn Tst!"
    @test remove_vowels("i am using pyt12345687890hon") == " m sng pyt12345687890hn"
    @test remove_vowels("1234Python is awesome!5629890") == "1234Pythn s wsm!5629890"
    @test remove_vowels("Thhel12344567890This sesntehellhelloonce has vowels: aeioue quick brown fox jumps over azy dog.") == "Thhl12344567890Ths ssnthllhllnc hs vwls:  qck brwn fx jmps vr zy dg."
    @test remove_vowels("How are youyHow are you today? today?") == "Hw r yyHw r y tdy? tdy?"
    @test remove_vowels("hel12344567890This sesntehellhelloonce has vowels: aei123465687890ou") == "hl12344567890Ths ssnthllhllnc hs vwls: 123465687890"
    @test remove_vowels("123445691207890") == "123445691207890"
    @test remove_vowels("This sent t!: a") == "Ths snt t!: "
    @test remove_vowels("Thise ence haaei:ou") == "Ths nc h:"
    @test remove_vowels("This sentence has vowels: aeHow are you today?iou") == "Ths sntnc hs vwls: Hw r y tdy?"
    @test remove_vowels("Progmming is fun") == "Prgmmng s fn"
    @test remove_vowels("i am usinng python") == " m snng pythn"
    @test remove_vowels("12314561207890") == "12314561207890"
    @test remove_vowels("This senheltence has vowels: aeiou") == "Ths snhltnc hs vwls: "
    @test remove_vowels("hel12344567890This sesntehellhelloonce has vowels: iou") == "hl12344567890Ths ssnthllhllnc hs vwls: "
    @test remove_vowels("This is a T1234561207890This is ai am using pythomn Test!est!") == "Ths s  T1234561207890Ths s  m sng pythmn Tst!st!"
    @test remove_vowels("123456789The quick  the This sentence has vowels: aeioulazy dog.0") == "123456789Th qck  th Ths sntnc hs vwls: lzy dg.0"
    @test remove_vowels("172345678890") == "172345678890"
    @test remove_vowels("The quick over the This senntence has vowels: aeioulazy dog.") == "Th qck vr th Ths snntnc hs vwls: lzy dg."
    @test remove_vowels("1234456912807890") == "1234456912807890"
    @test remove_vowels("123456789The quick  sthe This sentence has vowels: aeioulazThis is a T1234561207890This is ai am using python Test!est!y dog.0") == "123456789Th qck  sth Ths sntnc hs vwls: lzThs s  T1234561207890Ths s  m sng pythn Tst!st!y dg.0"
    @test remove_vowels("This is a Testi!") == "Ths s  Tst!"
    @test remove_vowels("ProgThise ence haaei:oumming is fun1234567890This sentence has vowels: aeiou") == "PrgThs nc h:mmng s fn1234567890Ths sntnc hs vwls: "
    @test remove_vowels("The quick over the This sentence has vowels: aeiouy dog.") == "Th qck vr th Ths sntnc hs vwls: y dg."
    @test remove_vowels("1234Python This is a Test!is awesome!5629890") == "1234Pythn Ths s  Tst!s wsm!5629890"
    @test remove_vowels("strawberries an12345687890d cream") == "strwbrrs n12345687890d crm"
    @test remove_vowels("Ths sent t!: a") == "Ths snt t!: "
    @test remove_vowels("Thstrawberriehs an12345687890d c a") == "Thstrwbrrhs n12345687890d c "
    @test remove_vowels("Thisa is a Testi!") == "Ths s  Tst!"
    @test remove_vowels("This is ahellhellooi am This sentence has vowels: ausing python Test!") == "Ths s hllhll m Ths sntnc hs vwls: sng pythn Tst!"
    @test remove_vowels("123140") == "123140"
    @test remove_vowels("This is ahellst1234567890mg python Test!") == "Ths s hllst1234567890mg pythn Tst!"
    @test remove_vowels("12734567890") == "12734567890"
    @test remove_vowels("How are you t oday?") == "Hw r y t dy?"
    @test remove_vowels("123445691280789This sentence has vowels: aeHow are you today?iou0") == "123445691280789Ths sntnc hs vwls: Hw r y tdy?0"
    @test remove_vowels("CX") == "CX"
    @test remove_vowels("This senheltence has v1234568789s: aeiou") == "Ths snhltnc hs v1234568789s: "
    @test remove_vowels("1234656helloThis is ai am using python Test!0") == "1234656hllThs s  m sng pythn Tst!0"
    @test remove_vowels("CCX") == "CCX"
    @test remove_vowels("Progmminig is fun") == "Prgmmng s fn"
    @test remove_vowels("121234Python This is a Test!is awesome!56298903445691207890") == "121234Pythn Ths s  Tst!s wsm!56298903445691207890"
    @test remove_vowels("123456121234Python This is a Test!is awesome!562989034456912078901207890") == "123456121234Pythn Ths s  Tst!s wsm!562989034456912078901207890"
    @test remove_vowels("Thisa This is a T1234561207890This is ai am using pythomn Test!est!is a Testi!") == "Ths Ths s  T1234561207890Ths s  m sng pythmn Tst!st!s  Tst!"
    @test remove_vowels("1234This sentence has vowels: a561207890This is ai am using python Test!") == "1234Ths sntnc hs vwls: 561207890Ths s  m sng pythn Tst!"
    @test remove_vowels("hel12344567890This sesntehThise sentence haaei:ouellhelloonce has vowels: waei123465687890ou") == "hl12344567890Ths ssnthThs sntnc h:llhllnc hs vwls: w123465687890"
    @test remove_vowels("This is ahhellhellooellhellooi am using python Test!") == "Ths s hhllhllllhll m sng pythn Tst!"
    @test remove_vowels("This sentence has vowels: aeiouC") == "Ths sntnc hs vwls: C"
    @test remove_vowels("1232140") == "1232140"
    @test remove_vowels("1234Python is awesome!123456789The quicThis sentence has vowels: areiouk over t he This sentence has vowels: aeioulazy dog.0") == "1234Pythn s wsm!123456789Th qcThs sntnc hs vwls: rk vr t h Ths sntnc hs vwls: lzy dg.0"
    @test remove_vowels("1234562989012344569Programming is fun1207890") == "1234562989012344569Prgrmmng s fn1207890"
    @test remove_vowels("123456789The quick e the This sentence has 3vowels: aeioulazy dog.0") == "123456789Th qck  th Ths sntnc hs 3vwls: lzy dg.0"
    @test remove_vowels("1236912807890") == "1236912807890"
    @test remove_vowels("This is ahhellhellooelThis sentt!: alhellooi am using python Test!") == "Ths s hhllhlllThs sntt!: lhll m sng pythn Tst!"
    @test remove_vowels("This sentence has vowelss: aeHow are you today?iou") == "Ths sntnc hs vwlss: Hw r y tdy?"
    @test remove_vowels("This senThis is a Test!t t!: a") == "Ths snThs s  Tst!t t!: "
    @test remove_vowels("This is ahhellhellooelThis sentt!helloThis is ai am using python Test!: alhellooi am using python Test!") == "Ths s hhllhlllThs sntt!hllThs s  m sng pythn Tst!: lhll m sng pythn Tst!"
    @test remove_vowels("This 123445691280789This sentence has vowels: aeHow are you today?iou0ssentence has vowels: a") == "Ths 123445691280789Ths sntnc hs vwls: Hw r y tdy?0ssntnc hs vwls: "
    @test remove_vowels("i am 123140using python") == " m 123140sng pythn"
    @test remove_vowels("Thais sentence has vowels: aeHow are you today?iou") == "Ths sntnc hs vwls: Hw r y tdy?"
    @test remove_vowels("This sentence has vowels: aeHowThais sentence has vowels: aeHow are you today?iou are you today?iou") == "Ths sntnc hs vwls: HwThs sntnc hs vwls: Hw r y tdy? r y tdy?"
    @test remove_vowels("This sentence hsas vowelss: aeHow are you today?iou") == "Ths sntnc hss vwlss: Hw r y tdy?"
    @test remove_vowels("Thisa iProgThise ence haaei:oumming is fun1234567890This sentence has vowels: aeious a Testi!") == "Ths PrgThs nc h:mmng s fn1234567890Ths sntnc hs vwls: s  Tst!"
    @test remove_vowels("How ahelloThis is ai am using python Test!re you today?") == "Hw hllThs s  m sng pythn Tst!r y tdy?"
    @test remove_vowels("AEIOUaeiouq") == "q"
    @test remove_vowels("abcd\n\n\n\nefghijklmnopqrstuvwxyz") == "bcd\n\n\n\nfghjklmnpqrstvwxyz"
    @test remove_vowels("Hello, how are you today?") == "Hll, hw r y tdy?"
    @test remove_vowels("aaaaAAAABBBCCCdddDEEEE!") == "BBBCCCdddD!"
    @test remove_vowels("xXyYzZ") == "xXyYzZ"
    @test remove_vowels("Hello world!") == "Hll wrld!"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10jklmnopqrstuvwxyzzzzzzz") == "12b3c4d56f7g8h910jklmnpqrstvwxyzzzzzzz"
    @test remove_vowels("example@example.com") == "xmpl@xmpl.cm"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and var!ous caps.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vr!s cps."
    @test remove_vowels("Th!s") == "Th!s"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ousar!ous caps.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!sr!s cps."
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10jklmnopqrstuvwxyzzzzzzzaaaaAAAABBBCCCdddDEEEE!") == "12b3c4d56f7g8h910jklmnpqrstvwxyzzzzzzzBBBCCCdddD!"
    @test remove_vowels("Hello worlld!") == "Hll wrlld!"
    @test remove_vowels("w!th") == "w!th"
    @test remove_vowels("AE") == ""
    @test remove_vowels("AxXyYzZE") == "xXyYzZ"
    @test remove_vowels("abcd") == "bcd"
    @test remove_vowels("Acaps.xXyYzZE") == "cps.xXyYzZ"
    @test remove_vowels("AxZXyYzZE") == "xZXyYzZ"
    @test remove_vowels("the") == "th"
    @test remove_vowels("CaaaaAAAABBBCCCdddDEEEE!") == "CBBBCCCdddD!"
    @test remove_vowels("are") == "r"
    @test remove_vowels("ATh!s 1s @ str!ng w!th numb3rs, punctuat!on, and var!ous caps.xXyYzZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vr!s cps.xXyYzZ"
    @test remove_vowels("caps.") == "cps."
    @test remove_vowels("worlld!") == "wrlld!"
    @test remove_vowels("Hello") == "Hll"
    @test remove_vowels("puuat!on,") == "pt!n,"
    @test remove_vowels("abquickcd") == "bqckcd"
    @test remove_vowels("The") == "Th"
    @test remove_vowels("The quitoday?ck brown fo x jumps over the l azy dog.") == "Th qtdy?ck brwn f x jmps vr th l zy dg."
    @test remove_vowels("xXyYZzZ") == "xXyYZzZ"
    @test remove_vowels("you") == "y"
    @test remove_vowels("w!twh") == "w!twh"
    @test remove_vowels("aaaaAAAABBBCCCdddDaEEEE!") == "BBBCCCdddD!"
    @test remove_vowels("AEIOUaeioiuq") == "q"
    @test remove_vowels("var!ous") == "vr!s"
    @test remove_vowels("x") == "x"
    @test remove_vowels("AxZX") == "xZX"
    @test remove_vowels("vvar!ousar!ous") == "vvr!sr!s"
    @test remove_vowels("1a2b3c4d5e6fz7g8h9i10jklmnopqrstuvwxyzzzzzzzaaaaAAAABBBCCCdddDEEEE!") == "12b3c4d56fz7g8h910jklmnpqrstvwxyzzzzzzzBBBCCCdddD!"
    @test remove_vowels("dog.Hello") == "dg.Hll"
    @test remove_vowels("w!wtwh") == "w!wtwh"
    @test remove_vowels("1a2b3c4d5e6fzAxXyYzZE7gcaps.8h9i10jklmnopqrstuvwxyzzzzzzzaaaaAAAABBBCCCdddDEEEE!") == "12b3c4d56fzxXyYzZ7gcps.8h910jklmnpqrstvwxyzzzzzzzBBBCCCdddD!"
    @test remove_vowels("over") == "vr"
    @test remove_vowels("fo") == "f"
    @test remove_vowels("Hello worldThe!") == "Hll wrldTh!"
    @test remove_vowels("aaaaAAAABBBCCCfoxdddDaEEEE!") == "BBBCCCfxdddD!"
    @test remove_vowels("world!") == "wrld!"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ousar!ous caps.AYxXyYzZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!sr!s cps.YxXyYzZ"
    @test remove_vowels("doelloo") == "dll"
    @test remove_vowels("ww!wtwh") == "ww!wtwh"
    @test remove_vowels("Hello worlAcaps.xXyYzZEhe!!") == "Hll wrlcps.xXyYzZh!!"
    @test remove_vowels("vvar!world!ousar!ous") == "vvr!wrld!sr!s"
    @test remove_vowels("vvar!ousar!aaaaAAAABBBCCCdddDaEEEE!") == "vvr!sr!BBBCCCdddD!"
    @test remove_vowels("oveHello worlAcaps.xXyYzZEhe!!") == "vHll wrlcps.xXyYzZh!!"
    @test remove_vowels("numb3rs,") == "nmb3rs,"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10jklmnopqrstworldThe!zzzzzzz") == "12b3c4d56f7g8h910jklmnpqrstwrldTh!zzzzzzz"
    @test remove_vowels("Hello worllquitoday?ck!") == "Hll wrllqtdy?ck!"
    @test remove_vowels("how") == "hw"
    @test remove_vowels("aAEIOUaeiouqndd") == "qndd"
    @test remove_vowels("example@example.colm") == "xmpl@xmpl.clm"
    @test remove_vowels("efghijklmnopqrstuvwxyz") == "fghjklmnpqrstvwxyz"
    @test remove_vowels("Helww!wtwhlo") == "Hlww!wtwhl"
    @test remove_vowels("doelo") == "dl"
    @test remove_vowels("1a2b3c4d5e6fzAxXyYzZE7gcaps.8h9i10jklmnopqrstuvwxyzzzzzzzaaaquickaAAAABBBCCCdddDEEEE!") == "12b3c4d56fzxXyYzZ7gcps.8h910jklmnpqrstvwxyzzzzzzzqckBBBCCCdddD!"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqrstuvwxyzzzzzzz") == "12b3c4d56f7g8h910jklmnpHlww!wtwhlqrstvwxyzzzzzzz"
    @test remove_vowels("anopqrstuvwxyxXyYZzZz") == "npqrstvwxyxXyYZzZz"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ouusarxXyYZzZ!ous caps.AYxXyYzZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!srxXyYZzZ!s cps.YxXyYzZ"
    @test remove_vowels("anazyl") == "nzyl"
    @test remove_vowels("thhe") == "thh"
    @test remove_vowels("l") == "l"
    @test remove_vowels("abcd\n\n\n\nefghlijklmnopqrstuvwxyz") == "bcd\n\n\n\nfghljklmnpqrstvwxyz"
    @test remove_vowels("worllquitoday?ck!") == "wrllqtdy?ck!"
    @test remove_vowels("lAxZX") == "lxZX"
    @test remove_vowels("tworlAcaps.xXyYzZEhe!!hhhe") == "twrlcps.xXyYzZh!!hhh"
    @test remove_vowels("caps.AYxXyYzZE") == "cps.YxXyYzZ"
    @test remove_vowels("brownAEIOUaeioiuq") == "brwnq"
    @test remove_vowels("anorstuvwxyxXyYZzZz") == "nrstvwxyxXyYZzZz"
    @test remove_vowels("ATh!s 1s @ strHello,!ng w!th numb3rs, punctuat!on, and var!ous caps.xXyYzZE") == "Th!s 1s @ strHll,!ng w!th nmb3rs, pnctt!n, nd vr!s cps.xXyYzZ"
    @test remove_vowels("caps.AEAYxXyYzZE") == "cps.YxXyYzZ"
    @test remove_vowels("exampletworlAcaps.xXyYzZEhe!!hhhe@example.colm") == "xmpltwrlcps.xXyYzZh!!hhh@xmpl.clm"
    @test remove_vowels("Hello worhe!") == "Hll wrh!"
    @test remove_vowels("lftoSCkoD") == "lftSCkD"
    @test remove_vowels("vvar!worcaps.AYxXyYzZEld!ousar!ous") == "vvr!wrcps.YxXyYzZld!sr!s"
    @test remove_vowels("and") == "nd"
    @test remove_vowels("ll") == "ll"
    @test remove_vowels("Hello wor") == "Hll wr"
    @test remove_vowels("str!ng") == "str!ng"
    @test remove_vowels("Hello,") == "Hll,"
    @test remove_vowels("oveHello wstrHello,!ngorlAcaps.xXyYzZEhe!!") == "vHll wstrHll,!ngrlcps.xXyYzZh!!"
    @test remove_vowels("Hello worllquy?ck!") == "Hll wrllqy?ck!"
    @test remove_vowels("quick") == "qck"
    @test remove_vowels("strHello,!ng") == "strHll,!ng"
    @test remove_vowels("@") == "@"
    @test remove_vowels("punctuat!on,") == "pnctt!n,"
    @test remove_vowels("sSsS") == "sSsS"
    @test remove_vowels("pp") == "pp"
    @test remove_vowels("AxXyYwzZEworllquitoday?ck!") == "xXyYwzZwrllqtdy?ck!"
    @test remove_vowels("dog.") == "dg."
    @test remove_vowels("aaaaAAAABBBCCCfovvar!world!ousar!ousxdddDaEEEE!") == "BBBCCCfvvr!wrld!sr!sxdddD!"
    @test remove_vowels("punctuat!oHello worlld!n,") == "pnctt!Hll wrlld!n,"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, AxZXand vvar!ouusarxXyYZzZ!ous caps.AYxXyYzZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, xZXnd vvr!srxXyYZzZ!s cps.YxXyYzZ"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ousar!ous caps.AzZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!sr!s cps.zZ"
    @test remove_vowels("Th!s 1s @ str!ng wt!th numb3rs, punctuat!on, and vvar!ousar!ous caps.AzZE") == "Th!s 1s @ str!ng wt!th nmb3rs, pnctt!n, nd vvr!sr!s cps.zZ"
    @test remove_vowels("CaaaaAAAABBBCCCdddDEEEEE!") == "CBBBCCCdddD!"
    @test remove_vowels("vvar!ousar!ABBBCCCdddDaEEEE!") == "vvr!sr!BBBCCCdddD!"
    @test remove_vowels("HTh!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ousar!ous caps.AYxXyYzZEello world!") == "HTh!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!sr!s cps.YxXyYzZll wrld!"
    @test remove_vowels("over1a2b3c4d5e6f7g8h9i10jklmnopqrstuvwxyzzzzzzz") == "vr12b3c4d56f7g8h910jklmnpqrstvwxyzzzzzzz"
    @test remove_vowels("Th!s 1s @ stsr!ng w!th numb3rs, punctuat!on, and vvar!ousar!ous caps.AYxXyYzZEAxZXyYzZE") == "Th!s 1s @ stsr!ng w!th nmb3rs, pnctt!n, nd vvr!sr!s cps.YxXyYzZxZXyYzZ"
    @test remove_vowels("doeloIZdDL") == "dlZdDL"
    @test remove_vowels("AxZXyYzZbrownE") == "xZXyYzZbrwn"
    @test remove_vowels("Hello wd!") == "Hll wd!"
    @test remove_vowels("1a2b3c4d5e6fz7g8h9i10jklmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE!") == "12b3c4d56fz7g8h910jklmnpqrstvwxyzzzzzzzHll wd!BBBCCCdddD!"
    @test remove_vowels("lazy") == "lzy"
    @test remove_vowels("xXyYzdoeloIZdDLZ") == "xXyYzdlZdDLZ"
    @test remove_vowels("lftoSCkotD") == "lftSCktD"
    @test remove_vowels("quitoday?ck") == "qtdy?ck"
    @test remove_vowels("Hello theworllquitoday?ck!") == "Hll thwrllqtdy?ck!"
    @test remove_vowels("wor") == "wr"
    @test remove_vowels("brown") == "brwn"
    @test remove_vowels("caps.xXyYzZE") == "cps.xXyYzZ"
    @test remove_vowels("abqabcd\n\n\n\nefghijklmnopqrstuvwxyzuickvcd") == "bqbcd\n\n\n\nfghjklmnpqrstvwxyzckvcd"
    @test remove_vowels("1s") == "1s"
    @test remove_vowels("thvvayYZzZ!ouse") == "thvvyYZzZ!s"
    @test remove_vowels("1a2b3c4d5e6fzAxXyYzZE7gcaps.8kh9i10jklmnopqrstuvwxyzzzzzzzaaaquickaAAAABBBCCCdddDEEEE!") == "12b3c4d56fzxXyYzZ7gcps.8kh910jklmnpqrstvwxyzzzzzzzqckBBBCCCdddD!"
    @test remove_vowels("ATh!s 1s @ straHello,!ng w!th numb3rs, punctuat!on, and var!ous caps.xXyYzZE") == "Th!s 1s @ strHll,!ng w!th nmb3rs, pnctt!n, nd vr!s cps.xXyYzZ"
    @test remove_vowels("1a2b3c4d5e6fzAxXyYzZE7gcaps.8h9i") == "12b3c4d56fzxXyYzZ7gcps.8h9"
    @test remove_vowels("Hlo wor") == "Hl wr"
    @test remove_vowels("wd!") == "wd!"
    @test remove_vowels("The quick brown fox jumps over the lazdog.") == "Th qck brwn fx jmps vr th lzdg."
    @test remove_vowels("AxZXyYzZbraaaaAAAABBBCCCdddDaEEEE!ownE") == "xZXyYzZbrBBBCCCdddD!wn"
    @test remove_vowels("Hello  worlld!") == "Hll  wrlld!"
    @test remove_vowels("AxZXyYzEZE") == "xZXyYzZ"
    @test remove_vowels("1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE!") == "12b3c4d56fz7g8h910jkldlZdDLmnpqrstvwxyzzzzzzzHll wd!BBBCCCdddD!"
    @test remove_vowels("vvar!ouusarxXyYZzZ!ous") == "vvr!srxXyYZzZ!s"
    @test remove_vowels("aaaaAAAABBBCCCfEoxdddDaEEEE!") == "BBBCCCfxdddD!"
    @test remove_vowels("ATh!s 1s @ stsr!ng w!th numb3rs, punctuat!on, and vvar!ousar!ous caps.AYxXyYzZEAxZXyYzZEcaps.xXyYzZE") == "Th!s 1s @ stsr!ng w!th nmb3rs, pnctt!n, nd vvr!sr!s cps.YxXyYzZxZXyYzZcps.xXyYzZ"
    @test remove_vowels("w!h") == "w!h"
    @test remove_vowels("howoveHello worlAcaps.xXyYzZEhe!!") == "hwvHll wrlcps.xXyYzZh!!"
    @test remove_vowels("worlAcaps.xXyYzZEhe!!") == "wrlcps.xXyYzZh!!"
    @test remove_vowels("AEIOHlo woroiuq") == "Hl wrq"
    @test remove_vowels("ww!wtwth") == "ww!wtwth"
    @test remove_vowels("aaaaACCCdddDaEEEE!") == "CCCdddD!"
    @test remove_vowels("w!thHello wd!") == "w!thHll wd!"
    @test remove_vowels("oveello worlAcaps.xXyYzZEhe!!") == "vll wrlcps.xXyYzZh!!"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvnar!ousar!ous caps.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvnr!sr!s cps."
    @test remove_vowels("wdoeloIZdDL") == "wdlZdDL"
    @test remove_vowels("over1a2b3c4d5anopqrstuvwxyxXyYZzZzvwxyzzzzzzz") == "vr12b3c4d5npqrstvwxyxXyYZzZzvwxyzzzzzzz"
    @test remove_vowels("mFjXdJWPBt") == "mFjXdJWPBt"
    @test remove_vowels("The quick brown fox jumps ovelftoSCkoDr the lazdog.") == "Th qck brwn fx jmps vlftSCkDr th lzdg."
    @test remove_vowels("HTh!s 1s @ str!ng w!th numb3rs, punctuat!on,brown and vvar!ousar!ous caps.AYxXyYzZEello world!") == "HTh!s 1s @ str!ng w!th nmb3rs, pnctt!n,brwn nd vvr!sr!s cps.YxXyYzZll wrld!"
    @test remove_vowels("bHTh!s 1s @ str!ng w!th numb3rs, punctuat!on,brown and vvar!ousar!ous caps.AYxXyYzZEello world!rownw!thHello wd!") == "bHTh!s 1s @ str!ng w!th nmb3rs, pnctt!n,brwn nd vvr!sr!s cps.YxXyYzZll wrld!rwnw!thHll wd!"
    @test remove_vowels("anazylyou") == "nzyly"
    @test remove_vowels("anopqrstuvwTh!sxyxXyYZzZz") == "npqrstvwTh!sxyxXyYZzZz"
    @test remove_vowels("Hello1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE! worldThe!") == "Hll12b3c4d56fz7g8h910jkldlZdDLmnpqrstvwxyzzzzzzzHll wd!BBBCCCdddD! wrldTh!"
    @test remove_vowels("bHTh!s 1s @ str!ng w!world!, punctuat!on,brown and vvar!ousar!ous caps.AYxXyYzZEello world!rownw!thHello wd!") == "bHTh!s 1s @ str!ng w!wrld!, pnctt!n,brwn nd vvr!sr!s cps.YxXyYzZll wrld!rwnw!thHll wd!"
    @test remove_vowels("tworlAcaps.xXyyYzZEhe!!hhhe") == "twrlcps.xXyyYzZh!!hhh"
    @test remove_vowels("Helww!wtwhloAxZXyYzZbraaaaAAAABBBCCCdddDaEEEE!ownE") == "Hlww!wtwhlxZXyYzZbrBBBCCCdddD!wn"
    @test remove_vowels("worlld!n,") == "wrlld!n,"
    @test remove_vowels("braaaaAAAABBBCCCfEoxdddDaEEEEn") == "brBBBCCCfxdddDn"
    @test remove_vowels("ATh!s 1s @ stsr!ng w!th numb3rs, punctuat!on, and vvar!ousarr!ous caps.AYxXyYzZEAxZXyYzZEcaps.xXyYzZE") == "Th!s 1s @ stsr!ng w!th nmb3rs, pnctt!n, nd vvr!srr!s cps.YxXyYzZxZXyYzZcps.xXyYzZ"
    @test remove_vowels("anazaaaaAAAABBBCCCdddDEEEE!yl") == "nzBBBCCCdddD!yl"
    @test remove_vowels("caps.AYxXyYzZEAxZXyYzZEcaps.xXyYzZE") == "cps.YxXyYzZxZXyYzZcps.xXyYzZ"
    @test remove_vowels("wd!aAAAAAxZXyYzEZEBBBCCCdddDEEEE!") == "wd!xZXyYzZBBBCCCdddD!"
    @test remove_vowels("1a2b3c4d5e6fz7g8h9i10jklmnopqrstuvwxyzzzzzzzaaaHello") == "12b3c4d56fz7g8h910jklmnpqrstvwxyzzzzzzzHll"
    @test remove_vowels("AEIOlHlo woroiuq") == "lHl wrq"
    @test remove_vowels("eHello worllquy?ck!wdoeloIZdDL") == "Hll wrllqy?ck!wdlZdDL"
    @test remove_vowels("worllquy?ck!wdoeloIZdDL") == "wrllqy?ck!wdlZdDL"
    @test remove_vowels("mFjoveHello wstrHello,!ngorlAcaps.xXyYzYZEhe!!JWPBt") == "mFjvHll wstrHll,!ngrlcps.xXyYzYZh!!JWPBt"
    @test remove_vowels("ATh!s 1s @ stsr!ng w!th numb3rs, punctuat!on, and vvar!ousabqabcd\n\n\n\nefghijklmnopqrstuvwxyzuickvcdarr!ous caps.AYxXyYzZEAxZXyYzZEcaps.xXyYzZE") == "Th!s 1s @ stsr!ng w!th nmb3rs, pnctt!n, nd vvr!sbqbcd\n\n\n\nfghjklmnpqrstvwxyzckvcdrr!s cps.YxXyYzZxZXyYzZcps.xXyYzZ"
    @test remove_vowels("1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE!") == "12b3c4d56fz7g8h910jkldlZdDLxyzzzzzzzHll wd!BBBCCCdddD!"
    @test remove_vowels("AEE") == ""
    @test remove_vowels("doeCaaaaAAAABBBCCCdddDEEEE!lloo") == "dCBBBCCCdddD!ll"
    @test remove_vowels("caps.AYxXyYzZEAxZXyYzZE") == "cps.YxXyYzZxZXyYzZ"
    @test remove_vowels("lAxZXyYzZbraaaaAAAABBBCCCdddDaEEEE!ownEftoSCkoD") == "lxZXyYzZbrBBBCCCdddD!wnftSCkD"
    @test remove_vowels("worll1a2b3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqrstuvwxyzzzzzzzquitoday?ck!") == "wrll12b3c4d56f7g8h910jklmnpHlww!wtwhlqrstvwxyzzzzzzzqtdy?ck!"
    @test remove_vowels("AEIOlHlo") == "lHl"
    @test remove_vowels("AAxZX") == "xZX"
    @test remove_vowels("vousar!ous") == "vsr!s"
    @test remove_vowels("vvar!ousar!ABBBCCCdddDaEEBEE!") == "vvr!sr!BBBCCCdddDB!"
    @test remove_vowels("1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLxyzzzzzzzaaaHello") == "12b3c4d56fz7g8h910jkldlZdDLxyzzzzzzzHll"
    @test remove_vowels("AEIOlareHlo") == "lrHl"
    @test remove_vowels("doworoiuqelo") == "dwrql"
    @test remove_vowels("Hello theworllquitodacaps.AzZEy?ck!") == "Hll thwrllqtdcps.zZy?ck!"
    @test remove_vowels("anorstuvwxyxXyYZzZzdoeloIZdDL") == "nrstvwxyxXyYZzZzdlZdDL"
    @test remove_vowels("worlAcaps.xsXyYzZEheAxZXyYzZE!!") == "wrlcps.xsXyYzZhxZXyYzZ!!"
    @test remove_vowels("lazyy") == "lzyy"
    @test remove_vowels("oveHello worlAcHello worllquy?ck!aps.xXyYzZEhe!!") == "vHll wrlcHll wrllqy?ck!ps.xXyYzZh!!"
    @test remove_vowels("over1awt!th2b3c4d5anopqrstuvwxyxXyYZzZzvwxyzzzzzzz") == "vr1wt!th2b3c4d5npqrstvwxyxXyYZzZzvwxyzzzzzzz"
    @test remove_vowels("HelAxZXyYzZbrownElo worldThe!") == "HlxZXyYzZbrwnl wrldTh!"
    @test remove_vowels("over1a2b3c4d5e6f7g8h9i10jklmnopqrstuvCaaaaAAAABBBCCCdddDEEEEE!wxyzzzzzzz") == "vr12b3c4d56f7g8h910jklmnpqrstvCBBBCCCdddD!wxyzzzzzzz"
    @test remove_vowels("tIZdDLhvvayYZzZ!ouse") == "tZdDLhvvyYZzZ!s"
    @test remove_vowels("oveHello worlAcHello worllquy?ck!aps.xXyYzZEhe!caps.xXyYzZE!") == "vHll wrlcHll wrllqy?ck!ps.xXyYzZh!cps.xXyYzZ!"
    @test remove_vowels("1a2b3c4dmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE!") == "12b3c4dmnpqrstvwxyzzzzzzzHll wd!BBBCCCdddD!"
    @test remove_vowels("Hlo wolAxZXyYzZbraaaaAAAABBBCCCdddDaEEEE!ownEftoSCkoDr") == "Hl wlxZXyYzZbrBBBCCCdddD!wnftSCkDr"
    @test remove_vowels("Hello1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello") == "Hll12b3c4d56fz7g8h910jkldlZdDLmnpqrstvwxyzzzzzzzHll"
    @test remove_vowels("vvar!ous!ar!ous") == "vvr!s!r!s"
    @test remove_vowels("yYzZbraaaaAAAABBBCCCdddDaEEEE!ownE") == "yYzZbrBBBCCCdddD!wn"
    @test remove_vowels("") == ""
    @test remove_vowels("ww!wtwefghijklmnopqrstuvwxyzuickvcdarr!oush") == "ww!wtwfghjklmnpqrstvwxyzckvcdrr!sh"
    @test remove_vowels("wwor") == "wwr"
    @test remove_vowels("1a2b3c4d5e6fzAxXyYzZE7gcaps.8h9i10jklmnopqrstuvwxyzzzazzzzaaaquickaAAAABBBCCCdddDEEEE!") == "12b3c4d56fzxXyYzZ7gcps.8h910jklmnpqrstvwxyzzzzzzzqckBBBCCCdddD!"
    @test remove_vowels("punctuat!on,brown") == "pnctt!n,brwn"
    @test remove_vowels("Helww!wtwhloAxZXyYworllquitoday?ck!zZbraaaaAAAABBBCCCdddDaEEEE!ownE") == "Hlww!wtwhlxZXyYwrllqtdy?ck!zZbrBBBCCCdddD!wn"
    @test remove_vowels("AxXyworlAxcaps.xXyYzZEhe!!YzZE") == "xXywrlxcps.xXyYzZh!!YzZ"
    @test remove_vowels("mFjXdJWPBmt") == "mFjXdJWPBmt"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10jklmnopstworldThe!zzzzzzz") == "12b3c4d56f7g8h910jklmnpstwrldTh!zzzzzzz"
    @test remove_vowels("1a2b3c4dmnopqrstuvwxyzzzzzzzaaaHello") == "12b3c4dmnpqrstvwxyzzzzzzzHll"
    @test remove_vowels("ww!wtwtwh") == "ww!wtwtwh"
    @test remove_vowels("1a2b3c4dmnopqrstuvwxyzzzzzzzaabrownaHello") == "12b3c4dmnpqrstvwxyzzzzzzzbrwnHll"
    @test remove_vowels("Hestsr!ngllo  worlld!") == "Hstsr!ngll  wrlld!"
    @test remove_vowels("eT") == "T"
    @test remove_vowels("ov") == "v"
    @test remove_vowels("ofo") == "f"
    @test remove_vowels("thanopqrstuvwTh!sxyxXyYZzZz") == "thnpqrstvwTh!sxyxXyYZzZz"
    @test remove_vowels("AEIOHlo woroiuql") == "Hl wrql"
    @test remove_vowels("efghijklmnopqrstuvwxyzuickvcdarr!ous") == "fghjklmnpqrstvwxyzckvcdrr!s"
    @test remove_vowels("oveHeleHellolo worlAcaps.xXyYzZEhe!!") == "vHlHlll wrlcps.xXyYzZh!!"
    @test remove_vowels("oveHeleHellolo") == "vHlHlll"
    @test remove_vowels("var!xXyYZzZous") == "vr!xXyYZzZs"
    @test remove_vowels("vvar!ouosar!ous") == "vvr!sr!s"
    @test remove_vowels("1a2b3c4d5e6fz7g8h9i10jklmnopqrstuvwxyzzzzzzzaaaaAA1AABBBCCCdddDEEEE!") == "12b3c4d56fz7g8h910jklmnpqrstvwxyzzzzzzz1BBBCCCdddD!"
    @test remove_vowels("oveello") == "vll"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ouusarxXZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!srxXZ"
    @test remove_vowels("oveHello wstrHello,!ngorlAcaps.xXyYzZEhe!!lazy") == "vHll wstrHll,!ngrlcps.xXyYzZh!!lzy"
    @test remove_vowels("ATh!s 1s @ stsr!ng w!th numb3rs, punctuat!on, and vvar!ousabqabcd\n\n\n\nefghijklmnopqrsaaaaAAAABBBCCCfEoxdddDaEEEE!tuvwxyzuickvcdarr!ous caps.AYxXyYzZEAxZXyYEzZEcaps.xXyYzZE") == "Th!s 1s @ stsr!ng w!th nmb3rs, pnctt!n, nd vvr!sbqbcd\n\n\n\nfghjklmnpqrsBBBCCCfxdddD!tvwxyzckvcdrr!s cps.YxXyYzZxZXyYzZcps.xXyYzZ"
    @test remove_vowels("Hellcaps.o,") == "Hllcps.,"
    @test remove_vowels("over1a2b3c4dt5anopqrstuvwxyxXyYZzZzvwxyzzzzzzz") == "vr12b3c4dt5npqrstvwxyxXyYZzZzvwxyzzzzzzz"
    @test remove_vowels("lftoSCkoDl") == "lftSCkDl"
    @test remove_vowels("HellHello1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE! wdoeloIZdDLworldThe!yYzZEhe!!") == "HllHll12b3c4d56fz7g8h910jkldlZdDLmnpqrstvwxyzzzzzzzHll wd!BBBCCCdddD! wdlZdDLwrldTh!yYzZh!!"
    @test remove_vowels("over1a2b3c4d5e6f7rstuvwxyzzzzzzz") == "vr12b3c4d56f7rstvwxyzzzzzzz"
    @test remove_vowels("anzazylyou") == "nzzyly"
    @test remove_vowels("caps.AYxXyYzZEworllquy?ck!AxZXyYzZE") == "cps.YxXyYzZwrllqy?ck!xZXyYzZ"
    @test remove_vowels("AEIOlHlEo") == "lHl"
    @test remove_vowels("AxXyYwzZEworllquitoday?ck!AxXyworlAxcaps.xXyYzZEhe!!YzZE") == "xXyYwzZwrllqtdy?ck!xXywrlxcps.xXyYzZh!!YzZ"
    @test remove_vowels("@anazyl") == "@nzyl"
    @test remove_vowels("c1a2b3c4d5e6fzAxXyYzZE7gcaps.8h9i10jklmnopqrstuvwxyzzzzzzzaaaaAAAABBBCCCdddDEEEE!apZE") == "c12b3c4d56fzxXyYzZ7gcps.8h910jklmnpqrstvwxyzzzzzzzBBBCCCdddD!pZ"
    @test remove_vowels("quitoday?cworll1a2b3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqrstuvwxyzzzzzzzquitoday?ck!") == "qtdy?cwrll12b3c4d56f7g8h910jklmnpHlww!wtwhlqrstvwxyzzzzzzzqtdy?ck!"
    @test remove_vowels("AxZXyYzZbrotIZdDLhvvayYZzZ!ousewnE") == "xZXyYzZbrtZdDLhvvyYZzZ!swn"
    @test remove_vowels("aHello,nazylyou") == "Hll,nzyly"
    @test remove_vowels("Helww!wtwhloAxZXyYy?ck!zZbraaaaAAAABBBCCCdddDaEEEE!ownE") == "Hlww!wtwhlxZXyYy?ck!zZbrBBBCCCdddD!wn"
    @test remove_vowels("ATh!s 1s @ stsr!ng w!th numb3rs, punworllquy?ck!wdoeloIZdDLctuat!on, and vvar!ousar!ous caps.AYxXyYzZEAxZXyYzZEcaps.xXyYzZE") == "Th!s 1s @ stsr!ng w!th nmb3rs, pnwrllqy?ck!wdlZdDLctt!n, nd vvr!sr!s cps.YxXyYzZxZXyYzZcps.xXyYzZ"
    @test remove_vowels("vvar!ouusarxXZE") == "vvr!srxXZ"
    @test remove_vowels("Hello worl!") == "Hll wrl!"
    @test remove_vowels("efghistuvwxyz") == "fghstvwxyz"
    @test remove_vowels("hthe") == "hth"
    @test remove_vowels("1a2b3cvvar!ouusarxXyYZuzZ!ous4d5e6fz7g8h9i10jkldoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello") == "12b3cvvr!srxXyYZzZ!s4d56fz7g8h910jkldlZdDLmnpqrstvwxyzzzzzzzHll"
    @test remove_vowels("1a2b3c4d5e6fz7g8h9i10jklmnopqrstuvBCCCdddDEEEtE!") == "12b3c4d56fz7g8h910jklmnpqrstvBCCCdddDt!"
    @test remove_vowels("IZdDL") == "ZdDL"
    @test remove_vowels("tworlAcaps.xyyYzZEhe!!hhhe") == "twrlcps.xyyYzZh!!hhh"
    @test remove_vowels("dog.HelllftoSCkoDlo") == "dg.HlllftSCkDl"
    @test remove_vowels("efghijklmnopqrsttuvwxyz") == "fghjklmnpqrsttvwxyz"
    @test remove_vowels("Hello theworllquritoday?ck!") == "Hll thwrllqrtdy?ck!"
    @test remove_vowels("Hlo") == "Hl"
    @test remove_vowels("worlld!ln,") == "wrlld!ln,"
    @test remove_vowels("andbrown") == "ndbrwn"
    @test remove_vowels("Hl") == "Hl"
    @test remove_vowels("anorstuvwxyxXyYZzZzzdoeloIZdDL") == "nrstvwxyxXyYZzZzzdlZdDL"
    @test remove_vowels("abquicckcd") == "bqcckcd"
    @test remove_vowels("Helww!wtwhloAxZXyYzZbraaaaAAAABBBCCCdpuuat!on,ddDaEEEE!ownE") == "Hlww!wtwhlxZXyYzZbrBBBCCCdpt!n,ddD!wn"
    @test remove_vowels("Helww!wtwhloAxZXyYzZbraaaaworll1a2b3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqrstuvwxyzzzzzzzquitoday?ck!AAAABBBCCCdddDaEEEE!ownE") == "Hlww!wtwhlxZXyYzZbrwrll12b3c4d56f7g8h910jklmnpHlww!wtwhlqrstvwxyzzzzzzzqtdy?ck!BBBCCCdddD!wn"
    @test remove_vowels("howoveHello worl!!") == "hwvHll wrl!!"
    @test remove_vowels("mFjoveHello") == "mFjvHll"
    @test remove_vowels("AAxcaps.AYxXyYzZEAxZXyYzZEZX") == "xcps.YxXyYzZxZXyYzZZX"
    @test remove_vowels("abqabcd\n\n\n\nefghijnklmnopqrstuvwxyzuickvcd") == "bqbcd\n\n\n\nfghjnklmnpqrstvwxyzckvcd"
    @test remove_vowels("ae") == ""
    @test remove_vowels("HelllAxZXo worlAcaps.xXyYzZEhe!!") == "HlllxZX wrlcps.xXyYzZh!!"
    @test remove_vowels("AxZXand") == "xZXnd"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, a nd vvar!ousar!ous caps.AYxXyYzZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n,  nd vvr!sr!s cps.YxXyYzZ"
    @test remove_vowels("1a2b3cz4d5e6f7g8h9i10jklmnopqrstuvwxyzzzzzzz") == "12b3cz4d56f7g8h910jklmnpqrstvwxyzzzzzzz"
    @test remove_vowels("ATh!s 1s @ str!ng w!th anazylyounumb3rs, punctuat!on, and var!ous caps.xXyYzZE") == "Th!s 1s @ str!ng w!th nzylynmb3rs, pnctt!n, nd vr!s cps.xXyYzZ"
    @test remove_vowels("exaemple@exaHelAxZXyYzZbrownElomple.com") == "xmpl@xHlxZXyYzZbrwnlmpl.cm"
    @test remove_vowels("ATh!s 1s @ straHello,!ng w!tATh!s 1s @ stsr!ng w!th numb3rs, punctuat!on, and vvar!ousabqabcd\n\n\n\nefghijklmnopqrstuvwxyzuickvcdarr!ous caps.AYxXyYzZEAxZXyYzZEcaps.xXyYzZE caps.xXyYzZE") == "Th!s 1s @ strHll,!ng w!tTh!s 1s @ stsr!ng w!th nmb3rs, pnctt!n, nd vvr!sbqbcd\n\n\n\nfghjklmnpqrstvwxyzckvcdrr!s cps.YxXyYzZxZXyYzZcps.xXyYzZ cps.xXyYzZ"
    @test remove_vowels("abcd\n\nww!wtwh\n\nefghlijklmnopqrstuvwxyz") == "bcd\n\nww!wtwh\n\nfghljklmnpqrstvwxyz"
    @test remove_vowels("vousarr!sous") == "vsrr!ss"
    @test remove_vowels("oHelww!wtwhloAxZXyYzZbraaaaAAAABBBCCCdpuuat!on,ddDaEEEE!ownEveelvlo") == "Hlww!wtwhlxZXyYzZbrBBBCCCdpt!n,ddD!wnvlvl"
    @test remove_vowels("ppAcaps.xXyYzZE") == "ppcps.xXyYzZ"
    @test remove_vowels("oveello worlAcaps.xXyYzZEhhe!!") == "vll wrlcps.xXyYzZhh!!"
    @test remove_vowels("strHo,!ng") == "strH,!ng"
    @test remove_vowels("stsr!ng") == "stsr!ng"
    @test remove_vowels("efghijklmnopqrstuvwxyzhow") == "fghjklmnpqrstvwxyzhw"
    @test remove_vowels("Th!s 1s @ str!ng w1!th numb3rs, punctuat!on, and vvar!ousar!ous caps.AzZE") == "Th!s 1s @ str!ng w1!th nmb3rs, pnctt!n, nd vvr!sr!s cps.zZ"
    @test remove_vowels("numb3randsAxZXyYzZbraaaaAAAABBBCCCdddDaEEEE!ownE,") == "nmb3rndsxZXyYzZbrBBBCCCdddD!wn,"
    @test remove_vowels("ofoo") == "f"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqrstuv8wxyzzzzzzz") == "12b3c4d56f7g8h910jklmnpHlww!wtwhlqrstv8wxyzzzzzzz"
    @test remove_vowels("tworlAcaps.xXyyYzZEhe!h!hhhe") == "twrlcps.xXyyYzZh!h!hhh"
    @test remove_vowels("AxZXyYzAcaps.xXyYzZEZE") == "xZXyYzcps.xXyYzZZ"
    @test remove_vowels("efghistvuvwxyz") == "fghstvvwxyz"
    @test remove_vowels("Th!s 1s @ str!ng w1!th nuHello1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE! worldThe!mb3rs, punctuat!on, and vvar!ousar!ous caps.AzZE") == "Th!s 1s @ str!ng w1!th nHll12b3c4d56fz7g8h910jkldlZdDLmnpqrstvwxyzzzzzzzHll wd!BBBCCCdddD! wrldTh!mb3rs, pnctt!n, nd vvr!sr!s cps.zZ"
    @test remove_vowels("The quick brown fox jumps overppAcaps.xXyYzZE lthe lazdog.") == "Th qck brwn fx jmps vrppcps.xXyYzZ lth lzdg."
    @test remove_vowels("lAxazyZX") == "lxzyZX"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvnar!ousar!ous ca.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvnr!sr!s c."
    @test remove_vowels("Th!s 1s @ str!ng w!th nuoveello worlAcaps.xXyYzZEhe!!mb3rs, punctuat!on, and vvar!ouusarxXyYZzZ!ousand caps.AYxXyYzZE") == "Th!s 1s @ str!ng w!th nvll wrlcps.xXyYzZh!!mb3rs, pnctt!n, nd vvr!srxXyYZzZ!snd cps.YxXyYzZ"
    @test remove_vowels("worll1a2b3c4d5e6f7g8h9iworlld!ln,10jklmnopHelww!wtwhloqrstuvwxyzzzzzzzquitoday?ck!") == "wrll12b3c4d56f7g8h9wrlld!ln,10jklmnpHlww!wtwhlqrstvwxyzzzzzzzqtdy?ck!"
    @test remove_vowels("twhabcd\n\n\n\nefghijklmnopqrstuvwxyz") == "twhbcd\n\n\n\nfghjklmnpqrstvwxyz"
    @test remove_vowels("wdd!") == "wdd!"
    @test remove_vowels("aefghistvuvwxyzbcd") == "fghstvvwxyzbcd"
    @test remove_vowels("1a2b3c4d5e6fzAxXyYzZE7gcaps.8kh9i10jklmnopqrstuvwxyzzzzzaaaquickaAAAABBBCCCdddDEEEE!") == "12b3c4d56fzxXyYzZ7gcps.8kh910jklmnpqrstvwxyzzzzzqckBBBCCCdddD!"
    @test remove_vowels("HbHTh!s 1s @ str!ng w!th numb3rs, punctuat!on,brown and vv") == "HbHTh!s 1s @ str!ng w!th nmb3rs, pnctt!n,brwn nd vv"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ouusavrxXZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!svrxXZ"
    @test remove_vowels("UVzMKnT") == "VzMKnT"
    @test remove_vowels("w!thh") == "w!thh"
    @test remove_vowels("Th!s 1s @ stsr!ngworlld! w!th numb3rs, punctuat!on, and vvar!ousar!ous caps.AYxXyYzZEAxZXyYzZE") == "Th!s 1s @ stsr!ngwrlld! w!th nmb3rs, pnctt!n, nd vvr!sr!s cps.YxXyYzZxZXyYzZ"
    @test remove_vowels("dodeloIZdDL") == "ddlZdDL"
    @test remove_vowels("1a2b3c4d5e6fzAxXyYzZE7gcap5s.8h9i") == "12b3c4d56fzxXyYzZ7gcp5s.8h9"
    @test remove_vowels("ATh!s 1s @ stsr!ng w!th numb3rs, punctuat!on, ") == "Th!s 1s @ stsr!ng w!th nmb3rs, pnctt!n, "
    @test remove_vowels("vanorstuvwxyxXyYZzZzzdoeloIZdDLousarr!sous") == "vnrstvwxyxXyYZzZzzdlZdDLsrr!ss"
    @test remove_vowels("capaov.") == "cpv."
    @test remove_vowels("AEIOlHlo uq") == "lHl q"
    @test remove_vowels("Thn!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ouusavrxXZE") == "Thn!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!svrxXZ"
    @test remove_vowels("efgijklmnopqrstuvwxyzhow") == "fgjklmnpqrstvwxyzhw"
    @test remove_vowels("quitodayd?ck") == "qtdyd?ck"
    @test remove_vowels("YFx") == "YFx"
    @test remove_vowels("dodeloIZd") == "ddlZd"
    @test remove_vowels("wwworlld!or") == "wwwrlld!r"
    @test remove_vowels("anoorstuvwxyxXyYZzZz") == "nrstvwxyxXyYZzZz"
    @test remove_vowels("apuncabqabcd\n\n\n\nefghijklmnopqrstuvwxyzuickvcdtuat!on,brown") == "pncbqbcd\n\n\n\nfghjklmnpqrstvwxyzckvcdtt!n,brwn"
    @test remove_vowels("Thn!s 1s @ ouusavrxXZE") == "Thn!s 1s @ svrxXZ"
    @test remove_vowels("AEIOlHlo wo") == "lHl w"
    @test remove_vowels("w!thHello") == "w!thHll"
    @test remove_vowels("wt!th") == "wt!th"
    @test remove_vowels("tworlAcaps.xXyyYzZEhe!!hdog.Hellohhe") == "twrlcps.xXyyYzZh!!hdg.Hllhh"
    @test remove_vowels("efghijnklmnopqrstuvwxyzuickvcd") == "fghjnklmnpqrstvwxyzckvcd"
    @test remove_vowels("HepllHello1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE! wdoeloIZdDLworldThe!yYzZEhe!!") == "HpllHll12b3c4d56fz7g8h910jkldlZdDLmnpqrstvwxyzzzzzzzHll wd!BBBCCCdddD! wdlZdDLwrldTh!yYzZh!!"
    @test remove_vowels("vvar!ouusavrxXZE") == "vvr!svrxXZ"
    @test remove_vowels("Thn!s 1ss @ ouunsavrxXZE") == "Thn!s 1ss @ nsvrxXZ"
    @test remove_vowels("theworllquitodacapwdd!s.AzZEy?ck!") == "thwrllqtdcpwdd!s.zZy?ck!"
    @test remove_vowels("eww!wtwhT") == "ww!wtwhT"
    @test remove_vowels("efghijklmnopqtIZdDLhvvayYZzZ!ouserstuvwxyz") == "fghjklmnpqtZdDLhvvyYZzZ!srstvwxyz"
    @test remove_vowels("braaaaAAAABBBCCCHello worldThe!fEoxdddDaEEEEn") == "brBBBCCCHll wrldTh!fxdddDn"
    @test remove_vowels("1a2b3c4dmwnopqrstuvwxyzzzzzzzaabrownaHello") == "12b3c4dmwnpqrstvwxyzzzzzzzbrwnHll"
    @test remove_vowels("1a2b3c4d5e6fworldThe!pstworldThe!zzzzzzz") == "12b3c4d56fwrldTh!pstwrldTh!zzzzzzz"
    @test remove_vowels("AxHello1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABthheBBCCCdddDEEEE! worldThe!ZXyYzZDE") == "xHll12b3c4d56fz7g8h910jkldlZdDLmnpqrstvwxyzzzzzzzHll wd!BthhBBCCCdddD! wrldTh!ZXyYzZD"
    @test remove_vowels("bHTh!s 1s @ str!ng w!th numb3vvar!ouusarxXZErs, punctuat!on,brown and vvar!ousar!ous caps.AYxXyYzZEello world!rownw!thHello wd!") == "bHTh!s 1s @ str!ng w!th nmb3vvr!srxXZrs, pnctt!n,brwn nd vvr!sr!s cps.YxXyYzZll wrld!rwnw!thHll wd!"
    @test remove_vowels("Thn!s 1s @ ouussavrxXZE") == "Thn!s 1s @ ssvrxXZ"
    @test remove_vowels("ATh!s 1s @ straHello,!ng w!th numb3rs, punctuat!.on, and var!ous caps.xXyYzZE") == "Th!s 1s @ strHll,!ng w!th nmb3rs, pnctt!.n, nd vr!s cps.xXyYzZ"
    @test remove_vowels("vousar!o") == "vsr!"
    @test remove_vowels("eHello worllquy?ck!wdouunsavrxXZEloIZdDL") == "Hll wrllqy?ck!wdnsvrxXZlZdDL"
    @test remove_vowels("Th!s 1s @ str!ng w1!th numb3rs, puzZE") == "Th!s 1s @ str!ng w1!th nmb3rs, pzZ"
    @test remove_vowels("AxXyYwzZEworllquitoday?ck!xcaps.xXyYzZEhe!!YzZE") == "xXyYwzZwrllqtdy?ck!xcps.xXyYzZh!!YzZ"
    @test remove_vowels("vv") == "vv"
    @test remove_vowels("twporlAcaps.xXyyYzefgijklmnopqrstuvwxyzhowhe") == "twprlcps.xXyyYzfgjklmnpqrstvwxyzhwh"
    @test remove_vowels("dog.Hellworhe!o") == "dg.Hllwrh!"
    @test remove_vowels("twhawbcd") == "twhwbcd"
    @test remove_vowels("ouunsavrxXZE") == "nsvrxXZ"
    @test remove_vowels("f1a2b3c4d5e6fz7g8h9i10jklmnopqrTh!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ouusarxXZEstuvBCCCdddDEEEtE!") == "f12b3c4d56fz7g8h910jklmnpqrTh!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!srxXZstvBCCCdddDt!"
    @test remove_vowels("ndoveHello worlAcaps.xXyYzZEhe!!d") == "ndvHll wrlcps.xXyYzZh!!d"
    @test remove_vowels("Hello1a2b3c4d5e6fz7g8h9i10jklHelww!wtwhloAxZXyYworllquitoday?ck!zZbraaaaAAAABBBCCCdddDaEEEE!ownEdoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello") == "Hll12b3c4d56fz7g8h910jklHlww!wtwhlxZXyYwrllqtdy?ck!zZbrBBBCCCdddD!wndlZdDLmnpqrstvwxyzzzzzzzHll"
    @test remove_vowels("exampletworlAycaps.xXyYzZEhe!!hhhe@example.colm") == "xmpltwrlycps.xXyYzZh!!hhh@xmpl.clm"
    @test remove_vowels("anorstuvwxyxXHello theworllquitodacaps.AzZEy?ck!L") == "nrstvwxyxXHll thwrllqtdcps.zZy?ck!L"
    @test remove_vowels("ooveello") == "vll"
    @test remove_vowels("HbHTh!s 1s @ str!ng w!th numb3rs, punctuat!on,brown and vvl") == "HbHTh!s 1s @ str!ng w!th nmb3rs, pnctt!n,brwn nd vvl"
    @test remove_vowels("mpYworld!rownw!thHelloSq") == "mpYwrld!rwnw!thHllSq"
    @test remove_vowels("wwwstrHello,!ngorlAcaps.xXyYzZEhe!!lazy!wtwth") == "wwwstrHll,!ngrlcps.xXyYzZh!!lzy!wtwth"
    @test remove_vowels("efghijklmnopqtIZdDLhvvayYZzZ!ouserstuvwxyzAE") == "fghjklmnpqtZdDLhvvyYZzZ!srstvwxyz"
    @test remove_vowels("anorstuvwxyxXHello theexample@example.comworllquitodacaps.AzZEy?ck!L") == "nrstvwxyxXHll thxmpl@xmpl.cmwrllqtdcps.zZy?ck!L"
    @test remove_vowels("mFjoeHello") == "mFjHll"
    @test remove_vowels("oworlAcaps.xsXyYzZEheAxZXyYzZE!!fo") == "wrlcps.xsXyYzZhxZXyYzZ!!f"
    @test remove_vowels("ww!wtwefghijklmnopqrstuvwxyzuickanzazylyouvcdarr!oush") == "ww!wtwfghjklmnpqrstvwxyzcknzzylyvcdrr!sh"
    @test remove_vowels("Th!s 1s @ str!ng w!th num.b3rs, punctuat!on, and vvnar!ousar!ous caps.") == "Th!s 1s @ str!ng w!th nm.b3rs, pnctt!n, nd vvnr!sr!s cps."
    @test remove_vowels("vvnar!ousar!ous") == "vvnr!sr!s"
    @test remove_vowels("vstsr!ngar!xXyYZzZous") == "vstsr!ngr!xXyYZzZs"
    @test remove_vowels("oveHelworlAcaps.xXyYzZEhe!!") == "vHlwrlcps.xXyYzZh!!"
    @test remove_vowels("ppAcquitoday?cworll1a2b3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqrstuvwxyzzzzzzzquitoday?ck!aps.xXyYzZE") == "ppcqtdy?cwrll12b3c4d56f7g8h910jklmnpHlww!wtwhlqrstvwxyzzzzzzzqtdy?ck!ps.xXyYzZ"
    @test remove_vowels("dw!thHello wd!") == "dw!thHll wd!"
    @test remove_vowels("evvar!ouusarxXyYZzZ!ousandfghijnklmnopqrstuvwxyzuickvd") == "vvr!srxXyYZzZ!sndfghjnklmnpqrstvwxyzckvd"
    @test remove_vowels("efghijklmnwopqrstuvwxyz") == "fghjklmnwpqrstvwxyz"
    @test remove_vowels("1amnopqrstuvwxyzzzzzaaaquickaAAAABBBCCCdddDEEEE!") == "1mnpqrstvwxyzzzzzqckBBBCCCdddD!"
    @test remove_vowels("efghijklmnopqtaaaaACCCdddDaEEEE!ouserstuvwxyz") == "fghjklmnpqtCCCdddD!srstvwxyz"
    @test remove_vowels("AAx1a2b3c4d5e6f7g8h9i10jklmnopstworldThe!zzzzzzzZX") == "x12b3c4d56f7g8h910jklmnpstwrldTh!zzzzzzzZX"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ousar!ous caps.AYxXyY zZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!sr!s cps.YxXyY zZ"
    @test remove_vowels("Ththeworllquritoday?ck!n!s 1ssThn!s 1s @ str!ng w!th numb3rs, punctuat!onHello worldThe!, and vvar!ouusavrxXZE @ ouunsavrxXZE") == "Ththwrllqrtdy?ck!n!s 1ssThn!s 1s @ str!ng w!th nmb3rs, pnctt!nHll wrldTh!, nd vvr!svrxXZ @ nsvrxXZ"
    @test remove_vowels("AxZXyYzZbraaaaAAAABBBCCCdAEIOHlo woroiuqddDaEEEE!ownE") == "xZXyYzZbrBBBCCCdHl wrqddD!wn"
    @test remove_vowels("mFjX1a2b3c4d5e6fz7g8h9i10jklmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE!dJWPBmmt") == "mFjX12b3c4d56fz7g8h910jklmnpqrstvwxyzzzzzzzHll wd!BBBCCCdddD!dJWPBmmt"
    @test remove_vowels("Hellwo world!") == "Hllw wrld!"
    @test remove_vowels("w!wwtwh") == "w!wwtwh"
    @test remove_vowels("AxZXyYzZbraaaaAAAABBBCCCdAEIoOHlo woroiuqddDaEEEE!ownE") == "xZXyYzZbrBBBCCCdHl wrqddD!wn"
    @test remove_vowels("The quick brown fox juumpos ovelftoSCkoDr the lazdog.") == "Th qck brwn fx jmps vlftSCkDr th lzdg."
    @test remove_vowels("xXCaaaaAEEEE!yYzdoeloIZdDLZ") == "xXC!yYzdlZdDLZ"
    @test remove_vowels("Hellcaabcdps.o,") == "Hllcbcdps.,"
    @test remove_vowels("oHlabquickcdo") == "Hlbqckcd"
    @test remove_vowels("Th!s 1s @ stsr!ngworlld! w!and vvar!ousar!ous caps.AYxXyYzZEAxZXyYzZE") == "Th!s 1s @ stsr!ngwrlld! w!nd vvr!sr!s cps.YxXyYzZxZXyYzZ"
    @test remove_vowels("worl!") == "wrl!"
    @test remove_vowels("He!llwo world!") == "H!llw wrld!"
    @test remove_vowels("punctuat!oHello") == "pnctt!Hll"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i130jklmnopqrstuvwxyzzzzzzzaaaaAAAABBBCCCdddDEEEE!") == "12b3c4d56f7g8h9130jklmnpqrstvwxyzzzzzzzBBBCCCdddD!"
    @test remove_vowels("1a2b3c4d5e6fz7g8hC9i10jklmnopqrstuvBCCCdddDEEEtE!") == "12b3c4d56fz7g8hC910jklmnpqrstvBCCCdddDt!"
    @test remove_vowels("a") == ""
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvnar!owusar!ous ca.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvnr!wsr!s c."
    @test remove_vowels("oo") == ""
    @test remove_vowels("aaaaACCCquitoday?cworll1a2b3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqrstuvwxyzzzzzzzquitoday?ck!dddDaEEEEC!") == "CCCqtdy?cwrll12b3c4d56f7g8h910jklmnpHlww!wtwhlqrstvwxyzzzzzzzqtdy?ck!dddDC!"
    @test remove_vowels("world!rownw!thHello") == "wrld!rwnw!thHll"
    @test remove_vowels("anoorstuvwxyxXYZzZz") == "nrstvwxyxXYZzZz"
    @test remove_vowels("anopqrstvvar!ZouusavrxXZEXyYZzZz") == "npqrstvvr!ZsvrxXZXyYZzZz"
    @test remove_vowels("The quick brown fox jumpos overppAcaps.xXyYzZE lthe lazdog.") == "Th qck brwn fx jmps vrppcps.xXyYzZ lth lzdg."
    @test remove_vowels("anazzylyou") == "nzzyly"
    @test remove_vowels("JmFjXdJWPBt") == "JmFjXdJWPBt"
    @test remove_vowels("yYzATh!s 1s @ stsr!ng AxZXyYzZbraaaaAAAABBBCCCdddDaEEEE!ownEw!th numb3rs, punctuat!on, ZbraaaaAAAABBBCCCdddDaEEEE!ownE") == "yYzTh!s 1s @ stsr!ng xZXyYzZbrBBBCCCdddD!wnw!th nmb3rs, pnctt!n, ZbrBBBCCCdddD!wn"
    @test remove_vowels("worll1a2b3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqr!stuvwxyzzzzzzuitoday?ck!") == "wrll12b3c4d56f7g8h910jklmnpHlww!wtwhlqr!stvwxyzzzzzztdy?ck!"
    @test remove_vowels("The quick brown fox jumpos overptworlAcaps.xXyyYzZEhe!!hhheaps.xXyYzZE lthe lazdog.") == "Th qck brwn fx jmps vrptwrlcps.xXyyYzZh!!hhhps.xXyYzZ lth lzdg."
    @test remove_vowels("aapuncabqabcd") == "pncbqbcd"
    @test remove_vowels("wdorld!") == "wdrld!"
    @test remove_vowels("eeT") == "T"
    @test remove_vowels("punctuwat!oHello worlld!n,") == "pnctwt!Hll wrlld!n,"
    @test remove_vowels("exww!wtwthampletwortlAycaps.xXyYzZEhee!!hhhe@example.colm") == "xww!wtwthmpltwrtlycps.xXyYzZh!!hhh@xmpl.clm"
    @test remove_vowels("HbHTh!s 1s @ stur!ng w!th numb3rs, punctuat!on,brown and vvl") == "HbHTh!s 1s @ str!ng w!th nmb3rs, pnctt!n,brwn nd vvl"
    @test remove_vowels("aaaaAAAABBBCCCfoxdddDaEEEEoveHello wstrHello,!ngorlAcaps.xXyYzZEhe!!") == "BBBCCCfxdddDvHll wstrHll,!ngrlcps.xXyYzZh!!"
    @test remove_vowels("caps.AYxXTRzFAAxyYzZEAxZXyYzZEcaps.xXyYzZE") == "cps.YxXTRzFxyYzZxZXyYzZcps.xXyYzZ"
    @test remove_vowels("anorstuvwxyxXyYZzZzdoelTh!s 1s @ str!ng w!th numb3rs, punctuat!on, and vvar!ouusavrxXZEoIZdDL") == "nrstvwxyxXyYZzZzdlTh!s 1s @ str!ng w!th nmb3rs, pnctt!n, nd vvr!svrxXZZdDL"
    @test remove_vowels("vxXyYZzZvar!ousar!ABBBCCCdddDaEEBEE!") == "vxXyYZzZvr!sr!BBBCCCdddDB!"
    @test remove_vowels("AxXyYwzZEworllquitoday?ck!AxXyworlAxcaps.xXyYzZEohe!!YzZE") == "xXyYwzZwrllqtdy?ck!xXywrlxcps.xXyYzZh!!YzZ"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i110jklmnopqrstworldThe!zzzzzzz") == "12b3c4d56f7g8h9110jklmnpqrstwrldTh!zzzzzzz"
    @test remove_vowels("andbrow1a2b3c4d5e6f7g8h9i110jklmnotworlAcaps.xXyyYzZEhe!h!hhhepqrstworldThe!zzzzzzz") == "ndbrw12b3c4d56f7g8h9110jklmntwrlcps.xXyyYzZh!h!hhhpqrstwrldTh!zzzzzzz"
    @test remove_vowels("worll!quy?ck!wdoeloIZdDL") == "wrll!qy?ck!wdlZdDL"
    @test remove_vowels("He!llwo") == "H!llw"
    @test remove_vowels("over1awt!th2b3c4d5anopqrstuvwxyxXyYyZzZzvwxyzzzzzzz") == "vr1wt!th2b3c4d5npqrstvwxyxXyYyZzZzvwxyzzzzzzz"
    @test remove_vowels("f1a2b3c4d5e6fz7g8h9i10jklm6nopqrTh!s") == "f12b3c4d56fz7g8h910jklm6npqrTh!s"
    @test remove_vowels("doeloIIIZdDL") == "dlZdDL"
    @test remove_vowels("ATh!s 1s @ stsr!ng w!th numb3rs, punctuat!on, and vvar!ousarr!ous caps.AxZXyYzZEcaps.xXyYzZE") == "Th!s 1s @ stsr!ng w!th nmb3rs, pnctt!n, nd vvr!srr!s cps.xZXyYzZcps.xXyYzZ"
    @test remove_vowels("HHelww!wtwhloAxZXyYzZbraaaaAAAABBBCCCdddDaEEEE!ownEellwo world!") == "HHlww!wtwhlxZXyYzZbrBBBCCCdddD!wnllw wrld!"
    @test remove_vowels("AEIq") == "q"
    @test remove_vowels("1a2b3c4d5e6fzAxXyYzZE7gcaps.8h9i10jklmnopqrstuvwx0yzzzazzzzaaaquickaAAAABBBCCCdddDEEEE!") == "12b3c4d56fzxXyYzZ7gcps.8h910jklmnpqrstvwx0yzzzzzzzqckBBBCCCdddD!"
    @test remove_vowels("mFjX1wd!aAAAABBBCCCdddDEEEE!dJWPBmmta2b3cd4d5e6fz7g8h9i10jklmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABBBCCCdddDEEEE!dJWPBmmt") == "mFjX1wd!BBBCCCdddD!dJWPBmmt2b3cd4d56fz7g8h910jklmnpqrstvwxyzzzzzzzHll wd!BBBCCCdddD!dJWPBmmt"
    @test remove_vowels("ATh!s 1s @ straHello,!ng w!th nwumb3rs, punctuat!.on, and var!ous caps.xXyYzZE") == "Th!s 1s @ strHll,!ng w!th nwmb3rs, pnctt!.n, nd vr!s cps.xXyYzZ"
    @test remove_vowels("wdooelo") == "wdl"
    @test remove_vowels("worldThe!fEoxdddDaEEEEn") == "wrldTh!fxdddDn"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!on, anhd vvar!ouusarxXyYZzZ!ous caps.AYxXyYzZE") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!n, nhd vvr!srxXyYZzZ!s cps.YxXyYzZ"
    @test remove_vowels("efghijklmnopqrsaaaaAAAABBBCCCfEoxdddDaEEEE!tuvwxyzuickvcdarr!ous") == "fghjklmnpqrsBBBCCCfxdddD!tvwxyzckvcdrr!s"
    @test remove_vowels("AxZXyYzZbraaaaAAAABBBCCCdAEIoOHlompYworld!rownw!thHelloSq") == "xZXyYzZbrBBBCCCdHlmpYwrld!rwnw!thHllSq"
    @test remove_vowels("oHelww!wtwhloAxZXover1a2b3c4dt5anopqrstuvwxyxXyYZzZzvwxyzzzzzzzyYzZbraaaaAAAABBBCCCdpuuat!on,ddDaEEEE!ownEveelvlo") == "Hlww!wtwhlxZXvr12b3c4dt5npqrstvwxyxXyYZzZzvwxyzzzzzzzyYzZbrBBBCCCdpt!n,ddD!wnvlvl"
    @test remove_vowels("Hell") == "Hll"
    @test remove_vowels("abqabcd\n\n\n\nefghvijnklmnopqrstuvwxyzuickvcd") == "bqbcd\n\n\n\nfghvjnklmnpqrstvwxyzckvcd"
    @test remove_vowels("AEIOHlo") == "Hl"
    @test remove_vowels("wolAxZXyYzZbraaaaAAAABBBCCCdddDaEEEE!ownEftoSCkoDr") == "wlxZXyYzZbrBBBCCCdddD!wnftSCkDr"
    @test remove_vowels("AxZXyYzZbraaaaAAAABBBCCCdAEIoOHlo") == "xZXyYzZbrBBBCCCdHl"
    @test remove_vowels("theworllquitoday?ck!") == "thwrllqtdy?ck!"
    @test remove_vowels("wAxZXyYzAcaps.xXyYzZEZE!thHello wd!") == "wxZXyYzcps.xXyYzZZ!thHll wd!"
    @test remove_vowels("azy") == "zy"
    @test remove_vowels("dFymXw") == "dFymXw"
    @test remove_vowels("ATh!s 1s @ stsr!ng w!th numbcaps.AYxXTRzFAAxyYzZEAxZXyYzZEcaps.xXyYzZE, ") == "Th!s 1s @ stsr!ng w!th nmbcps.YxXTRzFxyYzZxZXyYzZcps.xXyYzZ, "
    @test remove_vowels("Hello1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqr1a2b3c4d5e6f7g8h9i130jklmnopqrstuvwxyzzzzzzzaaaaAAAABBBCCCdddDEEEE!stuvwxyzzzzzzzaaaHello") == "Hll12b3c4d56fz7g8h910jkldlZdDLmnpqr12b3c4d56f7g8h9130jklmnpqrstvwxyzzzzzzzBBBCCCdddD!stvwxyzzzzzzzHll"
    @test remove_vowels("He!llxXyYZzZwo") == "H!llxXyYZzZw"
    @test remove_vowels("1a2b3c4d5zz") == "12b3c4d5zz"
    @test remove_vowels("braaaaAAAABBBCCCHello") == "brBBBCCCHll"
    @test remove_vowels("ww!wtwefghijklmnopqrstuvwxyzuickanzazylyouvcdsarr!oush") == "ww!wtwfghjklmnpqrstvwxyzcknzzylyvcdsrr!sh"
    @test remove_vowels("mFjX1a2b31a2b3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqrstuv8wxyzzzzzzzc4d5e6fz7g8h9i10jklmnopqrstuvwxyzzzzzzzaaaHello wdw!aAAAABBBCCCdddDEEEE!dJWPBmmt") == "mFjX12b312b3c4d56f7g8h910jklmnpHlww!wtwhlqrstv8wxyzzzzzzzc4d56fz7g8h910jklmnpqrstvwxyzzzzzzzHll wdw!BBBCCCdddD!dJWPBmmt"
    @test remove_vowels("ATh!s") == "Th!s"
    @test remove_vowels("w!aaaaAAAABBBCCCdddDaEEEE!hHello") == "w!BBBCCCdddD!hHll"
    @test remove_vowels("AxZXyYzZbraaaaHe!llwoAAAABBBCCCdAEIoOHlo woroiuqddDaEEEE!ownE") == "xZXyYzZbrH!llwBBBCCCdHl wrqddD!wn"
    @test remove_vowels("abquiccUVzMKnTvvar!ousar!ouscd") == "bqccVzMKnTvvr!sr!scd"
    @test remove_vowels("HelllAxZXo wHellwooexampletworlAcaps.xXyYzZEhe!!hhhe@example.colms.xXyYzZEhe!!") == "HlllxZX wHllwxmpltwrlcps.xXyYzZh!!hhh@xmpl.clms.xXyYzZh!!"
    @test remove_vowels("cpaps.") == "cpps."
    @test remove_vowels("theworllqouitoday!") == "thwrllqtdy!"
    @test remove_vowels("quitoday?cworll1a2btheworllqouitoday!3c4d5e6f7g8h9i10jklmnopHelww!wtwhloqrstuvwxyzzzzzzzquitoday?ck!") == "qtdy?cwrll12bthwrllqtdy!3c4d56f7g8h910jklmnpHlww!wtwhlqrstvwxyzzzzzzzqtdy?ck!"
    @test remove_vowels("Th!s 1s @ str!ng w!th nuoveello worlAcaps.xXyYzZEhrxXyYZzZ!ousand caps.AYxXyYzZE") == "Th!s 1s @ str!ng w!th nvll wrlcps.xXyYzZhrxXyYZzZ!snd cps.YxXyYzZ"
    @test remove_vowels("AEIOUaeoHlabquickcdoioiuq") == "Hlbqckcdq"
    @test remove_vowels("AAxcaps.AYxXyYzZEAxZZEZX") == "xcps.YxXyYzZxZZZX"
    @test remove_vowels("1a2b3cz4d5e6f7g8h910jklmnopqrstuvwxyzzzzzzz") == "12b3cz4d56f7g8h910jklmnpqrstvwxyzzzzzzz"
    @test remove_vowels("oveHelleHellolo worlAcaps.worlAcaps.xXyYzZEhXyYzZEhe!!") == "vHllHlll wrlcps.wrlcps.xXyYzZhXyYzZh!!"
    @test remove_vowels("doHello1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqr1a2b3c4d5e6f7g8h9i130jklmnopqrstuvwxyzzzzzzzaaaaAAAABBBCCCdddDEEEE!stuvwxyzzzzzzzaaaHelloeCaaaaAAAABBBCCCdddDEEEE!lloo") == "dHll12b3c4d56fz7g8h910jkldlZdDLmnpqr12b3c4d56f7g8h9130jklmnpqrstvwxyzzzzzzzBBBCCCdddD!stvwxyzzzzzzzHllCBBBCCCdddD!ll"
    @test remove_vowels("vvar!ouar!ous") == "vvr!r!s"
    @test remove_vowels("1seuvwxyz") == "1svwxyz"
    @test remove_vowels("bHTh!s") == "bHTh!s"
    @test remove_vowels("Th!s 1s @ stsr!ng w!th numb3rs, punctuatThe!on, and vvar!ousar!ous caps.AYxXyYzZEAxZXyYzZE") == "Th!s 1s @ stsr!ng w!th nmb3rs, pncttTh!n, nd vvr!sr!s cps.YxXyYzZxZXyYzZ"
    @test remove_vowels("Helww!wtwhloAxZXyYworllquitoday?ck!zZbraaaaAAAABBBCIZdDLCCdddDaEEEE!ownE") == "Hlww!wtwhlxZXyYwrllqtdy?ck!zZbrBBBCZdDLCCdddD!wn"
    @test remove_vowels("aHlnd") == "Hlnd"
    @test remove_vowels("HelAxZXyYzZbrownElo wrorldThe!") == "HlxZXyYzZbrwnl wrrldTh!"
    @test remove_vowels("vopunctuwat!!oHellousar!ous") == "vpnctwt!!Hllsr!s"
    @test remove_vowels("w!wvar!xXyYZzZouswtwh") == "w!wvr!xXyYZzZswtwh"
    @test remove_vowels("worllquy?ck!") == "wrllqy?ck!"
    @test remove_vowels("numbcaps.AYxXTRzFAAxyYzZEAxZXyYzZEcaps.xXyYzZE,") == "nmbcps.YxXTRzFxyYzZxZXyYzZcps.xXyYzZ,"
    @test remove_vowels("theworllquitodacaps.AzZEy?ck!L") == "thwrllqtdcps.zZy?ck!L"
    @test remove_vowels("vvar!ouarr!ous") == "vvr!rr!s"
    @test remove_vowels("f1a2b3c4d5e6fzrTh!s") == "f12b3c4d56fzrTh!s"
    @test remove_vowels("vvar!oAxHello1a2b3c4d5e6fz7g8h9i10jkldoeloIZdDLmnopqrstuvwxyzzzzzzzaaaHello wd!aAAAABthheBBCCCdddDEEEE! worldThe!ZXyYzZDEuusarxXyYZzZ!ous") == "vvr!xHll12b3c4d56fz7g8h910jkldlZdDLmnpqrstvwxyzzzzzzzHll wd!BthhBBCCCdddD! wrldTh!ZXyYzZDsrxXyYZzZ!s"
    @test remove_vowels("aHlbHTh!s 1s @ str!ng w!world!, punctuat!on,brown and vvar!ousar!ous caps.AYxXyYzZEello world!rownw!thHello wd!nd") == "HlbHTh!s 1s @ str!ng w!wrld!, pnctt!n,brwn nd vvr!sr!s cps.YxXyYzZll wrld!rwnw!thHll wd!nd"
    @test remove_vowels("dogg.") == "dgg."
    @test remove_vowels("@@") == "@@"
    @test remove_vowels("varos") == "vrs"
    @test remove_vowels("abqabcd") == "bqbcd"
    @test remove_vowels("qquick") == "qqck"
    @test remove_vowels("wworhow") == "wwrhw"
    @test remove_vowels("punctluwat!oHello worlld!jumposp,") == "pnctlwt!Hll wrlld!jmpsp,"
    @test remove_vowels("aefghistvuvwxyz") == "fghstvvwxyz"
    @test remove_vowels("1a2b3c4d5e6fzAxXyYzZE7gcaps.8h9i10jklmnopqBBBCCCddidDEEEE!") == "12b3c4d56fzxXyYzZ7gcps.8h910jklmnpqBBBCCCdddD!"
    @test remove_vowels("ATh!s 1s @ straHello,!ng w!th numb3ros, punctuatThe!on,punctuat!.on, and var!ous caps.xXyYzZE") == "Th!s 1s @ strHll,!ng w!th nmb3rs, pncttTh!n,pnctt!.n, nd vr!s cps.xXyYzZ"
    @test remove_vowels("AlftoSCkoDEIOlHlo wo") == "lftSCkDlHl w"
    @test remove_vowels("xx") == "xx"
    @test remove_vowels("mFjoemHello") == "mFjmHll"
    @test remove_vowels("Hlo wolAxZXyYzZbraaaaAAAABBBCCCdddDaEEoveHelworlAcaps.xXyYzZEhe!!EE!ownEftoSCkoDr") == "Hl wlxZXyYzZbrBBBCCCdddDvHlwrlcps.xXyYzZh!!!wnftSCkDr"
    @test remove_vowels("Thn!s 1worlAcaps.xXyYzZEhrxXyYZzZ!ousands @ ouusavrxXZE") == "Thn!s 1wrlcps.xXyYzZhrxXyYZzZ!snds @ svrxXZ"
    @test remove_vowels("dog.Hellwor") == "dg.Hllwr"
    @test remove_vowels("xXCaaaaAEEEE!yYzdoeloIZdDLZvar!ous") == "xXC!yYzdlZdDLZvr!s"
    @test remove_vowels("theworllquitodacaps.AzZEy?ack!L") == "thwrllqtdcps.zZy?ck!L"
    @test remove_vowels("puzZE") == "pzZ"
    @test remove_vowels("fLDZzeBh") == "fLDZzBh"
    @test remove_vowels("fox") == "fx"
    @test remove_vowels("apuncabqabcd") == "pncbqbcd"
    @test remove_vowels("efghijklmnopqtIZdDLoveHello worlAcHello worllquy?ck!aps.xXyYzZEhe!!hvvayYZzZ!ouserstuvwxyz") == "fghjklmnpqtZdDLvHll wrlcHll wrllqy?ck!ps.xXyYzZh!!hvvyYZzZ!srstvwxyz"
    @test remove_vowels("worllquy?ck!aps.xXyYzZEhe!!hvvayYZzZ!ouserstuvwxyz") == "wrllqy?ck!ps.xXyYzZh!!hvvyYZzZ!srstvwxyz"
    @test remove_vowels("wt!thvvar!ousar!ABBBCCCdddDaEEEE!") == "wt!thvvr!sr!BBBCCCdddD!"
    @test remove_vowels("wdw!aAAAABBBCCCddDEEEE!dJWPBmmt") == "wdw!BBBCCCddD!dJWPBmmt"
    @test remove_vowels("AAxXyzZE") == "xXyzZ"
    @test remove_vowels("EjGkZwKvO") == "jGkZwKv"
    @test remove_vowels("anazylyounumb3rs,") == "nzylynmb3rs,"
    @test remove_vowels("oveello worlAcaps.xXyYzZEhhe!!lftoSCkoDl") == "vll wrlcps.xXyYzZhh!!lftSCkDl"
    @test remove_vowels("AEIOUaeiou") == ""
    @test remove_vowels(".") == "."
    @test remove_vowels("0123456789") == "0123456789"
    @test remove_vowels("AbCdeFGHiJklmnOPqRsTuVwXYz") == "bCdFGHJklmnPqRsTVwXYz"
    @test remove_vowels("AAaaBBbbCCccDDddEEeeFFff") == "BBbbCCccDDddFFff"
    @test remove_vowels("akdj nsoirewqabfj nal kjaks kdas") == "kdj nsrwqbfj nl kjks kds"
    @test remove_vowels("\n") == "\n"
    @test remove_vowels("    ") == "    "
    @test remove_vowels("\t") == "\t"
    @test remove_vowels("\r") == "\r"
    @test remove_vowels("Hello worldd!") == "Hll wrldd!"
    @test remove_vowels("AEIOUaeHello worldd!iouq") == "Hll wrldd!q"
    @test remove_vowels("The quick brown fox jaaaaAAAABBBCCCdddDEEEE!oveHello,dog.") == "Th qck brwn fx jBBBCCCdddD!vHll,dg."
    @test remove_vowels("AEIOUeiouq") == "q"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat!oHellon, and var!ous caps.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt!Hlln, nd vr!s cps."
    @test remove_vowels("examplle@example.com") == "xmpll@xmpl.cm"
    @test remove_vowels("Hello, how tare you today?") == "Hll, hw tr y tdy?"
    @test remove_vowels("example@example.comThe quick brown fox jumps over the lazy dog.") == "xmpl@xmpl.cmTh qck brwn fx jmps vr th lzy dg."
    @test remove_vowels("aaaaAAdDEEEE!") == "dD!"
    @test remove_vowels("Hello, h tare you today?") == "Hll, h tr y tdy?"
    @test remove_vowels("str!ngand") == "str!ngnd"
    @test remove_vowels("The quick brown fox jumps over the lazy  dog.") == "Th qck brwn fx jmps vr th lzy  dg."
    @test remove_vowels("punctuat!oHellolazyn,") == "pnctt!Hlllzyn,"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, and var!ous caps.") == "Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cps."
    @test remove_vowels("aaaaaAAdDEEEE!") == "dD!"
    @test remove_vowels("aaaaAAdDEEaaaaAAdDEEEE!EEE!") == "dDdD!!"
    @test remove_vowels("The quick brown foxy  dog.") == "Th qck brwn fxy  dg."
    @test remove_vowels("examplle@example.copm") == "xmpll@xmpl.cpm"
    @test remove_vowels("The quick brown foxy g.") == "Th qck brwn fxy g."
    @test remove_vowels("AEIOUeoiouq") == "q"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10Hello, h tare you today?jklmnoprstuvwxyzzzzzzz") == "12b3c4d56f7g8h910Hll, h tr y tdy?jklmnprstvwxyzzzzzzz"
    @test remove_vowels("worl") == "wrl"
    @test remove_vowels("str!!ng") == "str!!ng"
    @test remove_vowels("aaexample@example.comTheaaAAAABBBCCCdddDEEEE!") == "xmpl@xmpl.cmThBBBCCCdddD!"
    @test remove_vowels("The quick brown fox jumps over the lazyog.") == "Th qck brwn fx jmps vr th lzyg."
    @test remove_vowels("str!ngandlazy") == "str!ngndlzy"
    @test remove_vowels("punctuat!oHellon,") == "pnctt!Hlln,"
    @test remove_vowels("tokday?jklmnoprstuvwxyzzzzzzzz") == "tkdy?jklmnprstvwxyzzzzzzzz"
    @test remove_vowels("Hello, how efghijklmnopqrstuvwxyztare you totokday?jklmnoprstuvwxyzzzzzzzzday?") == "Hll, hw fghjklmnpqrstvwxyztr y ttkdy?jklmnprstvwxyzzzzzzzzdy?"
    @test remove_vowels("The quick brown fox jumps over the lazy dog.h") == "Th qck brwn fx jmps vr th lzy dg.h"
    @test remove_vowels("str!ngl") == "str!ngl"
    @test remove_vowels("The quiver the lazy dog.h") == "Th qvr th lzy dg.h"
    @test remove_vowels("today?jklmnoprstuvwxyzzzzzzz") == "tdy?jklmnprstvwxyzzzzzzz"
    @test remove_vowels("Hello, how efghijklmnopqrstuvwxyztare you totokday?jklmnoprstuvwxyzzzzzzzzThe quick brown fox jumps over the lazy dog.hday?") == "Hll, hw fghjklmnpqrstvwxyztr y ttkdy?jklmnprstvwxyzzzzzzzzTh qck brwn fx jmps vr th lzy dg.hdy?"
    @test remove_vowels("Hello, how tare youexample@example.comThe today?") == "Hll, hw tr yxmpl@xmpl.cmTh tdy?"
    @test remove_vowels("lazyog.") == "lzyg."
    @test remove_vowels("eHello,") == "Hll,"
    @test remove_vowels("AEIOUaeHello worlaaaaAAdDEEEE!dd!iouq") == "Hll wrldD!dd!q"
    @test remove_vowels("jyJiBLGfRP") == "jyJBLGfRP"
    @test remove_vowels("The quick brown fox jumps odver the lazy dog.h") == "Th qck brwn fx jmps dvr th lzy dg.h"
    @test remove_vowels("efghijklmnopqrstuvwxyztare") == "fghjklmnpqrstvwxyztr"
    @test remove_vowels("The quick brown fox jumps ovner the lazy  dog.") == "Th qck brwn fx jmps vnr th lzy  dg."
    @test remove_vowels("abcd\n\n\n\nefghijklmnopquickyz") == "bcd\n\n\n\nfghjklmnpqckyz"
    @test remove_vowels("efghijklmnopqrstuvwxyzytaredog.hday?") == "fghjklmnpqrstvwxyzytrdg.hdy?"
    @test remove_vowels("aaaaAAAABBBCCdDEEEE!") == "BBBCCdD!"
    @test remove_vowels("aaaaAAdEexample@example.comTheDEEaaaaAAdDEEEE!EEE!") == "dxmpl@xmpl.cmThDdD!!"
    @test remove_vowels("The qThe quick brown fox jumps over the lazy  dog.uick brown foxy g.") == "Th qTh qck brwn fx jmps vr th lzy  dg.ck brwn fxy g."
    @test remove_vowels("foxy") == "fxy"
    @test remove_vowels("Hello,  h tare you today?") == "Hll,  h tr y tdy?"
    @test remove_vowels("lazzyog.") == "lzzyg."
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat,!oHellon, and var!ous caps.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt,!Hlln, nd vr!s cps."
    @test remove_vowels("Hellay?") == "Hlly?"
    @test remove_vowels("Th!s 1s @ str!ng  w!th numb3rs, punctuat!oHellon, and var!ous caps.") == "Th!s 1s @ str!ng  w!th nmb3rs, pnctt!Hlln, nd vr!s cps."
    @test remove_vowels("Hellobrown world!") == "Hllbrwn wrld!"
    @test remove_vowels("Hello,  hh  tare you today?") == "Hll,  hh  tr y tdy?"
    @test remove_vowels("g.") == "g."
    @test remove_vowels("aaaAEIOUeiouqquiveraAAdDEEaaaaAAdDEEDEE!EEE!") == "qqvrdDdDD!!"
    @test remove_vowels("aaaaaAAAABBBCCdDEEEE!") == "BBBCCdD!"
    @test remove_vowels("woyourl") == "wyrl"
    @test remove_vowels("MBSXebBdc") == "MBSXbBdc"
    @test remove_vowels("efghijklmnogpqrstuvwxyztare") == "fghjklmngpqrstvwxyztr"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10Hello,") == "12b3c4d56f7g8h910Hll,"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10jklmnopqrstuvwxkyzzzzzzz") == "12b3c4d56f7g8h910jklmnpqrstvwxkyzzzzzzz"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand var!ous caps.") == "Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cps."
    @test remove_vowels("ayoubcd\n\n\n\nefghijklmnopqrstuvwxyz") == "ybcd\n\n\n\nfghjklmnpqrstvwxyz"
    @test remove_vowels("HelThe qThe quick brown fox jumps over the lazy  dog.howuick brown foxy g.lay?") == "HlTh qTh qck brwn fx jmps vr th lzy  dg.hwck brwn fxy g.ly?"
    @test remove_vowels("abcdHello, how tare youexample@example.comThe today?") == "bcdHll, hw tr yxmpl@xmpl.cmTh tdy?"
    @test remove_vowels("worlefghijklmnopqrstuvwxyztare") == "wrlfghjklmnpqrstvwxyztr"
    @test remove_vowels("dog.hday?") == "dg.hdy?"
    @test remove_vowels("lazzyaoog.") == "lzzyg."
    @test remove_vowels("s1a2b3c4d5e6f7g8h9i10jklmnopqrstuvwxyzzzzzzztr!ngl") == "s12b3c4d56f7g8h910jklmnpqrstvwxyzzzzzzztr!ngl"
    @test remove_vowels("1a2b34c4d5e6f7g8h9i10Hello,") == "12b34c4d56f7g8h910Hll,"
    @test remove_vowels("xkfHeZTld") == "xkfHZTld"
    @test remove_vowels("foy") == "fy"
    @test remove_vowels("str!gngnandlazy") == "str!gngnndlzy"
    @test remove_vowels("str!n") == "str!n"
    @test remove_vowels("g.lay?") == "g.ly?"
    @test remove_vowels("efghredog.hday?") == "fghrdg.hdy?"
    @test remove_vowels("jumps") == "jmps"
    @test remove_vowels("Helleo wtoday?jklmnoprstuvwxyzzzzzzzorld!") == "Hll wtdy?jklmnprstvwxyzzzzzzzrld!"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat,!hoHellon, and var!ous caps.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt,!hHlln, nd vr!s cps."
    @test remove_vowels("Helleo") == "Hll"
    @test remove_vowels("andd") == "ndd"
    @test remove_vowels("anThe quick brown fox jumps over the lazyog.dd") == "nTh qck brwn fx jmps vr th lzyg.dd"
    @test remove_vowels("tare") == "tr"
    @test remove_vowels("xkfHeZTldAEIOUaeHello worldd!iouq") == "xkfHZTldHll wrldd!q"
    @test remove_vowels("str!ngandlaTh!s 1s @ str!ng  w!th numb3rs, punctuat!oHellon, and var!ous caps.zy") == "str!ngndlTh!s 1s @ str!ng  w!th nmb3rs, pnctt!Hlln, nd vr!s cps.zy"
    @test remove_vowels("ayoubcd\n\n\n\nefghijklmnopqrstuvwxyzTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand var!ous caps.") == "ybcd\n\n\n\nfghjklmnpqrstvwxyzTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cps."
    @test remove_vowels("w!!h") == "w!!h"
    @test remove_vowels("aaaaAAAABBBnumb3rs,CCCdddDEEEE!") == "BBBnmb3rs,CCCdddD!"
    @test remove_vowels("wayoubcdorl") == "wybcdrl"
    @test remove_vowels("abcd\n\n\nc\nefghijklmnopquickyz") == "bcd\n\n\nc\nfghjklmnpqckyz"
    @test remove_vowels("aaaaAAAABBBnumb3rs,CCCdddDEw!!hEEE!") == "BBBnmb3rs,CCCdddDw!!h!"
    @test remove_vowels("AEIOUThe quick brown fox jumps over the lazy  dog.") == "Th qck brwn fx jmps vr th lzy  dg."
    @test remove_vowels("Hello wefghijklmnopqrstuvwxyztareorldd!") == "Hll wfghjklmnpqrstvwxyztrrldd!"
    @test remove_vowels("AEIcaps.zyOUaeiouq") == "cps.zyq"
    @test remove_vowels("lo,") == "l,"
    @test remove_vowels("ovner") == "vnr"
    @test remove_vowels("str!caps.zyngcand") == "str!cps.zyngcnd"
    @test remove_vowels("jaaaaAAAABBBCCCdddDEEEE!oveHello,dog.") == "jBBBCCCdddD!vHll,dg."
    @test remove_vowels("worol") == "wrl"
    @test remove_vowels("xkfHeZTldAEIOUaeHello worpunctuat,!hoHellon,ldd!iouq") == "xkfHZTldHll wrpnctt,!hHlln,ldd!q"
    @test remove_vowels("The quick brown fox jaaaaAAAAeBBBCCCg.") == "Th qck brwn fx jBBBCCCg."
    @test remove_vowels("strTh!s") == "strTh!s"
    @test remove_vowels("example@example.comThe") == "xmpl@xmpl.cmTh"
    @test remove_vowels("The qThe quick brown fox jumpsexample@example.comThe over the lazy  dog.uick brown foxy g.") == "Th qTh qck brwn fx jmpsxmpl@xmpl.cmTh vr th lzy  dg.ck brwn fxy g."
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aanvar!ous caps.") == "Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nvr!s cps."
    @test remove_vowels("wtoday?jklmnoprstuvwxyzzzzzzzorld!") == "wtdy?jklmnprstvwxyzzzzzzzrld!"
    @test remove_vowels("dHello,  hh  tare you today?og.h") == "dHll,  hh  tr y tdy?g.h"
    @test remove_vowels("abcd\np\n\nc\nefghijklmnopquickyz") == "bcd\np\n\nc\nfghjklmnpqckyz"
    @test remove_vowels("ayoubcd\n\n\n\nefghijklmnopqrstuvwxyzTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand vawr!ous caps.") == "ybcd\n\n\n\nfghjklmnpqrstvwxyzTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vwr!s cps."
    @test remove_vowels("MBSXebnumb3rs,Bdc") == "MBSXbnmb3rs,Bdc"
    @test remove_vowels("oHello,  hh h tare you today?") == "Hll,  hh h tr y tdy?"
    @test remove_vowels("Th!s 1s @ str!ng  w!th numb3rs, punctuat!uoHellon, and var!ous caps.") == "Th!s 1s @ str!ng  w!th nmb3rs, pnctt!Hlln, nd vr!s cps."
    @test remove_vowels("wlo,!h") == "wl,!h"
    @test remove_vowels("AEIOUaeiojyJiBLRGfRP") == "jyJBLRGfRP"
    @test remove_vowels("hHello, how are you today?") == "hHll, hw r y tdy?"
    @test remove_vowels("The quick brown fox jaaaaAAAAeBBBCCtoday?og.hCg.") == "Th qck brwn fx jBBBCCtdy?g.hCg."
    @test remove_vowels("abcd\np\n\nc\nefghijklmnopquickytoday?jklmnoprstuvwxyzzzzzzzz") == "bcd\np\n\nc\nfghjklmnpqckytdy?jklmnprstvwxyzzzzzzzz"
    @test remove_vowels("worldd!") == "wrldd!"
    @test remove_vowels("aaaaAAdDEEaaaaAHello wefghijklmnopqrstuvwxyztareorldd!AdDEEEE!EEE!") == "dDHll wfghjklmnpqrstvwxyztrrldd!dD!!"
    @test remove_vowels("The qThe quick brown fox jumpseThe qThe quick brown fox jumpsexample@example.comThe over the lazy  dog.uick brown foxy g.xample@example.comThe over the lazy  dog.uick brown foxy g.") == "Th qTh qck brwn fx jmpsTh qTh qck brwn fx jmpsxmpl@xmpl.cmTh vr th lzy  dg.ck brwn fxy g.xmpl@xmpl.cmTh vr th lzy  dg.ck brwn fxy g."
    @test remove_vowels("AEEIOUaeHelHlo") == "HlHl"
    @test remove_vowels("abcd\n\n\njc\nefghijklmnopquickyz") == "bcd\n\n\njc\nfghjklmnpqckyz"
    @test remove_vowels("The quiTh!s 1s @ str!ng w!th numb3rs, punctuat,!hoHellon, and var!ous caps.ck brown fox jumps odverlazy dog.h") == "Th qTh!s 1s @ str!ng w!th nmb3rs, pnctt,!hHlln, nd vr!s cps.ck brwn fx jmps dvrlzy dg.h"
    @test remove_vowels("Helle") == "Hll"
    @test remove_vowels("efghijklmnTh!s 1s @ str!ng  w!th numb3rs, punctuat!uoHellon, and var!ous caps.opqrstuvwxyztare") == "fghjklmnTh!s 1s @ str!ng  w!th nmb3rs, pnctt!Hlln, nd vr!s cps.pqrstvwxyztr"
    @test remove_vowels("gh.") == "gh."
    @test remove_vowels("c") == "c"
    @test remove_vowels("xkfHeZld") == "xkfHZld"
    @test remove_vowels("jaaaaAAAAeBBBCCCg.") == "jBBBCCCg."
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10Hejcllocaps.ck,") == "12b3c4d56f7g8h910Hjcllcps.ck,"
    @test remove_vowels("xkfHld") == "xkfHld"
    @test remove_vowels("worlefghijklmnopquickytoday?jklmnoprstuvwxyzzzzzzzzdd!") == "wrlfghjklmnpqckytdy?jklmnprstvwxyzzzzzzzzdd!"
    @test remove_vowels("abcd\np\n\nc\nefghijlazzyog.klmnopquickyz") == "bcd\np\n\nc\nfghjlzzyg.klmnpqckyz"
    @test remove_vowels("caps.zy") == "cps.zy"
    @test remove_vowels("aaexamDEEEE!") == "xmD!"
    @test remove_vowels("punctuat!uoHellon,") == "pnctt!Hlln,"
    @test remove_vowels("Hexample@example.comello, how efghijklmnopqrstuvwxyztare you totokday?jklmnoprstuvwxyzzzzzzzzday?") == "Hxmpl@xmpl.cmll, hw fghjklmnpqrstvwxyztr y ttkdy?jklmnprstvwxyzzzzzzzzdy?"
    @test remove_vowels("lThe quick brown fox jaaaaAAAABBBCCCdddDEEEE!oveHello,dog.") == "lTh qck brwn fx jBBBCCCdddD!vHll,dg."
    @test remove_vowels("dog.hoday?") == "dg.hdy?"
    @test remove_vowels("examplle@example..copm") == "xmpll@xmpl..cpm"
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat,!oHellnumb3rs,on, and var!ous caps.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt,!Hllnmb3rs,n, nd vr!s cps."
    @test remove_vowels("The quick brown AEEIOUaeHelHlofox jumps over the lazyog.") == "Th qck brwn HlHlfx jmps vr th lzyg."
    @test remove_vowels("lazyog.dd") == "lzyg.dd"
    @test remove_vowels("example@example.comThe quick brown fvawr!ousox jumps over the lazy dog.") == "xmpl@xmpl.cmTh qck brwn fvwr!sx jmps vr th lzy dg."
    @test remove_vowels("dog.howuick") == "dg.hwck"
    @test remove_vowels("quiefghijklmnopquickyzck") == "qfghjklmnpqckyzck"
    @test remove_vowels("AEIcaps.zyOUpaeiouq") == "cps.zypq"
    @test remove_vowels("abcdHelloanThe, how tare youexample@example.comThe today?") == "bcdHllnTh, hw tr yxmpl@xmpl.cmTh tdy?"
    @test remove_vowels("1a2b3c4d5e6fTh!s 1s @ str!ng  w!th numb3rs, punctuat!oHellon, and var!ous caps.7g8h9i10jklmnopqrstuvwxyzzzzzzz") == "12b3c4d56fTh!s 1s @ str!ng  w!th nmb3rs, pnctt!Hlln, nd vr!s cps.7g8h910jklmnpqrstvwxyzzzzzzz"
    @test remove_vowels("Hello, hTh!sare you today?") == "Hll, hTh!sr y tdy?"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3rs, puncotuat!oHellon, and var!ous caps.") == "Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cps."
    @test remove_vowels("Hstr!caps.zyngcandllo, how are you today?") == "Hstr!cps.zyngcndll, hw r y tdy?"
    @test remove_vowels("The quick kbrown fox jumps overt the lazyog.") == "Th qck kbrwn fx jmps vrt th lzyg."
    @test remove_vowels("punctuat!ocn,") == "pnctt!cn,"
    @test remove_vowels("efgxkfHeZTldAEIOUaeHellohijklmnopqrstuvwxyz") == "fgxkfHZTldHllhjklmnpqrstvwxyz"
    @test remove_vowels("aaaEaAAdDEEEEE!") == "dD!"
    @test remove_vowels("AEIOUe") == ""
    @test remove_vowels("The quick brown fosx jumps over the lazyog.") == "Th qck brwn fsx jmps vr th lzyg."
    @test remove_vowels("eThe quickare brown fe") == "Th qckr brwn f"
    @test remove_vowels("examplxHello,le@example.com") == "xmplxHll,l@xmpl.cm"
    @test remove_vowels("xkfHeZTldAEIOUaeHello worpunctuat,!hoiHellon,ldd!iouq") == "xkfHZTldHll wrpnctt,!hHlln,ldd!q"
    @test remove_vowels("youexample@examcaps.ckple.comThe") == "yxmpl@xmcps.ckpl.cmTh"
    @test remove_vowels("xkfHeZTldAEIOUaeH worlddd!iouq") == "xkfHZTldH wrlddd!q"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i1ja0jklmnopqrstuvwxyzzzzzzz") == "12b3c4d56f7g8h91j0jklmnpqrstvwxyzzzzzzz"
    @test remove_vowels("The qThe quick brown fox jumpsexample@example.comThe overfosx the lazy  dog.uick brown foxy g.") == "Th qTh qck brwn fx jmpsxmpl@xmpl.cmTh vrfsx th lzy  dg.ck brwn fxy g."
    @test remove_vowels("MBSXaaaaAAAABBBnumb3rs,CCCdddDEEEE!ebBdc") == "MBSXBBBnmb3rs,CCCdddD!bBdc"
    @test remove_vowels("The quick brown fox jumps over the  lazy dog.h") == "Th qck brwn fx jmps vr th  lzy dg.h"
    @test remove_vowels("sexamplxHello,le@example.comtr!!ng") == "sxmplxHll,l@xmpl.cmtr!!ng"
    @test remove_vowels("lazzyaooog.") == "lzzyg."
    @test remove_vowels("examplle@examle.com") == "xmpll@xml.cm"
    @test remove_vowels("Helllay?") == "Hllly?"
    @test remove_vowels("puncotuat!oHellon,") == "pnctt!Hlln,"
    @test remove_vowels("eample.com") == "mpl.cm"
    @test remove_vowels("worlaaaaAAdDEEEE!dd!iouq") == "wrldD!dd!q"
    @test remove_vowels("MBSXaaaaAAAABBdc") == "MBSXBBdc"
    @test remove_vowels("laovnerzyog.") == "lvnrzyg."
    @test remove_vowels("fe") == "f"
    @test remove_vowels("The quick kbrown fox jumpThe quick brown fox jumqTheps over the lazyog.s overt the lazyog.") == "Th qck kbrwn fx jmpTh qck brwn fx jmqThps vr th lzyg.s vrt th lzyg."
    @test remove_vowels("examplle@examexamplle@example.copm.com") == "xmpll@xmxmpll@xmpl.cpm.cm"
    @test remove_vowels("xkfHeZTldAEIOUaeHello worpunctua t,!hoiHellon,ldd!iouq") == "xkfHZTldHll wrpnct t,!hHlln,ldd!q"
    @test remove_vowels("He") == "H"
    @test remove_vowels("yoo") == "y"
    @test remove_vowels("The quick brown fox jumps odver the l azy dog.h") == "Th qck brwn fx jmps dvr th l zy dg.h"
    @test remove_vowels("caps.ck") == "cps.ck"
    @test remove_vowels("laovnerzyog.jyJiBLGfRP") == "lvnrzyg.jyJBLGfRP"
    @test remove_vowels("laovnerzhyoHelTheg.jyJiBLGfRP") == "lvnrzhyHlThg.jyJBLGfRP"
    @test remove_vowels("punctuaTh!s 1s @ str!ng w!th numb3rs, punctuat,!oHellnumb3rs,on, and var!ous caps.t!on,") == "pnctTh!s 1s @ str!ng w!th nmb3rs, pnctt,!Hllnmb3rs,n, nd vr!s cps.t!n,"
    @test remove_vowels("t,!hoiHellon,ldd!iouq") == "t,!hHlln,ldd!q"
    @test remove_vowels("aaexample@example.comTheaaAAAABabcd\np\n\nc\nefghijklmnopquickytoday?jklmnoprstuvwxyzzzzzzzz!") == "xmpl@xmpl.cmThBbcd\np\n\nc\nfghjklmnpqckytdy?jklmnprstvwxyzzzzzzzz!"
    @test remove_vowels("worrol") == "wrrl"
    @test remove_vowels("xkfHeZTldAEIOUaeHello wdd!iouq") == "xkfHZTldHll wdd!q"
    @test remove_vowels("Th!s 1s @ str!ngctuat,!oHellon, and var!ous caps.") == "Th!s 1s @ str!ngctt,!Hlln, nd vr!s cps."
    @test remove_vowels("aaaaAAdEexample@example.comTheaDEEaaaaAAdDEEEaE!EEE!") == "dxmpl@xmpl.cmThDdD!!"
    @test remove_vowels("Hellodog. world!") == "Hlldg. wrld!"
    @test remove_vowels("The quick brown fox jumps over the lazy do.") == "Th qck brwn fx jmps vr th lzy d."
    @test remove_vowels("aaexample@example.comTheaaAAAABabcd") == "xmpl@xmpl.cmThBbcd"
    @test remove_vowels("aaaaAAdDEEaaaaHexample@example.comello,DEEEE!EEE!") == "dDHxmpl@xmpl.cmll,D!!"
    @test remove_vowels("ww!h") == "ww!h"
    @test remove_vowels("Hello, how tare youexamplefghijlazzyog.klmnopquickexample@example.comTheyze@example.comThe today?") == "Hll, hw tr yxmplfghjlzzyg.klmnpqckxmpl@xmpl.cmThyz@xmpl.cmTh tdy?"
    @test remove_vowels("strTh!hpunctuat!oHellon,s") == "strTh!hpnctt!Hlln,s"
    @test remove_vowels("The quick brown AEEIOUaeHdo.elHlofox jumps over the lazyog.") == "Th qck brwn Hd.lHlfx jmps vr th lzyg."
    @test remove_vowels("aaaaAAdEexample@aexample.comTheaDEEaaaaAAdDEEEaE!EEE!") == "dxmpl@xmpl.cmThDdD!!"
    @test remove_vowels("totokday?jklmnoprstuvwxyzzzzzzzzThe") == "ttkdy?jklmnprstvwxyzzzzzzzzTh"
    @test remove_vowels("wtoday?jklmnoprstuvwxHstr!caps.zyngcandllo,yzzzzzzzorld!") == "wtdy?jklmnprstvwxHstr!cps.zyngcndll,yzzzzzzzrld!"
    @test remove_vowels("wefghijklmnogpqrstuvwxyztare") == "wfghjklmngpqrstvwxyztr"
    @test remove_vowels("HelThe qThe quick brown strTh!hpunctuat!oHellon,ss over the lazy  dog.howuick brown foxy g.?") == "HlTh qTh qck brwn strTh!hpnctt!Hlln,ss vr th lzy  dg.hwck brwn fxy g.?"
    @test remove_vowels("caps.t!on,") == "cps.t!n,"
    @test remove_vowels("!h") == "!h"
    @test remove_vowels("Th!s 1s @") == "Th!s 1s @"
    @test remove_vowels("XbFTQMiAwt") == "XbFTQMwt"
    @test remove_vowels("MBSXaaaaBAAAABBdc") == "MBSXBBBdc"
    @test remove_vowels("eThe quicykare blazzyaoog.rown fe") == "Th qcykr blzzyg.rwn f"
    @test remove_vowels("Hello,worldd!iouq   hh  tare you today?") == "Hll,wrldd!q   hh  tr y tdy?"
    @test remove_vowels("Hello, h tarAEIOUaeHello worlaaaaAAdDEEEE!dd!iouqe you today?") == "Hll, h trHll wrldD!dd!q y tdy?"
    @test remove_vowels("today?og.h") == "tdy?g.h"
    @test remove_vowels("aaaaaAAAABBBCCdDEEEE!Th!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, and var!ous caps.") == "BBBCCdD!Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cps."
    @test remove_vowels("laovnerzyog.jyJiBLGfRsngandP") == "lvnrzyg.jyJBLGfRsngndP"
    @test remove_vowels("The quick brown AEEIayoubcd\n\n\n\nefghijklmnopqrstuvwxyzOUaeHdo.elHlofox jumps over the lazyog.") == "Th qck brwn ybcd\n\n\n\nfghjklmnpqrstvwxyzHd.lHlfx jmps vr th lzyg."
    @test remove_vowels("tokday?jklmnoprstuvwxyzzztzzzzz") == "tkdy?jklmnprstvwxyzzztzzzzz"
    @test remove_vowels("xkfHeZTldAHexample@example.comello,EIOUaepHello wdd!iouq") == "xkfHZTldHxmpl@xmpl.cmll,pHll wdd!q"
    @test remove_vowels("xkfHeZTldAEIOUaeH") == "xkfHZTldH"
    @test remove_vowels("punt!on,") == "pnt!n,"
    @test remove_vowels("MBSXadHello,  hh  tare you today?og.hEEEE!ebBdc") == "MBSXdHll,  hh  tr y tdy?g.h!bBdc"
    @test remove_vowels("eHellHellodog. world!o,") == "HllHlldg. wrld!,"
    @test remove_vowels("The quiHellobrownck brown AEEIOUaeHelHlofox jumps over the lazyog.") == "Th qHllbrwnck brwn HlHlfx jmps vr th lzyg."
    @test remove_vowels("xkfHeZTldAHexample@examllo,EIOUaepHello wdd!iouq") == "xkfHZTldHxmpl@xmll,pHll wdd!q"
    @test remove_vowels("Hexample@example.comello, how efge you totokdayzzzzzday?") == "Hxmpl@xmpl.cmll, hw fg y ttkdyzzzzzdy?"
    @test remove_vowels("CpCOvCPPy") == "CpCvCPPy"
    @test remove_vowels("wefghijklmnopqrstuvwxyztareorldd!") == "wfghjklmnpqrstvwxyztrrldd!"
    @test remove_vowels("1a2b3c4d5e6f7g8h9i10jklmnopqrstuvwxyzzzczzz") == "12b3c4d56f7g8h910jklmnpqrstvwxyzzzczzz"
    @test remove_vowels("The quick brown fox juamps odver aaaaAAdDEEaaaaHexample@example.comello,DEEEE!EEE!the lazy dog.h") == "Th qck brwn fx jmps dvr dDHxmpl@xmpl.cmll,D!!th lzy dg.h"
    @test remove_vowels("tokday?jklumnoprstuvwxyzzztzzzzz") == "tkdy?jklmnprstvwxyzzztzzzzz"
    @test remove_vowels("abcdHelloanThe,") == "bcdHllnTh,"
    @test remove_vowels("AEEIOUaeHdo.elHlofox") == "Hd.lHlfx"
    @test remove_vowels("aaaaAAAABBBCCCdddDElazzyaoog.EE!") == "BBBCCCdddDlzzyg.!"
    @test remove_vowels("aaaaAAdDEEaaaaAHello wefghijklmnopqrstuvwxyztareorldd!AdDEEEstr!ngandlazyE!EEE!") == "dDHll wfghjklmnpqrstvwxyztrrldd!dDstr!ngndlzy!!"
    @test remove_vowels("str!!ngstr!!ng") == "str!!ngstr!!ng"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3rs, puncotuat!oHellon, and var!ous caayoubcd\n\n\n\nefghijklmnopqrstuvwxyzTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand vawr!ous caps.ps.") == "Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cybcd\n\n\n\nfghjklmnpqrstvwxyzTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vwr!s cps.ps."
    @test remove_vowels("AThe quiver the lazy dog.heiou") == "Th qvr th lzy dg.h"
    @test remove_vowels("lago.") == "lg."
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3jaaaaAAAABBBCCCdddDEEEE!oveHello,dog.Hellon, and var!ous caps.") == "Th!s 1s @ str!ngl w!th nmb3jBBBCCCdddD!vHll,dg.Hlln, nd vr!s cps."
    @test remove_vowels("worlefghijklmnopqrstuvwxyztareyoo") == "wrlfghjklmnpqrstvwxyztry"
    @test remove_vowels("watoday?jklmnoprstuvwxyzzzzzzzyoubcdorl") == "wtdy?jklmnprstvwxyzzzzzzzybcdrl"
    @test remove_vowels("Hello, how e you totokday?jklmnoprstuvwxyzzzzzzzzday?") == "Hll, hw  y ttkdy?jklmnprstvwxyzzzzzzzzdy?"
    @test remove_vowels("quiver") == "qvr"
    @test remove_vowels("t,!hoiHellon,ldd!liouq") == "t,!hHlln,ldd!lq"
    @test remove_vowels("txkfHeZTldAEIOUaeHare") == "txkfHZTldHr"
    @test remove_vowels("xXyjcYzZ") == "xXyjcYzZ"
    @test remove_vowels("taree") == "tr"
    @test remove_vowels("caayoubd") == "cybd"
    @test remove_vowels("Hello, how tare youexamplefghijlazzyog.klmnople.comTheyze@example.comThe today?") == "Hll, hw tr yxmplfghjlzzyg.klmnpl.cmThyz@xmpl.cmTh tdy?"
    @test remove_vowels("Th!s 1s @ str!ngl w!thg.? numb3rs, puncotuat!oHellon, and var!ous caayoubcd\n\n\n\nefghijklmnopqrstuvwxyzTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand vawr!ous caps.ps.") == "Th!s 1s @ str!ngl w!thg.? nmb3rs, pnctt!Hlln, nd vr!s cybcd\n\n\n\nfghjklmnpqrstvwxyzTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vwr!s cps.ps."
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3jaaaaAAAABBBCCCdddDEEEE!oveHello,dog.Hellon, and vaaaaAAdDEEaaaaHexample@example.comello,DEEEE!EEE!r!ous caps.") == "Th!s 1s @ str!ngl w!th nmb3jBBBCCCdddD!vHll,dg.Hlln, nd vdDHxmpl@xmpl.cmll,D!!r!s cps."
    @test remove_vowels("HelloanThe worldd!") == "HllnTh wrldd!"
    @test remove_vowels("aa@example.comTheaDEEaaaaAAdDEEEaE!EEE!") == "@xmpl.cmThDdD!!"
    @test remove_vowels("abcd\n\n\nc\novertfghijklmnopquickyz") == "bcd\n\n\nc\nvrtfghjklmnpqckyz"
    @test remove_vowels("watodayhow?jklmnoprstuvwxyzzzzzzzyoubcdorl") == "wtdyhw?jklmnprstvwxyzzzzzzzybcdrl"
    @test remove_vowels("pun!t!on,") == "pn!t!n,"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3jaaaaAAAABBBCCCdddDEEEE!oveHello,dog.Hellon, and vaaaaAAdDEEaaaaHexample@example.comello,DEEEE!EEE!r!ous .") == "Th!s 1s @ str!ngl w!th nmb3jBBBCCCdddD!vHll,dg.Hlln, nd vdDHxmpl@xmpl.cmll,D!!r!s ."
    @test remove_vowels("AEIxkfHeZldOUThe quick brown fox jumps over the lazy  dog.") == "xkfHZldTh qck brwn fx jmps vr th lzy  dg."
    @test remove_vowels("cpunctuaTh!s 1s @ str!ng w!th numb3rs, punctuat,!oHellnumb3rs,on, and var!ous caps.t!on,aayoubd") == "cpnctTh!s 1s @ str!ng w!th nmb3rs, pnctt,!Hllnmb3rs,n, nd vr!s cps.t!n,ybd"
    @test remove_vowels("The quick brown fox juamps odver a.comello,DEEEE!EEE!the lazy dog.h") == "Th qck brwn fx jmps dvr .cmll,D!!th lzy dg.h"
    @test remove_vowels("Heayoubcd\n\n\n\nefghijklmnopqrstuvwxyzTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand var!ous caps.xample@example.comello, how efge you totokdayzzzzzday?") == "Hybcd\n\n\n\nfghjklmnpqrstvwxyzTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cps.xmpl@xmpl.cmll, hw fg y ttkdyzzzzzdy?"
    @test remove_vowels("The quick brown AEEIOUaeHdo.elHlofoxHelloanThe jumps over the lazyog.") == "Th qck brwn Hd.lHlfxHllnTh jmps vr th lzyg."
    @test remove_vowels("abcd\np\n\nc\nefghijklmnopquickytoworld!day?jklmnoprstuvwxyzzzzzzzz") == "bcd\np\n\nc\nfghjklmnpqckytwrld!dy?jklmnprstvwxyzzzzzzzz"
    @test remove_vowels("efghijklmnopquickytoday?jklmnoprstuvwxyzzzzzzzz") == "fghjklmnpqckytdy?jklmnprstvwxyzzzzzzzz"
    @test remove_vowels("tkokday?jklmnoprstuvwxyzzztzzzzz") == "tkkdy?jklmnprstvwxyzzztzzzzz"
    @test remove_vowels("worlefghijklmnopquickytoday?jklmnoprstuvwxzzzzdd!") == "wrlfghjklmnpqckytdy?jklmnprstvwxzzzzdd!"
    @test remove_vowels("jumqTheps") == "jmqThps"
    @test remove_vowels("worlaaaaAAd!dd!iouqe") == "wrld!dd!q"
    @test remove_vowels("Th!s 1s @ str!ngl w!.th numb3rs, punctuat!oHellon, aand var!ous caps.") == "Th!s 1s @ str!ngl w!.th nmb3rs, pnctt!Hlln, nd vr!s cps."
    @test remove_vowels("punt!Hello wefghijklmnopqrstuvwxyztareorldd!,") == "pnt!Hll wfghjklmnpqrstvwxyztrrldd!,"
    @test remove_vowels("aand") == "nd"
    @test remove_vowels("The quick brocaayoubcdwn foxr jumps ovner the lazy  dog.") == "Th qck brcybcdwn fxr jmps vnr th lzy  dg."
    @test remove_vowels("xkfHeZTldAHexample@XbFTQMiAwtexample.comello,EIOUaepHello") == "xkfHZTldHxmpl@XbFTQMwtxmpl.cmll,pHll"
    @test remove_vowels("lazzy") == "lzzy"
    @test remove_vowels("odverlazy") == "dvrlzy"
    @test remove_vowels("wMdE") == "wMd"
    @test remove_vowels("Hellobrowntare") == "Hllbrwntr"
    @test remove_vowels("Th!s 1s @ str!ngl w!.th numb3rs, punctuat!oHellon, aand var!ous caexample@example.comTheps.") == "Th!s 1s @ str!ngl w!.th nmb3rs, pnctt!Hlln, nd vr!s cxmpl@xmpl.cmThps."
    @test remove_vowels("trstuvwxyzzztzzzzz") == "trstvwxyzzztzzzzz"
    @test remove_vowels("examplle@Th!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand var!ous caps.exameamplle@example.copm.com") == "xmpll@Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cps.xmmpll@xmpl.cpm.cm"
    @test remove_vowels("The quiHellobrownck brown AEEIOUaeHelHlofox jumps over the lazyAEIOUe") == "Th qHllbrwnck brwn HlHlfx jmps vr th lzy"
    @test remove_vowels("strTh!hpunctuat!oHel") == "strTh!hpnctt!Hl"
    @test remove_vowels("eTheaaaaAAAABBBnumb3rs,CCCdddDEw!!hEEE! quicykare blazzyaoog.rown fe") == "ThBBBnmb3rs,CCCdddDw!!h! qcykr blzzyg.rwn f"
    @test remove_vowels("Heayoubcd\n\n\n\nefghijklmnopqrstuvwxyzTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand quivervar!ous caps.xample@example.comello, how efge you totokdayzzzzzday?") == "Hybcd\n\n\n\nfghjklmnpqrstvwxyzTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd qvrvr!s cps.xmpl@xmpl.cmll, hw fg y ttkdyzzzzzdy?"
    @test remove_vowels("jyJJiBLGfRP") == "jyJJBLGfRP"
    @test remove_vowels("The quick br ocaayoubcdwn foxr jumps ovner the lazy  dog.") == "Th qck br cybcdwn fxr jmps vnr th lzy  dg."
    @test remove_vowels("aa@example.comTheaaDEEaaaaAThe quick brown fox juamps odver a.comello,DEEEE!EEE!the lazy dog.hAdDEEEaE!EEE!") == "@xmpl.cmThDTh qck brwn fx jmps dvr .cmll,D!!th lzy dg.hdD!!"
    @test remove_vowels("Hellodog. worstr!nld!") == "Hlldg. wrstr!nld!"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3rs, puncotuat!oHellon, and var!ous caayoubcd\n\n\n\nefghijklmnopqrstuvwxyzTh!s 1s @Th!s 1s @ str!ng w!th numb3rs, punctuat!oHellon, and var!ous caps. str!ngl w!th numb3rs, punctuat!oHellon, aand vawr!ous caps.ps.") == "Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cybcd\n\n\n\nfghjklmnpqrstvwxyzTh!s 1s @Th!s 1s @ str!ng w!th nmb3rs, pnctt!Hlln, nd vr!s cps. str!ngl w!th nmb3rs, pnctt!Hlln, nd vwr!s cps.ps."
    @test remove_vowels("dHello,") == "dHll,"
    @test remove_vowels("aa@exampwlo,!hle.comTheaDEEaaaaAAdDEEEaE!EEE!") == "@xmpwl,!hl.cmThDdD!!"
    @test remove_vowels("jumpsexamplecaps.xample@example.comello,@example.comThe") == "jmpsxmplcps.xmpl@xmpl.cmll,@xmpl.cmTh"
    @test remove_vowels("p,unc,") == "p,nc,"
    @test remove_vowels("AEIOUThefghijklmnopquickytoday?jklmnoprstuvwxyzzzzzzzz!e quick brown hfox  jumps over the lazy  dog.") == "Thfghjklmnpqckytdy?jklmnprstvwxyzzzzzzzz! qck brwn hfx  jmps vr th lzy  dg."
    @test remove_vowels("lagoTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aanvar!ous caps.") == "lgTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nvr!s cps."
    @test remove_vowels("br") == "br"
    @test remove_vowels("Hellodog. worstr!nltoday?og.hd!") == "Hlldg. wrstr!nltdy?g.hd!"
    @test remove_vowels("AEEIayoubc") == "ybc"
    @test remove_vowels("caaydoubd") == "cydbd"
    @test remove_vowels("dog.howuoverfosxick") == "dg.hwvrfsxck"
    @test remove_vowels("aaaaAAdDEEaaaaAHello wefghijklmnopqrstuvwxyztareorldd!AdDEEEstr!ngstr!ngandlaTh!s 1s @ str!ng  w!th numb3rs, punctuat!oHellon, and var!ous caps.zyandlazyE!EEE!") == "dDHll wfghjklmnpqrstvwxyztrrldd!dDstr!ngstr!ngndlTh!s 1s @ str!ng  w!th nmb3rs, pnctt!Hlln, nd vr!s cps.zyndlzy!!"
    @test remove_vowels("AEIOUaThe quick brown fox juamps odver aaaaAAdDEEaaaaHexample@example.comello,DEEEE!EEE!the lazy dog.heiou") == "Th qck brwn fx jmps dvr dDHxmpl@xmpl.cmll,D!!th lzy dg.h"
    @test remove_vowels("!!anThehwayoubcdorl") == "!!nThhwybcdrl"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3rs, puncotuat!oHellon, and var!ous caayoubcd\n\n\n\nefghijklmnopqrstuvwxy!zTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand vawr!ous caps.ps.") == "Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cybcd\n\n\n\nfghjklmnpqrstvwxy!zTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vwr!s cps.ps."
    @test remove_vowels("lazHellod1a2b3c4d5e6f7g8h9i10Hello,og.zcaexample@example.comTheps.") == "lzHlld12b3c4d56f7g8h910Hll,g.zcxmpl@xmpl.cmThps."
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3rs, punctuat,!oHellon, an d var!ous caps.") == "Th!s 1s @ str!ng w!th nmb3rs, pnctt,!Hlln, n d vr!s cps."
    @test remove_vowels("wdThe quick brown fox jumps over the  lazy dog.hd!iouq") == "wdTh qck brwn fx jmps vr th  lzy dg.hd!q"
    @test remove_vowels("thHello, how efghijklmnopqrstuvwxyztare you totokday?jklmnoprstuvwxyzzzzzzzzThe quick brown fox jumps over the lazy dog.hday?wefghijklmnopqrstuvwxyztareorldd!AdDEEEstr!ngstr!ngandlaTh!se") == "thHll, hw fghjklmnpqrstvwxyztr y ttkdy?jklmnprstvwxyzzzzzzzzTh qck brwn fx jmps vr th lzy dg.hdy?wfghjklmnpqrstvwxyztrrldd!dDstr!ngstr!ngndlTh!s"
    @test remove_vowels("hHellodog.ow") == "hHlldg.w"
    @test remove_vowels("caps.exameamplle@example.copm.com") == "cps.xmmpll@xmpl.cpm.cm"
    @test remove_vowels("AEIxkfHeZldOUThe quick bzy  dog.") == "xkfHZldTh qck bzy  dg."
    @test remove_vowels("wlazzyayoubcdorl") == "wlzzyybcdrl"
    @test remove_vowels("The quick brown foHello, how tare you today?x jumps over txXyYzZhe lazy dog.h") == "Th qck brwn fHll, hw tr y tdy?x jmps vr txXyYzZh lzy dg.h"
    @test remove_vowels("caps.zyandlazyE!EEE!") == "cps.zyndlzy!!"
    @test remove_vowels("efgxkfHeZTldAEIOUaeHellohijklmnopqrustuvwxyz") == "fgxkfHZTldHllhjklmnpqrstvwxyz"
    @test remove_vowels("jyJHellobrown world!iBLGfRP") == "jyJHllbrwn wrld!BLGfRP"
    @test remove_vowels("Tver the  lazy dog.h") == "Tvr th  lzy dg.h"
    @test remove_vowels("AEIOUThefghijklmnopquickytoday?jklmnoprstuvwxyzzzzzzzz!e") == "Thfghjklmnpqckytdy?jklmnprstvwxyzzzzzzzz!"
    @test remove_vowels("foxx") == "fxx"
    @test remove_vowels("The quick br ocaayoubcdwn foxr jukmps ovner the lazy  dog.") == "Th qck br cybcdwn fxr jkmps vnr th lzy  dg."
    @test remove_vowels("AThe") == "Th"
    @test remove_vowels("AEIOUae") == ""
    @test remove_vowels("quiefghijklmnopquick") == "qfghjklmnpqck"
    @test remove_vowels("caps.exameamplAEIOUaele@example.copm.com") == "cps.xmmpll@xmpl.cpm.cm"
    @test remove_vowels("jumpseThe") == "jmpsTh"
    @test remove_vowels("lagoTh!s 1s @ str!ngl w!th numb3rs,wdd!iouq") == "lgTh!s 1s @ str!ngl w!th nmb3rs,wdd!q"
    @test remove_vowels("xkflazyog.ddHld") == "xkflzyg.ddHld"
    @test remove_vowels("quiefghijkulmnopquick") == "qfghjklmnpqck"
    @test remove_vowels("dHello,  hh  taare you today?og.h") == "dHll,  hh  tr y tdy?g.h"
    @test remove_vowels("examplle@examexamplle@exampaa@exampwlo,!hle.comTheaDEEaaaaAAdDEEEaE!EEE!le.copm.com") == "xmpll@xmxmpll@xmp@xmpwl,!hl.cmThDdD!!l.cpm.cm"
    @test remove_vowels("dog.hAdDEEEaE!EEE!") == "dg.hdD!!"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3jaaaaAAAABBBCCCdddDEEEE!oveHello,dog.Hellon, and var!ojyJHellobrown world!iBLGfRPus caps.") == "Th!s 1s @ str!ngl w!th nmb3jBBBCCCdddD!vHll,dg.Hlln, nd vr!jyJHllbrwn wrld!BLGfRPs cps."
    @test remove_vowels("aaaaAAAxkfHeZTldAHexample@example.comello,EIOUaepHelloABBBCCdDEEEE!") == "xkfHZTldHxmpl@xmpl.cmll,pHllBBBCCdD!"
    @test remove_vowels("HellTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aanvar!ous.o,") == "HllTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nvr!s.,"
    @test remove_vowels("worlefghijklmnopqrstuvwxyzt") == "wrlfghjklmnpqrstvwxyzt"
    @test remove_vowels("jummps") == "jmmps"
    @test remove_vowels("quiefghijkulmnAEIOUaeiojyJiBLRGfRPopqpuick") == "qfghjklmnjyJBLRGfRPpqpck"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3rs, puncotuat!oHellon, and var!ous caayoubcd\n\n\n\nefghijklmnopqrstuvwxy!zTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aar!ous caps.ps.") == "Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cybcd\n\n\n\nfghjklmnpqrstvwxy!zTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, r!s cps.ps."
    @test remove_vowels("pun!t!onworld!iBLGfRPus,") == "pn!t!nwrld!BLGfRPs,"
    @test remove_vowels("youexamplefghijlazzyog.klmnopquickexample@example.comTheyze@example.comThe") == "yxmplfghjlzzyg.klmnpqckxmpl@xmpl.cmThyz@xmpl.cmTh"
    @test remove_vowels("HHe") == "HH"
    @test remove_vowels("caps.ps.") == "cps.ps."
    @test remove_vowels("aaexamDEEE!") == "xmD!"
    @test remove_vowels("aaaaAAAABBBnumb3t,!hoiHellon,ldd!liouqrs,CCCdddDEEEE!") == "BBBnmb3t,!hHlln,ldd!lqrs,CCCdddD!"
    @test remove_vowels("foHello,worlaaaaAAdDEEEE!dd!iouq") == "fHll,wrldD!dd!q"
    @test remove_vowels("Th!s 1s @ str!ngl w!thg.? numb3rs, puncotuat!oHellon, and var!ous caayoubcd\n\n\n\nefghijklmnopqrstuvwxyzTh!s 1s @ str!ngl w!th numb3rs, punctuat!oHellon, aand vawr!ous caps.ps.1a2b34c4d5e6f7g8h9i10Hello,") == "Th!s 1s @ str!ngl w!thg.? nmb3rs, pnctt!Hlln, nd vr!s cybcd\n\n\n\nfghjklmnpqrstvwxyzTh!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vwr!s cps.ps.12b34c4d56f7g8h910Hll,"
    @test remove_vowels("lworldd!azzyog.") == "lwrldd!zzyg."
    @test remove_vowels("Hello, how tare youexamplefghijlazzyog.klmnopquickexamplle@example.comTheyze@example.comThe today?") == "Hll, hw tr yxmplfghjlzzyg.klmnpqckxmpll@xmpl.cmThyz@xmpl.cmTh tdy?"
    @test remove_vowels("!!anThcehwayoubcdorl") == "!!nThchwybcdrl"
    @test remove_vowels("todTh!s 1s @ str!ng at,!jyJJiBLGfRPoHellon, and var!ous caps.ay?og.h") == "tdTh!s 1s @ str!ng t,!jyJJBLGfRPHlln, nd vr!s cps.y?g.h"
    @test remove_vowels("Hello, how tare youexamplefghijlazzyog.klmnopayoubcd\n\n\n\nefghijklmnopqrstuvwxyzle.comTheyze@example.comThe today?") == "Hll, hw tr yxmplfghjlzzyg.klmnpybcd\n\n\n\nfghjklmnpqrstvwxyzl.cmThyz@xmpl.cmTh tdy?"
    @test remove_vowels("1xkfHeZTldAEIOUaeHelloa2b3c4d5e6f7g8h9i10jklmnopqrstuvwxyzzz") == "1xkfHZTldHll2b3c4d56f7g8h910jklmnpqrstvwxyzzz"
    @test remove_vowels("w") == "w"
    @test remove_vowels("aaaaAAdDEEaaaaHEexample@example.comello,DEEEE!EEE!") == "dDHxmpl@xmpl.cmll,D!!"
    @test remove_vowels("cpunctuaTh!s") == "cpnctTh!s"
    @test remove_vowels("strtokday?jklmnoprstuvwxyzzztzzzzz!ng") == "strtkdy?jklmnprstvwxyzzztzzzzz!ng"
    @test remove_vowels("Th!s 1s @ str!ngl w!th numb3rs, puncotuat!oHellon, and var!ous cappun!t!onworld!iBLGfRPus,s.") == "Th!s 1s @ str!ngl w!th nmb3rs, pnctt!Hlln, nd vr!s cppn!t!nwrld!BLGfRPs,s."
    @test remove_vowels("caps.worlefghijklmnopqrstuvwxyztareyoot!on,") == "cps.wrlfghjklmnpqrstvwxyztryt!n,"
    @test remove_vowels("The quick tbrown AEEIayoubcd\n\n\n\nefghijklmnopqrstuvwxyzOUaeHdo.elHlofox jumps over the lazyog.") == "Th qck tbrwn ybcd\n\n\n\nfghjklmnpqrstvwxyzHd.lHlfx jmps vr th lzyg."
    @test remove_vowels("hHello,") == "hHll,"
    @test remove_vowels("jaaaaAAAAeBBBCCtoday?og.hCg.") == "jBBBCCtdy?g.hCg."
    @test remove_vowels("Th!s 1s @ str!ng w!th numb3Hello, how e you totokday?jklmnoprstuvwxyzzzzzzzzday?rs, punctuat,!oHellnumb3rs,on, and var!ous caps.") == "Th!s 1s @ str!ng w!th nmb3Hll, hw  y ttkdy?jklmnprstvwxyzzzzzzzzdy?rs, pnctt,!Hllnmb3rs,n, nd vr!s cps."
    @test remove_vowels("The quick brown ox jumps over the  lazy dog.h") == "Th qck brwn x jmps vr th  lzy dg.h"
    @test remove_vowels("tokday?jkxkfHeZTldAEIOUaeHlmnoprstuvxwxyzzzzzzzz") == "tkdy?jkxkfHZTldHlmnprstvxwxyzzzzzzzz"
    @test remove_vowels("gefghredog.hday?") == "gfghrdg.hdy?"
    @test remove_vowels("aaaaAAAAABBBCCCdddDElazzyaoog.EE!") == "BBBCCCdddDlzzyg.!"
    @test remove_vowels("Hello,  hh  tare you tod?") == "Hll,  hh  tr y td?"
    @test remove_vowels("dog.hoAEIOUaeHello worlaaaaAAdDEEEE!dd!iouqwuick") == "dg.hHll wrldD!dd!qwck"
    @test remove_vowels("str!ngctuat,!oHellon,") == "str!ngctt,!Hlln,"
    @test remove_vowels("xXyjcYzZwntare") == "xXyjcYzZwntr"
    @test remove_vowels("The qexamplle@example.comuick brown foxw!!hy g") == "Th qxmpll@xmpl.cmck brwn fxw!!hy g"
    @test remove_vowels("eThe") == "Th"
    @test remove_vowels("caps.efghijklmnTh!szy") == "cps.fghjklmnTh!szy"
    @test remove_vowels("aaexamDEE!") == "xmD!"
    @test remove_vowels("trstuvwxHello world!yzzztzzzzz") == "trstvwxHll wrld!yzzztzzzzz"
    @test remove_vowels("w!hthAEEIOUaeHelHlo") == "w!hthHlHl"
    @test remove_vowels("qexamplle@example.comuick") == "qxmpll@xmpl.cmck"
end
