@testitem "064_vowels_count_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "064_vowels_count.jl"))
    @test vowels_count("hello") == 2
    @test vowels_count("apple") == 2
    @test vowels_count("time") == 2
    @test vowels_count("glue") == 2
    @test vowels_count("candy") == 2
    @test vowels_count("parody") == 3
    @test vowels_count("monkey") == 3
    @test vowels_count("why") == 1
    @test vowels_count("bay") == 2
    @test vowels_count("aeiouy") == 6
    @test vowels_count("JBXFOFH") == 1
    @test vowels_count("c") == 0
    @test vowels_count("aeiouyaeiouy") == 11
    @test vowels_count("aeiouoy") == 7
    @test vowels_count("applebay") == 4
    @test vowels_count("eaeiouy") == 7
    @test vowels_count("applebaglue") == 5
    @test vowels_count("glumonkeye") == 4
    @test vowels_count("ndy") == 1
    @test vowels_count("ctieme") == 3
    @test vowels_count("wyhy") == 1
    @test vowels_count("parpody") == 3
    @test vowels_count("apndyple") == 2
    @test vowels_count("glumonglluekeye") == 6
    @test vowels_count("ctiparpodyecme") == 5
    @test vowels_count("aeicouyaeiouy") == 11
    @test vowels_count("pplebay") == 3
    @test vowels_count("glumonglluekewyhyye") == 6
    @test vowels_count("aeiooy") == 6
    @test vowels_count("applaebay") == 5
    @test vowels_count("bpplebay") == 3
    @test vowels_count("bayy") == 2
    @test vowels_count("hwhy") == 1
    @test vowels_count("aeioyoy") == 6
    @test vowels_count("aaappleeioauy") == 10
    @test vowels_count("candaeioyoyyndy") == 7
    @test vowels_count("candaeioyoyynad") == 7
    @test vowels_count("glumonappleglluekeye") == 8
    @test vowels_count("aeioowyhyy") == 6
    @test vowels_count("cthelloieme") == 5
    @test vowels_count("ctiieme") == 4
    @test vowels_count("glumonkeyee") == 5
    @test vowels_count("aeuyaeibayouy") == 10
    @test vowels_count("bcandaeioyoyynadpplebay") == 10
    @test vowels_count("eaeiy") == 5
    @test vowels_count("aeioappleuyaeiouy") == 13
    @test vowels_count("bcandaeioyoeyynadpplebay") == 11
    @test vowels_count("aeuyaeibayoyuy") == 10
    @test vowels_count("applebaglueaeiye") == 9
    @test vowels_count("aeictiemeoappleuyaeiouy") == 16
    @test vowels_count("ttimeime") == 4
    @test vowels_count("aeiouyaeglumonkeyeiouy") == 15
    @test vowels_count("aeioydndyoy") == 6
    @test vowels_count("aeioowyhyoy") == 7
    @test vowels_count("ahelloaappleeioauy") == 12
    @test vowels_count("glumone") == 3
    @test vowels_count("aeiyy") == 4
    @test vowels_count("gluemone") == 4
    @test vowels_count("bcandyndaeioapplebaglueyoyynadpplebay") == 15
    @test vowels_count("ctiparpodyaecme") == 6
    @test vowels_count("glumoaeioowyhyyne") == 8
    @test vowels_count("applebaglueaeiyectiieme") == 13
    @test vowels_count("ba") == 1
    @test vowels_count("nddy") == 1
    @test vowels_count("eaeeiouy") == 8
    @test vowels_count("pardy") == 2
    @test vowels_count("aba") == 2
    @test vowels_count("glumopnappleglluekeye") == 8
    @test vowels_count("applebagluyeaeiye") == 9
    @test vowels_count("aeicandaeioyoyynadooewyhyy") == 14
    @test vowels_count("glumlonkoeaeioowyhyoyyee") == 12
    @test vowels_count("aeuyaeeibayouy") == 11
    @test vowels_count("teglumonglluekeyeime") == 9
    @test vowels_count("cmonkeyandy") == 4
    @test vowels_count("candaeioyd") == 5
    @test vowels_count("canddaeyd") == 3
    @test vowels_count("aeiouwyhyyaeglumonkeyeiouy") == 15
    @test vowels_count("cthelloiecanddyndyme") == 6
    @test vowels_count("pzUzSiO") == 3
    @test vowels_count("aeyaeibayoyuy") == 9
    @test vowels_count("aeeyaeibayoyuy") == 10
    @test vowels_count("bcandyndaeioapplaebaglueyoyynadpplebay") == 16
    @test vowels_count("aeiyycandaeioyoyynad") == 10
    @test vowels_count("ctiemictiiemee") == 8
    @test vowels_count("aeicandaeioyoyynadooewyhyyaeiouyaeiouypzUzSiO") == 26
    @test vowels_count("hKaAyE") == 3
    @test vowels_count("canddy") == 2
    @test vowels_count("gluemglumlonkoeaeioowyhyoyyeaeiouoye") == 20
    @test vowels_count("applaebbaglumonglluekewyhyyey") == 11
    @test vowels_count("aeiyycandaeihwhyoyoyynad") == 10
    @test vowels_count("applebaglueaeiyectiieeme") == 14
    @test vowels_count("aeuyaeiyuy") == 8
    @test vowels_count("aeioappleuyaeiiouy") == 14
    @test vowels_count("y") == 1
    @test vowels_count("applebageluyeaeiye") == 10
    @test vowels_count("eapple") == 3
    @test vowels_count("ctipttimeimearpodyaeceme") == 11
    @test vowels_count("acanddyteglumonapplaebbaglumonglluekewyhyyeyglluekeyeimeeyaeibayoyuy") == 29
    @test vowels_count("ctmeimearpodyaeceme") == 9
    @test vowels_count("pctiparpodyecmearpody") == 8
    @test vowels_count("bcdfghjklmnpqrstvwxyz") == 0
    @test vowels_count("aAAaAaaAaaaaa") == 13
    @test vowels_count("ABCDEFGHIJKLMNOPQRSTUVWXYZ") == 5
    @test vowels_count("AEIOUYXW") == 5
    @test vowels_count("cryptography") == 3
    @test vowels_count("psychology") == 3
    @test vowels_count("dizziness") == 3
    @test vowels_count("abstemiousness") == 6
    @test vowels_count("facetiousness") == 6
    @test vowels_count("bcdfghjklmnpabstemiousnessqrstvwxyz") == 6
    @test vowels_count("bcdfghjklmnpabstemiousnessqrstvxyz") == 6
    @test vowels_count("aeiouyfacetiousness") == 11
    @test vowels_count("asbstemiousness") == 6
    @test vowels_count("psypsychology") == 3
    @test vowels_count("facetioubcdfghjklmnpqrstvwxyzsness") == 6
    @test vowels_count("ABCDEFGHIJKLMNOPQRSTUVWXZ") == 5
    @test vowels_count("AEIOUYYXW") == 5
    @test vowels_count("cpsychology") == 3
    @test vowels_count("cryptograpy") == 3
    @test vowels_count("aAEIOUYXWouy") == 9
    @test vowels_count("cryptographcy") == 3
    @test vowels_count("aeioaAAaAaaAaaaaauyfacetiousness") == 24
    @test vowels_count("psypsycfacetioubcdfghjklmnpqrstvwxyzsnesshology") == 9
    @test vowels_count("iaeaeiouyfacetiousnessioouy") == 19
    @test vowels_count("bcdfgjhjklmnpqrstvwxyz") == 0
    @test vowels_count("AEW") == 2
    @test vowels_count("cryptogracpy") == 3
    @test vowels_count("facetioubcdffghjklmnpqrstvwxyzsness") == 6
    @test vowels_count("aAAaAaaAaaa") == 11
    @test vowels_count("iaeaeiouyfacetiousnessioAEIOUYYXWouy") == 24
    @test vowels_count("aOAEIOUYXWouy") == 10
    @test vowels_count("cryptograpyy") == 3
    @test vowels_count("psyc") == 0
    @test vowels_count("cpsyccryptographyhology") == 5
    @test vowels_count("cryptograacpsychologyOAEIOUYXWouycpy") == 14
    @test vowels_count("aieiouy") == 7
    @test vowels_count("cryptbcdfgjhjklmnpqrstvwxyzograacpsychologyOAEIOUYXWouycpy") == 14
    @test vowels_count("aeioaAAaAaaAaaaaauyfacfacetiousnessetiousness") == 30
    @test vowels_count("aeioiaeaeiouyfacetiousnessioouyuy") == 24
    @test vowels_count("aeiouyfaceftiousness") == 11
    @test vowels_count("aeioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuy") == 28
    @test vowels_count("aAAaaAaaAaaaaa") == 14
    @test vowels_count("aoeiouyfaceaeiouyfacetiousnessss") == 19
    @test vowels_count("psypsycfacetioubcdfghjklmdizzinessnpqrstvwxyscryptograacpsychologyOAEIOUYXWouycpyhology") == 24
    @test vowels_count("aieioABCDEFGHIJKLMNOPQRSTUVWXZuy") == 12
    @test vowels_count("dizzinesds") == 3
    @test vowels_count("iaeaeiiouyfacetiousnessioouy") == 20
    @test vowels_count("aaaAaaa") == 7
    @test vowels_count("oaAEIOUYXWouy") == 10
    @test vowels_count("cpsbcdfghjklmnpabstemiousnessqrstvwxyzology") == 9
    @test vowels_count("bcdfgbhjklmnpabstemiousnessqrstvxyz") == 6
    @test vowels_count("aeiocryptographcyuyfacetiousness") == 13
    @test vowels_count("pssypsychology") == 3
    @test vowels_count("asbstemiousnessaeiouyfaceftiousness") == 17
    @test vowels_count("facetioubcdffghjklfmnpqrstvwxyzsness") == 6
    @test vowels_count("bcdfghjklgmnpabstemiousnessqrstvwxyz") == 6
    @test vowels_count("facetioubcdffbcdfghjklmnpabstemiousnessqrstvxyzghjklmnpqrstvwxyzsness") == 12
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaa") == 32
    @test vowels_count("iaeaeiiouyfacetioiusnessioouy") == 21
    @test vowels_count("bcdfgjhabstemiousnessjklmnpqrstvwxyz") == 6
    @test vowels_count("bcdfgjhabstemaeioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuynessjklmnpqrstvwxyz") == 30
    @test vowels_count("psiaeaeiiouyfacetioiusnessioouyyc") == 20
    @test vowels_count("aeioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuyenns") == 28
    @test vowels_count("aeipsypsycfacetioubcdfghjklmdizzinessnpqrstvwxyscryptograacpsychologyOAEIOUYXWouycpyholuyuy") == 28
    @test vowels_count("bcdfgjhabstemiousnessjklmnpqrstvvwxyz") == 6
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyz") == 32
    @test vowels_count("iaeaeiiouyfacetiocryptograacpsychologyOAEIOUYXWouycpyiusnessioouy") == 34
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnvwxyz") == 32
    @test vowels_count("cryptogracaAEIOUYXWouypy") == 11
    @test vowels_count("crypotography") == 4
    @test vowels_count("aieioABCDEFGHIJKCLMNOPQRSTUVWXZuy") == 12
    @test vowels_count("aeipsypsycfacetioubcdfghjklmdizzinessnpqrstvwxyscryptograacpsychsologyOAEIOUYXWouycpyholuyuy") == 28
    @test vowels_count("cryptogracfacetioubcdffghjklfmnpqrstvwxyzsnesspy") == 9
    @test vowels_count("afacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousness") == 36
    @test vowels_count("facetioubcdffghjklmnpqrswxyzsness") == 6
    @test vowels_count("pbcdfghjklgmnpabstemiousnessqrstvwxyzlogy") == 8
    @test vowels_count("facetioubcdffghjklmnpqraAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyzstvwxyzsness") == 38
    @test vowels_count("bcdfgjhabstfecryptogracaAEIOUYXWouypymiousnessjklmnpqrstvvwxyz") == 16
    @test vowels_count("aieieouy") == 8
    @test vowels_count("aeioiaeaeiouyfacetiousnesasbstemiousnesssioouyuy") == 30
    @test vowels_count("bcdfghjklgmnpqrstvwxyz") == 0
    @test vowels_count("psycpbcdfghjklgmnpabstemiousnessqrstvwxyzlogy") == 8
    @test vowels_count("afacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsnessiousness") == 42
    @test vowels_count("facetioubcdfghjwxyzsness") == 6
    @test vowels_count("bcdfgbhjklmnpabstemiousnessqrstvaOAEIOUYXWouyxyz") == 15
    @test vowels_count("aieiiouy") == 8
    @test vowels_count("aaaaaAaaaa") == 10
    @test vowels_count("iaeaeiiouyfacetiousaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnvwxyzy") == 47
    @test vowels_count("aipbcdfghjklgmnpabstemiousnessqrstvwxyzlogyeiiouy") == 15
    @test vowels_count("OAEIOUYXW") == 6
    @test vowels_count("cryptiaeaeiouyfacetiousnessioAEIOUYYXWouyogracpy") == 26
    @test vowels_count("psypsycfacetioubcdfghjklmnpqrstvwxyfzsnesshology") == 9
    @test vowels_count("facetioubcdffghjklmnpqraAAaaAaaAaaiaeaeiouyfacetiousnessioouss") == 34
    @test vowels_count("bcdfgjhabstemiousnessjklmnpqrstvvxwxyz") == 6
    @test vowels_count("crypttographcy") == 3
    @test vowels_count("aeiouyfaceftiousnesasbstemiousness") == 17
    @test vowels_count("aeioiaeaeiocpsyccryptographyhologyouyfacetiousssioouyuy") == 28
    @test vowels_count("aeiouyfaceftiousneness") == 12
    @test vowels_count("bcdfghjklmnpqrsaieioABCDEFGHIJKLMNOPQRSTUVWXZuyxyz") == 11
    @test vowels_count("psiaeaeiiobcdfghjcetioiusnessioouyyc") == 18
    @test vowels_count("aeiioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuyenns") == 29
    @test vowels_count("bcdfghjklmnpqrstvyz") == 0
    @test vowels_count("aeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsnessaaauyfacfacetiousnessetiousness") == 36
    @test vowels_count("psypsycfacetioubcdfghjklmdizzinfacetioubcdffghjklmnpqrswxyzsnessessnpqrstvwxyscryptograacpsychologyOAEIOUYXWouycpyhology") == 30
    @test vowels_count("afacetinessetiousness") == 10
    @test vowels_count("aeiouyfacetiousnessy") == 12
    @test vowels_count("aeiouyfacetiousnbcdfghjklmnpqrstvyzessy") == 12
    @test vowels_count("fazcetioubcdffghjklmnpqrstvwxyzsness") == 6
    @test vowels_count("psyypsycfacetioubcdfghjklmdizzinfacetioubcdffghjklmnpqrswxyzsnessessnpqrstvwxysouycpyhology") == 19
    @test vowels_count("facetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 25
    @test vowels_count("facetioubcdffghjpbcdfghjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 32
    @test vowels_count("afacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsnessiAousness") == 43
    @test vowels_count("aeioiaeaeiocpsyccryptographyhologyuyfacouyuy") == 21
    @test vowels_count("OAEaAAaaAaaAaaaaaUYXW") == 18
    @test vowels_count("aoeiouyfaceaeiouyfacetieousnessss") == 20
    @test vowels_count("facetioubcdffghstvwxyzsness") == 6
    @test vowels_count("ai") == 2
    @test vowels_count("aiei") == 4
    @test vowels_count("yy") == 1
    @test vowels_count("pcsypsycfacetioubcdfghjklmnpqrstvwxyzsnesshology") == 9
    @test vowels_count("facetioubcdffghjkfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnesslmnpqrstvwxyzsness") == 31
    @test vowels_count("aOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnessWouy") == 21
    @test vowels_count("aaaaaAapsychologyaaa") == 12
    @test vowels_count("aeiiociaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuyenns") == 29
    @test vowels_count("abs") == 1
    @test vowels_count("psypsycfacetioubcdfghjklmdizzinfacetioubcdffghjklmnpqrswxyzsnessessnpqrstvwxyscryptograacpsychyologyOAEIOUYXWouycpyhology") == 30
    @test vowels_count("aAAaaAaafacetioubcdffghjklmnpqrstvwxyzsnessAaaaaa") == 20
    @test vowels_count("facettioubcdffghstvwxyzsness") == 6
    @test vowels_count("iaeaeiouyfacetiousnessiioAEIOUYYXWouy") == 25
    @test vowels_count("aeiouyffazcetioubcdffghjklmnpqrstvwxyzsnessacetiousnessy") == 18
    @test vowels_count("aAAaaAaacrypotographyAaaaaa") == 17
    @test vowels_count("aeioiaeaeiocpsyccryptographyhologyuyfacetiousnessiaoouyuyenns") == 29
    @test vowels_count("aAEIcryptograpyOUYXWouy") == 11
    @test vowels_count("facetioubcdaeiouyfacetiousnbcdfghjklmnpqrstvyzessyffghjklmnpqrstvwxyzsness") == 17
    @test vowels_count("cryptbcdfgjhjklmnpqrstvwxyzograacpsychologyOAEIOUYXWouybcdfgjhjklmnpqrstvwxyzcpy") == 14
    @test vowels_count("iaeaoeiiouyfacetiousnessioouy") == 21
    @test vowels_count("aeioiaeaeiocpsyccryptogaoeiouyfaceaaieieiouyfacetieousnessssraphyhologyouyfacetiousssioouyuy") == 52
    @test vowels_count("aAEIaAAaaAaaAaaaaaograpyOUYXWouy") == 25
    @test vowels_count("facetioubcdffghjpbcdfghjklgmnpabstemiousnessqrstvwaAEIOUYXWouyxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 40
    @test vowels_count("cryptbcdfgjhjklmnaieioABCDEFGHIJKCLMNOPQRSTUVWXZuycdfgjhjklmnpqrstvwxyzcpy") == 12
    @test vowels_count("psypsycfacetioubcdfghjklmdizziycpyhology") == 10
    @test vowels_count("AEIYOUYYXW") == 5
    @test vowels_count("aipbcdfghjklgmnpabstemiousnessqrzlogyeiiouy") == 15
    @test vowels_count("bcdfgjhabqrstvwxyz") == 1
    @test vowels_count("aeiocryptographcyuyfacetpsycinousness") == 13
    @test vowels_count("afacetioubcdfghjklmnfacetioubcdfghjwxyzsnesspqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsnesssiousness") == 48
    @test vowels_count("psypsycfacetioubcdfghjklmdizzinessnpqrstvwxyscryptograacpsychologyOAEIOUYfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessXWouycpyhology") == 49
    @test vowels_count("cpsyccrypaeiioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuyennstographyhology") == 34
    @test vowels_count("crypytograpyy") == 3
    @test vowels_count("cpsyccrypaeiioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuyennstograpahyhology") == 35
    @test vowels_count("aeiocryptographcyyuyfacetpsycinousness") == 13
    @test vowels_count("afacetioubcdfghjklmnpqrstvwaxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsnessiAousness") == 44
    @test vowels_count("cryptogracaAEIOUYXWoucpsyccryptographyhologyypy") == 15
    @test vowels_count("cryptbaeiouycdfgjhjklmnpqrstvwxyzograacpsychologyOAUEIOUYXWouybcdfgjhjklmnpqrstvwxyzcpy") == 20
    @test vowels_count("iaeaoeiiouyfacetiioouy") == 18
    @test vowels_count("facettioubcdffghstvwxyzsnOAEaAAaaAaaAaaaaaUYXWess") == 24
    @test vowels_count("bcdfghjklmnpqrsaieioABCDEFGHIJKLMNOPQRSTUVWXZuyyz") == 11
    @test vowels_count("aaaaaaAapsychologyaaai") == 14
    @test vowels_count("aOAEIOUYXWaeiocryptographcyuyfacetiousnessouy") == 23
    @test vowels_count("asbstemioussnessaeiouyfaceftiousness") == 17
    @test vowels_count("asbstemiousnessaeioouyfaceftiousnesis") == 19
    @test vowels_count("kBhhbjyoPZ") == 1
    @test vowels_count("aeioiabsaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuy") == 29
    @test vowels_count("aeiocryAEWptographcyyuyfacetpsycinousness") == 15
    @test vowels_count("facetioubcdffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyzs") == 38
    @test vowels_count("aAAaaAaaAaaiacryptogracaAEIOUYXWoucpsyccryptographyhologyypyeaeiouyfacetiousnessioouyaaabcdfghjklmnvwxyz") == 46
    @test vowels_count("cpsycholaaaaaaAapsychologyaaaiogy") == 17
    @test vowels_count("aaeiouyfaceftiousnenessieiiouy") == 20
    @test vowels_count("afacetioubcdfghjklmnpqrstvwaxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqfacetioubcdffghstvwxyzsnesssiAousness") == 49
    @test vowels_count("facetioaAAaaAaacrypotographyAaaaaaubcdfghjklmnpqrstvwxyzsness") == 23
    @test vowels_count("aeipsypsycfacetoubcdfghjklmdizzinessnpqrstvwxyscryptograacpsychologyOAEIOUYXWouycpyholuyuy") == 27
    @test vowels_count("iaeaeiiouyfacetiousaAAaaAaaAaaiaaieioABCDEFGHIJKLMNOPQRSTUVWXZuyeaeiouyfacetiousnessioouyaaabcdfghjklmnvwxyzy") == 58
    @test vowels_count("aAAaaAaaAaaiacryptogracaAEIOUYXWoucpsyccryptographyhologyypyeaeiouyfaacetiousnessioouyaaabcdfghjklmnvwxyz") == 47
    @test vowels_count("iaeaeiiouyfacetiocryptograacpsychologyOAEIOUYXWoguycpyiusnessioouy") == 34
    @test vowels_count("aeioiaeaeiocpsyccryptographyholaogyuyfacetiousnessioouyuyenns") == 29
    @test vowels_count("bcdfgbhjklmnpabstemiousneABCDEFGHIJKLMNOPQRSTUVWXZssqrstvxyz") == 11
    @test vowels_count("bcdfghjklgmnpqrtvwxyz") == 0
    @test vowels_count("aeipbcdfghjklgmnpabstemiousnessqrzlogyeiiouy") == 16
    @test vowels_count("aeiiociaeaeiocpsyccryptographyhologyuyfacetiousnyenns") == 23
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstvwxyzologyxyz") == 40
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiaousnessioouyaaa") == 33
    @test vowels_count("aAAaAaaAaaaaaa") == 14
    @test vowels_count("bcdfgbhjklmnpabsbcdfgbhjklmnpabstemiousnessqrstvaOAEIOUYXWouyxyztemiousnseABCDEFGHIJKLMNOPQRSTUVWXZssqrstvxyz") == 26
    @test vowels_count("aOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouy") == 21
    @test vowels_count("facetioubcdffbcdmfghjklmnpabstemiousnessqrstvxyzghjklmnpqrstvwxyzsness") == 12
    @test vowels_count("OAEIOUYXOW") == 7
    @test vowels_count("bcdfgbhjklmnpabsteemiousnessqrstvxyz") == 7
    @test vowels_count("iaeaeiouyfacetiouaeioiaeaeiocpsyccryptographyhologyuyfacouyuysnessioAEIOUYYXWouy") == 44
    @test vowels_count("aipbcdfghjklgmnpabstemiousnpsypsycfacetioubcdfghjklmdizzinfacetioubcdffghjklmnpqrswxyzsnessessnpqrstvwxyscryptograacpsychologyOAEIOUYXWouycpyhologyessqrzlogyeiiouy") == 44
    @test vowels_count("aeipbcdfghjklgmnpabstemiousnessqrzlogyyeiiouy") == 16
    @test vowels_count("pcsypsycfacebcdfghjklgmnpqrstvwxyzrstvwxyzsnesshology") == 6
    @test vowels_count("aeiouyffazcetioubcdffghjklmnpqrstvwxyzsnessacetaAEIOUYXWouyiousnessy") == 26
    @test vowels_count("aeiouyfacetiousneses") == 12
    @test vowels_count("aipbcdfghjklgmnpabstepmiousnessqrzlogyeiiouy") == 15
    @test vowels_count("basbstemiousness") == 6
    @test vowels_count("ABCDEFGHIJKLMNOPQRSTUYZ") == 5
    @test vowels_count("facetioubcdffghjpbcdfghfacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 38
    @test vowels_count("dizzifacettioubcdffghstvwxyzsnOAEaAAaaAaaAaaaaaUYXWessness") == 27
    @test vowels_count("bcdfgjhabstemaeioiaeaeiocpsyccryptographyhologyuyfacetiousinessioouyuynessjklmnpqrstvwxyz") == 31
    @test vowels_count("aieioABCDEFGHIJKLMNOPQRiaeaeiiouyfacetiousnessioouySTUVWXZuy") == 31
    @test vowels_count("aAAaaAaaAaaniaeaeiouyfacetiousnessioouyaaa") == 32
    @test vowels_count("iaeaoeiiouyfacetiiooaeioiabsaeaeiocpsyccryptographyhologyuyfacetiousnessioaAAaaAaafacetioubcdffghjklmnpqrstvwxyzsnessAaaaaaouyuyuy") == 66
    @test vowels_count("iaeaeiouyfacetiousnessioAEIYXWouy") == 22
    @test vowels_count("facetioubcdffghjklfmniaeaeiiouyfacetiouspsypsycfacetioubcdfghjklmdizzinessnpqrstvwxyscryptograacpsychologyOAEIOUYfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessXWouycpyhologynessioouypqrstvwxyzsness") == 73
    @test vowels_count("aOAEIOUYXfazcetioubcdffghjklAEIaeiocryptographcyuyfacetiousnessOUYXWmnpqrstvwxyzsnessWouy") == 34
    @test vowels_count("crypytograpaeioiaeaeiocpsyccryptogaoeiouyfaceaaieieiouyfacetieousnessssraphyhologyouyfacetiousssioouyuyyy") == 54
    @test vowels_count("bcdfgjhabstemiousnessjdklmnpqrstvwxyz") == 6
    @test vowels_count("asbstemiousnessaeioouyfaceftiousnesais") == 20
    @test vowels_count("cryptogracfacetioubcdffghjklfmnpqrstvwxyzsneaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyzsspyaeiouyfacetiousnbcdfghjklmnpqrstvyzessy") == 52
    @test vowels_count("dizzinesdcryptbcdfgjhjklmnpqrstvwxyzograacpsychologyOAEIOUYXWouycpys") == 16
    @test vowels_count("facetioubcdffghjpbcdfghjklgmnpabstemiousneaeiouyfaceftiousnnesasbstemiousnessYXWouyxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 51
    @test vowels_count("bcdfghjklmnpabstemiousnessqrsstvwxyz") == 6
    @test vowels_count("aeiouyfaceftiousneneuss") == 13
    @test vowels_count("aAAaaAaaAaaiacryptogrWacaAEIOUYXWoucpsyccryptographyhologyypyeaeiouyfaacetiousnessioouyaaabcdfghjklmnvwxyz") == 47
    @test vowels_count("bcdfcrypytograpyyghjklmnpabstemiousnessqrsstvwxyz") == 8
    @test vowels_count("aeioiaeaeiocpsyccryptogaoeiouyfaceaaieieoiouyfacetieousnessssraphyhologyouyfacetiousssioouyuy") == 53
    @test vowels_count("aeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsnessaaauyfacfacetiousnessetiousnesspsyc") == 36
    @test vowels_count("cryptbcdfgjhjklmnpqrstvwxyzograacpsychologyOAEIOUYXWouaeiouyfacetiousnesesy") == 26
    @test vowels_count("bcdfghjklmnpabstemiousnesssqrsstvwxyz") == 6
    @test vowels_count("gAaeiouyffazcetioubcdffghjklmnpqrstvwxyzsnessacetaAEIOUYXWouyiousnessy") == 27
    @test vowels_count("aOAyEIOUYXWouy") == 10
    @test vowels_count("cryptogracaAEIOUYXWoucpsycocryptographyhologyypy") == 16
    @test vowels_count("aieiiaaaAaaaouy") == 15
    @test vowels_count("aeiouyfaceeftiousness") == 12
    @test vowels_count("asbstemiousnessaeiouyfac") == 12
    @test vowels_count("afacetineousness") == 8
    @test vowels_count("psypsycfacetioubcdfghjklmnpqqrstvwxyzsnesshology") == 9
    @test vowels_count("cpsyccrypaeiioiaeaeiocpsyccryptographyhoglogyuyfacetiousnessioouyuyennstograpahyhology") == 35
    @test vowels_count("iAEIOUYYXWaeaeiiouyfacetaaaaaAapsychologyaaaiousaAAaaAaaAaaiaaieioABCDEFGHIJKLMNOPQRSTUVWXZuyeaeiouyfacetiousnessioouyaaabcdfghjklmnvwxyzy") == 75
    @test vowels_count("asbstemiousnessaeiasbstemiousnessaeiouyfaceftiousnessouyfaceaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouyfsness") == 51
    @test vowels_count("facetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrsdizzinesstvwxyzsiaeaeiouyfacetiousnessioouyness") == 46
    @test vowels_count("iaeaeiiouyfacetiousaAAaaAaaAaaiaaieioABCDEFGHIJKLMNOPQRSTUVWXZuyeaeiouyfacetioioouyaaabcdfghjklmnvwxyzy") == 56
    @test vowels_count("aoeiouyfaceaeiouyfacetiousnescsss") == 19
    @test vowels_count("bcdfghjklgmnpqrstvwxyzai") == 2
    @test vowels_count("aeioiaoeaeiocpsyccryptographyhologyouyfaceteiousssioouyuy") == 30
    @test vowels_count("cryptog") == 1
    @test vowels_count("rcrypotography") == 4
    @test vowels_count("ciaeaeiouyfacetiousnessioouy") == 19
    @test vowels_count("cryptogracpyaAEIOUYXWouy") == 11
    @test vowels_count("casbstemiousnessaeiasbstemiousnessaeiouyfaceftiousnessouyfaceaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouyfsness") == 51
    @test vowels_count("asbstemioussnessaeioucryptogracfacetioubcdffghjklfmnpqrstvwxyzsnesspyyfaceftiousness") == 25
    @test vowels_count("psypsycfacetioubcdfghjklmdizziyycpyhology") == 10
    @test vowels_count("aipcbcdfghjklgmnpabstepmiousnessqrzlogyeiiouy") == 15
    @test vowels_count("aAAaaaAaaAaaaaa") == 15
    @test vowels_count("dizziaieABCDEFGHIJKLMNOPQRSTUYZiness") == 12
    @test vowels_count("afacetinessetiousnness") == 10
    @test vowels_count("aieieoyuy") == 8
    @test vowels_count("facetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouydffghjpbcdfghfacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 58
    @test vowels_count("cpsycholog") == 2
    @test vowels_count("fazcryptogcetioubcdffghjklmnpqrstvwxyzsness") == 7
    @test vowels_count("aa") == 2
    @test vowels_count("facettioubcdffghstvwxyzsfnOAEaAAaaAaaAaaaaaUYXWess") == 24
    @test vowels_count("facetioubgcdffghjpbcdfghjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 32
    @test vowels_count("aAAaAaaAaafacetioubgcdffghjpbcdfghjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessa") == 43
    @test vowels_count("afacetioubcdfghjklmnpuyfacfacetiousnessetiousness") == 19
    @test vowels_count("facetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnessydffghjpbcdfghfacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 94
    @test vowels_count("aeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsnesaisaaauyfacfacetiousnessetiousness") == 38
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiousnessioaeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsnessaaauyfacfacetiousnessetiousnessouyaaabcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstevwxyzologyxyz") == 77
    @test vowels_count("aAAaAaaAaafacetioubgcousnessioouypqrstvwxyzsnessa") == 24
    @test vowels_count("aeiocryptographccpsychologfacetpsyaicinousness") == 16
    @test vowels_count("asfacetioaAAaaAaacrypotographyAaaaaaubcdfghjklmnpqrstvwxyzbcdfghjklmnpabstemiousnessqrstvxyzsnessbstemioussnessaeiouyfaceftiousness") == 46
    @test vowels_count("cpsyccrypaeiioiaeaeiuocpsyccryptographyhologyuyfacetiousnessioouyuyennstograpahyhology") == 36
    @test vowels_count("f") == 0
    @test vowels_count("afacetineousnesss") == 8
    @test vowels_count("ABCDEFGHIJKLrcrypotographyMNOPQRSTUYZ") == 8
    @test vowels_count("facetioubcdffbcdmfghjklmnpabstaeioiaeaeiouyfacetiousnesasbstemiousnesssioouyuy") == 36
    @test vowels_count("iaeaoeiiouyfacetiouisnessioouy") == 22
    @test vowels_count("cryptbcdfgjhjklmnpqrstvwxyzograacpsychologyhOAEIOUYXWouybcdfgjhjklmnpqrstvwxyzcpy") == 14
    @test vowels_count("aieioABCDEFGHIJKLMNOPQRSTUVWXZpsiaeaeiiobcdfghjcecpsyccryptographyhologytioiusnessioouyycuy") == 34
    @test vowels_count("facetioubcdfaeiouyfacetiousnessyfghjpbcdfghfacetioubcdfghfacetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnessydffghjpbcdfghfacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 143
    @test vowels_count("bcdfgjhabstemaeioiaeaeiocpsyccryptographyhologyuyfacetafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsnessiousnessessjklmnpqrstvwxyz") == 63
    @test vowels_count("facetioubcdffghjkfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnesslcryptogracaAEIOUYXWoucpsycocryptographyhologyypymnpqrstvwxyzsness") == 46
    @test vowels_count("OUYXW") == 2
    @test vowels_count("cpsaAEIcryptograpyOUYXWouyychology") == 13
    @test vowels_count("aeiouyffazcetioubcdcpsyccrypaeiioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuyennstographyhologyffghjklmnpqrstvwxyzsnessacetaAEIOUYXWouyiousnessy") == 59
    @test vowels_count("aeiouyfaceftiousnesasbstemiousnuess") == 18
    @test vowels_count("aeiaeaoeiiouyfacetiouisnessioouyipsypsycfacetoubcdfghjklmdizzinessnpqrstvwxyscryptograacpsychologyOAEIOUYXWouycpyholuyuy") == 48
    @test vowels_count("bcdfghjklmnpabsteusnessqrstyyvxyz") == 4
    @test vowels_count("aAAaieioABCDEFGHIJKLMNOPQRSTUVaAAaaAaacrypotographyAaaaaaWXZuyaAaaAaafacetioubgcousnessioouypqrstvwxyzsnessa") == 52
    @test vowels_count("absaipbcdfghjklgmnpabstemiousnpsypsycfacetioubcdfghjklmdizzinfacetioubcdffghjklmnpqrswxyzsnessessnpqrstvwxyscryptograacpsychologyOAEIOUYXWouycpyhologyessqrzlogyeiiouy") == 45
    @test vowels_count("aipbcdfghjklgmnpabstemiousnpsypsycfacetioubcdfafacetineousnessghjklmdizzinfacetioubcdffghjklmnpqrswxyzsnessessnpqrstvwxyscryptograacpsychologyOAEIOUYXWouycpyhologyessqrzlogyeiiouy") == 52
    @test vowels_count("aipbcdfghjklgmnpabstemiousnpsypsycfacetioubcdfghjklmdizzinfacetioubcdffghjklmnpqrswxyzsnessessnpqrstvwxyscryptograacpsychologyOAEIOUYdizzifacettioubcdffghstvwxyzsnOAEaAAaaAaaAaaaaaUYXWessnesscpyhologyessqrzlogyeiiouy") == 69
    @test vowels_count("eiouyffazcetioubcdffghjklmnpqrstvwxyzsnessacetaAEIOUYXWouyiousnessy") == 25
    @test vowels_count("facetioubgcdffghjpbcdfghjklgmnpabstemiousnessqrstvwxyzlogynessioouypqrstvwxyzsness") == 18
    @test vowels_count("aeiouyfaceftiousnesfacetioaAAaaAaacrypotographyAaaaaaubcdfghjklmnpqrstvwxyzsness") == 34
    @test vowels_count("cpsyccrypaeiioiaeaeiuocpsyccryptographyhologyuyfacetiousnessioouyuyennscpsyccryptographyhologytograpahyhology") == 40
    @test vowels_count("bcdfgjhabstfecryptogracaAEIOUYXWouygpymiousnessjklmnpqrstvvwxyz") == 16
    @test vowels_count("aeiouyffazcetioubcsnessy") == 12
    @test vowels_count("hhZCavYLHr") == 1
    @test vowels_count("facetoiouabcdffghjkfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnesslcryptogracaaAEIOUYXWoucpsycocryptographyhologyypymnpqrstvwxyzsness") == 49
    @test vowels_count("asfacetioaAAaaAaacrypotographyAaaaaaubcdfghjklmnpqrstvwxyzbcdfghjklmnpabstemiousnessqrstvxyzsnessbstemioussneytiousness") == 39
    @test vowels_count("aoeiouyfaceaeiouyfaceetieousnessss") == 21
    @test vowels_count("psypsycfacetioubcdfghjklmnpqrstvwxyfzsnesshologyfazcetioubcdffghjklmnpqrstvwxyzsness") == 14
    @test vowels_count("AaeioiaeaeiocpsyccryptogaoeiouyfaceaaieieoiouyfacetieousnessssraphyhologyouyfacetiousssioouyuyIOUYXW") == 56
    @test vowels_count("facetioubcdffghjpbcdfghjklgmnpabstemiousnessqrstvwaAEIOUYXWoutyxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 40
    @test vowels_count("aeibcdfghjklmnpabstemiousnessqrsstvwxyzouyfacetiaousness") == 18
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiousneouyaaabcdfghjklmnpqrstvwbcdfghjklgmnpqrstvwxyzz") == 30
    @test vowels_count("aieioABCDEoFGHIJKCLMNOPaAAaaAaaAaaiaeaeiouyfacetiousnessioaeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsnessaaauyfacfacetiousnessetiousnessouyaaabcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstevwxyzologyxyzQRSTUVWXZuy") == 90
    @test vowels_count("aaeiouyfaceftiousnenesouy") == 16
    @test vowels_count("facetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessaeiouyffazcetioubcdffghjklmnpqrstvwxyzsnessacetaAEIOUYXWouyiousnessy") == 51
    @test vowels_count("aaeiouyefaceftiousnaenessieiiouy") == 22
    @test vowels_count("bcdfghjklpcsypsycfacetioubcdfghjklmnpqrstvwxyzsnesshologymnpabstemiousnessqrsstvwxyz") == 14
    @test vowels_count("cpsghjklmnpabstemiousnessqrstvwxyzology") == 9
    @test vowels_count("crcpy") == 1
    @test vowels_count("heBLBaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstvwxyzologyxyz") == 41
    @test vowels_count("facetioubgcdffghjpbcdfghjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessiosness") == 30
    @test vowels_count("ioAEIYXWouy") == 8
    @test vowels_count("AYXsZdlSV") == 1
    @test vowels_count("cpsyccrypaeiioiaeaeiocpsyccryptographyhologyuyfacetioouyuyennstograpahyhology") == 31
    @test vowels_count("aeioaAAaAaaAaaaaauyfacfacetiousnessetiousnessABCDEFGHIJKLrcrypotographyMNOPQRSTUYZ") == 38
    @test vowels_count("aeioaAAdizziaieABCDEFGHIJKLMNOPQRSTUYZinessaAaaAaaaaauyfacetiousness") == 36
    @test vowels_count("aeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsonesaisaaauyfacfacetiousnessetiousness") == 39
    @test vowels_count("bcdfghjklmnpqrsaieioABCDEFGHIJKLMNOPRSTUVWXZuyxyz") == 11
    @test vowels_count("afacetioubcdfghjklmnpuyfacfacetiousnessetiosness") == 18
    @test vowels_count("absaipbcdfghjklgmnpabstemiousnpsypsycfacetiouaieiiouybcdfghjklmdizzinfacetioubcdffghjklmnpqrswxyzsnessessnpqrstvwxyscryptograacpsychologyOAEIOUYXWouycpyhologyessqrzlogyeiiouy") == 52
    @test vowels_count("aOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxaeiouyffazcetioubcsnessyeyuy") == 31
    @test vowels_count("facetifoubcdffghjklfmnpqrustvwxyzsness") == 7
    @test vowels_count("aaeiouyfaceftiofusnenesouy") == 16
    @test vowels_count("sGYls") == 0
    @test vowels_count("bcaAAaaAaaAaaaaadfgjhabstemiousnessjdklmnpqrstvwxyz") == 20
    @test vowels_count("facetoiouabcdffghjkfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessslcryptogracaaAEIOUYXWoucpsycocryptographyhologyypymnpqrstvwxyzsness") == 49
    @test vowels_count("facetiobcdfghjklmnpqrstvyzubcdffghjklmnpqrstvwxyzsness") == 6
    @test vowels_count("cryptbcdfgjhjklmnpqrstvwxyzograacpsychologyOAEIOUYXcpy") == 12
    @test vowels_count("abcdfgbhjklmnpabsteemiousnessfacetioubcdffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeiouyfacetiousnessaAAaaAaaAaaiaeaeiouyfacetiousnessioaeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsnessaaauyfacfacetiousnessetiousnessouyaaabcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstevwxyzologyxyzabcdfghjklmnpqrstvwxyzsqrstvxyzAAaAaaAaaaaaa") == 130
    @test vowels_count("facetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouydffghjpbcdfghfacetioubcdfghjwxyzsnessjklggmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 58
    @test vowels_count("cpsyccrypaeiioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuyennstographyafacetioubcdfghjklmnfacetioubcdfghjwxyzsnesspqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnesaieioABCDEFGHIJKLMNOPQRSTUVWXZuysetfacetioubcdffghjklfmnpqrstvwxyzsnesssiousnesshology") == 93
    @test vowels_count("aOAEIOUYXWouafacetioubcdfghjklmnpqrstvwaxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsnessiAousnessy") == 54
    @test vowels_count("cpology") == 3
    @test vowels_count("psypsycfqacetioubcdfghjklmnpqrstvwxyzsnesshology") == 9
    @test vowels_count("aieioABCDEFologyypyZuy") == 11
    @test vowels_count("dizziaieABCDEFGHIJKLMNOPQRSTUYZinessyaaabcdfghjklmnvwxyz") == 15
    @test vowels_count("facetioubgcdffghjpbcdfghjklgmnpabstemiousnessqrstvwxyzldizziaieABCDEFGHIJKLMNOPQRSTUYZinessyaaabcdfghjklmnvwxyzogykaipbcdfghjklgmnpabstemiousnessqrstvwxyzlogyeiiouyessioouypqrsstvwxyzsness") == 47
    @test vowels_count("aieioABCDEFGHIJKLMNOPQRSTUVWXZpsiaeaeiiobcdfghjcecpsyccrypbtographyhologytioiusnessioouyycuy") == 34
    @test vowels_count("crypytograpaeioiaeaeiocpsyaeiouyffazcetioubcdffghjklmnpqrstvwxyzsnessacetiousnessyccryptogaoeiouyfaceaaieieiouyfacetieousnessssraphyhologyouyfacetiousssioouyuyyy") == 71
    @test vowels_count("cryptograIOUYXWouy") == 8
    @test vowels_count("asbsiousness") == 5
    @test vowels_count("facetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouydffghjpbcdfghfacetioubcdfghjwxyzsnessjklggmcryptogracaAEIOUYXWouypynpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouysness") == 68
    @test vowels_count("cpsycholaaaaaaAapsyafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnesschologyaaaiogy") == 53
    @test vowels_count("aAAaAaaAaafacetiaeibcdfghjklmnpabstemiousnessqrsstvwxyzouyfacetiaousnessoubgcousnessioouypqrstvwxyzsnessa") == 42
    @test vowels_count("AEIYXW") == 3
    @test vowels_count("ciaeaeiouyfacefacetioubcdffghjkfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnesslmnpqrstvwxyzsnessousnessioouy") == 49
    @test vowels_count("asbstemiousnessaeioouyfaceftiousnciaeaeiouyfacetiousnessioouyesais") == 38
    @test vowels_count("iaaAAaAaaAaaaaaeaoeiiouyfacetiiooaeioiabsaeaeiocpsyccryptographyhologyuyfacetiousnessioaAAaaAaafacetioubcdffghjklmnpqrstvwxyzsnessAaaaaaouyuyuy") == 79
    @test vowels_count("aipbcdfghjklgmnpabstemiousnpsypsycfacetioubcdfghjklmdizzinfacetioubcdffghjklmnpqrswxyzsnessessnpqrstvwxyscryptograacpsychologyOAEIOUYdizzifacettioubcdffghstvwxyzsnOAEaAAaaAaaAaaabcdfgjhjklmnpqrstvwxyzyhologyessqrzlogyeiiouy") == 64
    @test vowels_count("psiaeaeiiobcdfghjcetioiusneasbstemiousnessaeiasbstemiousnessaeiouyfaceftiousnessouyfaceaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouyfsnessssioouyyc") == 69
    @test vowels_count("psypsychologyOUYXW") == 4
    @test vowels_count("facetioubcdfaeiouyfacetiousnessyfghjpbcdfghfacetioubcdfghfacetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnessydffghjpbcdfghfcacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 143
    @test vowels_count("iaeaeiiouyfacetiousaAAaaAaaAaaiaaieioABCDEFGHIJKLMNOPQRSTUVWXZuyeaeiouyfacetioioouyaaabcdcryptogracpyaAEIOUYXWouyfghjklmnvwxyzy") == 66
    @test vowels_count("bcdfgbhjkllmnpabstee") == 3
    @test vowels_count("abcdfgbhjklmnpabstciaeaeiouyfacetiousnessioouyeemiousnessfacetioubcdffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeiouyfacetiousnessaAAaaAaaAaaiaeaeiouyfacetiousnessioaeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsnessaaauyfacfacetiousnessetiousnessouyaaabcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstevwxyzologyxyzabcdfghjklmnpqrstvwxyzsqrstvxyzAAaAaaAaaaaaa") == 148
    @test vowels_count("aeioiaeaeiocpsyccryptogaoeiouyfaceaaieieiouyfacetieousnessssraphyaOAyEIOUYXWouycetiousssioouyuy") == 56
    @test vowels_count("aipcbcdfghjklgmnpabstepmiousnenssqrzlogyeiiouy") == 15
    @test vowels_count("aeioiaeaeiocpsyccryptographyhologyoaAAaaAaaAaaiacryptogrWacaAEIOUYXWoucpsyccryptographyhologyypyeaeiouyfaacetiousnessioouyaaabcdfghjklmnvwxyzousssioouyuy") == 71
    @test vowels_count("aoeiouyfaceaeiouyfacetieousnessaeiiociaeaeiocpsyccryptographyhologyuyfacpsypsycfacetioubcdfghjklmdizziyycpyhologyetiousnyennsss") == 52
    @test vowels_count("bcdfgbhjklmnpabstemiousnessqrstvaOAEInOUYXWouyxyz") == 15
    @test vowels_count("aeioiaeabcdfghjklgmnpabstemiousnessqrstvwxyzs") == 14
    @test vowels_count("tcrypttographcy") == 3
    @test vowels_count("aipbcdsfghjklgmnpabstemiaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyzousnessqrzlogyeiiouy") == 47
    @test vowels_count("asbstemiousnesfacetioubcdfaeiouyfacetiousnessyfghjpbcdfghfacetioubcdfghfacetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnessydffghjpbcdfghfcacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 149
    @test vowels_count("aeiiouyfaceftiousneness") == 13
    @test vowels_count("icpsychologyAEIOUYYXWaeaeiiouyfacetaaaaaAapsychologyaaaiousaAAaaAaaAaaiaaieioABCDEFGHIJKLMNOPQRSTUVWXZuyeaeiouyfacetiousnessioouyaaabcdfghjklmnvwxyzy") == 77
    @test vowels_count("cpoloygyaeioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuy") == 30
    @test vowels_count("aeioiaeaeiocpsyccryptographyhcolaogyuyfacetiousnessioouyuyenns") == 29
    @test vowels_count("facetioubcdfaeiouyfacetiousnessyfghjpbcdfghfacetioubcdfghfacetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnessydffghjpbcdfghfcacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfcryptogracpymniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 145
    @test vowels_count("facetioubcdffghjklfmniaeaeiiouyfsacetiousnessioouypqrstvwxyzsness") == 25
    @test vowels_count("facetioubcdffghfacetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouydffghjpbcdfghfacetioubcdfghjwxyzsnessjklggmcrypbcdfgjhabstemiousnessjdklmnpqrstvwxyztogracaAEIOUYXWouypynpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouysnessjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 99
    @test vowels_count("fazAEIYOUYYXWcetiofubcdffghjklmnpqrstvwxyzsness") == 11
    @test vowels_count("bcdfgjhabstemiosusnessjklmnpqrstvvwxyz") == 6
    @test vowels_count("faceatioubcffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyzs") == 39
    @test vowels_count("dizznebcdfghjklmnpabstemiousnesssqrsstvwxyzss") == 8
    @test vowels_count("aOAyEIOUaeiouyfaceftiousnessYXWouy") == 21
    @test vowels_count("cryptbaeiouycdfgjhjklmnpqrstvwxyzogruaacpsychologyOAUEIOUYXWouybcdfgjhjklmnpqrstvwxyzcpy") == 21
    @test vowels_count("rcgrypotographoy") == 5
    @test vowels_count("cryptogracfacetioubcdffghjklfmnpqrstvwxyzsneaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrsbcdfghjklmnpqrsaieioABCDEFGHIJKLMNOPQRSTUVWXZuyxyztvwxyzsspyaeiouyfacetiousnbcdfghjklmnpqrstvyzessy") == 63
    @test vowels_count("aipbcdfghjklgmnpabstgepmiousnessqrzlogyeiiouy") == 15
    @test vowels_count("OOAEIOaeiouyfaceftiousneneussUYXW") == 20
    @test vowels_count("aoeiouyfaceaeifacetioubcdffghjklmnpqrstvwxyzsnessouyfacetieousnessss") == 26
    @test vowels_count("craeioiaeaeiocpsyfaceatioubcffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyzsccryptogaoeiouyfaceaaieieoiouyfacetieousnessssraphyhologyouyfacetiousssioouyuyyptograacpsychologyOAEIOUYXWouycpy") == 105
    @test vowels_count("aeioiaeaeiocpsyccryptogaoeiouyfaceaaieaieiouyfacetieousnessssraphyaOAyEIOUYXWouycetiousssioouyuy") == 57
    @test vowels_count("aipbcdfghjklgmnpabstepmiousnessqrzlofacettioubcdffghstvwxyzsnOAEaAAaaAaaAaaaaaUYXWessgyeiiouy") == 39
    @test vowels_count("psiaeaeiiobcdfghjcetioiusneasbstemiousnessaeiasbstemiousnessaeivouyfaceftiousnessouyfaceaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouyfsnessssioouyyc") == 69
    @test vowels_count("asybstemioussnessaeiouyfaceftiousness") == 17
    @test vowels_count("afacetneousnesss") == 7
    @test vowels_count("asbstemiousnessaeioouyfaceftiousnesiaeaeiiouyfacetiousaAAaaAaaAaaiaaieioABCDEFGHIJKLMNOPQRSTUVWXZuyeaeiouyfacetioioouyaaabcdcryptogracpyaAEIOUYXWouyfghjklmnvwxyzyis") == 84
    @test vowels_count("heBLBaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaaibcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstvwxyzologyxyz") == 42
    @test vowels_count("iaeaeiouyfaceftiousnesasbstemiousnuessaeiouyfacetiousnessioAEIYXWouy") == 40
    @test vowels_count("aipbcdfghjklgmnpabstemciousnessqrzlogyeiiouy") == 15
    @test vowels_count("psypsycholoogy") == 4
    @test vowels_count("cryptogracpOyaAEIOUYXWouy") == 12
    @test vowels_count("aeiiociaeaeiocpsyccusnyenns") == 14
    @test vowels_count("facetioubcdfaeiouyfacetiousnessyfghjpbcdfghfacetidoubcdfghfacetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnessydffghjpbcdfghfcacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfcryptogracpymniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 145
    @test vowels_count("facetioubcdffbcdmfghjklmnpabstemiousnessqrstvxyzghjkflmnpqrstvwxyzsness") == 12
    @test vowels_count("aeioiaeaeiocpsyccryptographyholaogyuyfacetiousnessioouyuyennns") == 29
    @test vowels_count("heBLBaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaaibcdfghjklmnpqrstvwcpsbcdfghjklmnpabstogyxyz") == 36
    @test vowels_count("fghjklmnpabstemiousnessqrstvxyz") == 6
    @test vowels_count("facetioubcdfaeiouyfacetiousnessyfghjpbcdfghfacetidoubcdfghfacetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnessydffghjpbcdfghfcacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfcryptogracpymniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessf") == 145
    @test vowels_count("cryptogaoeiouyfaceaeifacetioubcdffghjklmnpqrstvwxyzsnessouyfacetieousnessss") == 27
    @test vowels_count("aAAaaAaaAaayniaeaeiouyfacetiousnessioouyaaa") == 32
    @test vowels_count("facetioubcdfaeiouyfacetiousnessyfghjpbcdfghfacetioubcdfghfacetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnessydffghjpbcdfghfcacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrsttvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfcryptogracpymniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 145
    @test vowels_count("aipcbcdfghjklgaieiouyenssqrzlogyeiiouy") == 16
    @test vowels_count("aieiaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouyouy") == 27
    @test vowels_count("abss") == 1
    @test vowels_count("cryptbaeiouycdfgjhjklmnpqrstvwxyzogruaacypsychologyOAUEIOUYXWouybcdfgjhjklmnpqrstvwxyzcpy") == 21
    @test vowels_count("cpsyccrypaeiioiaeaeiuocpsyccryptographyholorgyuyfacetiousnessioouyuyennscpsyccryptographyhologytograpahyhology") == 40
    @test vowels_count("aeiocryptographcycinousness") == 10
    @test vowels_count("aeiouyfacetioucsness") == 11
    @test vowels_count("aeiocryAEWptographcyyuaAEIOUYXWouyess") == 18
    @test vowels_count("aeioaAAaAaaAaafacetioubcdffghjklmaOaeiouyfacetiousnessAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxaeiouyffazcetioubcsnessyeyuynpqrswxyzsnessaaauyfacfacetiousnessetiousness") == 77
    @test vowels_count("aAAaaAaafacetioufbcdffghjklmnpqrstvwxyzsnessAaaaaa") == 20
    @test vowels_count("facetioubcdffbcdmfghjklmnpabstemiousnessqrstvxyzghjkflmnpqrstvwxytcrypttographcyzsness") == 14
    @test vowels_count("facetioubcdffghjklmnpqrstvwxyzsnessAaaaaa") == 12
    @test vowels_count("fss") == 0
    @test vowels_count("fazcrypstogcetioubcdffghjklmnpqrstvwxyzsness") == 7
    @test vowels_count("aeiiouyfaceftiousnneness") == 13
    @test vowels_count("asbstemiousnessaeioouyfaceftiousnesiaeabcdfgbhjklmnpabstemiousnessqrstvxyzyfghjklmnvwxyzyis") == 29
    @test vowels_count("bcdfghaeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsnessaaauyfacfacetiousnessetiousnesspsycjklmnpqrstvyz") == 36
    @test vowels_count("bcdfgjhabstemiousnesvsjdklmnpqrstvwxyz") == 6
    @test vowels_count("aipbcdsfghjklgmnpabstemiaAAaaAaaAaaiaeaeiouyfacetiousnessiiouy") == 35
    @test vowels_count("yyyy") == 1
    @test vowels_count("aAAaaAaaAaaiaieioABCDEFologyypyZuyaeaeiouyfacetiousnessioouyaaa") == 42
    @test vowels_count("aAAaAaaAaafacetiaeibcdfghjklmnpabfacetoiouabcdffghjkfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnesslcrypnessa") == 51
    @test vowels_count("aieiaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwuxyzsnnessWouyouy") == 28
    @test vowels_count("gAaeiouyffazcetioubcdffghjklmnpqrstvwxyzsnessaceaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyztaAEIOUYXWouyiousnessy") == 59
    @test vowels_count("nxPZx") == 0
    @test vowels_count("psypsychologyfacetioubcdffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyzs") == 40
    @test vowels_count("psypsycfacetioubcdfghjklmdizzinhology") == 10
    @test vowels_count("aAAaaAaacrypotographyAAaaaaa") == 18
    @test vowels_count("afacetinefssetiousness") == 10
    @test vowels_count("aeioiaeaeiocpsyccroyptographyhologyuyfacetiousnessioouyuy") == 29
    @test vowels_count("psypsycfacetioubcdfghjklmdbizzinhology") == 10
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiaaousnessiooaoeiouyfaceaeifacetioubcdffghjklmnpqrstvwxyzsnessouyfacetieousnessssuyaaa") == 60
    @test vowels_count("aeiouyfaceatiousneses") == 13
    @test vowels_count("hOUYXfacetioubcdfghjklmnpqrstvwxyzsnessWhZCavYLHr") == 9
    @test vowels_count("facetioubcdffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaatabcdfghjklmnpqrstvwxyzs") == 38
    @test vowels_count("psypsycfsacetioubcdfghjklmnpqrstvwxyzssnesshology") == 9
    @test vowels_count("afacetioubcasfacetioaAAaaAaacrypotographyAaaaaaubcdfghjklmnpqrstvwxyzbcdfghjklmnpabstemiousnessqrstvxyzsnessbstemioussnessaeiouyfaceftiousnessdfghjklmnpqrstvwaxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsnessiAousness") == 90
    @test vowels_count("bcdfgjhabstemaeioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuynessjklmcnpqrstvwxyz") == 30
    @test vowels_count("bcdfgjhabstfecryptogracaAmEIOUYXWouypymiousnessjklmnpqrstvvwxyz") == 16
    @test vowels_count("facetoiouabcdffghjkfacetaaeiouyfaceftiousnenesouyioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessslcryptogracaaAEIOUYXWoucpsycocryptographyhologyypymnpqrstvwxyzsness") == 64
    @test vowels_count("afacetioubcdfghjklmnfacetioubcdfghjwxyzsnesspqrstvwxyiaeaoeiiouyfacetiousnessioouyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsnesssiousness") == 68
    @test vowels_count("biaeaeiiouyfacetiousaAAaaAaaAaaiaaieioABCDEFGHIJKLMNOPQRSTUVWXZuyeaeiouyfacetiousnessioouyaaabcdfghjklmnvwxyzycdfghjklmnpqrstvwxyz") == 57
    @test vowels_count("aeiocryptographcyuyfacs") == 8
    @test vowels_count("aeioiaeaeiocpsyccryptographyhcolaogyuyfacetiopsypsychologyfacetioubcdffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrstvwxyzsusnessioouyuyenns") == 69
    @test vowels_count("facetoiouabcdffghjkfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessslcryptogracaaAEIOUYXWoucpsycocryptographoyhologyypymnpqrstvwxyzsness") == 50
    @test vowels_count("aeiiociaeaeiocpsyccusniyenns") == 15
    @test vowels_count("cryptbaeiouycdfgjhjklmnpqrstvwxyzogbcdfghjklmnpabstemiousnessqrstvwxyzruaacpsychologyOAUEIOUYXWouybcdfgjhjklmnpqrstvwxyzcpy") == 27
    @test vowels_count("dizziaieABCDEFGHIJKLMNOPQRSTUYZinessyaaabaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnessWouycdfghjklmnvwxyz") == 35
    @test vowels_count("aeioiaeaeiouyfacetiousniessioouyuy") == 25
    @test vowels_count("aeioiaeaeiouyfacetiousniuessioouyuy") == 26
    @test vowels_count("tcrycryptogracpyaphcy") == 4
    @test vowels_count("aeiouyffazcetioubcdcpsyccrypaeiioiaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuyennstographyhologyffghjklmnpqrstvwxyzsnessacetaAEIOAEIYXWUYXWouyiousnessy") == 62
    @test vowels_count("craeioiaeaeiocpsyfaceatioubcffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeioiouyfaceaaieieoiouyfacetieousnessssraphyhologyouyfacetiousssioouyuyyptograacpsychologyOAEIOUYXWouycpy") == 87
    @test vowels_count("cpy") == 1
    @test vowels_count("facetioubcdffghjpbcdfghaeiiociaeaeiocpsyccryptographyhologyuyfacetiousnessioouyuyennsjklgmnpabstemiousneaeiouyfaceftiousnnesasbstemiousnessYXWouyxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 80
    @test vowels_count("abbss") == 1
    @test vowels_count("bcdfghjklmnpqrsaieioABCDEFGHaieioABCDEFGHIJKLMNOPQRiaeaeiiouyfacetiousnessioouySTUVWXZuyIJKLMNOPQRSTUVWXZuyxyz") == 41
    @test vowels_count("aipcbcdfghjklgmnpabstepmihousnessqrzlogyeiiouy") == 15
    @test vowels_count("aOAEIOUYXWouafacetioubcdfghjklmnpqrstvwaxyzsnesseioaAAaApsypsycfacetioubcdfghjklmdizzinessnpqrstvwxyscryptograacpsychologyOAEIOUYfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessXWouycpyhologyaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsnessiAousnessy") == 102
    @test vowels_count("psypsychologyfacetioubcdffghjklmnpqrswxyzsnesaAAaaAaaAaaabcdwfghjklmnpqrstvwxyzs") == 20
    @test vowels_count("heBLBaAAaaAaaAaaiaeaeiouyfacetioafacetinefssetiousnessusnessioouyaaaibcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstvwxyzologyxyz") == 52
    @test vowels_count("afactetinessetiousnness") == 10
    @test vowels_count("abstemiouaaeiouyfaceftiofusnenesouysnss") == 20
    @test vowels_count("facetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrsdizzinessafacetinessetiousnesstvwxyzsiaeaeiouyfacetiousnessioouyness") == 56
    @test vowels_count("psypsycfacetioubcdfghjklmdizzinfacetiAEIYXWoubcdffghjklmnpqrswxyzsnessessnpqrstvwxyscryptografacetioubcdffbcdmfghjklmnpabstaeioiaeaeiouyfacetiousnesasbstemiousnesssioouyuyacpsychologyOAEIOUYXWouycpyhoslogy") == 68
    @test vowels_count("facetioubcdffghjkfacetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnesslmnpqrstvwxycryptographyzsness") == 33
    @test vowels_count("ABCDEFGHIJKLrcrypotographyMNOZ") == 7
    @test vowels_count("bcdfpsypsycfacetioubcdfghjklmnpqqrstvwxyzsnesshologygjhabstfecryptogracaAmEIOUYXWouypymiousnessjklmnpqrstvvwxyz") == 24
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfetiousnessioouyaaabcdfghjklmnpqrstvwxyz") == 31
    @test vowels_count("aieiaOAEIOUYXfaUYXWmnpqrstvwxyzsnnessWouyouy") == 19
    @test vowels_count("afacetioubcdfghjklmnpuyfacfacetiousnesseticrypotographyousness") == 22
    @test vowels_count("bcdfgjhabstfecryptogracaAEIOUYXWouypymiousnessjklcryptogracfacetioubcdffghjklfmnpqrstvwxyzsneaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnpqrsbcdfghjklmnpqrsaieioABCDEFGHIJKLMNOPQRSTUVWXZuyxyztvwxyzsspyaeiouyfacetiousnbcdfghjklmnpqrstvyzessymnpqrstvvwxyz") == 78
    @test vowels_count("asbstemiousnessaeioouyfis") == 13
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiousnessioaeioaAAaAaaAaafacetioubcdffghjklmnpqsrswxyzsnessaaauyfacfacetiousnessetiousnessouyaaabcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstevwxyzologyxy") == 78
    @test vowels_count("psypsycfacetioubcdfghjklmnpqrstvwxyxfzsnesshologyfazcetioubcdffghjklmnpqrstvwxyzsness") == 14
    @test vowels_count("facetifoubcudffghjklfmnpqqrustvwxyzsness") == 8
    @test vowels_count("craaeiouyfaceftiofusnenesouyypotography") == 19
    @test vowels_count("iaeaeiiouyfacetiousaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaabcdfghjklmnvwxyazy") == 48
    @test vowels_count("aeioiaeaeyccryptogaoeiouyfaceaaieieiouyfacetieousnessssraphyaOAyEIOUYXWouycetiousssioouyuy") == 54
    @test vowels_count("cpsyccrypcpsaAEIcryptograpyOUYXWouyychologyennscpsyccryptographyhologytograpahyhology") == 23
    @test vowels_count("cryptogracaAEIOUYXWoucpsyccryptographyhologyaeiiociaeaeiocpsyccusniyennsypy") == 30
    @test vowels_count("hOUYXfacetioubcdfghjklmnpqravYLHr") == 8
    @test vowels_count("afactetinessetious") == 9
    @test vowels_count("heBLBaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaaibcdfghjklmnpqrstvwcpsbcdfghjklmnpabscryptogracpOyaAEIOUYXWouytogyxyz") == 47
    @test vowels_count("crasbstemiousnessaeiasbstemiousnessaeiouyfaceftiousnessouyfaceaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouyfsnesstographyhologyypy") == 56
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiousnessioaeioaAAaAaaAaafacetioubcdffghjklmnpqsrswxyzsnessaaauyfacfacetiousnessetiousnessouyaaabcdfghjklmnpqrstvwcpsbcdfghjklmnpvwxyzologyxy") == 71
    @test vowels_count("iaeaeiiouyfacetiousaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaAAaaAaaAaaiaeaeiouyfetiousnessioouyaaabcdfghjklmnpqrstvwxyzaabcdfghjklmnvwxyzy") == 78
    @test vowels_count("facetioubcdffghjaAAaaAaafacetioufbcdffghjklmnpqrstvwxyzsnessAaaaaaklmnpqraAAaaAaaAaaiaeaeiouyfacetiousnessioouss") == 54
    @test vowels_count("heBLBaAAaaAaaAaaiaeaeiouyfacetidfacetioubcdfghjklmnpqrstvwxyzsnessfghjklmnpabstogyxyz") == 31
    @test vowels_count("rcgrypotograpaOAEIOUYXfazcetioubcdffghjklAEIaeiocryptographcyuyfacetiousnessOUYXWmnpqrstvwxyzsnessWouyhoabssy") == 39
    @test vowels_count("aAAaaAaafacetioufbcpsypsycfacetioubcdfghjklmdizziycpyhologydffghjklmnpqrstvwxyzsnessAaaaaa") == 29
    @test vowels_count("facetioubcdffghjxyzsnessAaaaaaklmnpqraAAaaAaaAaaiaeaeiouyfacetiousnessioouss") == 41
    @test vowels_count("fazcryptogcetioubcdffghjklmnpqrstvwxyaeiouyffazcetioubcdffghjklmnpqrstvwxyzsnessacetiousnessyzsness") == 24
    @test vowels_count("aOAEIOUYXWouafacetioubcdfghjklmnpqrstvwaxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetfacetioubcdffghjklfmnpqrstvwxyzsneasfacetioaAAaaAaacrypotographyAaaaaaubcdfghjklmnpqrstvwxyzbcdfghjklmnpabstemiousnessqrstvxyzsnessbstemioussneytiousnessssiAousnessy") == 93
    @test vowels_count("abcdfgbhjklmnpabsteemiousnessfacetioubcdffghjklmnpqrswxyzsnesaAAaaAaaAaaiaeaeiouyfacetiousnessaAAaaAaaaeiouyfaceftiousneneussAaaiaeaeiouyfacetiousnessioaeioaAAaAaaAaafacetioubcdffghjklmnpqrswxyzsnessaaauyfacfacetiousnessetiousniaeaeiiouyfacetiousnessioouyessouyaaabcdfghjklmnpqrstvwcpsbcdfghjklmnpabstemiousnessqrstevwxyzologyxyzabcdfghjklmnpqrstvwxyzsqrstvxyzAAaAaaAaaaaaa") == 162
    @test vowels_count("heBLBaAAaaAaaAaaiaeaeiouyfacetiousnessioouyaaaibcdfghjklmnpqrstvwcpsbcdfgbcaAAaaAaaAaaaaadfgjhabstemiousnessjdklmnpqrstvwxyzhjklmnpabstogyxyz") == 56
    @test vowels_count("aeioaAAaAaaAaaaaauyfacfacetiousnessetyiousness") == 30
    @test vowels_count("aAEuIOUYXWouy") == 10
    @test vowels_count("facetioubcdfaeiouyfacetiousnessyfghjpbcdfghfacetioubcdfghfacetioubcaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqrstvwxyzsnnessWouafacetioubcdfghjklmnpqrstvwxyzsnesseioaAAaAaaAaaaaauyfacfacetiousnessetiousnessydffghjpbcdfghfcacetioubcdfghjwxyzsnessjklgmnpabstemiousnessqrsttvwxyzlozgyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfcryptogracpymniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 145
    @test vowels_count("aoeiouyfacouyfacetieousnessaeiiociaeaeiocpsyccryptographyhologyuyfacpsypsycfacetioubcdfghjklmdizziyycpyhologyetiousnyennsss") == 48
    @test vowels_count("bcdfghjklmnpaieiieouyabstemioussnesssqrsstvwxyz") == 14
    @test vowels_count("aeipbcdfghjklgmnpabstaeiocryptographcyuyfacetiousnessemiousnessqrzlogyeiiouy") == 29
    @test vowels_count("fazcryptogcaoeiouyfacouyfacetieousnessaeiiociaeaeiocpsyccryptographyhologyuyfacpsypsycfacetioubcdfghjklmdizziyycpyhologyetiousnyennsssetioubcdffghjklmnpqrstvwxyzsnesscpology") == 58
    @test vowels_count("facetioubcdffghjpbcdfghfacetioubcdbcdfghjklmnpabsteusnessqrstyyvxyzfghjwxyzsnessjklgmnpabstemiousnessqrstvwxyzlogyklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsness") == 42
    @test vowels_count("facetioubcdffghjklfmniaeaeiiouyfacetiousnessioouypqrstvwxyzsnessaeiouyffazcetioubcdffghjklmnpqrstvwxyzsnessacetauAEIOUYXWouyiousnessy") == 52
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetibcdfgbhjklmnpabstemiousneABCDEFGHIJKLMNdOPQRSTUVWXZsisqrstvxyzaousnessioouyaaa") == 45
    @test vowels_count("aieiaOAEIOUYXfazcetioubcdffghjklAEIOUYXWmnpqaeiocryptographcyyuyfacetpsycinousnessrstvwxyzsnnessWouyouy") == 40
    @test vowels_count("aAAaaAaaAaaiaeaeiouyfacetiousneiaeaoeiiouyfacetiousnessioouyfghjklmnpqrstvwxyz") == 45
    @test vowels_count("bcdfgjhabaeioiaeaeiocpsyccryptographyhologyuyfacetiousnessiaoouyuyennsstemiousnessjklmnpqrstvwxyz") == 35
    @test vowels_count("Y") == 1
    @test vowels_count("Yy") == 1
    @test vowels_count("bb") == 0
    @test vowels_count("BCDFGHJKLMPQRSTVWXZ") == 0
    @test vowels_count("aeiou") == 5
    @test vowels_count("AEIOU") == 5
    @test vowels_count("AEIOUY") == 6
    @test vowels_count("Yaeiou") == 5
    @test vowels_count("AEIOUy") == 6
    @test vowels_count("tbcdfghjklmnpqrstvwxyz") == 0
    @test vowels_count("absetemiousneaeiouyss") == 12
    @test vowels_count("aeioaeiouyuy") == 11
    @test vowels_count("aedizzinessiouy") == 9
    @test vowels_count("cryptaedizzinessiouyography") == 11
    @test vowels_count("cryptaedizzinessiouyoegraphy") == 12
    @test vowels_count("asiouyAaaaaa") == 10
    @test vowels_count("aeio") == 4
    @test vowels_count("crypteaedizzinessiouyoegraphy") == 13
    @test vowels_count("aedizzinessiou") == 8
    @test vowels_count("cryptopgraphy") == 3
    @test vowels_count("AEIOUYaeioaeiouyuyXW") == 15
    @test vowels_count("absstemiousness") == 6
    @test vowels_count("faasiouyAaaaaacetiousness") == 16
    @test vowels_count("AEIOUYX") == 5
    @test vowels_count("tbcdfghjklmnpaeiotvwxyz") == 4
    @test vowels_count("abstem") == 2
    @test vowels_count("caeiouyryptopgraphy") == 8
    @test vowels_count("cryptofacetiousnesspgraphy") == 9
    @test vowels_count("absstemioussness") == 6
    @test vowels_count("cryptofacetieousnesspgraphy") == 10
    @test vowels_count("aeioaeiocryiptofacetiousnesspgyuy") == 18
    @test vowels_count("bckdfghjklmnpqrstvwxyz") == 0
    @test vowels_count("aeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyoegraphy") == 30
    @test vowels_count("EEcryptofacetiousnesspgraphyTfnuhVC") == 11
    @test vowels_count("UCuMNjTHX") == 2
    @test vowels_count("cryptographty") == 3
    @test vowels_count("yptograp") == 2
    @test vowels_count("cryptoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphy") == 27
    @test vowels_count("ABCDEIFGHIJKLSGTUVWXYZ") == 5
    @test vowels_count("ybcdfghjklmnpqrstvwxyztograp") == 2
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnpqrstvwxyz") == 13
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnvpqrstvwxyz") == 13
    @test vowels_count("caeiouyryptopgriaphy") == 9
    @test vowels_count("yptograAEIOUYaeioaeiouyuyXWp") == 17
    @test vowels_count("aAAaAaaAaaaaatlbcdfghjklmnpqrstvwxyz") == 13
    @test vowels_count("bcdfghjklmnpqrdizzinessstvwx") == 3
    @test vowels_count("aAAcryptoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaa") == 39
    @test vowels_count("aeiiy") == 5
    @test vowels_count("aedizzinesaAAaAaaAaaaaa") == 18
    @test vowels_count("absbtem") == 2
    @test vowels_count("AEIOUYfaasiouyAaaaXaacetiousnessXW") == 21
    @test vowels_count("dizzizness") == 3
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaa") == 47
    @test vowels_count("UCuMNjTCHX") == 2
    @test vowels_count("psychol") == 1
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvwxyz") == 3
    @test vowels_count("bvwxaedizzinessiouyyz") == 8
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvwxyzcryptofacetieousnesspgraphy") == 13
    @test vowels_count("abstaeiiyem") == 6
    @test vowels_count("bAGAJ") == 2
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaaa") == 32
    @test vowels_count("ypgtograp") == 2
    @test vowels_count("cryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphy") == 59
    @test vowels_count("aedizzinesaAAaAaaApsycholaaaaa") == 19
    @test vowels_count("aycrypteaedizzinessiouyoegraphy") == 14
    @test vowels_count("abstaieiiyem") == 7
    @test vowels_count("bcdfghjklmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyoegraphypqrstvwxyz") == 29
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryiptofaceaaAaaaaa") == 38
    @test vowels_count("tbcdfghjklaeiiymnpqrstvwxyz") == 4
    @test vowels_count("absaedizzinessioubtem") == 10
    @test vowels_count("aoeioaeiouyeuy") == 13
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryptofacetiousnesspgraphyceaaAaaaaa") == 43
    @test vowels_count("aAAcryptoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphynaAaaAaaaaa") == 39
    @test vowels_count("dizziznesns") == 3
    @test vowels_count("cryptografacetiousnessphty") == 9
    @test vowels_count("tbcdfghjklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwxyz") == 17
    @test vowels_count("aeioaeiocrpyiptofacetiousnesspgyuy") == 18
    @test vowels_count("AAEYXW") == 3
    @test vowels_count("aAAaAaaAaaaaatbabstemvpqrstvwxyz") == 15
    @test vowels_count("AaAAaAaaAaaaaatlbcdfghjklmnpqrstvwxyzEIOUyaeioaeiocrpyiptofacetiousnesspgyuyYaeioaeiouyuyXW") == 45
    @test vowels_count("aedizzineAsaAAaAaaAaaaaa") == 19
    @test vowels_count("aAAaAaaAaaaaatbtcdfghjklmnpqrstvwxyz") == 13
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvwxyzcrypaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryiptofaceaaAaaaaatofacetieousnesspgraphy") == 51
    @test vowels_count("bcdfghjklmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyz") == 26
    @test vowels_count("abssteminoussness") == 6
    @test vowels_count("ographty") == 3
    @test vowels_count("UCuMNujTHX") == 3
    @test vowels_count("aw") == 1
    @test vowels_count("aeicrypteaedizzinessiouyoegraphyoaeiouyuy") == 23
    @test vowels_count("absAAEYXWtemiousness") == 9
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvxwxyz") == 3
    @test vowels_count("tbcdfghdizzitnessjmnpqrstvwxyz") == 3
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnpqrstvwxybcdfghjklmnpqrstvwxyztograpyz") == 15
    @test vowels_count("aoeio") == 5
    @test vowels_count("aedizzinessioeuy") == 10
    @test vowels_count("AEIOUYfaasiouyAaaaXaacetiousnessXoW") == 22
    @test vowels_count("absaedizzicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphynessioubtem") == 68
    @test vowels_count("oKyvC") == 1
    @test vowels_count("aeiifacetiousnessy") == 11
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaa") == 44
    @test vowels_count("UCuoaoeioaeiouyeuyMNujTHX") == 16
    @test vowels_count("caedizzinessiouyryptaedizzinessiouyography") == 19
    @test vowels_count("aedizzinesaAAaAaaApsycholaaacryptografacetiousnessphtyaa") == 27
    @test vowels_count("cryptoaphty") == 3
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiypgtograpoaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaa") == 49
    @test vowels_count("fnacetiousness") == 6
    @test vowels_count("AaAAaAaaWAaaaaatlbcdfghjklmnpqrstvwxyzEIOUyaeioaeiocrpyiptofacetiousnesspgyuyYaeioaeiouyuyXW") == 45
    @test vowels_count("tbcdfghjklmnvwxyz") == 0
    @test vowels_count("bcdfghjklmnpqrstvwxaAAaAaaAaaaaatbabstemvpqrstvwxyzyz") == 15
    @test vowels_count("UCuMNjaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaaa") == 34
    @test vowels_count("ooio") == 4
    @test vowels_count("iaeiiy") == 6
    @test vowels_count("crypteaedizzinessiouyoegraphaedizzinessiouy") == 21
    @test vowels_count("tbcdfghjklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwtxyz") == 17
    @test vowels_count("bcdfghjsklmnpqrdizzinessstvwx") == 3
    @test vowels_count("UCuoaaedizzinessiouoeioaeiouyeuyMNujTHX") == 24
    @test vowels_count("UCuMNjaAAcrypcaeiabstaeiiyemeioaeiocryiptofaceaaAaaaaa") == 33
    @test vowels_count("AaAAaAaaAaaaaatlbcdfghjklmnpqrstvwxyzEIOUyaeioaeiocrpyiptofacetiousnesspgyuyYaetbcdfghdizzinessioaeiouyuyXW") == 48
    @test vowels_count("UCuMNujTX") == 3
    @test vowels_count("caeiouyryptoaedizzinesaAAaAaaAaaaaapgraphy") == 26
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaaaa") == 88
    @test vowels_count("aAAcrypcaeioeiabstemiousnessopaeiocryiptofaceaaAaaaaa") == 32
    @test vowels_count("aAAcrypcaeiabsstemiousnessouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaaa") == 38
    @test vowels_count("aAAcaaAaaaaa") == 11
    @test vowels_count("tbcdfghjlmnpaeiotvwxyz") == 4
    @test vowels_count("aoeiocaedizzinessiouyryptaedizzinessiouyography") == 24
    @test vowels_count("bcdfghjklcryptopgraphymnaeioaeiocryiptohfacetiousnesspgyuycrypteaedizzinessiouyz") == 28
    @test vowels_count("bcdfghjklcryptopgraphymnaeioaeiocryiptohfacetiousnesspgypuycrypteaedizzinessiouyz") == 28
    @test vowels_count("tbcdfgdhjklmnpqrstvwxyz") == 0
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofaceaaAbckdfghjklmnpqrstvwxyzaaaaa") == 32
    @test vowels_count("tbcdfghjklmnpyptograAEIOUYaeioaeiouyurstvwtxyz") == 17
    @test vowels_count("UCuMNujX") == 3
    @test vowels_count("abstaeiiyebcdfghjklmnpqrstvwxaAAaAbcdfghjklcryptopgraphymnaeioaeiocryiptohfacetiousnesspgyuycrypteaedizzinessiouyzaaAaaaaatbabstemvpqrstvwxyzyzm") == 49
    @test vowels_count("AMQRI") == 2
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgrapshyceaaAaaaaa") == 44
    @test vowels_count("bcdfghjklcryptopgraphymnaeabsAAEYXWtemiousnessioaeiocryiptohfacetiousnesspgyuycrypteaedizzinessiouyz") == 37
    @test vowels_count("phsogy") == 2
    @test vowels_count("UCuMphsogyNjTHX") == 3
    @test vowels_count("didzziness") == 3
    @test vowels_count("cryptaedizzaAAcrypbcdfghjklmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyzcaeiouyryptopgriaphytoaeioaeiocryiptofahyaAaaAaaaaainessiouyoegraphy") == 71
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvwxyzcrypaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryiptofaceaaAaabsaedizzicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphynessioubtemaaaatofacetieousnesspgraphy") == 119
    @test vowels_count("fnacetiousnaedizzinesaAAaAaaApsycholaaaaaess") == 25
    @test vowels_count("abcdfghjklmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyzeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyoegraphy") == 56
    @test vowels_count("aoeiocaedizzinessiouyryptaedizaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaaaazinessiouyography") == 112
    @test vowels_count("diztbcdfghjklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwtxyzzdizness") == 20
    @test vowels_count("aAAaAaaAAaaaaa") == 14
    @test vowels_count("aeiao") == 5
    @test vowels_count("aedicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphyzzinessioeuy") == 68
    @test vowels_count("abssaeioaeiouyuytemiousness") == 16
    @test vowels_count("aeioaeiocryiyptofacetiousnesspgyuycrypteaedizzinessiouyoegraphy") == 30
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeioaeriocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaa") == 47
    @test vowels_count("aedicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspegraphyzzinessioeuy") == 43
    @test vowels_count("tbcdfghdizzpinessjklmnpqrstvwxyzcrypaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryiptofaceaaAaabsaedizzicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphynessioubtemaaaatofacetieousnesspgraphy") == 119
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvwxyzcrypaAAcrypcaeiouyaedizzinessiouryptopgriaphytoaeiabstemiousnessopaeiocryiptofaceaaAaaaaatofacetieousnesspgraphy") == 59
    @test vowels_count("abssteminoAAEYXWussness") == 9
    @test vowels_count("crytptoapcryptaedizzinessiouyographyhty") == 13
    @test vowels_count("bcdfghjklmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessioeuyz") == 27
    @test vowels_count("aAAcrypcaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaaaiaeiiyeioeiabstemiousnessopaeiocryiptofaceaaAaaaaa") == 84
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnvpqrsybcdfghjklmnpqrstvwxyztograpxyz") == 15
    @test vowels_count("s") == 0
    @test vowels_count("AaedizzinesaAAaAaaAaaaaaI") == 20
    @test vowels_count("AEIOUYaeioaeiouyaAAcrypcaeioeiabstemioousnessopaeiocryiptofaceaaAaaaaauyXW") == 48
    @test vowels_count("abssteminoAAuEYXWussness") == 10
    @test vowels_count("AaAAaAaaWAaaaaatlbcdfghjklmnpqrstvwxyzEIOUyaeioaeiocrpyiptofacetiousnoaeiouyuyXW") == 40
    @test vowels_count("absaedizzicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphynessioubtemaaaatbcdfghjklmnpqrstvwxyz") == 72
    @test vowels_count("aAAaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaaaaAaaAaaaaa") == 45
    @test vowels_count("UCuMNjaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofaceaaAaaa") == 32
    @test vowels_count("aAAaAAcrypcaecaeiouyryptopgraphyiouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaaaaAaaAaaaaa") == 52
    @test vowels_count("abstaeiiyebcdfghjklmnpqrstvwxaAAaAbcdfghjklcryptopgraphymnaeioaecaeiouyryptopgriaphyiocryiptohfacetiousnesspgyuycrypteaedizzinessiouyzaaAaaaaatbabstemvpqrstvwxyzyzm") == 57
    @test vowels_count("psycholcaeiouyryptoaedizzinesaAAaAaaAaaaaapgraphyogy") == 28
    @test vowels_count("oKyvcrypteaedizzinessiouyoegraphyC") == 13
    @test vowels_count("aAAaAAcrypcaecaeiouyryptopgraphyiouyryptopgriaphytoaeioaeiocryiptofaceaAEIOUYXaAaaaaaaAaaAaaaaa") == 57
    @test vowels_count("") == 0
    @test vowels_count("absaedizzicryptaedUCuMNujTHXegraphynessioubtemaaaatbcdfghjklmnpqrstvwxyz") == 21
    @test vowels_count("aAAaAaaAaaaaatlbcdfghjklmnpqrstvwxfyz") == 13
    @test vowels_count("abstaeiiypsycholcaeiouyryptoaedizzinesaAAaAaaAaaaaapgraphyogyem") == 33
    @test vowels_count("tbcdfghjklmnpyptograAEIOUYaeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuyXWpqrsyz") == 36
    @test vowels_count("aAAatbcdfghjklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwxyzAaaAaaaaatbcdfghjklmnpqrstvwxyz") == 30
    @test vowels_count("tbcdfghjklmnpyptograAEIOUYaeioaeiouyurstvwtxydz") == 17
    @test vowels_count("aeioaeiocryiyptofacetiousnesspgyuycrypteabstaeiiyebcdfghjklmnpqrstvwxaAAaAbcdfghjklcryptopgraphymnaeioaecaeiouyryptopgriaphyiocryiptohfacetiousnesspgyuycrypteaedizzinessiouyzaaAaaaaatbabstemvpqrstvwxyzyzmaedizzinessiouyoegraphy") == 87
    @test vowels_count("caeiouyryptoaedizzinesaAAaAaabstemiousnessaAaaaaapgraphy") == 32
    @test vowels_count("AEIOUYaeioaeiouyiuyXW") == 16
    @test vowels_count("yptograAEIOUYaeioaeiotbcdfghjlmnpaeiotvwxyzyXWp") == 19
    @test vowels_count("AaAAaAaaAaaaaatlbcdfghjklmnpqrstvwaxyzEIOUyaeioaeiocrpyiptofacetiousnesspgyuyYaeioaeiouyuyXW") == 46
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvwxwxyz") == 3
    @test vowels_count("sss") == 0
    @test vowels_count("caeiouyryptoaedizzinesaAAaAaabstcryptofacetieousnesspgraphyemiousnessaAaaaaapgraphy") == 41
    @test vowels_count("iaaeiiy") == 7
    @test vowels_count("UCuoaaedizzinessiouoeiooaeiouyeuyMNujTHX") == 25
    @test vowels_count("tbcdfghjklmnpyptograAEIOUYaeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuaedizzinessiouz") == 44
    @test vowels_count("bcdfghjklmnpqrstvwxaAAaAaaaaaAaaAaaaaatbabstemvpqrstvwxyzyz") == 21
    @test vowels_count("aeiouuy") == 7
    @test vowels_count("bcdfghjkvlmnpqrstvwxyz") == 0
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvwxzyz") == 3
    @test vowels_count("aoeiozcaediozzinessiouyryptaedizzinessiouyography") == 25
    @test vowels_count("tbcdsfghjklmnpyptograAEIOUYaeiobckdfghjklmnpqrstvwxyzaeiouyurstvwtxyz") == 17
    @test vowels_count("tbcdfghjklmnpyptograAEIOUYaeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuaedizzinessiobAGAJuz") == 46
    @test vowels_count("crpyptography") == 3
    @test vowels_count("aediazzinesaAAaAaaApsychoaaaaa") == 20
    @test vowels_count("AEIOUYaeioaeiouyaAAcrypofaceaaAaaaaauyXWaAAaAaaAaaaaatbcdfghjklmnpqrstvwxyz") == 42
    @test vowels_count("caeiouyryptoaedizzinesaAAaAaabstetbcdfghdizzinessjklmnpqrstvwxzyzmiousnessaAaaaaapgraphy") == 35
    @test vowels_count("aAAaAaaAaaaaatlbcdfghjklmnpqrstvawxyz") == 14
    @test vowels_count("abssbcdfghjklmnaeioaeiocryiptofacetiousnesspggyuycrypteaedizzinessioeuyzteminoussness") == 33
    @test vowels_count("zoKyvcrypteaedizzinessiouyoegraphyC") == 13
    @test vowels_count("AEIOUYfaasiouyAaaatXaacetiousnessXoW") == 22
    @test vowels_count("aeioyaeiocryiptofacetiousnesspgyuy") == 18
    @test vowels_count("UCuAEIOUYaeioaeiouyiuyXWTX") == 18
    @test vowels_count("bcdfghjklmnpqrdizzinessstvtbcdfghjklmnpyptograAEIOUYaeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuyXWpqrsyzwx") == 39
    @test vowels_count("tbcdfghjkmnpqrstvwxyz") == 0
    @test vowels_count("aUCuMNjaAAcrypcaeiabstaeiiyemeioaeiocryiptofaceaaAaaaaaAAAEIOUYaeioaeiouyaAAcrypcaeioeiabstemioousnessopaeiocryiptofaceaaAaaaaauyXWaAaaAAaaaaa") == 95
    @test vowels_count("caeiouyryabsaedizzicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphynessioubtemhy") == 74
    @test vowels_count("AaAAaAaaAaaaaatlbcdfghjklmnpqrstvwaxyzEIOUyaeioaeiocrpyipAEIOUYXWtofacetiousnesspgyuyYaeioaeiouyuyXW") == 51
    @test vowels_count("aoeiAEIOUYaeioaeiouyaAAcrypcaeioeiabstemioousnessopaeiocryiptofaceaaAaaaaauyXW") == 52
    @test vowels_count("absasteminoAAuEYXWussness") == 11
    @test vowels_count("abstaeiiyebcdfghjklmnpqrstvwxaAAaAbcdfghjklcryptopgraphymnaeioaecaeiouyryptopgriaphyiocryiptohfacetiousnesspgyuycrypteaedizzninessiouypzaaAaaaaatbabstemvpqrstvwxyzyzm") == 57
    @test vowels_count("absaedizzicryptaedUCuMNujTHXegraphynessioubtemaaaatbcdfghjklmnpqrstwvwxyz") == 21
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryptofacetiousnesspgrapaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaahyceaaAaaaaa") == 90
    @test vowels_count("fnacetiousnahedizzinesaAAaAaaApsycholaaaaaaess") == 26
    @test vowels_count("UCuMNjaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptaycrypteaedizzinessiouyoegraphyofaceaaAaaaaa") == 47
    @test vowels_count("absaedizzicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaeiouyaAaaaaainessiouyoegraphynessioubtemaaaatbcdfghjklmnpqrstvwxyz") == 77
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnesssopaeiocryiptofaceaaAaaaaa") == 38
    @test vowels_count("psycohol") == 2
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvwxyzcrypaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryiptofaceaaAaabsaedizzicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphynessioubtemaaaatofacetieoussnesspgraphy") == 119
    @test vowels_count("cryptyoaphty") == 3
    @test vowels_count("cryptofacetieousnesspgraphyAaAAaAaaAaaaaatlbcdfghjklmnpqrstvwxyzEIOUyaeioaeiocrpyipawuyYaetbcdfghdizzinessioaeiouyuyXW") == 51
    @test vowels_count("UCuAEIOUYaeuioaeiouyiuyXWTX") == 19
    @test vowels_count("ovCKyvvC") == 1
    @test vowels_count("dizness") == 2
    @test vowels_count("absas") == 2
    @test vowels_count("aeiifacetiousnessydiztbcdfghjklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwtxyzzdizness") == 30
    @test vowels_count("ypgtogryarp") == 2
    @test vowels_count("tbcdfghjklmnpyptograAEIOUYaeioaeioueyurstvwbtxydz") == 18
    @test vowels_count("absaedizzicryptaedUCuMNujTHXegraphynessioubtemaxyz") == 18
    @test vowels_count("tbcdfgdhjkylmnpqrstvwxyz") == 0
    @test vowels_count("caeiouyryptoaedizzinesaAAaAaabstetbcdfghdizzinessjklmnpqrstvwxmzyzmiousnessaAaaaaapgraphy") == 35
    @test vowels_count("psylchlol") == 1
    @test vowels_count("bcdfghjklmnaeioaeiaeiiyocryiptofacetiousnesspgyuycrypteaedizzinessiouyoegraphypqrstvwxyz") == 33
    @test vowels_count("AaAAaycrypteaedizzinessiouyoegraphyaAaaAaaaaatlbcdfghjklmnpqrstvwxyzEIOUyaeioaeiocrpyiptofacetiousnesspgyuyYaeioaeiouyuyXW") == 58
    @test vowels_count("ssss") == 0
    @test vowels_count("tbcdfghjklmnvwxyzcryptoaphty") == 3
    @test vowels_count("caedizzinessiodizziznessssiouyography") == 16
    @test vowels_count("dizzinesscaedizzinessiouyryptaedizzinessiouyography") == 22
    @test vowels_count("aeioaeiiouyuy") == 12
    @test vowels_count("fnfnacetiousnahedizzinesaAAaAaaApsycholaaaaaaessacetiousnahedizzinesaAAaAaaApsycholaaaaaaess") == 52
    @test vowels_count("bcdfghjklmnaeioaeiaeiiyocryiptofacetiespsylchlolspgyuycrypteaedizzinessiouyoegraphypqrstvwxyz") == 32
    @test vowels_count("aoefnfnacetiousnahedizzinesaAAaAaaApsycholaaaaaaessacetiousnahedizzinesaAAaAaaApsycholaaaaaaesso") == 56
    @test vowels_count("pslychol") == 1
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnvpqrsybcdfghjklmnpqrstvwxyztograpxycaeiouyryptoaedizzinesaAAaAaaAaaaaapgraphyz") == 40
    @test vowels_count("aedizzineAsaAAaaAaaAaaaaa") == 20
    @test vowels_count("UCuoaoeioaeiouyeuayMNujTHX") == 17
    @test vowels_count("AMQRaAAcrypcaeiabsstemiousnessouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaaaI") == 40
    @test vowels_count("tbcdfghdizzitnessjmnpqrstvyptograAEIOUYaeioaeiotbcdfghjlmnpaeiotvwxyzyXWpyz") == 22
    @test vowels_count("aAAaAaaAaaaaapqrstvwxyz") == 13
    @test vowels_count("ABCDEIFGHIJKLSGTUVfnfnacetiousnahedizzinesaAAaAaaApsycholaaaaaaessacetiousnahedizzinesaAAaAaaApsycholaaaaaaessWXYZ") == 57
    @test vowels_count("absbtbem") == 2
    @test vowels_count("aAAaAAcrypcaecaeiouyryptopgyiouyryptopgriaphytoaaoeiocaedizzinessiouyryptaedizaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaaaazinessiouyographyeioaeiocryiptofaceaaAaaaaaaAaaAaaaaa") == 162
    @test vowels_count("aeioaeiocryiyptofacetiousnesspgyuycrypteabstaeiiyebcdfghjklmnpqrstvwxaAAaAbicdfghjklcryptopgraphymnaeioaecaeiouyryptopgriaphyiocryiptohfacetiousnesspgyuycrypteaedizzinessiouyzaaAaaaaatbabstemvpqrstvwxyzyzmaedizzinessiouyoegraphy") == 88
    @test vowels_count("bcdfghaaAaaaaatbabstemvpqrstvwxyzyz") == 10
    @test vowels_count("tbcdfghjklmoueyurstvwbtxyldz") == 4
    @test vowels_count("aooeioaouyeuy") == 12
    @test vowels_count("tbcdfghjklmnpyptograAEIOUYaeeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuaedizzinessiouz") == 45
    @test vowels_count("aAAaAaaAaaaaatlbcadfghjklmnpqrstvwxyz") == 14
    @test vowels_count("tbcdfgzhdizzinessjklmnpqrstvwxwxyz") == 3
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnvpqrsybdfghjklmnpqrstvwxyztograpxyz") == 15
    @test vowels_count("bcz") == 0
    @test vowels_count("absmtaieiiyem") == 7
    @test vowels_count("aediazzineAsaAAaAaaAaaaaa") == 20
    @test vowels_count("caeiouyryabsaediabstaeiiyebcdfghjklmnpqrstvwxaAAaAbcdfghjklcryptopgraphymnaeioaeiocryiptohfacetiousnesspgyuycrypteaedizzinessiouyzaaAaaaaatbabstemvpqrstvwxyzyzmzzicryptaedizzaAAcryphcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphynessioubtemhy") == 123
    @test vowels_count("bcdfghjklmnpqrdizzinesvwx") == 3
    @test vowels_count("absaedizzicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaeiouyaAaaaaphynessioubtemaaaatbcdfghjklmnpqrstvwxyz") == 68
    @test vowels_count("bcdfghjklmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyoegratvwxyz") == 29
    @test vowels_count("aeypgtogryarpiao") == 7
    @test vowels_count("aeiifacetiousnessydiztbcdfghjklmnpyaoeiozcaediozzinessiouyryptaedizzinessiouyographyptograAEIOUYaeioaeiouyuyXWpqrstvwtxyzzdizness") == 54
    @test vowels_count("tbcdfgdhjklmnpqrqstvwxyz") == 0
    @test vowels_count("aoefnfnacetiousnahedizzinesaAAaAaaApsycholaaaaaaessacetiousnahedizzinesaAAaAaaApsycholaaayaaaesso") == 56
    @test vowels_count("tbcdfghdizzinnessjklmnpqrstvwxzyz") == 3
    @test vowels_count("caeiouyryabsaedizzicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraeioaphynessioubtemhy") == 78
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocrytofacetiousnesspgraphyceaaAaaaaa") == 44
    @test vowels_count("tbcdfghjkmnpqraAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaaaatvwxyz") == 88
    @test vowels_count("AEIOUYYX") == 5
    @test vowels_count("abssteminoaAAaAaaAaaaaatbtcdfghjklmnpqrstvwxyzAAuEYXWussness") == 23
    @test vowels_count("AEIOUYaeioaeiouyaAAcrypcaeioeiabstemioousnessopaeiocryiptofaceaaAaaaAAaAaaAaaaaatbtcdfghjklmnpqrstvwxyzaaauyXW") == 61
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryptofacetiousnesspgUCuMNjaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaraphyceaaAaaaaa") == 75
    @test vowels_count("aAAcryptoayptographynaAaaiaaeiiyAaaaaa") == 23
    @test vowels_count("pslychpsycohol") == 2
    @test vowels_count("tbcdfghjklmnpyptpsycholcaeiouyryptoaedizzinesaAAaAaaAaaaaapgraphyogyograAEIOUYaeioaeiouyurstvwtxyz") == 44
    @test vowels_count("bcdfjklmnpqrdizzinesvwx") == 3
    @test vowels_count("crroKyrvCyptopgraphy") == 4
    @test vowels_count("UCuMNjaAAcrypcaeiabstaeiiyemeioaeiocryiptofaceaaAaaaa") == 32
    @test vowels_count("tbcdfghjklmnpoKyvCyptograAEIOUYaeeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuaedizzinessiouz") == 46
    @test vowels_count("UCUuMNNujX") == 4
    @test vowels_count("atbcdfghdizzinessjklmnpqrstvwxwxyzoeio") == 8
    @test vowels_count("tbcdfgdhdjklmnpqrqstvwxyz") == 0
    @test vowels_count("aAAaAAcrypcaecaaeiouyryptopgraphyiouyryptopgriaphytoaeioaeiocryiptofaceaAEIOaeioaeiocryiaAAcryptoayptographynaAaaiaaeiiyAaaaaaptofacetiousnesspgyuyaaaaAaaAaaaaa") == 93
    @test vowels_count("UCuWlDVSrhNaoaoeioaeiouyeuayMNujTHX") == 18
    @test vowels_count("cryptograpabsaedizzicryptaedUCuMNujTHXegraphynessioubtemaxyzhty") == 21
    @test vowels_count("aeioaeiocryipntofacetiousnesspgyuy") == 18
    @test vowels_count("tbcdfghAaAAaycrypteaedizzinessiouyoegraphyaAaaAaaaaatlbcdfghjklmnpqrstvwxyzEIOUyaeioaeiocrpyiptofacetiousnesspgyuyYaeioaeiouyuyXWjklmnpyptograAEIOUYaeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuyXWpqrsyz") == 94
    @test vowels_count("aoeiocaedizzinessiouyryptaedizaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnhessopaaeiocryptoffacetiousnesspgraphyceaaAaaaaaaazinessiouyography") == 70
    @test vowels_count("absbtabsstemioussnessem") == 8
    @test vowels_count("abcdfghjklmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyzeioaeiocryiptofacetiousUCuMNujXnesspgyuycryepteaedizzinessiouyoegraphy") == 60
    @test vowels_count("aedicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacbckdfghjklmnpqrstvwxyzetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphyzzinessioeuy") == 68
    @test vowels_count("bcdfghjsklmnpaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryptofacetiousnesspgUCuMNjaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaraphyceaaAaaaaaqrdizzinessstvwx") == 78
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnpqrstcdfghjkAlmnpqrstvwxyztograpyz") == 16
    @test vowels_count("ovCKyvvKC") == 1
    @test vowels_count("bcdfghjklncryptopgraphytbcdfghjkmnpqraAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaaaatvwxyzinessiouyz") == 95
    @test vowels_count("AEIOUYXXW") == 5
    @test vowels_count("tbcdfghAaAAaycrypteaedizzinessiouyoegraphyaAaaAaaaaatlbcdfghjklmnpqrstvwxyzEIOUyaeioaeiocrpyiptofacetiousnesspgyuyYaeioaeiouyuyXWjklmnpyptograAEIOUYaeioaeioouyaAAcrypauyXWuyuyXWpqrsyz") == 82
    @test vowels_count("abstaeiiyebcdfghjklmnpqrstvwxaAAaAbcdfghjklcryptopgraphymnaeioaecaeiouyryptopgriaphyiocmryiptohfacetiousnesspgyuycrypteaedizzninessiouypzaaAaaaaatbabstemvpqrstvwxyzyzm") == 57
    @test vowels_count("abssteminoAkBlAEYXWussness") == 9
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousneeaaAaaaaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaaaa") == 74
    @test vowels_count("crayptopgraphy") == 4
    @test vowels_count("abcdfghjklmnaoeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyzeioaeiocryiptofacetiousUCuMNujXnesspgyuycryepteaedizzinessiouyoegraphy") == 61
    @test vowels_count("bvwxaedizzinessiocaeiouyryptoaedizzinesaAAaAaabstemiousnessaAaaaaapgraphyuyyz") == 39
    @test vowels_count("aeioaeiocryiyptofacetiousnesspaedizzinessiouyoegraphy") == 28
    @test vowels_count("AAEYX") == 3
    @test vowels_count("oKyvcrypteaeiifacetiousnessydiztbcdfghjklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwtxyzzdiznessaedizzinessiouyoegraphyC") == 43
    @test vowels_count("UCUuMcaedizzinessiouyryptaedizzinessiouyographyNNujX") == 22
    @test vowels_count("crypteaedizzinoessiouyoegratbcdfghjklmnpoKyvCyptograAEIOUYaeeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuaedizzinessiouzphy") == 60
    @test vowels_count("aAAaAaaAafnacetiousnessaaaatbcdfghjklmnvpqrsybcdfghjklmnpqrstvwxyztograpxycaeiouyryptoaedizzinesaAAaAaaAaaaaapgraphyz") == 46
    @test vowels_count("abvwxaedizzinessiouyyzediazzineAsaAAaAaaAaaaaa") == 28
    @test vowels_count("bcdfghjklcryptopgraphymnaeioaeiyocryiptohfacetiousnesspgypuycrypteaedizzinessiouyz") == 28
    @test vowels_count("py") == 1
    @test vowels_count("tbcgdfghjkhz") == 0
    @test vowels_count("aeioaeiocrytbcdsfghjklmnpyptograAEIOUYaeiobckdfghjklmnpqrstvwxyzaeiouyurstvwtxyziyptofacetiousnesspgyuycrypteabstaeiiyebcdfghjklmnpqrstvwxaAAaAbicdfghjklcryptopgraphymnaeioaecaeiouyryptopgriaphyiocryiptohfacetiousnesspgyuycrypteaedizzinessiouyzaaAaaaaatbabstemvpqrstvwxyzyzmaedizzinessiouyoegraphy") == 105
    @test vowels_count("ogrraphty") == 3
    @test vowels_count("atbctbcdfghjklmnpoKyvCyptograAEIOUYaeeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuaedizzinessiouzio") == 49
    @test vowels_count("bcdfghjklmnaeioaeiocryiptofacetiousnessAEIOUYYXpgyuycrypteaedizzinessiouyoegratvwxyz") == 34
    @test vowels_count("UCuMNjaAAcrypcaeiabstaeitbcdfghjklmnvwxyzcryptoaphtyiyemeioaeiocryiptofaceaaAaaaaa") == 35
    @test vowels_count("diztbcdfghjklmnpypztograAEIOUYaeioaeiouyuyXWpqrstvwtxyzzdizness") == 20
    @test vowels_count("AEIOUYfaasiouyAaIaaXaacetiousnessXoW") == 23
    @test vowels_count("oKyvcrypteaeiifacetiousnessydiztbcdfghjklmnpyptograAEIOUYaeioaeiouypsycholcaeiouyryptoaedizzinesaAAaAaaAaaaaapgraphyogyuyXWpqrstvwtxyzzdiznessaedizzinessiouyoegraphyC") == 70
    @test vowels_count("UCTX") == 1
    @test vowels_count("tbcdfghAaAAaycrypteaedizzinessiouyoegraphyaAaaAaaaaatlbcdfghjklmnpqrstvwxyzEIOUyaeioaeiocrpyiptofacetiousnesspgyuyYaeioaebcdfghjsklmnpaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryptofacetiousnesspgUCuMNjaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaraphyceaaAaaaaaqrdizzinessstvwxoaeiouyaAAcrypauyXWuyuyXWpqrsyz") == 145
    @test vowels_count("aeiouutbcdfghjklmnpyptograAEIOUYaeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuyXWpqrsyzy") == 43
    @test vowels_count("aooeio") == 6
    @test vowels_count("aoeiocaedizzinessiouyryptaedizaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaAAcrypcaeiouyryptopgriaphytoaeusnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaaaazinessiouyography") == 107
    @test vowels_count("diznabstaeiiyebcdfghjklmnpqrstvwxaAAaAbcdfghjklcryptopgraphymnaeioaecaeiouyryptopgriaphyiocryiptohfacetiousnesspgyuycrypteaedizzninessiouypzaaAaaaaatbabstemvpqrstvwxyzyzms") == 58
    @test vowels_count("caeiouyryptoaedizzinesaAAacryptopgraphyAaabstetbcdfghdizzinessjUCuoaoeioaeiouyeuyMNujTHXklmnpqrstvwxzyzmiousnessaAaaaaapgraphy") == 53
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnvpqrsybcdfghjklmnpqrstvwxyztograpxycaeiabssteminoAkBlAEYXWussnessouyryptoaedizzinesaAAaAaaAaaaaapgraphyz") == 49
    @test vowels_count("abcdfghjklmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyzeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiotbcdfghjklmnvwxyzcryptoaphtyuyoegraphy") == 58
    @test vowels_count("aeeio") == 5
    @test vowels_count("aoeiocaedizzinessiouyryptaedizaAAcrypuyography") == 23
    @test vowels_count("bcdfAMQRIghjklmnpqrstvwxyz") == 2
    @test vowels_count("bcdfghjkUCuoaaedizzinessiouoeioaeiouyeuyMNujaAAaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofaceaaAaaaaaaAaaAaaaaaTHXlmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyoegraphypqrstvwxyz") == 98
    @test vowels_count("caeiouyryptoaeedizzinesaAAaAaabstetbcdxzyzamiousnessaAaaaaapgraphy") == 34
    @test vowels_count("aAAatbcdfghjklmnvwxyzAaaAaaaaatlbcadfghjklmnpqrstvwxyz") == 14
    @test vowels_count("aoeiocaedizzinessiouyryptaedizaAAcrypcaeiouyrycryptoaphtyptopgriaphytoaeiabstemiousnhessopaaeiocryptoffacetiousnesspgraphyceaaAaaaaaaazinessiouyography") == 72
    @test vowels_count("abbsas") == 2
    @test vowels_count("crypteaedizzinoessiouyoegratbcdfghjklmnpoKyvCyptograAEabsasIOUYaeeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuaedizzinessiouzphy") == 62
    @test vowels_count("caeioaedicryptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspeegraphyzzinessioeuyuyryptopgriaphy") == 52
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnvpqrsybcdfghjklmnpqrstvwxyztograpxycaeiouyryptoaeioaeiiouyuyaedizzinesaAAaAaaAaaaaapgraphyz") == 51
    @test vowels_count("aeiifacetiousnessydiztbcdfghjklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwtxyzzdidizzinesszness") == 33
    @test vowels_count("tbcdfghdizzinessjklmnpqrstvwxyzcrypaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaeiocryiptofaceaaAaabsaedizzicriyptaedizzaAAcrypcaeiouyryptopgriaphytoaeioaeiocryiptofacetiousnesspgyuyfacetieousnesspgraphyaAaaAaaaaainessiouyoegraphynessioubtemaaaatofacetieoussnesspgraphy") == 120
    @test vowels_count("absaedizzicryptaedUCuMNujTHXegraphynessioubtemaaaatbcdfghjklmnpqirstvwxyz") == 22
    @test vowels_count("tbcdfghajklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwtxyz") == 18
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiypgtogryarpabstemiousnessopaaeiocrytofacetiousnesspgraphyceaaAaaaaa") == 46
    @test vowels_count("caeiouyryptoaedizzinesaAAaAaabstetbcdfghdizzinessjklmnpqrstvwxzyzmiousnessUCuMNjaAAcrypcaeiabstaeiiyemeioaeiocryiptofaceaaAaaaaaAaaaaapgraphy") == 67
    @test vowels_count("aAAcrypcaeiouyryptopgriaphAMQRIytoaeiypgtogryarpabstemiousnessopaaeiocrytofacetiousnesspgraphyceaaAaaaaa") == 48
    @test vowels_count("aaw") == 2
    @test vowels_count("aAAaAaaAaaaaatbcdfghjkllmnpqrstvwxyz") == 13
    @test vowels_count("yuyYaeioaeiouyuyXW") == 11
    @test vowels_count("aAAaAaaAaaaaatbcdfghjklmnvpqrsybcdfghjklmnpqrstvwxyztograpxycaeioaAAaAaaAaaaaatbabstemvpqrstvwxyzuyryptoaeioaeiiouyuyaedizzinesaAAaAaaAaaaaapgraphyz") == 66
    @test vowels_count("aAAaAaaAaaaaatlbcadfghjklmnpqrstvwxtbcdfghdizzitnessjmnpqrstvyptograAEIOUYaeioaeiotbcdfghjlmnpaeiotvwxyzyXWpyzyz") == 36
    @test vowels_count("AaedizzinesaAAaAaAaaaaaI") == 19
    @test vowels_count("yptograAEIOUYaeioaeiottbEcdfyXWp") == 16
    @test vowels_count("aoeiocaedizzinessiouyryptaedizaAAcrypcaeiouyryptopgriaphytoaeiabstemiousinessopaaeaiocryptofacetiousnesspgraphyceaaAaaaaAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocryptofacetiousnesspgraphyceaaAaaaaaaazinessiouyography") == 114
    @test vowels_count("pslychpsyctbcdfghajklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwtxyz") == 18
    @test vowels_count("oKCyvC") == 1
    @test vowels_count("UCuMNaeioaeiocryiptofacetiousnessapgyuy") == 21
    @test vowels_count("aedizzineAsaAAaaAaaAaaaaaUCuAEIOUYaeuioaeiouyiuyXWTX") == 39
    @test vowels_count("UCuMNjaAAcrypcaeiouyryptopaeiouutbcdfghjklmnpyptograAEIOUYaeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuyXWpqrsyzygriaphytoaeioaeiocryiptofaceaaAaaa") == 74
    @test vowels_count("abAAEYXWtems") == 5
    @test vowels_count("aeiifacetiousnessydiztbcdfghjklmnpyptograAEIOUYaeioaeiouyuyXWpqrstvwtxyzzdidizzinesszneabcdfghjklmnaeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyzeioaeiocryiptofacetiousnesspgyuycrypteaedizzinessiouyoegraphyss") == 88
    @test vowels_count("aAAcrypcaeiouyryptopgriaphytoaeiabstemiousnessopaaeiocrayptofacetiousnesspgraphyceaaAaaaaa") == 45
    @test vowels_count("UCuMNjaAAcrypcaeiouyryptopgriapphytoaeioaeiocryiptofaceacrayptopg") == 29
    @test vowels_count("clUaEPUIN") == 5
    @test vowels_count("aedizzineAsaAAaaabstemiousnessAaaAaaaaa") == 26
    @test vowels_count("apiao") == 4
    @test vowels_count("ABCDEIFGHIJKLSGTUVfnfnacetiousnahediinesaAAaAaaApsycholaaaaaaessWXYZ") == 31
    @test vowels_count("tbcdfghjklmoueybtxyldz") == 3
    @test vowels_count("absaeddizzinesscaedizzinessiouyryptaedizzinessiouyographyizzicryptaedUCuMNujaphynessioubtemaaaatbcdfghjklmnpqirstvwxyz") == 42
    @test vowels_count("crypteaedizziouyoegratbcdfghjklmnpoKyvCyptograAEIOUYaeeioaeioAEIOUYaeioaeiouyaAAcrypauyXWuyuaedizzinessiouzphy") == 57
    @test vowels_count("bvwxaedizzinessiocaeiouyryptoUCuWlDVSrhNaoaoeioaeiouyeuayMNujTHXaedizzinesaAAaAaabstemiousnessaAaaaaapgraphyuyyz") == 57
end
