@testitem "075_is_multiply_prime_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "075_is_multiply_prime.jl"))
    @test is_multiply_prime(33) == false
    @test is_multiply_prime(49) == false
    @test is_multiply_prime(77) == false
    @test is_multiply_prime(91) == false
    @test is_multiply_prime(99) == true
    @test is_multiply_prime(6) == false
    @test is_multiply_prime(90) == false
    @test is_multiply_prime(98) == true
    @test is_multiply_prime(25) == false
    @test is_multiply_prime(21) == false
    @test is_multiply_prime(48) == false
    @test is_multiply_prime(20) == true
    @test is_multiply_prime(22) == false
    @test is_multiply_prime(32) == false
    @test is_multiply_prime(26) == false
    @test is_multiply_prime(78) == true
    @test is_multiply_prime(19) == false
    @test is_multiply_prime(47) == false
    @test is_multiply_prime(31) == false
    @test is_multiply_prime(5) == false
    @test is_multiply_prime(29) == false
    @test is_multiply_prime(-98) == false
    @test is_multiply_prime(-37) == false
    @test is_multiply_prime(-38) == false
    @test is_multiply_prime(28) == true
    @test is_multiply_prime(18) == true
    @test is_multiply_prime(23) == false
    @test is_multiply_prime(-92) == false
    @test is_multiply_prime(-2) == false
    @test is_multiply_prime(57) == false
    @test is_multiply_prime(-99) == false
    @test is_multiply_prime(58) == false
    @test is_multiply_prime(56) == false
    @test is_multiply_prime(-1) == false
    @test is_multiply_prime(92) == true
    @test is_multiply_prime(1) == false
    @test is_multiply_prime(-80) == false
    @test is_multiply_prime(34) == false
    @test is_multiply_prime(-75) == false
    @test is_multiply_prime(-100) == false
    @test is_multiply_prime(-95) == false
    @test is_multiply_prime(16) == false
    @test is_multiply_prime(-94) == false
    @test is_multiply_prime(17) == false
    @test is_multiply_prime(59) == false
    @test is_multiply_prime(-7) == false
    @test is_multiply_prime(93) == false
    @test is_multiply_prime(-82) == false
    @test is_multiply_prime(-15) == false
    @test is_multiply_prime(-81) == false
    @test is_multiply_prime(-96) == false
    @test is_multiply_prime(-74) == false
    @test is_multiply_prime(2) == false
    @test is_multiply_prime(3) == false
    @test is_multiply_prime(7) == false
    @test is_multiply_prime(97) == false
    @test is_multiply_prime(42) == true
    @test is_multiply_prime(-101) == false
    @test is_multiply_prime(43) == false
    @test is_multiply_prime(44) == true
    @test is_multiply_prime(45) == true
    @test is_multiply_prime(-56) == false
    @test is_multiply_prime(60) == false
    @test is_multiply_prime(-55) == false
    @test is_multiply_prime(46) == false
    @test is_multiply_prime(62) == false
    @test is_multiply_prime(55) == false
    @test is_multiply_prime(61) == false
    @test is_multiply_prime(41) == false
    @test is_multiply_prime(40) == false
    @test is_multiply_prime(-57) == false
    @test is_multiply_prime(63) == true
    @test is_multiply_prime(-102) == false
    @test is_multiply_prime(52) == true
    @test is_multiply_prime(-72) == false
    @test is_multiply_prime(-97) == false
    @test is_multiply_prime(94) == false
    @test is_multiply_prime(12) == true
    @test is_multiply_prime(89) == false
    @test is_multiply_prime(53) == false
    @test is_multiply_prime(0) == false
    @test is_multiply_prime(8) == true
    @test is_multiply_prime(64) == false
    @test is_multiply_prime(-58) == false
    @test is_multiply_prime(65) == false
    @test is_multiply_prime(-71) == false
    @test is_multiply_prime(95) == false
    @test is_multiply_prime(35) == false
    @test is_multiply_prime(-70) == false
    @test is_multiply_prime(96) == false
    @test is_multiply_prime(-59) == false
    @test is_multiply_prime(15) == false
    @test is_multiply_prime(-33) == false
end
