@testitem "111_histogram_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "111_histogram.jl"))
    @test histogram("x y z x y z x") == Dict("x" => 3)
    @test histogram("c a r s") == Dict("c" => 1, "r" => 1, "a" => 1, "s" => 1)
    @test histogram("h e l l o") == Dict("l" => 2)
    @test histogram("a b b b b b") == Dict("b" => 5)
    @test histogram("p u z z l e") == Dict("z" => 2)
    @test histogram("a a a a a a a b b b b b b b") == Dict("b" => 7, "a" => 7)
    @test histogram("c c c c b b b a a a") == Dict("c" => 4)
    @test histogram("p p p r r r") == Dict("r" => 3, "p" => 3)
    @test histogram("a b c d e f g") == Dict("f" => 1, "g" => 1, "c" => 1, "e" => 1, "b" => 1, "a" => 1, "d" => 1)
    @test histogram("h i j j k l m m m n o o o o p") == Dict("o" => 4)
    @test histogram("a b b  b b b") == Dict("b" => 5)
    @test histogram("h i j j k l m m m p") == Dict("m" => 3)
    @test histogram("a a a a a a a b b b b b b") == Dict("a" => 7)
    @test histogram("a b h i j j k l m m m n o o o o p") == Dict("o" => 4)
    @test histogram("h i j j k l m m m n o o o o  p") == Dict("o" => 4)
    @test histogram("a") == Dict("a" => 1)
    @test histogram("a b b  b b  b") == Dict("b" => 5)
    @test histogram("h i j j  k l m m m n o o o o  p") == Dict("o" => 4)
    @test histogram("a b c  d e f g") == Dict("f" => 1, "g" => 1, "c" => 1, "e" => 1, "b" => 1, "a" => 1, "d" => 1)
    @test histogram("p  l  e") == Dict("e" => 1, "l" => 1, "p" => 1)
    @test histogram("h i j j   k l  m m m n o o o o  p") == Dict("o" => 4)
    @test histogram("p u z l e") == Dict("e" => 1, "u" => 1, "l" => 1, "z" => 1, "p" => 1)
    @test histogram(" p p p r r r") == Dict("r" => 3, "p" => 3)
    @test histogram(" p p p  r r r") == Dict("r" => 3, "p" => 3)
    @test histogram("a a a a a a a b b  b b b b") == Dict("a" => 7)
    @test histogram("p l  e") == Dict("e" => 1, "l" => 1, "p" => 1)
    @test histogram("h i j j   k l  m  o o  p") == Dict("j" => 2, "o" => 2)
    @test histogram(" p r") == Dict("r" => 1, "p" => 1)
    @test histogram("a b b b b b  b") == Dict("b" => 6)
    @test histogram(" p ") == Dict("p" => 1)
    @test histogram("a b c  d  e f g") == Dict("f" => 1, "g" => 1, "c" => 1, "e" => 1, "b" => 1, "a" => 1, "d" => 1)
    @test histogram("a b b b b") == Dict("b" => 4)
    @test histogram("h i j m m m p") == Dict("m" => 3)
    @test histogram("h i j j   k l  m  p") == Dict("j" => 2)
    @test histogram("h  i j j   k l  m  o o  ") == Dict("j" => 2, "o" => 2)
    @test histogram("h i j j    k l  m   p") == Dict("j" => 2)
    @test histogram("a a a a a a a b b  b") == Dict("a" => 7)
    @test histogram("") == Dict{String, Int64}()
    @test histogram("a b b  b b   b") == Dict("b" => 5)
    @test histogram(" p  ") == Dict("p" => 1)
    @test histogram("  p p r r r") == Dict("r" => 3)
    @test histogram("h  i j j   k l  m  o  ") == Dict("j" => 2)
    @test histogram("h i j j k l m m m n  o o o o  p") == Dict("o" => 4)
    @test histogram("h  i j j k l  m  o  ") == Dict("j" => 2)
    @test histogram("h i j j   k l  m  o p") == Dict("j" => 2)
    @test histogram("x y z x y  z x") == Dict("x" => 3)
    @test histogram(" p h  i j j k l  m  o  ") == Dict("j" => 2)
    @test histogram("h  i j j   k l  m  o   ") == Dict("j" => 2)
    @test histogram("a b c  e f g") == Dict("f" => 1, "g" => 1, "c" => 1, "e" => 1, "b" => 1, "a" => 1)
    @test histogram("c c c c b b b a  a a") == Dict("c" => 4)
    @test histogram("p u z z  l e") == Dict("z" => 2)
    @test histogram("h i j j k l m m m n o  o o o  p") == Dict("o" => 4)
    @test histogram("a b c d e  p  f g") == Dict("f" => 1, "g" => 1, "c" => 1, "e" => 1, "b" => 1, "a" => 1, "p" => 1, "d" => 1)
    @test histogram("a b h i j j m m m n o o o o p") == Dict("o" => 4)
    @test histogram("x y z x y  z x ") == Dict("x" => 3)
    @test histogram("h i j j k l m m m n o o p") == Dict("m" => 3)
    @test histogram("a b  b b b b") == Dict("b" => 5)
    @test histogram("h   i j j   k l  m  o   ") == Dict("j" => 2)
    @test histogram("p  l h i j j k l m m m p e") == Dict("m" => 3)
    @test histogram("a b b  b b b  b") == Dict("b" => 6)
    @test histogram("h e") == Dict("e" => 1, "h" => 1)
    @test histogram("h i j j k l m m m n o  o o   p") == Dict("m" => 3, "o" => 3)
    @test histogram("p  l h i j j k l m  e") == Dict("j" => 2, "l" => 2)
    @test histogram(" p p p r r r p ") == Dict("p" => 4)
    @test histogram("  p p  r r r") == Dict("r" => 3)
    @test histogram("a b c h  i j j k l  m  o  d e  p  f g") == Dict("j" => 2)
    @test histogram("p u z z  e") == Dict("z" => 2)
    @test histogram("p  u z z  e") == Dict("z" => 2)
    @test histogram("p u z z  l  e") == Dict("z" => 2)
    @test histogram("  p  ") == Dict("p" => 1)
    @test histogram("  s") == Dict("s" => 1)
    @test histogram("h i j j k  h i j j   k l  m  o o  p p p p r r r m m n o o o o  p") == Dict("o" => 6)
    @test histogram("h  i j m m m p") == Dict("m" => 3)
    @test histogram("p  l h i j j k  l m  e") == Dict("j" => 2, "l" => 2)
    @test histogram("  p p r h i j j k l m m m n  o o o o  p r") == Dict("o" => 4)
    @test histogram(" p") == Dict("p" => 1)
    @test histogram(" a b b  b b   b") == Dict("b" => 5)
    @test histogram(" a b b  b b    b") == Dict("b" => 5)
    @test histogram(" a  b b  b b   b") == Dict("b" => 5)
    @test histogram("h  i j  p p r r r j   k l  m") == Dict("r" => 3)
    @test histogram("c c c c b b a a") == Dict("c" => 4)
    @test histogram(" p p p r  r r") == Dict("r" => 3, "p" => 3)
    @test histogram(" r") == Dict("r" => 1)
    @test histogram("a b b  b") == Dict("b" => 3)
    @test histogram("h  i  j m m m") == Dict("m" => 3)
    @test histogram("h  i j j k l   m  o  ") == Dict("j" => 2)
    @test histogram("h i j j k  h i j j   k l  m  o o  p p p p r r r m m n  o o o o  p") == Dict("o" => 6)
    @test histogram("a a a a a a a b b b  b") == Dict("a" => 7)
    @test histogram("  p p p  r r r ") == Dict("r" => 3, "p" => 3)
    @test histogram("p  l  h i j j k l m  e") == Dict("j" => 2, "l" => 2)
    @test histogram("p  p p r h i j j  p p p r r r p k l m m m n  o o o o  p r  u z z  e") == Dict("p" => 8)
    @test histogram("a  b c d e f g") == Dict("f" => 1, "g" => 1, "c" => 1, "e" => 1, "b" => 1, "a" => 1, "d" => 1)
    @test histogram("  p") == Dict("p" => 1)
    @test histogram("   p  ") == Dict("p" => 1)
    @test histogram("a a p h  i j j k l  m  o   a a a a a b b b b b b") == Dict("a" => 7)
    @test histogram("a  a a a a a a b b  b b b b") == Dict("a" => 7)
    @test histogram("  p   p ") == Dict("p" => 2)
    @test histogram("p   l  e") == Dict("e" => 1, "l" => 1, "p" => 1)
    @test histogram("h  i p p r h  i j j   k l  m  o o   r r j   k l  m") == Dict("j" => 3, "r" => 3)
    @test histogram("c a a a a b b d d d d f f f g h i") == Dict("a" => 4, "d" => 4)
    @test histogram("p p q q q r r r s s s t t t u u u v v w w x x y y z z") == Dict("t" => 3, "r" => 3, "u" => 3, "q" => 3, "s" => 3)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y y y y y z z z z z") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "x" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("l m m m m m m m m n n n n n n n n n n n n n n o o p p q q r r s") == Dict("n" => 14)
    @test histogram("     a a a a b b d d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("x y z x y z x y z x y z x y z x y z x y z x y z x") == Dict("x" => 9)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g") == Dict("f" => 3, "g" => 3, "c" => 3, "e" => 3, "b" => 3, "a" => 3, "d" => 3)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w") == Dict("t" => 8)
    @test histogram("    x      a b c d e f   a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("h") == Dict("h" => 1)
    @test histogram("l") == Dict("l" => 1)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w") == Dict("t" => 8)
    @test histogram("d") == Dict("d" => 1)
    @test histogram("u") == Dict("u" => 1)
    @test histogram("b") == Dict("b" => 1)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("p") == Dict("p" => 1)
    @test histogram("z") == Dict("z" => 1)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n o p q r r r s s      a a a a b b d d d d f f f g h i  s s s s s t t t t t t t t u v w") == Dict("t" => 8, "d" => 8)
    @test histogram("g") == Dict("g" => 1)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t t u v w") == Dict("t" => 8)
    @test histogram("s") == Dict("s" => 1)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t t u v  w") == Dict("t" => 8)
    @test histogram("c") == Dict("c" => 1)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t t  t t u v w") == Dict("t" => 8)
    @test histogram("n") == Dict("n" => 1)
    @test histogram("v") == Dict("v" => 1)
    @test histogram("x y z x y z  x y z x y z x y z x y z x y z x y z x") == Dict("x" => 9)
    @test histogram("f") == Dict("f" => 1)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y     a a a a b b d d d d f f f g h i   y y y y z z z z z") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "x" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("i") == Dict("i" => 1)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v  w x y z") == Dict("t" => 8)
    @test histogram("    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("    x      a b c d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("t") == Dict("t" => 1)
    @test histogram("    a b   k k l l t t t t t t u v w x y z") == Dict("t" => 6)
    @test histogram("o") == Dict("o" => 1)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i  j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w") == Dict("t" => 8)
    @test histogram("m") == Dict("m" => 1)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("x y z x y z  x y z x y z x y z x y z x y z x y z  x") == Dict("x" => 9)
    @test histogram("     a b   k k l l t t t t t t u v w x y z") == Dict("t" => 6)
    @test histogram("w") == Dict("w" => 1)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t     x      a b c d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w") == Dict("s" => 14)
    @test histogram("x") == Dict("x" => 1)
    @test histogram("r") == Dict("r" => 1)
    @test histogram("j") == Dict("j" => 1)
    @test histogram("    a b        c d e f   a g g h h h i j a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g m n o p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 10)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v s x x x x y     a a a a b b d d d d f f f g h i   y y y y z z z z z") == Dict("s" => 7)
    @test histogram("    a b        c d e f   a g g h  h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("e") == Dict("e" => 1)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i  j j j  j k k k k  l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w") == Dict("t" => 8)
    @test histogram("l     a a a a b b d d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("x y z x y z  x y z x y z x y z z x y z x y z x") == Dict("x" => 8, "z" => 8)
    @test histogram("    x      a b c d e f   a g   g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("x y a a  a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t     x      a b c d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w") == Dict("s" => 14)
    @test histogram("  l  a b   k k l l t t t t t t u v w x y z") == Dict("t" => 6)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 13)
    @test histogram("x y z x y z x y z x y z x y  z x y z x y z x  y z x") == Dict("x" => 9)
    @test histogram("     a b        c d e f   a g g h  h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y z   x      a b c d e f   a g   g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 14)
    @test histogram("x y z x y z  x y x y z x") == Dict("x" => 5)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t") == Dict("s" => 13)
    @test histogram("    x      a b c d e f   a g   g h h h h i j j j k k k k l l l l m n o p q r r r  s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("l m m m m m m m m n n n n n n n n n n n n n  p p q q r r s") == Dict("n" => 13)
    @test histogram("     a b    s s s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t   x      a b c d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w") == Dict("s" => 14)
    @test histogram("x y z x y z x y z l     a a a a b b d d d d f f f g h i  x y z x y z x y z x y z x y z x") == Dict("x" => 9)
    @test histogram("k") == Dict("k" => 1)
    @test histogram("    x      a b c d e f   a g g h h h h i    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 14)
    @test histogram("l     a a a a b b d  d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x  z z") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("l     a a a a b b d  d d d f f f g h i") == Dict("a" => 4, "d" => 4)
    @test histogram("x y a a a o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z s s s s s s s t t t t t t t t u v w") == Dict("t" => 14)
    @test histogram("y") == Dict("y" => 1)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t   a a a a b b d d d d f f f g h i  ") == Dict("s" => 13)
    @test histogram("x y z x y z  x y z x y z x y z x y z  x") == Dict("x" => 7)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l  l l l m n o p q r r r s s s s s s s t t t t t   a a a a b b d d d d f f f g h i  ") == Dict("s" => 13)
    @test histogram("l a b b d  d d d f f f g h i") == Dict("d" => 4)
    @test histogram("x y z x y z  x y z x y z x y z x y z e y z  x") == Dict("x" => 7, "z" => 7, "y" => 7)
    @test histogram("    x      a b c d e f   a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t  t") == Dict("s" => 7)
    @test histogram("x y z x y z  x y z o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y y y y y z z z z z y z e y z  x") == Dict("x" => 10, "z" => 10, "y" => 10)
    @test histogram("x x y y z z") == Dict("x" => 2, "z" => 2, "y" => 2)
    @test histogram("     a a a a b b d d d d f f f g  h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y s s t t t t t") == Dict("t" => 11)
    @test histogram("     a a a a b b x y z x y z x y z l     a a a a b b d d d d f f f g h i  x y z x y z x y z x y z x y z x") == Dict("x" => 9)
    @test histogram("x y z x  z x y z x y z x") == Dict("x" => 5)
    @test histogram("l     a a a a  b b d d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t   x      a b c d e f  x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t     x      a b c d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w") == Dict("s" => 28)
    @test histogram("    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t  t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("x y a a a b b d d  d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s  s s s t t t   t t t t t u v w") == Dict("t" => 8)
    @test histogram("p p q q q r r r s s s t t t  u u u v v w w x x y y z z") == Dict("t" => 3, "r" => 3, "u" => 3, "q" => 3, "s" => 3)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v z") == Dict("o" => 6, "t" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("x y z x y z  x y z x y z x y z z x y z x  y z x") == Dict("x" => 8, "z" => 8)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t   x      a b c d e f   a g  g h    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w") == Dict("s" => 21)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t     x  j    a b c d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w") == Dict("s" => 14)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y     a a a a b b d d d d f f f g h i  p y y y y z z z z z") == Dict("p" => 7)
    @test histogram("    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t  t t t u v w x y z") == Dict("t" => 8)
    @test histogram("x y z x y z  x y z  x y z x y z z x y z x  y z x") == Dict("x" => 8, "z" => 8)
    @test histogram("    x      a b c d e f   a g   g h h h h  i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("    a b       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 16)
    @test histogram("x y z x y z  x y z x y z x  y z z x y z x y z x") == Dict("x" => 8, "z" => 8)
    @test histogram("x y a a a b b d d  d d f f f g l m n o p q r r r s s s s  s s s t t t   t t t t t    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z v w") == Dict("t" => 16)
    @test histogram("x y z x y z  x y z  x y z x y z z x y z    x      a b c d e f   a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t  t x  y z x") == Dict("x" => 9)
    @test histogram("    x      a b c d e f   a g   g h l     a a a a  b b d d d d f f f g h i  h h h i j j j k k k k l l l l m n o p q r r r  s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("x y a a a b b d d d d f f f g h i i i i  i j j j j k k k k l l l l m t t t u v w") == Dict("i" => 5)
    @test histogram("c a a a a i") == Dict("a" => 4)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t") == Dict("t" => 27)
    @test histogram("    x      a b c d e f    a g   g h h h h  i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("c a a a  a i") == Dict("a" => 4)
    @test histogram("x y z x y z  x y z x y z x  y z x") == Dict("x" => 6)
    @test histogram("x y z x y z x y z x y z x y z x  z x y z x y z x z x y z x y z x y z x") == Dict("x" => 13)
    @test histogram("l    a b   k k l l t t t t t t u v w x y z") == Dict("t" => 6)
    @test histogram("     a b   k k l l t t t t t t u v w    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l  l l l m n o p q r r r s s s s s s s t t t t t   a a a a b b d d d d f f f g h i  x y z") == Dict("t" => 17)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t  t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 13)
    @test histogram("     a b    k k l l t t t t t t u v w x y z") == Dict("t" => 6)
    @test histogram("x y z x y z x y     a b   k k l l t t t t t t u v w x y z z x y z x y z x y z x y z x y z x") == Dict("x" => 10)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o  p q r r r  s s s s s s s t t x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t") == Dict("s" => 25)
    @test histogram("x y z x y z  x y z  x y z x y z z x y z    x      a b c d e f   a g g h h h h i j j j k k k k l l m n o p q r r r s s s s s s s t t t  t x  y z x") == Dict("x" => 9)
    @test histogram("l     a a a  a b b  f f g h i  ") == Dict("a" => 4)
    @test histogram("x y z x y z  x y z x y z x y z x y z e y z  ") == Dict("z" => 7, "y" => 7)
    @test histogram("c a a a  a i    a b        c d e f   a g g h  h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("x y z x y z x y z x y z z x y z x y z x y z x") == Dict("x" => 8, "z" => 8)
    @test histogram("l     f f f g h i  ") == Dict("f" => 3)
    @test histogram("x y z x y z  x y z x y z x y z z x y z x  y z  x") == Dict("x" => 8, "z" => 8)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o  p q r r r  s s s s s s s t t x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y y y y y z z z z z") == Dict("s" => 31)
    @test histogram("x y a a a o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z s s s s s t t t t t t t t u v w") == Dict("t" => 14)
    @test histogram("     a b   k k l l t t t t l     a a a a  b   b d d d d f f f g h i  t t u v w x y z") == Dict("t" => 6)
    @test histogram("x y z x y z x y     a b   k k l l t  t t t t t u v w x y z z x y z x y z x y z x y z x y z x") == Dict("x" => 10)
    @test histogram("x y z x y z   x y z o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y y y y y z z z z z y z e y z  x") == Dict("x" => 10, "z" => 10, "y" => 10)
    @test histogram("    o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a a a a b b d d d d f f f g  h i  ") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t    t t t t t u v  w") == Dict("t" => 8)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t     x  j    a b c d e f   a g  g h h h  j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w") == Dict("s" => 14)
    @test histogram("x y z x y z  x y z  x y z x y z z x    a b        c d e f   a g g h h h i j a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g m n o p q r r r s s s s s s s t t t t t t t t u v w x y z y z    x      a b c d e f   a g g h h h h i j j j k k k k l l m n o p q r r r s s s s s s s t t t  t x  y z x") == Dict("s" => 16)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t     x  j    a b c d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v  w") == Dict("s" => 14)
    @test histogram("l      a a a  a b b  f f g h i  ") == Dict("a" => 4)
    @test histogram("c a a a a b b d f g h i") == Dict("a" => 4)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r  s s s s s s s t t t t     a b   k k l l t t t t l     a a a a  b   b d d d d f f f g h i  t t u v w x y z t  t t t u v w x y z") == Dict("t" => 14)
    @test histogram("l     a a a  a b b  f f g  i  ") == Dict("a" => 4)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s    x      a b c d e f   a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t  t s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t") == Dict("s" => 20)
    @test histogram("    a b   k k l l  l l m n o p q r r r  s s s s s s s t t t t  t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t   a a     x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t   a a a a b b d d d d f f f g h i  a a b b d d d d f f f g h i  ") == Dict("s" => 26)
    @test histogram("l     a a a  a b b d  d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("x y z x y z  x y z  x y z x y z z x y z    x      a b c d e f   a g g h h h h  i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t  t x  y z x") == Dict("x" => 9)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p  q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t") == Dict("t" => 27)
    @test histogram("l     a a a  a b b  f f g  i ") == Dict("a" => 4)
    @test histogram("x y z x y z  x y z  x y z x y z z x    a b        c d e f   a g g h h x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t t u v w h h i j j j k k k k l l m n o p q r r r s s s s s s s t t t  t x  y z x") == Dict("s" => 14)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b        a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o  p q r r r  s s s s s s s t t x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t") == Dict("s" => 25)
    @test histogram("      a b   k k l l t t t t t t u v w x y z") == Dict("t" => 6)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i  j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t t t t t u v w") == Dict("t" => 7, "s" => 7)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s  s s s t t t t t") == Dict("t" => 27)
    @test histogram("    a b   k k l l l l m n o p q r r r  s s s s s s s  t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("l      a a a  a b b d  d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("    x      a b c d e f   a g g h h h h  i    a b        s s t t t t t t t t u v w x y z j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("t" => 13)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s     a a a a b b x y z x y z x y z l     a a a a b b d d d d f f f g h i  x y z x y z x y z x y z x y z x s s s s s s t t t   t t t t t u v  w") == Dict("a" => 11)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t  t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z t t t") == Dict("s" => 20)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i  j j j  j k s s s s t t t t t t t t u v w") == Dict("t" => 8)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b        a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o  p q r r r  s s s  s s s s s t t t t t") == Dict("t" => 19, "s" => 19)
    @test histogram("x y a a a b b d d d d f f f g h  i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t t u v w") == Dict("t" => 8)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t  t t t t u u u u u u v v v v v v w w w w w w x x x x  y  y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z t t t") == Dict("s" => 20)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s    x      a b c d e f   a g g h h h h i j j j k k k k l l l l     a a a  a b b  f f g  i  l m n o p q r r r s s s s s s s t t t  t s s s t t t t t t u u u u u u v v v l l l m n o p q  r r s s s s s s s t t t t t") == Dict("s" => 20)
    @test histogram("x y z x y z x  y z l     a a a a b b d d d d f f f g h i  x y z x y z x y z x y z x y z x") == Dict("x" => 9)
    @test histogram("x y a a a b b d d d d  f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t t u v  w") == Dict("t" => 8)
    @test histogram("x y z x y z  x  y z  x y z x y z z x y z x  y z x") == Dict("x" => 8, "z" => 8)
    @test histogram("    x      a b c d e f   a g g h h h h i    a b        c  d e f   a g g h h h i j j j k k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 14)
    @test histogram("l a b b d  d d d f f    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s  s s t t t t t   a a     x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t   a a a a b b d d d d f f f g h i  a a b b d d d d f f f g h i   f g h i") == Dict("s" => 26)
    @test histogram("x y z x y z  x y z x y z x y z x y z x y z x y z u x") == Dict("x" => 9)
    @test histogram("l     a a a  a b b      a b   k k l l t t t t t t u v w x y z f f g h i  ") == Dict("t" => 6)
    @test histogram("t    a b   k k l l  l l m n o p q r r r  s s s s s s s t t t t  t t t t u v w x y z") == Dict("t" => 9)
    @test histogram("x y a a a b b d d d d f f f g      a a a a b b x y z x y z x y z l     a a a a b b d d d d f f f g h i  x y z x y z x y z x y z x y z x i i i i  i j j j j k k k k l l l l m t t t u v w") == Dict("a" => 11)
    @test histogram("x y z x y z   x y z o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y y y y y    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b        a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o  p q r r r  s s s  s s s s s t t t t t z z z z z y z e y z  x") == Dict("t" => 25, "s" => 25)
    @test histogram("    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t  t t t u v  z") == Dict("t" => 8)
    @test histogram("x y z x y z x y     a b   k k l l t t t t t t u v w x y z z x y z x y z x y z x y z x y z     a b   k k l l t t t t t t u v w x y z") == Dict("t" => 12)
    @test histogram("    x t t t t t") == Dict("t" => 5)
    @test histogram("x y z x y z  x y z x y z  x  y z x") == Dict("x" => 6)
    @test histogram("x y z x y z  x y z x y z x y z z x y  z x  y z x") == Dict("x" => 8, "z" => 8)
    @test histogram("x y z x y z  x y z  x y z x y z z x    a b        c d e f   a g g h h h i j a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y  z a b c d e f g m n o p q r r r s s s s s s s t t t t t t t t u v w x y z y z    x      a b c d e f   a g g h h h h i j j j k k k k l l m n o p q r r r s s s s s s s t t t  t x  y z x") == Dict("s" => 16)
    @test histogram("    o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s  t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a a a a b    x t t t t t b d d d d f f f g  h i  ") == Dict("t" => 8)
    @test histogram("l     f f f g h  i  ") == Dict("f" => 3)
    @test histogram("x y z x y    x      a b c d e f    a g   g h h h h  i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t z  x y z x y z x y z z x y  z x  y z x") == Dict("x" => 9)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b        a b    s s s s s  t t t t t t t t u v w x y z k k  l l l l m n o  p q r r r  s s s  s s s s s t t t t t") == Dict("t" => 19, "s" => 19)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p  q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z v  v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t") == Dict("t" => 27)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w  z") == Dict("v" => 6, "o" => 6, "t" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("l     a a a  a b b      a b   k k l l t  t t t t t u v w x y z f f g h i  ") == Dict("t" => 6)
    @test histogram("   h x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s  s s s t t t t t") == Dict("t" => 27)
    @test histogram("x y z x") == Dict("x" => 2)
    @test histogram("o o u u u v v v v v v w w w w w w x x x  z z") == Dict("v" => 6, "w" => 6)
    @test histogram("x y z x y z x y z x y z x y z x  z x y z x y z x z x y z x y z x") == Dict("x" => 12)
    @test histogram("    a b        c d e f   a g g h h h i j a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q s t u v w x y z a b c d e f g m n o p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 10)
    @test histogram("x y z x y z   x y z o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y y y y y z z z z z y z e y z  x") == Dict("x" => 10, "z" => 10, "y" => 10)
    @test histogram("x z x") == Dict("x" => 2)
    @test histogram("x y z x y z  x y z x y z z e y z  x") == Dict("z" => 6)
    @test histogram("x y z x y z   x y z o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t v v v v v w w w w w w x x x x x x y y y y y z z z z z y z e y z  x") == Dict("x" => 10, "z" => 10, "y" => 10)
    @test histogram("s    a b   k k l l  l l m n o p q r r r  s s s s s s s t t t t  t t t t u v w x y z") == Dict("t" => 8, "s" => 8)
    @test histogram("x y y z x y z  x y z x y z x  y z z x y z x y z x") == Dict("x" => 8, "z" => 8, "y" => 8)
    @test histogram("x y z x y z  x y z  x y z x y z z x y z    x      a b c d e f   a g g h h h h i j j j k k  k k l l l t x  y z x") == Dict("x" => 9)
    @test histogram("l      a a a  a   f f g h i  ") == Dict("a" => 4)
    @test histogram("x y z x y z x y z x y z x y  z x y z     a a a a b b x y z x y z x y z l     a a a a b b d d d d f f f g h i  x y z x y z x y z x y z x y z x x y z x  y z x") == Dict("x" => 18)
    @test histogram("x y z x y z   x y z o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t v v v v v w w w w w w x x x x x x y y y y y z z z z z y  z e y z  x") == Dict("x" => 10, "z" => 10, "y" => 10)
    @test histogram("     a a a a c a a a  a i    a b        c d e f   a g g h  h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y z  h i  ") == Dict("a" => 10)
    @test histogram("p p q q q r r r s s s  y y z z") == Dict("r" => 3, "q" => 3, "s" => 3)
    @test histogram("x y z x y z  x y z x y z   x  y z x") == Dict("x" => 6)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o  p q r r r  s s s s s s s t t x x  y y z z z z z a g g h h h h i j j j k k k k l l  n o p q  r r s s s s s s s t t t t t") == Dict("s" => 25)
    @test histogram("c a    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t  t t t t u u u u u u v v v v v v w w w w w w x x x x  y  y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z t t t a a a b b d f g h i") == Dict("s" => 20)
    @test histogram("x y z x  x y z x  y z x") == Dict("x" => 5)
    @test histogram("     a b   k k l l t t t t l     a a a a  b   x y z x y z  x y z x y z x y z x y z e y z   u v w x y z") == Dict("z" => 8, "y" => 8)
    @test histogram(" x y z x y z x  y z l     a a a a b b d d d d f f f g h i  x y z x y z x y z x y z x y z x   x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b        a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o  p q r r r  s s s s s s s t t x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t") == Dict("s" => 25)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b        a b    s s s s  s  t t t t t t t t u v w x y z k k  l s t t t t t") == Dict("t" => 19)
    @test histogram("     a b   k k l l t t t t l     a a a a  b   x y z x y z   u v w x y z") == Dict("a" => 5)
    @test histogram("     a b   k k l l t t t t l     a a a a  b   x y z x y z  x y z x y z x y z x y  y z") == Dict("y" => 7)
    @test histogram("x y z x y z x y z x y z x y z x y z x y z x") == Dict("x" => 8)
    @test histogram("x y z x y z  x y z  x y z x y z z x y z    x      a b c d e f   a g g h h h h i j j j k k k k l l m n o p q r r r  s s s s s s s t t t  t x  y z x") == Dict("x" => 9)
    @test histogram("x y  z x y z  x y z x y z x y z z x y z x  y z  x") == Dict("x" => 8, "z" => 8)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t  t t t t u u u u u u v v v v v v w w w w w w x x x x  y  y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z t t ") == Dict("s" => 20)
    @test histogram("l     a a a  a b b      a b   k k l l t  t t t t t u v w     a b   k k l l t t t t l     a a a a  b   x y z x y z  x y z x y z x y z x y z e y z   u v w x y z x y z f f g h i  ") == Dict("t" => 10, "a" => 10)
    @test histogram("x y z x y z  x y z  x y z x y z z x y z    x      a b c d e f   a g g h h h h i j j j k k k k l l m n o p q r r r s t x  y z x") == Dict("x" => 9)
    @test histogram("x l     a a a a  b b d d d d f f f g h i  y z x y z  x y x y z x") == Dict("x" => 5)
    @test histogram("c a    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t  t t t t u u u u u u v v v v v v w w w w w w x x x x  y  y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t t t    a b   k k l l t t t t t t u v w x y z t u v w x y z t t t a a a b b d f g h i") == Dict("t" => 25)
    @test histogram("x y a a a o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z s s s s  u v w") == Dict("s" => 10)
    @test histogram("    a b   k    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b        a b    s s s s  s  t t t t t t t t u v w x y z k k  l s t t t t t k l l t t t t t t u v w x y z") == Dict("t" => 25)
    @test histogram("x y z x y z   x y z o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s y z  x") == Dict("o" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("o o u u u v v v v v v w w w w w") == Dict("v" => 6)
    @test histogram("p p  s t t t u u u v v w w x x y y z z") == Dict("t" => 3, "u" => 3)
    @test histogram("x y z x y z  x y z  x y z x y z z x    a b        c d e f   a g g h h h i j a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r  s t u v w x y z a b c d e f g m n o p q r r r s s s s s s s t t t t t t t t u v w x y z y z    x      a b c d e f   a g g h h h h i j j j k k k k l l m n o p q r r r s s s s s s s t t t  t x  y z x") == Dict("s" => 16)
    @test histogram("x y z x y z     a b   k k l l  l l m n o p q r r r  s s s s s s s t t t t  t t t t u v w x y z y z x y z x y z x y z x y z x y z u x") == Dict("x" => 9, "z" => 9, "y" => 9)
    @test histogram("    x      a b c d e f  o t u u u u u u v    a b        a b    s s s s  s  t t t t t t t t u v w x y z k k  l s t t t t t") == Dict("t" => 14)
    @test histogram("x y z x y z x y     a b   k k l l t  t t t t t u v w x y z z x y z x y z x y z x  y z x y z x") == Dict("x" => 10)
    @test histogram("l  f f f g h  i  ") == Dict("f" => 3)
    @test histogram("    a b   k k l l l l m n o p q r r r  s s s s s    x      a b c d e f   a g g h h h h  i    a b        s s t t t t t t t t u v w x y z j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v  z") == Dict("t" => 16)
    @test histogram("c a a a a b b d d d d f f  f g h i") == Dict("a" => 4, "d" => 4)
    @test histogram("x y a a a b b d d d d f f f g      a a a a b b x y z x y z x y z l     a a a a b b d d d d f f f g h i  x y z x y z x y z x y z x y z x i i i i  i j j j j k k k k l l l l m t t t u v w   a a a  a b b      a b   k k l l t  t t t t t u v w x y z f f g h i  ") == Dict("a" => 16)
    @test histogram("l     a a a  a b b  f f g x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w i  ") == Dict("t" => 8)
    @test histogram("x y z x y  z  x y z x y z   x  y z x") == Dict("x" => 6)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l  m n o p q  r r s s s s s s s t t t t t") == Dict("s" => 13)
    @test histogram("    a b   k k l l l l m n o p q r r r  s s s s s s s   v w x y z") == Dict("s" => 7)
    @test histogram("    a b        c d e f   a g g h h h i j a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g m n o    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v    a b        a b    s s s s  s  t t t t t t t t u v w x y z k k  l s t t t t t p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 29)
    @test histogram("    o o o  v w w w w w w x x   h i  ") == Dict("w" => 6)
    @test histogram("     x t t t t t") == Dict("t" => 5)
    @test histogram("    a b   k k l l  l l m n o   t t t t u v w x y z") == Dict("t" => 4, "l" => 4)
    @test histogram("o o o o o o p p p  r r r s s s s s s t t t t t t u u u u u u v v v v v z") == Dict("o" => 6, "t" => 6, "u" => 6, "s" => 6)
    @test histogram("    x      a b c d e f   a g g h h h h i    a b        c  d e f   a g g h h h i j j j k k k l l l l m n o p q r r r  s s s s s t t t t t") == Dict("h" => 7)
    @test histogram("    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v  w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t") == Dict("s" => 13)
    @test histogram("x y z x y z  x y z  x y z x y z z x    a b        c d e f   a g g h h h i j a b c d e f g h i j k l m n o p  q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y  z a b c d e f g m n o p q r r r s s s s s s s t t t t t t t t u v w x y z y z    x      a b c d e f   a g g h h h h i j j j k k k k l l m n o p q r r r s s s s s s s t t t  t x  y z x") == Dict("s" => 16)
    @test histogram("l     a a a  a b b  f f g  ") == Dict("a" => 4)
    @test histogram("x  x") == Dict("x" => 2)
    @test histogram("l     a a a  a b b      a b   k k l l t t t t t t u v w x y z f f g h i ") == Dict("t" => 6)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r u v w") == Dict("i" => 5)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o     a b    k k l l t t t t t t u v w x y z p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 14)
    @test histogram("    x      a b c d e f    a g g h h h h i    a b        c  d e f   a g g h h h i j j j k k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 14)
    @test histogram("    x    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v  w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q  r r s s s s s s s t t t t t      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t  t t t t u u u u u u v v v v v v w w w w w w x x x x  y  y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t    a b   k k l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z t t ") == Dict("s" => 33)
    @test histogram("x y z x y  z  x y z x y z   x  y z ") == Dict("x" => 5, "z" => 5, "y" => 5)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j k k k k l l l l m n o p q r r r s s s s s s s t t t   t t t t   x      a b c d e f   a  g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w") == Dict("s" => 14)
    @test histogram("c a  a a a b b d f g h i") == Dict("a" => 4)
    @test histogram("    x t t t t") == Dict("t" => 4)
    @test histogram("p p  s t t t u u u v    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t v w w x x y y z z") == Dict("t" => 14, "s" => 14)
    @test histogram("l     a a a  a  ") == Dict("a" => 4)
    @test histogram("     a b   k k l l t t t z") == Dict("t" => 3)
    @test histogram("p p  s t t t u u u v    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u q r r r s s s s s s s t t t t  t v w w x x y y z z") == Dict("t" => 14, "s" => 14)
    @test histogram("    a b     a b    s s s s s t t t t t t t t u v w x y z       a b    s s s s s t t t t t t t t u v w x y z k k  l l l l m n o p q r r r  s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 24)
    @test histogram("x y z x y z x x y z x y z x y z x y z  x") == Dict("x" => 8)
    @test histogram("l    p p q q q r r r s s s t t t u u u v v w w x x y y z z a a a a  b b d d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("t    a b   k k l l  l l m n o p q r r r   s s s s s s s t t t t  t t t t u v w x y z") == Dict("t" => 9)
    @test histogram("    x      a b c d e f   a g g h h h h i    a b        c  d e f   a g g h h h i j j j k k      a b   k k l l t t t t t t u v w    x      a b c d e f  o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x  y y z z z z z a g g h h h h i j j j k k k k l  l l l m n o p q r r r s s s s s s s t t t t t   a a a a b b d d d d f f f g h i  x y z o p q r r r  s s s s s t t t t t") == Dict("t" => 22)
    @test histogram("x y z x  z x y z x  y  x") == Dict("x" => 5)
    @test histogram("x y z x y z  x y z  x y z x y z z x y z    x      a b c d e f   a g  g h h h h  i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t  t x  y z x") == Dict("x" => 9)
    @test histogram("x y z x y z  x y z x y z x y  z z x y z x  y z  x") == Dict("x" => 8, "z" => 8)
    @test histogram("a a b b c c d d") == Dict("c" => 2, "b" => 2, "a" => 2, "d" => 2)
    @test histogram("x x x x x") == Dict("x" => 5)
    @test histogram("a b c d a b c d a b c d") == Dict("c" => 3, "b" => 3, "a" => 3, "d" => 3)
    @test histogram(" a") == Dict("a" => 1)
    @test histogram("ä å ö") == Dict("ä" => 1, "ö" => 1, "å" => 1)
    @test histogram("    x      a b c d e f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("    x      a b  c d e f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("l m m m m m m m m n n n n n n n n n n n n n n o o p p q  q r r s") == Dict("n" => 14)
    @test histogram("    x      a  b  c d e f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("c a a a a b b d d d d f f f  g h i") == Dict("a" => 4, "d" => 4)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y ") == Dict("t" => 8)
    @test histogram("      g h i  ") == Dict("g" => 1, "h" => 1, "i" => 1)
    @test histogram("o o o o o o p p p p p  p q  q q q q q r r r r r r s s s s s  y y y z z z z z") == Dict("o" => 6, "r" => 6, "q" => 6, "p" => 6)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n p q r r r s s s s s s s t t t t t t t t u v w") == Dict("t" => 8)
    @test histogram("c       g h i  ") == Dict("g" => 1, "c" => 1, "h" => 1, "i" => 1)
    @test histogram("  o t x      a b c d e f   a g g  t t") == Dict("t" => 3)
    @test histogram("     a a a a b b d d d d f f f g h    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   ") == Dict("t" => 8)
    @test histogram("    x b     a  b  c d e f   a g g  t t") == Dict("g" => 2, "t" => 2, "b" => 2, "a" => 2)
    @test histogram("l m  m m m m m m m n n n n n n n n n n n n n n o o p p q q r r s") == Dict("n" => 14)
    @test histogram("o o o o o o p p p p p p q q q q  q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y y y y y z z z z z") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "x" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t  t t t u v w x y z") == Dict("t" => 8)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n p q r r r s s s s s s s t t t t t    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t  t t t u v w x y z t t t u v w") == Dict("t" => 16)
    @test histogram("    x      a b c  d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("q") == Dict("q" => 1)
    @test histogram("  o t x  t    a b c d e f   a g g  t t") == Dict("t" => 4)
    @test histogram("     a a a a b b d d d d f f f g h i  e") == Dict("a" => 4, "d" => 4)
    @test histogram("o o o o o o p p p p p  p q  q q q q q r r r r r r s s s    x      a b c d e f   a g g  t t s s  y y y z z z z z") == Dict("o" => 6, "r" => 6, "q" => 6, "p" => 6)
    @test histogram("       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t") == Dict("a" => 6)
    @test histogram("l m m m m m m m m n n n n n n n n n n n n  n n o o p p q q r r s") == Dict("n" => 14)
    @test histogram("c a a a a b b d d d d  f f f g h i") == Dict("a" => 4, "d" => 4)
    @test histogram("    a b        c d e f   a g g  h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t  t t t u v w x y z") == Dict("t" => 8)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z") == Dict("o" => 6, "t" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("a b c d e f z b c d e f g") == Dict("f" => 2, "c" => 2, "e" => 2, "b" => 2, "d" => 2)
    @test histogram("l m m m m m m m m n n n n n n n n n n n n m n n o o p p q q r r s") == Dict("n" => 14)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u v w x y ") == Dict("t" => 8)
    @test histogram("    x b     a  b  c d e f   a t t") == Dict("t" => 2, "b" => 2, "a" => 2)
    @test histogram("    x      a  b  c d e  f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("    x      a  b  c d e f e  a g g  t t") == Dict("g" => 2, "e" => 2, "t" => 2, "a" => 2)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t t t t t u u z z z z z") == Dict("o" => 6, "t" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p  v w x y ") == Dict("l" => 4)
    @test histogram("o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z") == Dict("t" => 8)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t t t t t u  u z z z z z") == Dict("o" => 6, "t" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u v v v v v v w w w w w w x x x x x x y y y y y z z") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "x" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("  o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 10)
    @test histogram("    a b        c d e f   a g g h h h i  j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t u u z z z z z") == Dict("o" => 6, "t" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("    x      a b  c d e f   a g g  t") == Dict("g" => 2, "a" => 2)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t  t t t u  u z z z z z") == Dict("o" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("  o  t x      a  b c d e f   a g g  t t") == Dict("t" => 3)
    @test histogram("    x      a b  c d e f   a g g t") == Dict("g" => 2, "a" => 2)
    @test histogram("a b c d e f g    x b     a  b  c d e f   a t t h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g") == Dict("b" => 5, "a" => 5)
    @test histogram("l m m m m  p p q q r r s") == Dict("m" => 4)
    @test histogram("    a b        c d e f   a g g h h s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n p q r r r s s s s s s s t z t t t u v w") == Dict("s" => 7)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u  v w x y ") == Dict("t" => 8)
    @test histogram("    x      a b   c d e f   a g g t") == Dict("g" => 2, "a" => 2)
    @test histogram("    a b        c d e f   a g g  h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t      a a a a b b d d d d f f f g h    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z") == Dict("t" => 16)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j  j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t  t t t u v w x y z t t t u v w") == Dict("t" => 11)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t  u u z z z z z") == Dict("o" => 6, "t" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("l m m m m m m m m n n  n n n n n n n n n n n n o o p p q q r r s") == Dict("n" => 14)
    @test histogram("l m  m m  m m m m m n n n n n n n n n n n n n n o o p p q q r r s") == Dict("n" => 14)
    @test histogram("  g    g h i  ") == Dict("g" => 2)
    @test histogram("o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q  q r r r r r r s s s s s s t t t t t t u u z z z z z") == Dict("t" => 8)
    @test histogram("o o o o  b     a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z") == Dict("t" => 8)
    @test histogram("p p q q q r r r s s s t t t u u u v v  g    g h i   w w x x y y z z") == Dict("t" => 3, "r" => 3, "u" => 3, "q" => 3, "s" => 3)
    @test histogram("  o o o o       a a a a b b d d d d f f  f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 10)
    @test histogram("    a b        c d e  f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t  t t t u v w x y z") == Dict("t" => 8)
    @test histogram("    x      a b c d e f   a g g    t") == Dict("g" => 2, "a" => 2)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u  v v v v v v w w w w w w x x x x x x y y y y y z z") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "x" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("  o o o o        a a a a b b d d d d f f  f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 10)
    @test histogram("d      g h i  ") == Dict("d" => 1, "g" => 1, "h" => 1, "i" => 1)
    @test histogram("o o o o  b     a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z") == Dict("t" => 8)
    @test histogram("o o o o o o p  x x x x y y y y y z z") == Dict("o" => 6)
    @test histogram("p p q q r r r s s s t t t u u u v v w w x x y y z z") == Dict("t" => 3, "r" => 3, "u" => 3, "s" => 3)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r  z z") == Dict("o" => 6, "q" => 6, "p" => 6)
    @test histogram("a    x      a b c d e f   a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("p p q q r r r s s  s t t t u u u v v w w x x y y z z") == Dict("t" => 3, "r" => 3, "u" => 3, "s" => 3)
    @test histogram("l m m m m m m m m n n n n n n n n n n n n n n o o p p q o o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t u u z z z z z q r r s") == Dict("n" => 14)
    @test histogram("p p q q r r r s s s t t t u x x y y z z") == Dict("t" => 3, "r" => 3, "s" => 3)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n p q r r r s s s s s s s t t t t t    a b        c d e f   a g g h h h i j j j k k k l l l l m n o     a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y p q r r r s s s s s s s t t t t t  t t t u v w x y z t t t u v w") == Dict("t" => 24)
    @test histogram("    x b     a  b  c d e f    a g g  t t") == Dict("g" => 2, "t" => 2, "b" => 2, "a" => 2)
    @test histogram("l m m m m m m m m n n n n n n n n n n n n n n o o p p q o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t u u z z z z z q r r s") == Dict("n" => 14)
    @test histogram("  o o o o        a a a a b b d d d d f f  f g h i    x      a b c d e f   a z s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 8)
    @test histogram("    a b        c d e f   a g g h h h i j j j   o o o o       a a a a b b d d d d f f  f     a a a a b b d d d d f f f g h i  w x y z") == Dict("a" => 10)
    @test histogram("    x      a  b  c d e f  t") == Dict("f" => 1, "c" => 1, "e" => 1, "t" => 1, "x" => 1, "b" => 1, "a" => 1, "d" => 1)
    @test histogram("    x      a  b  c d e f   a  g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("    x      a  b c d  e f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("  o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z d e f   a t  t") == Dict("t" => 10)
    @test histogram("    x       a  b  c d e  f   a  t t") == Dict("t" => 2, "a" => 2)
    @test histogram("l m m m m m m m m n n n n n n n n n n n n  n n  o o o o        a a a a b b d d d d f f  f g h i    x      a b c d e f   a z s s t t t t t t u u z z z z z d e f   a t t r r s") == Dict("n" => 14)
    @test histogram("d      g h i d ") == Dict("d" => 2)
    @test histogram("    x      a b  c d e  f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t  t t t t u u z z z z z") == Dict("t" => 8)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u  z z z z z") == Dict("o" => 6, "t" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("o o o o o o p p  s s s s  y y y z z z z z") == Dict("o" => 6)
    @test histogram("    c d e f   a g g t") == Dict("g" => 2)
    @test histogram("    a b        c d e f   a g g  h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t      a a a a b b d d d d f f f g h    a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z") == Dict("t" => 16)
    @test histogram("    x b     a       a a a a b b d d d d f f f g h    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   b  c d e f   a g g  t t") == Dict("t" => 10)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r    a b  s s s s s s t t t t      a a a a b b d d d d f f f g h    a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z r r r s s s s s s t t t t t t u u u  z z z z z") == Dict("t" => 22)
    @test histogram("l m m m  o t x  t    a b c d e f   a g g  t t m m m m m n n n n n n n n n n n n n n o o p p q o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t u u z z z z z q r r s") == Dict("n" => 14)
    @test histogram("    x      a g g    t") == Dict("g" => 2)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r  r r s s s t t t t t t t t u v w x y ") == Dict("t" => 8)
    @test histogram("p p q q q r r r s s s t t t u u u v v w  w x x y y z z") == Dict("t" => 3, "r" => 3, "u" => 3, "q" => 3, "s" => 3)
    @test histogram("c a  a a a b b d d d d  f f f g h i") == Dict("a" => 4, "d" => 4)
    @test histogram("o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p  p p p p q q q q q  q r r r r r r s s s s s s t t t t t t u u z z z z z") == Dict("t" => 8)
    @test histogram("    a b        c d e f   a g g h h h s t t t t t t t t u v w x y ") == Dict("t" => 8)
    @test histogram("o o o o o o p p p p p p q q q q q  q r r r r r r s s s s s s t t t t t t u u u u u u  v v v v v v w w w w w w x x x x x x y y y y y z z") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "x" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("      a  b  c d e  f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("     c a  a a a b b d d d d  f f f g h i g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t t t t t u u u  z z z z z") == Dict("o" => 6, "t" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("    x       a b c d e f   a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("l m m m m  p  p q q r r s") == Dict("m" => 4)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u  v v v v x x x x y y y y y z z") == Dict("o" => 6, "t" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("     b c d  e f   a g g  t t") == Dict("g" => 2, "t" => 2)
    @test histogram("       a  b c d e f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("    a b        f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u v w x y ") == Dict("t" => 8)
    @test histogram("o o o o o o p p p p p p q q q q q  q r r r r r r s s s s s s t t t  z z") == Dict("o" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("    x    a b        c d e f   a g g h h h i j j j   o o o o       a a a a b b d d d d f f  f     a a a a b b d d d d f f f g h i  w x y z      a b c d e f   a g g  t t") == Dict("a" => 12)
    @test histogram("d       g h i d ") == Dict("d" => 2)
    @test histogram("    x      a g g t") == Dict("g" => 2)
    @test histogram("x y a a a b b d d d d f f f g h i i i  i i j j j  j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t  t t t u v w x y z t t t u v w") == Dict("t" => 11)
    @test histogram("     a a a a b b f f g h i  e") == Dict("a" => 4)
    @test histogram("    a b        c d e f   a g g  h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t  v    a a a a b b d d d d f f f g h    a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z") == Dict("t" => 16)
    @test histogram("    x  o o o o        a a a a b b d d d d f f  f g h i    x      a b c d e f   a z s s t t t t t t u u z z z z z d e f   a t t      a b c d e f   a g g  t t") == Dict("t" => 10)
    @test histogram("   g h i  ") == Dict("g" => 1, "h" => 1, "i" => 1)
    @test histogram("   f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("a    x      a b c d e f   a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s t t t t t") == Dict("t" => 5)
    @test histogram("    x        a  b  c d e  f   a  t t") == Dict("t" => 2, "a" => 2)
    @test histogram("     a a a a  e") == Dict("a" => 4)
    @test histogram("x y a a a b b d d  j j j j k k k k l l l l m n p q r r r s s s s s s s t t t t t t t t v w") == Dict("t" => 8)
    @test histogram(" p p q q r r r s s  s t t t u u u v v w w x x y y z z    a a a a b b d d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("     a a a a b b d d d d f f f g h o o o o o o p p p p p p q q q q q q r r r    a b  s s s s s s t t t t      a a a a b b d d d d f f f g h    a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z r r r s s s s s s t t t t t t u u u  z z z z z  ") == Dict("t" => 22)
    @test histogram("    x      a g g    x      a b c  d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("o o o o o o p p p p p p q r r  z z") == Dict("o" => 6, "p" => 6)
    @test histogram("    x      a b  c d e f g  a g g  t t") == Dict("g" => 3)
    @test histogram("     b c d  e f   a g g  g t t") == Dict("g" => 3)
    @test histogram("p p q q r r r s s  s t t t u u u v v w     a a a a b b f f g h i  e w x x y y z z") == Dict("a" => 4)
    @test histogram("a    x       a b c d e f   a g g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("x y a a a b b d d  j j j j k k k k l l l l m n p q r r r s s s s s s s t t t t t t t t v     a a a a b b d d d d f f f g h o o o o o o p p p p p p q q q q q q r r r    a b  s s s s s s t t t t      a a a a b b d d d d f f f g h    a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z r r r s s s s s s t t t t t t u u u  z z z z z   w") == Dict("t" => 30)
    @test histogram("c a a a a b b    x b     a       a a a a b b d d d d f f f g h    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   b  c d e f   a g g  t t d d d d f f f g h i") == Dict("a" => 12)
    @test histogram("    a b        c d e f   a g g  h h h i j j j k k k l   a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z") == Dict("t" => 12)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t  u u z z z z z") == Dict("o" => 6, "t" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("    a b        f   a g g h h    x      a g g t h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u v w x y ") == Dict("t" => 9)
    @test histogram("    a b        f   a g g h h    x      a g g t h i j j    x      a  b  c d e f   a g g  t t j k k k l l l l m n o p q r r r s s s t t t t t t t t u v w x y ") == Dict("t" => 11)
    @test histogram("c a a  a a b b d d d d f f f  g h i") == Dict("a" => 4, "d" => 4)
    @test histogram("       a a a a b b d d   t t") == Dict("a" => 4)
    @test histogram(" p p q q r r r s s  s t t t u u u v v w w x x y y z z     a a a a b b d d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("     a a a a b b d  d d d f f f g h i  e") == Dict("a" => 4, "d" => 4)
    @test histogram("       a     c a  a a a b b d d d d  f f f g h i g h i   f   a g g  t t") == Dict("a" => 6)
    @test histogram("a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v d e f g") == Dict("f" => 3, "g" => 3, "e" => 3, "d" => 3)
    @test histogram("o o o o o o p  x x     a a a a  e x x y y y y y z z") == Dict("o" => 6)
    @test histogram("       a a a a b b d d d d f f a g g  t t") == Dict("a" => 5)
    @test histogram("  o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s  s s s s t t t t t t u u z z z z z d e f   a t  t") == Dict("t" => 10)
    @test histogram("    x     x      a g g t     a b  c d e f   a g g t") == Dict("g" => 4)
    @test histogram("d       g h i  ") == Dict("d" => 1, "g" => 1, "h" => 1, "i" => 1)
    @test histogram("     a  a a a  e") == Dict("a" => 4)
    @test histogram("l m m m  o t x  t    a b c d e f   a g g  t t m m m m m n n n n n n n n n n n n n n o o p p q o o o o o p p p p p p q q q q q q r r r r r s s s s s   s t t t t t t u u z z z z z q r r s") == Dict("n" => 14)
    @test histogram("o o o o       a a a a b b d d d d f f f g h    x      a g g    t r r r s s s s s s t t t t t t u u z z z z z") == Dict("t" => 7)
    @test histogram("x y a a a b b d d  j j j j k k k k l l l l m n p q r r r s s s s s s s t t t t t t t t v w       a  b c d e f   a g g  t t") == Dict("t" => 10)
    @test histogram("o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r z z") == Dict("o" => 6, "q" => 6, "a" => 6, "p" => 6)
    @test histogram("  g    g h i      x     x      a b  c d e f   a g g  t t  c d e f   a g g  t t") == Dict("g" => 6)
    @test histogram("  o o o o        a a a a b b d d d d f f  f g h i    x      a b c d e f    a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 10)
    @test histogram("o o o o o o p p p p    x      a  b  c d e f  t p p q q q q q q r r r r r r s s s s s  s t t t t t p p q q r r r s s  s t t t u u u v v w w x x y y z z    a a a a b b d d d d f f f g h i   t u u u  z z z z z") == Dict("t" => 10)
    @test histogram("a b c d e f g    x b     a  b  c d e f   a t t h i j k l m n o p q r s t  u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g") == Dict("b" => 5, "a" => 5)
    @test histogram(" p p q   a a a  d d d f f f g h i  ") == Dict("f" => 3, "a" => 3, "d" => 3)
    @test histogram("c a a a a b b    x b     a       a a a a b b d d d d f f f g h    a b    r s s s s s s s t t t t t t t t u v w x y   b  c d e f   a g g  t t d d d d f f f g h i") == Dict("a" => 11)
    @test histogram("  o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s  s s s s t t t t t z z z d e  f   a t  t") == Dict("t" => 9)
    @test histogram("    x   o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t  t t t u  u z z z z z   a  b  c d e f e  a g g y t t") == Dict("t" => 7)
    @test histogram("    a b        c d t t t u v w x y ") == Dict("t" => 3)
    @test histogram("   a b        c d e f   a g g h h h s t t t t t t t t u v w x y ") == Dict("t" => 8)
    @test histogram("  o o o o         a a a a b b d d d d f f  f g h i    x      a b c d e f   a z s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 8)
    @test histogram("    n   a  b c d e f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("     a a a  a b b f f g h i  e") == Dict("a" => 4)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t t t t t u u z     a a a a b b d d d d f f f g h    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y    z z z z") == Dict("t" => 14)
    @test histogram("o o o o o o p p p p p p q q q q q q r    x b     a  b  c d e f   a t t r r r r r s s s s s  s t t t t t t u u u  z z z z z") == Dict("t" => 8)
    @test histogram("d      g h  i  ") == Dict("d" => 1, "g" => 1, "h" => 1, "i" => 1)
    @test histogram("d    x      a b c d e f   a g g  t t      g h  i  ") == Dict("g" => 3)
    @test histogram("o o o o o o p p p p    x      a  b  c d e f  t p p q q q q q q r r r r r r s s s s s  s t t t t t p p q q  r r r s s  s t t t u u u v v w w x x y y z z    a a a a b b d d d d f f f g h i   t u u u  z z z z z") == Dict("t" => 10)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t  u u z z z z") == Dict("o" => 6, "t" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("p p q q q  r r r s s s t t t u u u v v  g    g h i   w w x x y y z z") == Dict("t" => 3, "r" => 3, "u" => 3, "q" => 3, "s" => 3)
    @test histogram("o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f  a a g g  t t o o p p p p p p q q q q q q r r z z") == Dict("a" => 7)
    @test histogram("o o o o o o p  x x     a a a a  e x x y  y y y y z z") == Dict("o" => 6)
    @test histogram("  o o o o         a a a a b b d d d d f f  f g h i l m m m  o t x  t    a b c d e f   a g g  t t m m m m m n n n n n n n n n n n n n n o o p p q o o o o o p p p p p p q q q q q q r r r r r s s s s s   s t t t t t t u u z z z z z q r r s   x      a b c d e f   a z s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 18)
    @test histogram("o o o o       a a a a b b d d d d f f f g h i    x      a b c    x b     a       a a a a b b d d d d f f f g h    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   b  c d e f   a g g  t t d e f   a g g  t t o o p p p p p p q q q q q q r r z z") == Dict("a" => 14)
    @test histogram("    a b        c d e f   a g g  h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t      a b        c d t t t u v w x y  v w x y z") == Dict("t" => 7, "s" => 7)
    @test histogram("   o o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t  u u z z z z x      a b   c d e f   a g g t") == Dict("t" => 7)
    @test histogram("    x b     a       a a a a b b d d d d f f  t t t t t t t u v w x y   b  c d e f   a g g  t t") == Dict("t" => 9)
    @test histogram("    x      a b c j d e f   a g  g h h h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("    x      f   a g g    t") == Dict("g" => 2)
    @test histogram("l m m m m  p  p q q r s") == Dict("m" => 4)
    @test histogram("p p q q q r r r s s s t t t u u u v v  g    g h i    a b        f   a g g h h    x      a g g t h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u v w x y    w w x x y y z z") == Dict("t" => 12)
    @test histogram("  o o o o        a a a a b b d d d d f f  f g  h i    x      a b c d e f   z z d e f   a t t") == Dict("a" => 6, "d" => 6)
    @test histogram("x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n p q r r o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u  v v v v x x x x y y y y y z z z t t t u v w") == Dict("t" => 9)
    @test histogram("    x b     a  b  c d e f    a  g g  t t") == Dict("g" => 2, "t" => 2, "b" => 2, "a" => 2)
    @test histogram("    x       x b     a  b  c d e f   a t t   a  b  c d e  f   a g g  t t") == Dict("t" => 4, "a" => 4)
    @test histogram("p p q q q r r r s s s t t t u u u v v  g    g h i    w w x x y y z z") == Dict("t" => 3, "r" => 3, "u" => 3, "q" => 3, "s" => 3)
    @test histogram("l m m m      a a a a b b d d d d f f f g h o o o o o o p p p p p p q q q q q q r r r    a b  s s s s s s t t t t      a a a a b b d d d d f f f g h    a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z r r r s s s s s s t t t t t t u u u  z z z z z  m  p  p q q r s") == Dict("t" => 22)
    @test histogram("    n   a  b c d e f   a g g l") == Dict("g" => 2, "a" => 2)
    @test histogram("    x      a b c j d e f   a g  g h  h h i j j j k k k k l l l l m n o p q r r r s s s s s s s t t t t t") == Dict("s" => 7)
    @test histogram("l m m m m  p  p q q r s    x      a b  c d e f   a g g  t") == Dict("m" => 4)
    @test histogram("    x     a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g h i j k l m n o p q r s t u v d e f g a b c d e f   a g g  t t") == Dict("g" => 5)
    @test histogram("  a b  c d e f   a g g t") == Dict("g" => 2, "a" => 2)
    @test histogram("l m m m  o t x  t    a b c d e f   a g g  t t m m m m m n n n n n n n n n n n n n n o o p p q o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t u u    a b        f   a g g h h    x      a g g t h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u v w x y  z z z z z q r r s") == Dict("t" => 19)
    @test histogram("d        g h i d ") == Dict("d" => 2)
    @test histogram("l m n n n o o p p q o o o o o o p p p p q q q r r r r r s s s s s  s t t t t t t u u z z z z z q r r s") == Dict("o" => 8)
    @test histogram("    x b     a  b  c d e f    a  g  t t") == Dict("t" => 2, "b" => 2, "a" => 2)
    @test histogram("    a b        c d e f   a g g h h h i  j j j k k  k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y z") == Dict("t" => 8)
    @test histogram("    x b     a       a a a a b b d d d d f f f g h    a b        c  d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   b  c d e f   a g g  t t") == Dict("t" => 10)
    @test histogram("    a b        c d e f   a g g  h h h i j j j k k k l   a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v  w x y   t  t t t u v w x y z") == Dict("t" => 12)
    @test histogram("    x      a b   c d e f     o o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t  u u z z z z x      a b   c d e f   a g g t a g g t") == Dict("t" => 8)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f  a a g g  t t o o p p p p p p q q q q q q r r z z s s t t t t t  t t t u v w x y z") == Dict("t" => 10)
    @test histogram("p  p q q r r r s s s t t t u u u v v w w x x y y z z") == Dict("t" => 3, "r" => 3, "u" => 3, "s" => 3)
    @test histogram("     a a a a b b d d d d f f f g h    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v ") == Dict("t" => 8)
    @test histogram("    x      a b  c d e f g  a g g   t") == Dict("g" => 3)
    @test histogram("l m m m m m m m m n n n n n n n n n  n n n  n n o o p p q q r r s") == Dict("n" => 14)
    @test histogram("d      g   ") == Dict("g" => 1, "d" => 1)
    @test histogram("d       g h i  d ") == Dict("d" => 2)
    @test histogram("x y a a a b  b d d  j j j j k k k k l l l l m n p q r r r s s s s s s s t t t t t t t t v w") == Dict("t" => 8)
    @test histogram("      g h i  t") == Dict("g" => 1, "t" => 1, "h" => 1, "i" => 1)
    @test histogram("p p q q r r r s s s t t t u x x y y  z z") == Dict("t" => 3, "r" => 3, "s" => 3)
    @test histogram("    a b        c d e  f   a g g h h h i j j j k k k l l l l m n  o p q r r r s s s s s s s t t t t t  t t t u v w x y z") == Dict("t" => 8)
    @test histogram("    n   a  b c d e f   a g g   t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s     x b     a       a a a a b b d d d d f f f g h    a b        c  d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   b  c d e f   a g g  t t t t t t t u u z z z z z") == Dict("t" => 17)
    @test histogram("  x y z x y z x y z x y z x y z x y z x y z x y z x  x      a b  c d e f   a g g t") == Dict("x" => 10)
    @test histogram("     a a a a b b    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u v w x y  f f g h i  e") == Dict("t" => 8)
    @test histogram("    x   o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t  t t t u  u z z z z z   a  b  c d e f e  a g g y t ") == Dict("o" => 6, "t" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("  o o o o        a a a a b b d d d d f f  f g  h i    x      a b c d e f   a z s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 8)
    @test histogram("a b c d e f z b c d e  f g") == Dict("f" => 2, "c" => 2, "e" => 2, "b" => 2, "d" => 2)
    @test histogram("    a b        c d e  f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u  v w x y ") == Dict("t" => 8)
    @test histogram("  o o o o        a a a a b b d d d d f f  d e f    a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 10)
    @test histogram("    a b         c d e f   a g g h h h i j j j k k k l l l l m n o p  v w x y ") == Dict("l" => 4)
    @test histogram("o o o o       a a a a b b d d d d f f f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r z  z") == Dict("o" => 6, "q" => 6, "a" => 6, "p" => 6)
    @test histogram("l m m m  o t x  t    a b c d e f   a g g  t t m m m m m n n n n n n n n n n n n n n o o p p q o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t u u   w x y  z z z z z q r r s") == Dict("n" => 14)
    @test histogram("    x      a g g    x      a b c  d e f   a g  g h h h h i j j j k k k k l s s s s  t t") == Dict("g" => 4, "k" => 4, "h" => 4, "s" => 4)
    @test histogram("   o o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t  u u z z z z x      a b   c d e f   a g  g t") == Dict("t" => 7)
    @test histogram("x y a a a b b d d  j j j j k k k k l l l l m q r r r s s s s s s s t t t t t t t t v w       a  b c d e f   a g g  t t") == Dict("t" => 10)
    @test histogram("    a b         c d e  f   a g g h h h i j j j k k k l l l l m n  o p q r r r s  t u v w x y z") == Dict("l" => 4)
    @test histogram("     b  c d  e f   a g g  g t t") == Dict("g" => 3)
    @test histogram("    a b        c d e f   a g g h h h i  j j j k k k l l l l m n o p q r r r  s s s s s s  y z") == Dict("s" => 6)
    @test histogram(" p p q q r r r s s  s t t t u u u v v w w x x y y z z     a a a a b b d d d d f f f g h i    a b        f   a g g h h    x      a g g t h i j j    x      a  b  c d e f   a g g  t t j k k k l l l l m n o p q r r r s s s t t t t t t t t u v w x y   ") == Dict("t" => 14)
    @test histogram("      a      a b         c d e f   a g g h h h i j j j k k k l l l l m n o p  v w x y b  c d e  f   a g g  t t") == Dict("g" => 4, "l" => 4, "a" => 4)
    @test histogram("     a a a a b b d d d d f f f g h o o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t u u z z z z z   a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v ") == Dict("t" => 14)
    @test histogram("    x b     a  b  c d e f    a   g g  t t") == Dict("g" => 2, "t" => 2, "b" => 2, "a" => 2)
    @test histogram("      g h i   ") == Dict("g" => 1, "h" => 1, "i" => 1)
    @test histogram("  a  b c d e f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("a b c d e f g    x b   i j k l m n o p q r s t  u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g") == Dict("b" => 4)
    @test histogram("  o o o o       a a a a b b d d d d f f  f g h i    x      a b c d e f   a g g  t t o o p p p p p    x      a g g    x      a b c  d e f   a g  g h h h h i j j j k k k k l s s s s  t t a t t") == Dict("a" => 10)
    @test histogram("l m m m m m m m m n n n n n n n n n n n n n n o o p p q p p p q q q q q q r r r r r s s s s s  s t t t t t t u u z z z z z q r r s") == Dict("n" => 14)
    @test histogram(" d   x       x b     a  b  c d e f    a t t   a  b  c d e  f   a g g  t t") == Dict("t" => 4, "a" => 4)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r s s s s s  s t t t t t t  u u z z z z x y a a a b b d d d d f f f g h i i i i i j j j j k k k k l l l l m n p q r r r s s s s s s s t t t t t    a b        c d e f   a g g h h  j k k k l l l l m n o p q r r r s s s s s s s t t t t t  t t t u v w x y z t t t u v w") == Dict("t" => 22)
    @test histogram("c a a a a b b    x b      a       a a a a b b d d d d f f f g h    a b    r s s s s s s s t t t t t t t t u v w x y   b  c d e f   a g g  t t d d d d f f f g h i") == Dict("a" => 11)
    @test histogram("l m m m m  p m p q q r s") == Dict("m" => 5)
    @test histogram("    x       a  b     t t t t t u  v w x y    a g g    t") == Dict("t" => 6)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s o o o o o o p p p p p p q q q q q q r r r  z z s t t t t t t u  u z z z z z") == Dict("o" => 12, "q" => 12, "p" => 12)
    @test histogram("d      g h i d l") == Dict("d" => 2)
    @test histogram("    a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t    a b        c d e f   a g g  h h h i j j j k k k l   a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z t t t t t u v w x y z") == Dict("t" => 20)
    @test histogram("    x      a b   c d e f   a g g  t") == Dict("g" => 2, "a" => 2)
    @test histogram("    a b        c d e  f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u  v w x y h") == Dict("t" => 8)
    @test histogram("   g     a a a a b b d d d d f f f g h i  e h i  ") == Dict("a" => 4, "d" => 4)
    @test histogram("      x   a   a  b  c d e f  t") == Dict("a" => 2)
    @test histogram("    t") == Dict("t" => 1)
    @test histogram("o o o o o o  p p p p p p q q q q q q r r r r r r s s s s s  s t t t t t t u u  u  z z z z z") == Dict("o" => 6, "t" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("   o t x      a  b c d e f  t t") == Dict("t" => 3)
    @test histogram("a b c d e f g    x b  d       g h i  d  c d e f   a t t h i j k l m n o p q r s t  u v w x y z a b c d e f g h i j k l m n o p q r s t u v w x y z a b c d e f g") == Dict("d" => 6)
    @test histogram("l m m m  o t x  t    a b c d e f   a g g  t t m m m m m n n n n n n n n n n n n n n o o p p q o o o o o p p p p p p q q q q q q r r r r r s s s s s   s t t t t t t u u z z z z z q r  s") == Dict("n" => 14)
    @test histogram("  o o o o       a a a a b b d d d d f f  f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z d e f   a t t     a a a") == Dict("t" => 10, "a" => 10)
    @test histogram("s    a b         c d e f   a g g h h h i j j j k k k l l l l m n o p  v w x y ") == Dict("l" => 4)
    @test histogram("  o o o o        a a a a b b d d d d f f  d e f    a g g  t t  o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 10)
    @test histogram("l m m m m  p  p q o o o o o o p p p p p p q q q q q  q r r r r r r s s s s s s t t t  z z r s") == Dict("p" => 8)
    @test histogram("x y a a a b  b d d  j j j j k k k k l    x b     a  b  c d e f    a g g  t t l l l m n p q r r r s s s s s s s t t t t t t t t v w") == Dict("t" => 10)
    @test histogram("l m m m m m m m m n o q q r r s") == Dict("m" => 8)
    @test histogram("    x     x  g    a g g t     a b  c d e f   a g g t") == Dict("g" => 5)
    @test histogram("  o o o o   d     a a a a b b d d d d f f  f g h i    x      a b c d e f   a g g  t t o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u z z z z z d e f   a t t") == Dict("t" => 10)
    @test histogram("     x      a b  c d e  f   a g g  t t") == Dict("g" => 2, "t" => 2, "a" => 2)
    @test histogram("  x y z x y z x y z x y z x y z x y z x y z x y z x  x      a b  c d e f   a  g g t") == Dict("x" => 10)
    @test histogram("o o o o o o p p p p p p q q q q q q r    x b     a  b  c d e f   a t t u  z z z z z") == Dict("o" => 6, "q" => 6, "p" => 6)
    @test histogram("   e c d e f   a g g t    a b        c d e f   a g g  h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t      a a a a b b d d d d f f f g h    a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z") == Dict("t" => 17)
    @test histogram("    x      e c d e f   a g g t    a b        c d e f   a g g  h h h i j j j k k k l l l l m n o p q r r r s s s s s s s t t t t      a a a a b b d d d d f f f g h    a b        c d j j j k k k l l l l m n o p q r r r s s s s s s s t t t t t t t t u v w x y   t  t t t u v w x y z   a b c d e f   a g g    t") == Dict("t" => 18)
    @test histogram("  o t x  t    a  b c d e f   a g g  t t") == Dict("t" => 4)
    @test histogram("a b c d e  f g h i j k l m n o p q r s t u v w x y z a b c d e f g    x      a b  c d e f   a g g  t h i j k l m n o p q r s t u v w x y z a b c d e f g") == Dict("g" => 5, "a" => 5)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s  s t t t t t  t u u u  z z z z z") == Dict("o" => 6, "t" => 6, "r" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("o o o o o o p p p p p p q q q q q  q r s s s s t t t  z z") == Dict("o" => 6, "q" => 6, "p" => 6)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s o o o o o o p p p p p p q q q q q q r r r  z z s t t t z z z z") == Dict("o" => 12, "q" => 12, "p" => 12)
    @test histogram("o o o o o o p p p p p p q q q q q q r r r r r r s s s s s s t t t t t t u u u u u u  v v v v v v w w w w w w x x x x x x y y y y  z z") == Dict("v" => 6, "w" => 6, "o" => 6, "t" => 6, "x" => 6, "r" => 6, "u" => 6, "q" => 6, "s" => 6, "p" => 6)
    @test histogram("    a b        c d e f   a g g  h h h i j j j k k k l l l l m n o p q  r r r s s s s s s s t t t t t  t t t u v w x y z") == Dict("t" => 8)
    @test histogram("d       g h i  d") == Dict("d" => 2)
    @test histogram("      g h") == Dict("g" => 1, "h" => 1)
    @test histogram("    x      a b  c d e f     a b        c d e f   a g g h h h i j j j k k k l l l l m n o p q r r r s s s t t t t t t t t u  v w x y g  a g g   t") == Dict("t" => 9)
    @test histogram("x y a a a b  b d d  j j j j k k k k l    x b     a  b  c d e f    a g g o o o o o o p p p p p  p q  q q q q q r r r r r r s s s    x      a b c d e f   a g g  t t s s  y y y z z z z z t t l l l m n p q r r r s s s s s s s t t t t t t t t v w") == Dict("t" => 12, "s" => 12)
    @test histogram(" p p q q r  r r s s  s t t t u u u v v w w x x y y z z    a a a a b b d d d d f f f g h i  ") == Dict("a" => 4, "d" => 4)
end
