@testitem "138_is_equal_to_sum_even_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "138_is_equal_to_sum_even.jl"))
    @test is_equal_to_sum_even(20) == true
    @test is_equal_to_sum_even(22) == true
    @test is_equal_to_sum_even(24) == true
    @test is_equal_to_sum_even(30) == true
    @test is_equal_to_sum_even(36) == true
    @test is_equal_to_sum_even(40) == true
    @test is_equal_to_sum_even(42) == true
    @test is_equal_to_sum_even(48) == true
    @test is_equal_to_sum_even(50) == true
    @test is_equal_to_sum_even(28) == true
    @test is_equal_to_sum_even(41) == false
    @test is_equal_to_sum_even(21) == false
    @test is_equal_to_sum_even(39) == false
    @test is_equal_to_sum_even(23) == false
    @test is_equal_to_sum_even(25) == false
    @test is_equal_to_sum_even(35) == false
    @test is_equal_to_sum_even(19) == false
    @test is_equal_to_sum_even(49) == false
    @test is_equal_to_sum_even(51) == false
    @test is_equal_to_sum_even(52) == true
    @test is_equal_to_sum_even(47) == false
    @test is_equal_to_sum_even(37) == false
    @test is_equal_to_sum_even(34) == true
    @test is_equal_to_sum_even(-79) == false
    @test is_equal_to_sum_even(29) == false
    @test is_equal_to_sum_even(53) == false
    @test is_equal_to_sum_even(57) == false
    @test is_equal_to_sum_even(56) == true
    @test is_equal_to_sum_even(-2) == false
    @test is_equal_to_sum_even(0) == false
    @test is_equal_to_sum_even(2) == false
    @test is_equal_to_sum_even(5) == false
    @test is_equal_to_sum_even(9) == false
    @test is_equal_to_sum_even(15) == false
    @test is_equal_to_sum_even(27) == false
    @test is_equal_to_sum_even(100) == true
    @test is_equal_to_sum_even(105) == false
    @test is_equal_to_sum_even(8) == true
    @test is_equal_to_sum_even(-3) == false
    @test is_equal_to_sum_even(76) == true
    @test is_equal_to_sum_even(101) == false
    @test is_equal_to_sum_even(98) == true
    @test is_equal_to_sum_even(3) == false
    @test is_equal_to_sum_even(97) == false
    @test is_equal_to_sum_even(7) == false
    @test is_equal_to_sum_even(1) == false
    @test is_equal_to_sum_even(6) == false
    @test is_equal_to_sum_even(99) == false
    @test is_equal_to_sum_even(-50) == false
    @test is_equal_to_sum_even(102) == true
    @test is_equal_to_sum_even(-71) == false
    @test is_equal_to_sum_even(-1) == false
    @test is_equal_to_sum_even(-72) == false
    @test is_equal_to_sum_even(-27) == false
    @test is_equal_to_sum_even(104) == true
    @test is_equal_to_sum_even(96) == true
    @test is_equal_to_sum_even(10) == true
    @test is_equal_to_sum_even(-26) == false
    @test is_equal_to_sum_even(-39) == false
    @test is_equal_to_sum_even(-55) == false
    @test is_equal_to_sum_even(-29) == false
    @test is_equal_to_sum_even(-66) == false
    @test is_equal_to_sum_even(11) == false
    @test is_equal_to_sum_even(14) == true
    @test is_equal_to_sum_even(-42) == false
    @test is_equal_to_sum_even(4) == false
    @test is_equal_to_sum_even(77) == false
    @test is_equal_to_sum_even(-38) == false
    @test is_equal_to_sum_even(-30) == false
    @test is_equal_to_sum_even(-25) == false
    @test is_equal_to_sum_even(-34) == false
    @test is_equal_to_sum_even(78) == true
    @test is_equal_to_sum_even(103) == false
    @test is_equal_to_sum_even(-65) == false
    @test is_equal_to_sum_even(-49) == false
    @test is_equal_to_sum_even(-18) == false
    @test is_equal_to_sum_even(-7) == false
    @test is_equal_to_sum_even(75) == false
    @test is_equal_to_sum_even(-37) == false
    @test is_equal_to_sum_even(-73) == false
    @test is_equal_to_sum_even(-51) == false
    @test is_equal_to_sum_even(106) == true
    @test is_equal_to_sum_even(64) == true
    @test is_equal_to_sum_even(-52) == false
    @test is_equal_to_sum_even(-8) == false
    @test is_equal_to_sum_even(-6) == false
    @test is_equal_to_sum_even(-10) == false
    @test is_equal_to_sum_even(16) == true
    @test is_equal_to_sum_even(12) == true
    @test is_equal_to_sum_even(107) == false
    @test is_equal_to_sum_even(26) == true
    @test is_equal_to_sum_even(18) == true
    @test is_equal_to_sum_even(108) == true
    @test is_equal_to_sum_even(109) == false
    @test is_equal_to_sum_even(17) == false
    @test is_equal_to_sum_even(110) == true
    @test is_equal_to_sum_even(31) == false
    @test is_equal_to_sum_even(-98) == false
    @test is_equal_to_sum_even(-87) == false
    @test is_equal_to_sum_even(-5) == false
    @test is_equal_to_sum_even(-40) == false
    @test is_equal_to_sum_even(-88) == false
    @test is_equal_to_sum_even(-4) == false
    @test is_equal_to_sum_even(55) == false
    @test is_equal_to_sum_even(-86) == false
    @test is_equal_to_sum_even(13) == false
    @test is_equal_to_sum_even(32) == true
    @test is_equal_to_sum_even(54) == true
    @test is_equal_to_sum_even(-68) == false
    @test is_equal_to_sum_even(-90) == false
    @test is_equal_to_sum_even(-91) == false
    @test is_equal_to_sum_even(-78) == false
    @test is_equal_to_sum_even(-80) == false
end
