@testitem "140_fix_spaces_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "140_fix_spaces.jl"))
    @test fix_spaces("Hello,   world!") == "Hello,-world!"
    @test fix_spaces("happy 123") == "happy_123"
    @test fix_spaces("Hey    there!") == "Hey-there!"
    @test fix_spaces("  spaces  every  where  ") == "-spaces-every-where-"
    @test fix_spaces("NoSpacesHere") == "NoSpacesHere"
    @test fix_spaces("This is  a  test") == "This_is-a-test"
    @test fix_spaces("Testing     1  2   3") == "Testing-1-2-3"
    @test fix_spaces("Hello World") == "Hello_World"
    @test fix_spaces("Hello   World") == "Hello-World"
    @test fix_spaces("   Hello World") == "-Hello_World"
    @test fix_spaces("This is  a  tesst") == "This_is-a-tesst"
    @test fix_spaces("This is  a  tes") == "This_is-a-tes"
    @test fix_spaces("This is  a This is  a  tes test") == "This_is-a_This_is-a-tes_test"
    @test fix_spaces("Hello r  World") == "Hello_r-World"
    @test fix_spaces("This is  a Hello r  World tsesst") == "This_is-a_Hello_r-World_tsesst"
    @test fix_spaces("This is  a This is  a  tes test  spaceNoSpacesHere ") == "This_is-a_This_is-a-tes_test-spaceNoSpacesHere_"
    @test fix_spaces("Thish is  a  tesst") == "Thish_is-a-tesst"
    @test fix_spaces("HelloNoSpacesHere,   world!") == "HelloNoSpacesHere,-world!"
    @test fix_spaces("Hey   e there!") == "Hey-e_there!"
    @test fix_spaces("  spaces  eveThis is  a This This is  a This is  a  tes test  spaceNoSpacesHere is  a  tes testry  where  ") == "-spaces-eveThis_is-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHere_is-a-tes_testry-where-"
    @test fix_spaces("happy 123  spaces  every  where  ") == "happy_123-spaces-every-where-"
    @test fix_spaces("  spaces  eveThis is  a This  This is  a This ishappy 123  a  tes test  spaceNoSpacesHere is  a  tes testry  where  ") == "-spaces-eveThis_is-a_This-This_is-a_This_ishappy_123-a-tes_test-spaceNoSpacesHere_is-a-tes_testry-where-"
    @test fix_spaces("Hello r  Word") == "Hello_r-Word"
    @test fix_spaces("This is  a sst") == "This_is-a_sst"
    @test fix_spaces("  spaces  eveThis is  a This This is  a This is  a  tes test  spaceNoSpacesHello r  WorldHere is  a  tes testry  where  ") == "-spaces-eveThis_is-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHello_r-WorldHere_is-a-tes_testry-where-"
    @test fix_spaces("  spaces  eveery  where  ") == "-spaces-eveery-where-"
    @test fix_spaces("happy1233") == "happy1233"
    @test fix_spaces("  spaces  eveThis is  a This This is  a This is  a  tes test  spaceNoSpacesHeNoSpacesHerello r  WorldHere is  a  tes testry  where  ") == "-spaces-eveThis_is-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHeNoSpacesHerello_r-WorldHere_is-a-tes_testry-where-"
    @test fix_spaces("happy 123 p spaces  every  where  ") == "happy_123_p_spaces-every-where-"
    @test fix_spaces("  spaces  eveThis is  a This This is  a This is  tes testry  where  ") == "-spaces-eveThis_is-a_This_This_is-a_This_is-tes_testry-where-"
    @test fix_spaces("Thish isThis is  a Hello r  World tsTesting     1  2   3 a  This is  a ssttesst") == "Thish_isThis_is-a_Hello_r-World_tsTesting-1-2-3_a-This_is-a_ssttesst"
    @test fix_spaces("Helleo World") == "Helleo_World"
    @test fix_spaces("happyw 123 p spacees  every  where  ") == "happyw_123_p_spacees-every-where-"
    @test fix_spaces("Thish is  a  tesHey    there!st") == "Thish_is-a-tesHey-there!st"
    @test fix_spaces("happyw 123 p spacees  This is  a sstevery  wher  ") == "happyw_123_p_spacees-This_is-a_sstevery-wher-"
    @test fix_spaces("  spaces  every  w here  ") == "-spaces-every-w_here-"
    @test fix_spaces("Th is is  a This is  a  tes test") == "Th_is_is-a_This_is-a-tes_test"
    @test fix_spaces("This is   a This is  a  tes test  spacoeNoSpacesHere ") == "This_is-a_This_is-a-tes_test-spacoeNoSpacesHere_"
    @test fix_spaces("  spaces  eveThis is  a This  This is  a This is happy 123  a  tes test  spaceNoSpacesHere is  a  tes testry  where  ") == "-spaces-eveThis_is-a_This-This_is-a_This_is_happy_123-a-tes_test-spaceNoSpacesHere_is-a-tes_testry-where-"
    @test fix_spaces("Thihappyw 123 p spacees  This is  a sstevery  wher  s is  a Hello r  Woreld tsesst") == "Thihappyw_123_p_spacees-This_is-a_sstevery-wher-s_is-a_Hello_r-Woreld_tsesst"
    @test fix_spaces("  spaces  eveThis is  a This This is  a This is  a  tes test  spaceNoSpacesHtry  where  ") == "-spaces-eveThis_is-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHtry-where-"
    @test fix_spaces("happThis is  a  tessty") == "happThis_is-a-tessty"
    @test fix_spaces("This is  a T  spaces  eveThisTh is is  a This is  a  tes test is  a This  This is  a This ishappy 123  a  tes test  spaceNoSpacesHere is  a  tes testry  where  his is  a  tes test") == "This_is-a_T-spaces-eveThisTh_is_is-a_This_is-a-tes_test_is-a_This-This_is-a_This_ishappy_123-a-tes_test-spaceNoSpacesHere_is-a-tes_testry-where-his_is-a-tes_test"
    @test fix_spaces("This is Thish is  a  tesHey    there!st a This is  a  tes test  spaceNoSpacesHere ") == "This_is_Thish_is-a-tesHey-there!st_a_This_is-a-tes_test-spaceNoSpacesHere_"
    @test fix_spaces("Thish is  asst") == "Thish_is-asst"
    @test fix_spaces("  spaces  everThis is  a This is  a  tes testy  where  ") == "-spaces-everThis_is-a_This_is-a-tes_testy-where-"
    @test fix_spaces("This is  This is  a T  spaces  eveThisTh is is  a This is  a  tes test is  a This  This is  a This ishappy 123  a  tes test  spaceNoSpacesHere is  a  tes testry  where  his is  a  tes testa  tes") == "This_is-This_is-a_T-spaces-eveThisTh_is_is-a_This_is-a-tes_test_is-a_This-This_is-a_This_ishappy_123-a-tes_test-spaceNoSpacesHere_is-a-tes_testry-where-his_is-a-tes_testa-tes"
    @test fix_spaces("  spaces  eveThis tis  a This This is  a This is  a  tes test  spaceNoSpacesHere is  a  tes testry  where  ") == "-spaces-eveThis_tis-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHere_is-a-tes_testry-where-"
    @test fix_spaces("  spaces  eveThis is  a This This is  a This is  a  tes test  spaceNoSpacesHello r   WorldHere is  a  tes testry  where  ") == "-spaces-eveThis_is-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHello_r-WorldHere_is-a-tes_testry-where-"
    @test fix_spaces(" happyw 123 p spacees  every  where  ") == "_happyw_123_p_spacees-every-where-"
    @test fix_spaces("happyw 123 p spacees  This is  a sstevery  whser  ") == "happyw_123_p_spacees-This_is-a_sstevery-whser-"
    @test fix_spaces("  spaces  eveThis is  a This This is  a This is  a This is  a  tes test  spaceNoSpacesHere This is  tes testry  where  ") == "-spaces-eveThis_is-a_This_This_is-a_This_is-a_This_is-a-tes_test-spaceNoSpacesHere_This_is-tes_testry-where-"
    @test fix_spaces("haappy1233") == "haappy1233"
    @test fix_spaces("Testing   Hey   e there!  1  2   3") == "Testing-Hey-e_there!-1-2-3"
    @test fix_spaces("Hello r   spaces  eveThis is  a This This is  a This is  a  tes test  spaceNoSpacesHello r   WorldHere is  a  tes testry  where   Word") == "Hello_r-spaces-eveThis_is-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHello_r-WorldHere_is-a-tes_testry-where-Word"
    @test fix_spaces("Testing   s  1  2   3") == "Testing-s-1-2-3"
    @test fix_spaces("Th is is  a This is  a  tes teHello,   world!st") == "Th_is_is-a_This_is-a-tes_teHello,-world!st"
    @test fix_spaces("") == ""
    @test fix_spaces("ThThis is  a Hello r  World tsesstis is  a sst") == "ThThis_is-a_Hello_r-World_tsesstis_is-a_sst"
    @test fix_spaces("This is  This is  a T  spaces  eveThisThh is is  a This is  a  tes test is  a This  This is  a This ishappy 123  a  tes test  spaceNoSpacesHere is  a  tes testry  where  his is  a  tes testa  tes") == "This_is-This_is-a_T-spaces-eveThisThh_is_is-a_This_is-a-tes_test_is-a_This-This_is-a_This_ishappy_123-a-tes_test-spaceNoSpacesHere_is-a-tes_testry-where-his_is-a-tes_testa-tes"
    @test fix_spaces("This is  sst") == "This_is-sst"
    @test fix_spaces("NoSere") == "NoSere"
    @test fix_spaces("ThTthis is  a Hello r  World tsesstis is  a sst") == "ThTthis_is-a_Hello_r-World_tsesstis_is-a_sst"
    @test fix_spaces("This is  a This is  a  tes test  spaceNioSpacesHere ") == "This_is-a_This_is-a-tes_test-spaceNioSpacesHere_"
    @test fix_spaces("This iis  a sst") == "This_iis-a_sst"
    @test fix_spaces("Thihappyw 123 p spacees  Thi s is  a sstevery  wher  s is  a Hello r  Woreld tsesst") == "Thihappyw_123_p_spacees-Thi_s_is-a_sstevery-wher-s_is-a_Hello_r-Woreld_tsesst"
    @test fix_spaces("This is  a This istest") == "This_is-a_This_istest"
    @test fix_spaces("Helleo Worldhappyw 123 p spacThis iis  a sstees  every  where  ") == "Helleo_Worldhappyw_123_p_spacThis_iis-a_sstees-every-where-"
    @test fix_spaces("Hello r  Worlld") == "Hello_r-Worlld"
    @test fix_spaces("Testing This is  a sst  e there!  1  2   3") == "Testing_This_is-a_sst-e_there!-1-2-3"
    @test fix_spaces("ere!st") == "ere!st"
    @test fix_spaces("This is  a This is  a  t  spaces  eveThis is  a This This is  a This is  a This is  a  tes test  spaceNoSpacesHere This is  tes testry  where  est") == "This_is-a_This_is-a-t-spaces-eveThis_is-a_This_This_is-a_This_is-a_This_is-a-tes_test-spaceNoSpacesHere_This_is-tes_testry-where-est"
    @test fix_spaces("Hhappy 123 p spaces  every  where  ello r  Word") == "Hhappy_123_p_spaces-every-where-ello_r-Word"
    @test fix_spaces("He  spaces  eveThis is  a This This is  a This is  a This is  a  tes test  spaceNoSpacesHere This is  tes testry  where  llo,   wod!") == "He-spaces-eveThis_is-a_This_This_is-a_This_is-a_This_is-a-tes_test-spaceNoSpacesHere_This_is-tes_testry-where-llo,-wod!"
    @test fix_spaces("rCMrcvK") == "rCMrcvK"
    @test fix_spaces("This sis  a  tes") == "This_sis-a-tes"
    @test fix_spaces("  spaces  eveThis is  a This This is  a This is  a This is  a  tes test  spaceNoSpacesHere This is  tes testr  where  ") == "-spaces-eveThis_is-a_This_This_is-a_This_is-a_This_is-a-tes_test-spaceNoSpacesHere_This_is-tes_testr-where-"
    @test fix_spaces("  spaThis  This is  a This ishappy 123  a  tes test  spaceNoSpacesHere is  a  tes testry  where  ") == "-spaThis-This_is-a_This_ishappy_123-a-tes_test-spaceNoSpacesHere_is-a-tes_testry-where-"
    @test fix_spaces("Th is is  a This is  aHey   e there!  tes test") == "Th_is_is-a_This_is-aHey-e_there!-tes_test"
    @test fix_spaces("Thish Helleo Worldhappyw 123 p spacThis iis  a sstees  every  where  is  a  tesHey    there!st") == "Thish_Helleo_Worldhappyw_123_p_spacThis_iis-a_sstees-every-where-is-a-tesHey-there!st"
    @test fix_spaces("Hello r   spaces  eveThis is  a This This is  a This is  a  tes test  spaceNoSpacesHellThish isThis is  a Hello r  World tsTesting     1  2   3 a  This is  a ssttessto r   WorldHere is  a  tes testry  where   Word") == "Hello_r-spaces-eveThis_is-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHellThish_isThis_is-a_Hello_r-World_tsTesting-1-2-3_a-This_is-a_ssttessto_r-WorldHere_is-a-tes_testry-where-Word"
    @test fix_spaces("Th is is  a This is  a  tes teTHello,   world!st") == "Th_is_is-a_This_is-a-tes_teTHello,-world!st"
    @test fix_spaces("ThTthis sis  a Hello r ") == "ThTthis_sis-a_Hello_r_"
    @test fix_spaces("Thihappyw 123 p  spaces  eveThis is  a This This is  a This is  a  tes test  spaceNoSpacesHtry  where   spacees  This is  a sstevery  wher  s is  a Hello r  Woreld tsesst") == "Thihappyw_123_p-spaces-eveThis_is-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHtry-where-spacees-This_is-a_sstevery-wher-s_is-a_Hello_r-Woreld_tsesst"
    @test fix_spaces("  spaces  everThis is  a This is  a  tes tThish Helleo Worldhappyw 123 p spacThis iis  a sstees  every  where  is  a  tesHey    there!stesty where  ") == "-spaces-everThis_is-a_This_is-a-tes_tThish_Helleo_Worldhappyw_123_p_spacThis_iis-a_sstees-every-where-is-a-tesHey-there!stesty_where-"
    @test fix_spaces("NoSer") == "NoSer"
    @test fix_spaces("Thish Helleo Worldhappyw 123 p spacThis iis  a sstees  every  where  ishappy 123 p spaces  every  where    a  tesHey    there!st") == "Thish_Helleo_Worldhappyw_123_p_spacThis_iis-a_sstees-every-where-ishappy_123_p_spaces-every-where-a-tesHey-there!st"
    @test fix_spaces("Hello rr  Word") == "Hello_rr-Word"
    @test fix_spaces("Hello r   spaces  eveThis is  a This This iThis is  Hey   e there!a This is  a  tes tests  a This is  a  tes test  spaceNoSpacesHellThish isThis is  a Hello r  World tsTesting     1  2   3 a  This is  a ssttessto r   WorldHere is  a  tes testry  where   Word") == "Hello_r-spaces-eveThis_is-a_This_This_iThis_is-Hey-e_there!a_This_is-a-tes_tests-a_This_is-a-tes_test-spaceNoSpacesHellThish_isThis_is-a_Hello_r-World_tsTesting-1-2-3_a-This_is-a_ssttessto_r-WorldHere_is-a-tes_testry-where-Word"
    @test fix_spaces("HeThis is  a This istestlWlo World") == "HeThis_is-a_This_istestlWlo_World"
    @test fix_spaces("NoS") == "NoS"
    @test fix_spaces("Testing   Hey   e there!  1  2 This is  a This is  a  tes test  spaceNoSpacesHere   3") == "Testing-Hey-e_there!-1-2_This_is-a_This_is-a-tes_test-spaceNoSpacesHere-3"
    @test fix_spaces("  spaces  eveThis is  a This This is  a This is  a This is  a  tes test  spaceNoSpacesHere This is  tes testry  where ") == "-spaces-eveThis_is-a_This_This_is-a_This_is-a_This_is-a-tes_test-spaceNoSpacesHere_This_is-tes_testry-where_"
    @test fix_spaces("NSooSerre") == "NSooSerre"
    @test fix_spaces("Hello r   spaces  eveThis is  a This This iThis is  Hey   e there!a This is  a  tes tests  a This is  a  tes test  spaceNoSpacesHellThish isThis is  a Hello r  World happy 12Testing   s  1  2   33  spaces  every  where  tsTesting     1  2   3 a  This is  a ssttessto r   WorldHere is  a  tes testry  where   Word") == "Hello_r-spaces-eveThis_is-a_This_This_iThis_is-Hey-e_there!a_This_is-a-tes_tests-a_This_is-a-tes_test-spaceNoSpacesHellThish_isThis_is-a_Hello_r-World_happy_12Testing-s-1-2-33-spaces-every-where-tsTesting-1-2-3_a-This_is-a_ssttessto_r-WorldHere_is-a-tes_testry-where-Word"
    @test fix_spaces("This is  This is  a T  spaces  eveThisTh is is  a This is  a  tes test is  a This  This is  a This ishappy 123  a  tes test  spaceNoSpacesHere is  a  tesHello r   spaces  eveThis is  a This This iThis is  Hey   e there!a This is  a  tes tests  a This is  a  tes test  spaceNoSpacesHellThish isThis is  a Hello r  World tsTesting     1  2   3 a  This is  a ssttessto r   WorldHere is  a  tes testry  where   Word testry  where  his is  a  tes testa  tes") == "This_is-This_is-a_T-spaces-eveThisTh_is_is-a_This_is-a-tes_test_is-a_This-This_is-a_This_ishappy_123-a-tes_test-spaceNoSpacesHere_is-a-tesHello_r-spaces-eveThis_is-a_This_This_iThis_is-Hey-e_there!a_This_is-a-tes_tests-a_This_is-a-tes_test-spaceNoSpacesHellThish_isThis_is-a_Hello_r-World_tsTesting-1-2-3_a-This_is-a_ssttessto_r-WorldHere_is-a-tes_testry-where-Word_testry-where-his_is-a-tes_testa-tes"
    @test fix_spaces("Helo r  Worlld") == "Helo_r-Worlld"
    @test fix_spaces(" happyw 123 p spacees  every  whhere  ") == "_happyw_123_p_spacees-every-whhere-"
    @test fix_spaces("HTh is is  a This is  a  tehappy 123  spaces  everyHello r   spaces  eveThis is  a This This is  a This is  a  tes test  spaceNoSpacesHello r   WorldHere is  a  tes testry  where   Wordo,   world!stey   !") == "HTh_is_is-a_This_is-a-tehappy_123-spaces-everyHello_r-spaces-eveThis_is-a_This_This_is-a_This_is-a-tes_test-spaceNoSpacesHello_r-WorldHere_is-a-tes_testry-where-Wordo,-world!stey-!"
    @test fix_spaces("Thish isThis is  a Hello r  World tsTesting 3 a  This is  a ssttesst") == "Thish_isThis_is-a_Hello_r-World_tsTesting_3_a-This_is-a_ssttesst"
    @test fix_spaces("   Exa 1 2 2\nmple\tExample   3") == "-Exa_1_2_2\nmple\tExample-3"
    @test fix_spaces("   A-B-*_--C   ") == "-A-B-*_--C-"
    @test fix_spaces("---a-a-a---b-b-b-c-c-c---") == "---a-a-a---b-b-b-c-c-c---"
    @test fix_spaces("Big gaps    between words    in this sentence") == "Big_gaps-between_words-in_this_sentence"
    @test fix_spaces("          ") == "-"
    @test fix_spaces("    ") == "-"
    @test fix_spaces("         ") == "-"
    @test fix_spaces("Exa 1 2 2 mple") == "Exa_1_2_2_mple"
    @test fix_spaces("Example  1") == "Example-1"
    @test fix_spaces("    Example   2") == "-Example-2"
    @test fix_spaces("    Example   2    Example   2") == "-Example-2-Example-2"
    @test fix_spaces("  E  Example   2") == "-E-Example-2"
    @test fix_spaces("this") == "this"
    @test fix_spaces("----a-a-a---b-b-b-c-c-c---") == "----a-a-a---b-b-b-c-c-c---"
    @test fix_spaces("     ") == "-"
    @test fix_spaces("his") == "his"
    @test fix_spaces("words") == "words"
    @test fix_spaces("ExampleEthisxa3e  1") == "ExampleEthisxa3e-1"
    @test fix_spaces("Exx1") == "Exx1"
    @test fix_spaces("  his   ") == "-his-"
    @test fix_spaces("gaps") == "gaps"
    @test fix_spaces("ggaps") == "ggaps"
    @test fix_spaces("ggga") == "ggga"
    @test fix_spaces("  his    ") == "-his-"
    @test fix_spaces("   Ex     2\nmple\tExample   3") == "-Ex-2\nmple\tExample-3"
    @test fix_spaces("---a-a-a---b-b-b-c-c-c---     ") == "---a-a-a---b-b-b-c-c-c----"
    @test fix_spaces("Example    Example   2    Example   2  1") == "Example-Example-2-Example-2-1"
    @test fix_spaces("A-B-*_--C") == "A-B-*_--C"
    @test fix_spaces("EEx") == "EEx"
    @test fix_spaces("Exa") == "Exa"
    @test fix_spaces("   A-B-*_-E-C   Ex     2\nmple\tExample   3") == "-A-B-*_-E-C-Ex-2\nmple\tExample-3"
    @test fix_spaces("---a-ac-c---      ") == "---a-ac-c----"
    @test fix_spaces("ExampleEthisxa3e") == "ExampleEthisxa3e"
    @test fix_spaces("  his     ") == "-his-"
    @test fix_spaces("2") == "2"
    @test fix_spaces("in") == "in"
    @test fix_spaces("  E  Egapsxample   2") == "-E-Egapsxample-2"
    @test fix_spaces("  ExampleE  Expample   2") == "-ExampleE-Expample-2"
    @test fix_spaces("   Exa 1 2 Exa2\nmple\tExample   3") == "-Exa_1_2_Exa2\nmple\tExample-3"
    @test fix_spaces("  E  Ega psxample   2---sa-ac-c---") == "-E-Ega_psxample-2---sa-ac-c---"
    @test fix_spaces("ExampleeEthisxa3e") == "ExampleeEthisxa3e"
    @test fix_spaces("zPb") == "zPb"
    @test fix_spaces("ExampleEt  E  Ega psxample   2---sa-ac-c---hisxa3e") == "ExampleEt-E-Ega_psxample-2---sa-ac-c---hisxa3e"
    @test fix_spaces("hsis") == "hsis"
    @test fix_spaces("  E  Example  2") == "-E-Example-2"
    @test fix_spaces("   A-B-*_-E-C   Ex     2\nmple\tExample  m 3") == "-A-B-*_-E-C-Ex-2\nmple\tExample-m_3"
    @test fix_spaces("EExample  1Ex") == "EExample-1Ex"
    @test fix_spaces("  his    EExample") == "-his-EExample"
    @test fix_spaces("psxample") == "psxample"
    @test fix_spaces("ExampleEthitsxa3e") == "ExampleEthitsxa3e"
    @test fix_spaces("1") == "1"
    @test fix_spaces("----a-aa-a---b-b-b-c-c-c---") == "----a-aa-a---b-b-b-c-c-c---"
    @test fix_spaces("---a--a-a---b-b-b-c-c-c---") == "---a--a-a---b-b-b-c-c-c---"
    @test fix_spaces("hsExampleEthisxa3es") == "hsExampleEthisxa3es"
    @test fix_spaces("Expample") == "Expample"
    @test fix_spaces("his  ExampleE  Expample   2") == "his-ExampleE-Expample-2"
    @test fix_spaces("sentence") == "sentence"
    @test fix_spaces("Exa2") == "Exa2"
    @test fix_spaces("   Exa 1 2 2\nmple\tExample   2---sa-ac-c---") == "-Exa_1_2_2\nmple\tExample-2---sa-ac-c---"
    @test fix_spaces("   Exa 1 2 Exa2\nmple\tEx3") == "-Exa_1_2_Exa2\nmple\tEx3"
    @test fix_spaces("   ") == "-"
    @test fix_spaces("   Exa 1 2 2\nmple\tExample 3") == "-Exa_1_2_2\nmple\tExample_3"
    @test fix_spaces("ExampleEtEhisxa3e  1") == "ExampleEtEhisxa3e-1"
    @test fix_spaces("    E  Ega psxample   2---sa-ac-c--- A-B-*_-E-C   Ex     2\nmple\tExample   3") == "-E-Ega_psxample-2---sa-ac-c---_A-B-*_-E-C-Ex-2\nmple\tExample-3"
    @test fix_spaces("hsE2xampleEthisxa3es") == "hsE2xampleEthisxa3es"
    @test fix_spaces("Example    Example   2    Examle   2  1") == "Example-Example-2-Examle-2-1"
    @test fix_spaces("  hExampleEthitssxa3eis    EExample") == "-hExampleEthitssxa3eis-EExample"
    @test fix_spaces("          EEx") == "-EEx"
    @test fix_spaces("thits") == "thits"
    @test fix_spaces("----a-a-a---b-b-b-c-c-c---ExampleEtEhisxa3e") == "----a-a-a---b-b-b-c-c-c---ExampleEtEhisxa3e"
    @test fix_spaces("---a-ac-c---") == "---a-ac-c---"
    @test fix_spaces("      psxample EEx") == "-psxample_EEx"
    @test fix_spaces("E") == "E"
    @test fix_spaces("    his    A-B-*_--C   ") == "-his-A-B-*_--C-"
    @test fix_spaces("TnYIFZqaAz") == "TnYIFZqaAz"
    @test fix_spaces("between") == "between"
    @test fix_spaces("zEx3Pbb") == "zEx3Pbb"
    @test fix_spaces("gs") == "gs"
    @test fix_spaces("      ") == "-"
    @test fix_spaces("---a--a-a---b-b-b-c-c--c---") == "---a--a-a---b-b-b-c-c--c---"
    @test fix_spaces("   Ex     2\nmple\tExample   3i") == "-Ex-2\nmple\tExample-3i"
    @test fix_spaces("   Exa mpleample   3") == "-Exa_mpleample-3"
    @test fix_spaces("  hismpleample     ") == "-hismpleample-"
    @test fix_spaces("thitts") == "thitts"
    @test fix_spaces("ExampleEt  E  Ega psxample   2---sa-ac-c---h-isxa3e") == "ExampleEt-E-Ega_psxample-2---sa-ac-c---h-isxa3e"
    @test fix_spaces("  ") == "-"
    @test fix_spaces("  his  hismpleample ") == "-his-hismpleample_"
    @test fix_spaces("---a--a-a---b-b-b--c-c-c---") == "---a--a-a---b-b-b--c-c-c---"
    @test fix_spaces("word") == "word"
    @test fix_spaces("thi  E   Exa 1 2 2\nmple\tExample 3  2") == "thi-E-Exa_1_2_2\nmple\tExample_3-2"
    @test fix_spaces("---a-ac-   A-B-*_-E-C   Ex     2\nmple\tExample   3c---") == "---a-ac--A-B-*_-E-C-Ex-2\nmple\tExample-3c---"
    @test fix_spaces("Exampl   eEthishiExamlesxa3e  1") == "Exampl-eEthishiExamlesxa3e-1"
    @test fix_spaces(" Exx1   ") == "_Exx1-"
    @test fix_spaces("ggap") == "ggap"
    @test fix_spaces("  hExampleEthitssxa3eis    EExampple") == "-hExampleEthitssxa3eis-EExampple"
    @test fix_spaces("E  x3") == "E-x3"
    @test fix_spaces("  his  h  hismpleample     ismpleample ") == "-his-h-hismpleample-ismpleample_"
    @test fix_spaces("R") == "R"
    @test fix_spaces("   Ex     2\nmple\tExample   ExampleEi") == "-Ex-2\nmple\tExample-ExampleEi"
    @test fix_spaces("ExampleEtEhisxa3e  1gggaps") == "ExampleEtEhisxa3e-1gggaps"
    @test fix_spaces("hsExmampleEthisxa3es") == "hsExmampleEthisxa3es"
    @test fix_spaces("ExaxmpleEthitsxa3e") == "ExaxmpleEthitsxa3e"
    @test fix_spaces("   Exa 1ExampleEtEhisxe  1gggaps   3") == "-Exa_1ExampleEtEhisxe-1gggaps-3"
    @test fix_spaces("gss") == "gss"
    @test fix_spaces("           ") == "-"
    @test fix_spaces("hhis") == "hhis"
    @test fix_spaces("gggga") == "gggga"
    @test fix_spaces("Exampl") == "Exampl"
    @test fix_spaces("ExampleEtExampl   eEthishiExamlesxa3e  1") == "ExampleEtExampl-eEthishiExamlesxa3e-1"
    @test fix_spaces("    his    A-B-*           _--C   ") == "-his-A-B-*-_--C-"
    @test fix_spaces("ExampleEtExampl") == "ExampleEtExampl"
    @test fix_spaces("hhi---a-a-a---b-b-b-c-c-c---s") == "hhi---a-a-a---b-b-b-c-c-c---s"
    @test fix_spaces("---a--a-a---b-b-b-c-c--") == "---a--a-a---b-b-b-c-c--"
    @test fix_spaces("Big gaps    between words    i2---sa-ac-c---n this sentence") == "Big_gaps-between_words-i2---sa-ac-c---n_this_sentence"
    @test fix_spaces("Exam    Example   2pleEtEhisxa3e  1") == "Exam-Example-2pleEtEhisxa3e-1"
    @test fix_spaces("2---sa-ac-c---") == "2---sa-ac-c---"
    @test fix_spaces("11") == "11"
    @test fix_spaces("dwords") == "dwords"
    @test fix_spaces("betweeExampleEthisxa3e  1n") == "betweeExampleEthisxa3e-1n"
    @test fix_spaces("hhi---a-a-a---  E  Ega psxample   2---sa-ac-c---b-b-b-c-c-c---s") == "hhi---a-a-a----E-Ega_psxample-2---sa-ac-c---b-b-b-c-c-c---s"
    @test fix_spaces("E  E2---sa-ac-c---b-b-b-c-c-c---sx") == "E-E2---sa-ac-c---b-b-b-c-c-c---sx"
    @test fix_spaces("hhi-    his    A-B-*           _--C   --a-a-a---") == "hhi--his-A-B-*-_--C---a-a-a---"
    @test fix_spaces("hsExampthitsleEthisxa3es") == "hsExampthitsleEthisxa3es"
    @test fix_spaces("ismpleample") == "ismpleample"
    @test fix_spaces("hhi---a-a-a---") == "hhi---a-a-a---"
    @test fix_spaces("hsExampleEtheisxa3es") == "hsExampleEtheisxa3es"
    @test fix_spaces("   Exa mp  leample   3") == "-Exa_mp-leample-3"
    @test fix_spaces("ExampleEt  E  Ega psxample   2---sa-ac-c---h-isx") == "ExampleEt-E-Ega_psxample-2---sa-ac-c---h-isx"
    @test fix_spaces("EleEatEhisxa3e  1") == "EleEatEhisxa3e-1"
    @test fix_spaces("  hs") == "-hs"
    @test fix_spaces("---a--a-a---b-      psxample EExb-b-c-c--") == "---a--a-a---b--psxample_EExb-b-c-c--"
    @test fix_spaces("s") == "s"
    @test fix_spaces("ExExamplampleEthisxa3e") == "ExExamplampleEthisxa3e"
    @test fix_spaces("   his  h  hismpleample     ismpleample ") == "-his-h-hismpleample-ismpleample_"
    @test fix_spaces("---a-ac-ca---") == "---a-ac-ca---"
    @test fix_spaces("  hExa  hsmpleEthitssxa3eis    EExample") == "-hExa-hsmpleEthitssxa3eis-EExample"
    @test fix_spaces("A-B-*_  hExampleEthitssxa3eis    EExampple-E-C") == "A-B-*_-hExampleEthitssxa3eis-EExampple-E-C"
    @test fix_spaces("ExExamplampleEt  E  Example   2hisxggggaa3e") == "ExExamplampleEt-E-Example-2hisxggggaa3e"
    @test fix_spaces("---a-a-a----c---     ") == "---a-a-a----c----"
    @test fix_spaces("Exampitsxa3e") == "Exampitsxa3e"
    @test fix_spaces("----a-a-a---b-hsmpleEthitssxa3eisb-b-c-c-c---") == "----a-a-a---b-hsmpleEthitssxa3eisb-b-c-c-c---"
    @test fix_spaces("thtis") == "thtis"
    @test fix_spaces("---a-ac-c-thitts-") == "---a-ac-c-thitts-"
    @test fix_spaces("hihis") == "hihis"
    @test fix_spaces("---a-a  ExampleE  Expample   2  3c---") == "---a-a-ExampleE-Expample-2-3c---"
    @test fix_spaces("wo") == "wo"
    @test fix_spaces("Exaword") == "Exaword"
    @test fix_spaces("thhisis") == "thhisis"
    @test fix_spaces("hhi-") == "hhi-"
    @test fix_spaces("    his     A-B-*_-E-C   Ex     2\nmple\tExample  m 3thitssxa3eis    EExample-C   ") == "-his-A-B-*_-E-C-Ex-2\nmple\tExample-m_3thitssxa3eis-EExample-C-"
    @test fix_spaces("zPPb") == "zPPb"
    @test fix_spaces("EExampple-E-C") == "EExampple-E-C"
    @test fix_spaces("E  c-c-c---sx") == "E-c-c-c---sx"
    @test fix_spaces("i2---sa-ac-c---n") == "i2---sa-ac-c---n"
    @test fix_spaces("    his   Exx1   --C   ") == "-his-Exx1---C-"
    @test fix_spaces("ExampleEtEhisxa3e") == "ExampleEtEhisxa3e"
    @test fix_spaces("hhi---a-a-a---c-c---s") == "hhi---a-a-a---c-c---s"
    @test fix_spaces("Exmpl") == "Exmpl"
    @test fix_spaces("3") == "3"
    @test fix_spaces("Rhsis") == "Rhsis"
    @test fix_spaces("sjRboRkSy") == "sjRboRkSy"
    @test fix_spaces("2---sa-ac-c---h-isx") == "2---sa-ac-c---h-isx"
    @test fix_spaces("mples") == "mples"
    @test fix_spaces("Exa3c---leEtEhisxa3e") == "Exa3c---leEtEhisxa3e"
    @test fix_spaces("hsE    his   Exx1   --C   xmampleEthisxa3es") == "hsE-his-Exx1---C-xmampleEthisxa3es"
    @test fix_spaces("i2---sa-a-c-c---n") == "i2---sa-a-c-c---n"
    @test fix_spaces("   Exa 1 2 Exa2\nmpl") == "-Exa_1_2_Exa2\nmpl"
    @test fix_spaces("thi") == "thi"
    @test fix_spaces("hsExampleExthisxa3es") == "hsExampleExthisxa3es"
    @test fix_spaces("hh") == "hh"
    @test fix_spaces("hhhis") == "hhhis"
    @test fix_spaces("hsE    his   Exx1   --C   xmampleEthis   Exa mp  leample   3xa3es") == "hsE-his-Exx1---C-xmampleEthis-Exa_mp-leample-3xa3es"
    @test fix_spaces("EExample-C") == "EExample-C"
    @test fix_spaces("2  2   ") == "2-2-"
    @test fix_spaces("2---sa-ac-c---h-isxa3e") == "2---sa-ac-c---h-isxa3e"
    @test fix_spaces("3xa3es") == "3xa3es"
    @test fix_spaces("his  ExampleE  E3thitssxa3eisxpample   2") == "his-ExampleE-E3thitssxa3eisxpample-2"
    @test fix_spaces("Exam") == "Exam"
    @test fix_spaces("---a-ac-   A-B-*m_-E-C   Ex     2\nmple\tExample   3c---") == "---a-ac--A-B-*m_-E-C-Ex-2\nmple\tExample-3c---"
    @test fix_spaces("2----sa-ac-c---") == "2----sa-ac-c---"
    @test fix_spaces("thhiss") == "thhiss"
    @test fix_spaces("wodhhi-s") == "wodhhi-s"
    @test fix_spaces("FoFlZTDagW") == "FoFlZTDagW"
    @test fix_spaces("   Exa 1 2 2\nmple\tExBig gaps    between words    i2---sa-ac-c---n this sentenceample 3") == "-Exa_1_2_2\nmple\tExBig_gaps-between_words-i2---sa-ac-c---n_this_sentenceample_3"
    @test fix_spaces("ExampleEtExpampl") == "ExampleEtExpampl"
    @test fix_spaces("   Exa 1 2 2\nmple\tExa---a-ac-mple 3") == "-Exa_1_2_2\nmple\tExa---a-ac-mple_3"
    @test fix_spaces("   Exa mp  leample   3Example  1") == "-Exa_mp-leample-3Example-1"
    @test fix_spaces("Exa---a-ac-mple") == "Exa---a-ac-mple"
    @test fix_spaces("Example") == "Example"
    @test fix_spaces("sgs") == "sgs"
    @test fix_spaces("---a-thits-a-a---b-b-") == "---a-thits-a-a---b-b-"
    @test fix_spaces("xmampleEthisxa3es2  ExaxmpleEthitsxa3e3c---") == "xmampleEthisxa3es2-ExaxmpleEthitsxa3e3c---"
    @test fix_spaces("his  ExampleE     2") == "his-ExampleE-2"
    @test fix_spaces("  ---a-ac-c---       Example   2") == "----a-ac-c----Example-2"
    @test fix_spaces("3c---") == "3c---"
    @test fix_spaces("ggagp") == "ggagp"
    @test fix_spaces("EFoFlZTDagWE") == "EFoFlZTDagWE"
    @test fix_spaces("hs") == "hs"
    @test fix_spaces(" p ExaxmpleE  Expample   2") == "_p_ExaxmpleE-Expample-2"
    @test fix_spaces("111") == "111"
    @test fix_spaces("ggagExampleEtEhisexa3gep") == "ggagExampleEtEhisexa3gep"
    @test fix_spaces("   Exal mp  leample   3") == "-Exal_mp-leample-3"
    @test fix_spaces("gapshhi---a-a-a---  E  Ega psxample   2---sa-ac-c---b-b-b-c-c-c---s") == "gapshhi---a-a-a----E-Ega_psxample-2---sa-ac-c---b-b-b-c-c-c---s"
    @test fix_spaces("ga Exx1   s") == "ga_Exx1-s"
    @test fix_spaces("---a-a-a----c---") == "---a-a-a----c---"
    @test fix_spaces("wwo") == "wwo"
    @test fix_spaces("   Exa 1ExampleEtEhmisxe  ggaps   3") == "-Exa_1ExampleEtEhmisxe-ggaps-3"
    @test fix_spaces("A-B-*") == "A-B-*"
    @test fix_spaces("    Example   2    Example words  2") == "-Example-2-Example_words-2"
    @test fix_spaces(" Ex3  Ex     2\nmple\tExample   3i") == "_Ex3-Ex-2\nmple\tExample-3i"
    @test fix_spaces("thhi") == "thhi"
    @test fix_spaces("iin") == "iin"
    @test fix_spaces("--a-a-a---") == "--a-a-a---"
    @test fix_spaces("his  ExapmpleE  E3thitssxa3eisxpample   2") == "his-ExapmpleE-E3thitssxa3eisxpample-2"
    @test fix_spaces("---a-ac-c-a---") == "---a-ac-c-a---"
    @test fix_spaces("jgOtGgdMm") == "jgOtGgdMm"
    @test fix_spaces("ExampleEt  E  Ega pshhi---a-a-a---b-b-b-c-c-c---sxample   2---sa-ac-c--11-h-isx") == "ExampleEt-E-Ega_pshhi---a-a-a---b-b-b-c-c-c---sxample-2---sa-ac-c--11-h-isx"
    @test fix_spaces("1gggaps") == "1gggaps"
    @test fix_spaces("-E  c-c-c---sxxample EExb-b-c-c--") == "-E-c-c-c---sxxample_EExb-b-c-c--"
    @test fix_spaces("hhi-hhh") == "hhi-hhh"
    @test fix_spaces("   Exa 1gaps   3") == "-Exa_1gaps-3"
    @test fix_spaces("hsExampleExthi  hssxa3es") == "hsExampleExthi-hssxa3es"
    @test fix_spaces("----a--a-a---b-b-b-c-c--c---") == "----a--a-a---b-b-b-c-c--c---"
    @test fix_spaces(" p Exax  Expample   2") == "_p_Exax-Expample-2"
    @test fix_spaces("ExExameplampleEthisxa3e") == "ExExameplampleEthisxa3e"
    @test fix_spaces("thi  E   Exa 1 2 2\nmple\tExampExampleEtle 3  2") == "thi-E-Exa_1_2_2\nmple\tExampExampleEtle_3-2"
    @test fix_spaces("hsmpleeEthishiExamlesxa3eEthitssxa3eis") == "hsmpleeEthishiExamlesxa3eEthitssxa3eis"
    @test fix_spaces("---a-a-aExampleEt  E -c---hisxa3e--c---") == "---a-a-aExampleEt-E_-c---hisxa3e--c---"
    @test fix_spaces("  hExampxleEtEhisxa3e  1ile") == "-hExampxleEtEhisxa3e-1ile"
    @test fix_spaces("EleEatEhisxa3e") == "EleEatEhisxa3e"
    @test fix_spaces("ExampleEi") == "ExampleEi"
    @test fix_spaces("wo_--C") == "wo_--C"
    @test fix_spaces("Exampl   eEthish iExamlesxa3e  1") == "Exampl-eEthish_iExamlesxa3e-1"
    @test fix_spaces("c-c-c---sxxample") == "c-c-c---sxxample"
    @test fix_spaces("   Exple   3") == "-Exple-3"
    @test fix_spaces("  his ") == "-his_"
    @test fix_spaces("   hi s  h  hismpleample     ismpleample ") == "-hi_s-h-hismpleample-ismpleample_"
    @test fix_spaces("gapshhi---a-a-a---  E  Ega psxample   2---sa-ac-c----b-b-b-c-c-c---s") == "gapshhi---a-a-a----E-Ega_psxample-2---sa-ac-c----b-b-b-c-c-c---s"
    @test fix_spaces("  E  Ega psxa   Ex     2\nmple\tExample   3mple   2---sa-ac-c---") == "-E-Ega_psxa-Ex-2\nmple\tExample-3mple-2---sa-ac-c---"
    @test fix_spaces("A-B-*_") == "A-B-*_"
    @test fix_spaces("     his   Exx1   --C       ") == "-his-Exx1---C-"
    @test fix_spaces("sentenceample") == "sentenceample"
    @test fix_spaces("ggs") == "ggs"
    @test fix_spaces("    Example   2    Example   2   Exa 1ExampleEtEhisxe  1gggaps   3") == "-Example-2-Example-2-Exa_1ExampleEtEhisxe-1gggaps-3"
    @test fix_spaces("c-c-c----sx") == "c-c-c----sx"
    @test fix_spaces("hsmpleEthitssxa3eis") == "hsmpleEthitssxa3eis"
    @test fix_spaces("  his  hi2hisxggggaa3e ") == "-his-hi2hisxggggaa3e_"
    @test fix_spaces("----a-ac-c-thitts-") == "----a-ac-c-thitts-"
    @test fix_spaces("2   2   ") == "2-2-"
    @test fix_spaces("Ex3ampleEtEhisxa3e  1") == "Ex3ampleEtEhisxa3e-1"
    @test fix_spaces("his  Exam   A-B-*_-E-C   Ex     2\nmple\tExample  m 3pleE  mE3thitssxa3eisxpample   2") == "his-Exam-A-B-*_-E-C-Ex-2\nmple\tExample-m_3pleE-mE3thitssxa3eisxpample-2"
    @test fix_spaces("   Ex     2\nmple---a-a-a----c---\tExample  eEi") == "-Ex-2\nmple---a-a-a----c---\tExample-eEi"
    @test fix_spaces("   Exa 1 2 2\nmple\tExBig gaps    between words    i2---sa-ac-c---n this sentenceeample 3") == "-Exa_1_2_2\nmple\tExBig_gaps-between_words-i2---sa-ac-c---n_this_sentenceeample_3"
    @test fix_spaces("-E") == "-E"
    @test fix_spaces("---a--a-a---b-b-Example  1-c--c---") == "---a--a-a---b-b-Example-1-c--c---"
    @test fix_spaces("  E  Ega psxample   2---sa-ac-c-  E  Example   2--") == "-E-Ega_psxample-2---sa-ac-c--E-Example-2--"
    @test fix_spaces(" Exx   Ex     2\nmple\tExamhhple   3i1   ") == "_Exx-Ex-2\nmple\tExamhhple-3i1-"
    @test fix_spaces("hsExampleExthi  hssxA-B-*_--Ca3es") == "hsExampleExthi-hssxA-B-*_--Ca3es"
    @test fix_spaces("    his    A-B-*          3i1 _--C   ") == "-his-A-B-*-3i1__--C-"
    @test fix_spaces("E2---sa-ac-c---b-b-b-c-c-c---sx") == "E2---sa-ac-c---b-b-b-c-c-c---sx"
    @test fix_spaces("  E 2 Example   2") == "-E_2_Example-2"
    @test fix_spaces("A-B*--*_--C") == "A-B*--*_--C"
    @test fix_spaces("gapshhi---a-a-a---") == "gapshhi---a-a-a---"
    @test fix_spaces("thi  E   Exa 1 2 2\nmple\tExampExamplE  c-c-c---sxeEtle 3  2") == "thi-E-Exa_1_2_2\nmple\tExampExamplE-c-c-c---sxeEtle_3-2"
    @test fix_spaces("cc-cggs-c---sxxcample") == "cc-cggs-c---sxxcample"
    @test fix_spaces("hhi---a-a-a---b-b-b--c-c-c---s") == "hhi---a-a-a---b-b-b--c-c-c---s"
    @test fix_spaces("sggs") == "sggs"
    @test fix_spaces("  EExb-b-c-c--  Example   2") == "-EExb-b-c-c---Example-2"
    @test fix_spaces("ss") == "ss"
    @test fix_spaces("   Eexa 1 2 2\nmple\tExample 3") == "-Eexa_1_2_2\nmple\tExample_3"
    @test fix_spaces("gapshhi---a-2---sa-ac-c---hisxa3e---") == "gapshhi---a-2---sa-ac-c---hisxa3e---"
    @test fix_spaces("mple---a-a-a----c---") == "mple---a-a-a----c---"
    @test fix_spaces("xmampleEthisxa3es") == "xmampleEthisxa3es"
    @test fix_spaces("ggss") == "ggss"
    @test fix_spaces("E E x3") == "E_E_x3"
    @test fix_spaces("sjRboRkS") == "sjRboRkS"
    @test fix_spaces("  his   hi2hisxgEleEatEhisxa3egggaa3e ") == "-his-hi2hisxgEleEatEhisxa3egggaa3e_"
    @test fix_spaces("EEE") == "EEE"
    @test fix_spaces("ExampleEtExampl   eEthishiExamlesxa3e  e1") == "ExampleEtExampl-eEthishiExamlesxa3e-e1"
    @test fix_spaces("hhh") == "hhh"
    @test fix_spaces("   his     ") == "-his-"
    @test fix_spaces("22--") == "22--"
    @test fix_spaces("   3") == "-3"
    @test fix_spaces("---a--a-a---b-b-b-c-bismpleample") == "---a--a-a---b-b-b-c-bismpleample"
    @test fix_spaces("c-c-c---sxxamplthi  E   Exa 1 2 2\nmple\tExampExampleEtle 3  2e") == "c-c-c---sxxamplthi-E-Exa_1_2_2\nmple\tExampExampleEtle_3-2e"
    @test fix_spaces("   A-B-*_-E-C   Ex     2\nmple\tExamp1gggapsle  m 3") == "-A-B-*_-E-C-Ex-2\nmple\tExamp1gggapsle-m_3"
    @test fix_spaces("Examle") == "Examle"
    @test fix_spaces("    Example   2    Example words  22") == "-Example-2-Example_words-22"
    @test fix_spaces("tshitts") == "tshitts"
    @test fix_spaces("2---sssa-ac-c---h-isxa3e") == "2---sssa-ac-c---h-isxa3e"
    @test fix_spaces("his  ExExampl   eEthishiExamlesxa3e  1ampleE  Expample   2") == "his-ExExampl-eEthishiExamlesxa3e-1ampleE-Expample-2"
    @test fix_spaces("Examhhple") == "Examhhple"
    @test fix_spaces("hsE") == "hsE"
    @test fix_spaces("hisExampBig gaps    between words    in this sentenceleEthisxa3es") == "hisExampBig_gaps-between_words-in_this_sentenceleEthisxa3es"
    @test fix_spaces("ExampleEtEhisx") == "ExampleEtEhisx"
    @test fix_spaces("senteExamplnce") == "senteExamplnce"
    @test fix_spaces(" p ExaxmpleE  Expample a  2") == "_p_ExaxmpleE-Expample_a-2"
    @test fix_spaces("dwoc-c-c---sxeEtlerds") == "dwoc-c-c---sxeEtlerds"
    @test fix_spaces("Exal") == "Exal"
    @test fix_spaces("hsmpleeEthishiExame1lesxa3eEthitssxa3eis") == "hsmpleeEthishiExame1lesxa3eEthitssxa3eis"
    @test fix_spaces("E sc-c-c---sx") == "E_sc-c-c---sx"
    @test fix_spaces("worrd") == "worrd"
    @test fix_spaces("Exam    Example   2pleEA-B-*_-E-CtEhisxa3e  1") == "Exam-Example-2pleEA-B-*_-E-CtEhisxa3e-1"
    @test fix_spaces("Eexa") == "Eexa"
    @test fix_spaces("betweeExasxa3e  1n") == "betweeExasxa3e-1n"
    @test fix_spaces("sss") == "sss"
    @test fix_spaces("ExampleEtEhis3xa3e") == "ExampleEtEhis3xa3e"
    @test fix_spaces("   A-B-*_-E-C   Ex     2\nmple\tExampsenteExamplnce1gggapsle  m 3") == "-A-B-*_-E-C-Ex-2\nmple\tExampsenteExamplnce1gggapsle-m_3"
    @test fix_spaces("2---sa-ac-c-Exax--") == "2---sa-ac-c-Exax--"
    @test fix_spaces("Eampl") == "Eampl"
    @test fix_spaces("IclExampleEthisxa3e  1") == "IclExampleEthisxa3e-1"
    @test fix_spaces("---a--a-a---b-b--Example  1-c--c---") == "---a--a-a---b-b--Example-1-c--c---"
    @test fix_spaces("bet3e  1n") == "bet3e-1n"
    @test fix_spaces("---a-a--a----c---") == "---a-a--a----c---"
    @test fix_spaces("hsExampleExthi ExampleEi hssxA-B-*_--Ca3es") == "hsExampleExthi_ExampleEi_hssxA-B-*_--Ca3es"
    @test fix_spaces("EExx") == "EExx"
    @test fix_spaces("IclExample") == "IclExample"
    @test fix_spaces("fwlMxhGm") == "fwlMxhGm"
    @test fix_spaces(" sentenceleEthisxa3esc-c---") == "_sentenceleEthisxa3esc-c---"
    @test fix_spaces("hjnY") == "hjnY"
    @test fix_spaces("2   2") == "2-2"
    @test fix_spaces("2hsExampleExtEleEatEhisxa3e  1hi2--") == "2hsExampleExtEleEatEhisxa3e-1hi2--"
    @test fix_spaces("ga") == "ga"
    @test fix_spaces("    Example   2    Exampxle   2") == "-Example-2-Exampxle-2"
    @test fix_spaces("ExamxpbetweeExasxa3e  1nl") == "ExamxpbetweeExasxa3e-1nl"
    @test fix_spaces("---a-thits-a-a- sentenceleEthisxa3esc-c-----b-b-") == "---a-thits-a-a-_sentenceleEthisxa3esc-c-----b-b-"
    @test fix_spaces("ybsTcN") == "ybsTcN"
    @test fix_spaces("dw   his     ords") == "dw-his-ords"
    @test fix_spaces("2---sa-ac--c---") == "2---sa-ac--c---"
    @test fix_spaces("htsExampthitsleEthisxa3es") == "htsExampthitsleEthisxa3es"
    @test fix_spaces("hsihis") == "hsihis"
    @test fix_spaces("ihihis") == "ihihis"
    @test fix_spaces("  E  ExaExx2") == "-E-ExaExx2"
    @test fix_spaces("---a-thits-a-a- sentenceleEthisxa3esc-c-----bggagp-b-") == "---a-thits-a-a-_sentenceleEthisxa3esc-c-----bggagp-b-"
    @test fix_spaces("EExampple") == "EExampple"
    @test fix_spaces("Exmp---a--a-a---b-b-Examplel") == "Exmp---a--a-a---b-b-Examplel"
    @test fix_spaces(" sRentenceleEthisxa3esc-c--") == "_sRentenceleEthisxa3esc-c--"
    @test fix_spaces("-   ") == "--"
    @test fix_spaces("ExampleEmtExampl   eEthishiExamlesxa3e  e1") == "ExampleEmtExampl-eEthishiExamlesxa3e-e1"
    @test fix_spaces("  ExampleE  Expamplp2") == "-ExampleE-Expamplp2"
    @test fix_spaces("---a-thits-a-a- sentenceleEthisxa3esc-c-----his  ExampleE  Expample   2b-b-") == "---a-thits-a-a-_sentenceleEthisxa3esc-c-----his-ExampleE-Expample-2b-b-"
    @test fix_spaces("Exampthhisisa3e") == "Exampthhisisa3e"
    @test fix_spaces("--C") == "--C"
    @test fix_spaces("KsMcxuu") == "KsMcxuu"
    @test fix_spaces("ce-c-c---sxxample") == "ce-c-c---sxxample"
    @test fix_spaces("22  2   ") == "22-2-"
    @test fix_spaces("_--C") == "_--C"
    @test fix_spaces("EExpampl") == "EExpampl"
    @test fix_spaces("xmamspleEthisxae3es") == "xmamspleEthisxae3es"
    @test fix_spaces("-ExapmpleEc-thitts-") == "-ExapmpleEc-thitts-"
    @test fix_spaces("his  Exam   A-B-*_-E-C   Ex     2\nmple\tExample  m 3pleE  mE3thitssxa3ei   2") == "his-Exam-A-B-*_-E-C-Ex-2\nmple\tExample-m_3pleE-mE3thitssxa3ei-2"
    @test fix_spaces("ple") == "ple"
    @test fix_spaces("3Example    Example   2    Example   2   Exa 1ExampleEtEhisxe  1gggaps   3") == "3Example-Example-2-Example-2-Exa_1ExampleEtEhisxe-1gggaps-3"
    @test fix_spaces("ExampleEtExampl   eEthishiExamlesxa3e p e1") == "ExampleEtExampl-eEthishiExamlesxa3e_p_e1"
    @test fix_spaces("1gapszzPPb") == "1gapszzPPb"
    @test fix_spaces("DQaiLlVsgN") == "DQaiLlVsgN"
    @test fix_spaces("    his     A-B-*_-E-C   Ex     2\nmple\tExample  m 3thitssxa3eis    EExample  hismpleample     -C   ") == "-his-A-B-*_-E-C-Ex-2\nmple\tExample-m_3thitssxa3eis-EExample-hismpleample--C-"
    @test fix_spaces("ExamplhsEteEthitsxa3e") == "ExamplhsEteEthitsxa3e"
    @test fix_spaces("ExampleEt  E  Ega psxample   2---sa-abetweeExasxa3e  1n-isx") == "ExampleEt-E-Ega_psxample-2---sa-abetweeExasxa3e-1n-isx"
    @test fix_spaces("Ku   A-B-*_-E-C    Ex     2\nmple\tExample   3Mcxuu") == "Ku-A-B-*_-E-C-Ex-2\nmple\tExample-3Mcxuu"
    @test fix_spaces("ssgs") == "ssgs"
    @test fix_spaces("---a-thits-a-a- sentenceleEt p ExaxmpleE  Expample a  2-b-b-") == "---a-thits-a-a-_sentenceleEt_p_ExaxmpleE-Expample_a-2-b-b-"
    @test fix_spaces("ExaxmpleEthitsxa3e3c---") == "ExaxmpleEthitsxa3e3c---"
    @test fix_spaces("ExampleEt   E  Ega pshhi---a-a-a---b-ggsb-b-c-c-c---sxample   2---sa-ac-c--11-h-isx") == "ExampleEt-E-Ega_pshhi---a-a-a---b-ggsb-b-c-c-c---sxample-2---sa-ac-c--11-h-isx"
    @test fix_spaces("sentenceleEthisxa3esc-c---") == "sentenceleEthisxa3esc-c---"
    @test fix_spaces("thmple") == "thmple"
    @test fix_spaces("ssss") == "ssss"
    @test fix_spaces("cc-cggss-c---sxxcample") == "cc-cggss-c---sxxcample"
    @test fix_spaces("Ku   A-B-*_-E-C    Ex     2\nmple\tExample   cc-cggs-c---sxxcample3Mcxuu") == "Ku-A-B-*_-E-C-Ex-2\nmple\tExample-cc-cggs-c---sxxcample3Mcxuu"
    @test fix_spaces("  hExampleEthitssxa3eis Ex3ampleEtEhisxa3e  1   EExample") == "-hExampleEthitssxa3eis_Ex3ampleEtEhisxa3e-1-EExample"
    @test fix_spaces("sentenceleEthisxa3esc-c-----his") == "sentenceleEthisxa3esc-c-----his"
    @test fix_spaces("3Mcxu     u") == "3Mcxu-u"
    @test fix_spaces("gsss") == "gsss"
    @test fix_spaces("   A-B-*_-E-C   Ex    hismpleamplegapsle  m 3") == "-A-B-*_-E-C-Ex-hismpleamplegapsle-m_3"
    @test fix_spaces("---a-thits-a-a  his    ---b-b-") == "---a-thits-a-a-his----b-b-"
    @test fix_spaces("zExmplPb") == "zExmplPb"
    @test fix_spaces("EExammle") == "EExammle"
    @test fix_spaces("---a-a  ExampleE  Exp-ample   2  3c---") == "---a-a-ExampleE-Exp-ample-2-3c---"
    @test fix_spaces("EF2---sa-ac-c--11-h-isxoFlZTDagWE") == "EF2---sa-ac-c--11-h-isxoFlZTDagWE"
    @test fix_spaces("  his EF2---sa-ac-c--11-h-isxoFlZTDagWE") == "-his_EF2---sa-ac-c--11-h-isxoFlZTDagWE"
    @test fix_spaces("hExampleEthitssxa3eis") == "hExampleEthitssxa3eis"
    @test fix_spaces("hsExampaleEtheisxa3es") == "hsExampaleEtheisxa3es"
    @test fix_spaces("h") == "h"
    @test fix_spaces("T") == "T"
    @test fix_spaces("_wo_--C") == "_wo_--C"
    @test fix_spaces("2hsExampleExtEleEatEh-isxa3e  1hi2--") == "2hsExampleExtEleEatEh-isxa3e-1hi2--"
    @test fix_spaces("A-B---C") == "A-B---C"
    @test fix_spaces("2hsExampleExtEleEatEh-is-") == "2hsExampleExtEleEatEh-is-"
    @test fix_spaces("   Ex     2ple   3i") == "-Ex-2ple-3i"
    @test fix_spaces("his  ExampleE      2") == "his-ExampleE-2"
    @test fix_spaces("  his   ExampExampleEtle EExample") == "-his-ExampExampleEtle_EExample"
    @test fix_spaces("mE3thitssxa3eisxpample") == "mE3thitssxa3eisxpample"
    @test fix_spaces("    his     A-B-*_-E-C   Ex     2\nmple\tExample  m 3thitssx   A-B-*_-E-C   Ex     2\nmple\tExample  m 3a3eis    EExample-C   ") == "-his-A-B-*_-E-C-Ex-2\nmple\tExample-m_3thitssx-A-B-*_-E-C-Ex-2\nmple\tExample-m_3a3eis-EExample-C-"
    @test fix_spaces("c-c-c---sxxamplthi  E   Exa2 2\nmple\tExampExampleEtle 3  2e") == "c-c-c---sxxamplthi-E-Exa2_2\nmple\tExampExampleEtle_3-2e"
    @test fix_spaces("    his   Exx1 Exa2--C   ") == "-his-Exx1_Exa2--C-"
    @test fix_spaces("2pleEtEhisxa3e") == "2pleEtEhisxa3e"
    @test fix_spaces("xal") == "xal"
    @test fix_spaces("    Example   2     Example words  22") == "-Example-2-Example_words-22"
    @test fix_spaces("Examxpbetw--CeeExasxa3e  1nl") == "Examxpbetw--CeeExasxa3e-1nl"
    @test fix_spaces("hhi---a-a-a---b-b-bKu-c-c-c---s") == "hhi---a-a-a---b-b-bKu-c-c-c---s"
    @test fix_spaces("2----sa-aciin-c---") == "2----sa-aciin-c---"
    @test fix_spaces("rpfY") == "rpfY"
    @test fix_spaces("c-c-c---sxeEtle") == "c-c-c---sxeEtle"
    @test fix_spaces("---a--a-a---b-b-Example") == "---a--a-a---b-b-Example"
    @test fix_spaces("----a-aa-a2-b-b-c-c-c---") == "----a-aa-a2-b-b-c-c-c---"
    @test fix_spaces("Examxpbetweel") == "Examxpbetweel"
    @test fix_spaces("ExampExamplE") == "ExampExamplE"
    @test fix_spaces("wodhhi-ws") == "wodhhi-ws"
    @test fix_spaces("1ileExBig") == "1ileExBig"
    @test fix_spaces(" ExampleEtEhisx  Exa mp  leample   3") == "_ExampleEtEhisx-Exa_mp-leample-3"
    @test fix_spaces("2hsExampleEis-") == "2hsExampleEis-"
    @test fix_spaces("zExmbplPb") == "zExmbplPb"
    @test fix_spaces("2  2---a-a--a----c---   ") == "2-2---a-a--a----c----"
    @test fix_spaces("----a-a-a---b-b-b-c-c-c---ExamplceEtEhisxa3e") == "----a-a-a---b-b-b-c-c-c---ExamplceEtEhisxa3e"
    @test fix_spaces("2---sa-abetweeExasxa3e") == "2---sa-abetweeExasxa3e"
    @test fix_spaces("Ega") == "Ega"
    @test fix_spaces(" ExampleEtEhis  his   ExampExampleEtle EExamplex  Exa mp  lmeample   3") == "_ExampleEtEhis-his-ExampExampleEtle_EExamplex-Exa_mp-lmeample-3"
    @test fix_spaces("---a--ba-a---b-b-b-c-bismpleample") == "---a--ba-a---b-b-b-c-bismpleample"
    @test fix_spaces("beteweeExasxa3e  1n") == "beteweeExasxa3e-1n"
    @test fix_spaces("Exa1ExampleEtEhmisxemple  1") == "Exa1ExampleEtEhmisxemple-1"
    @test fix_spaces("hhi----a-thits-a-a- sentenceleEthisxa3esc-c-----bggagp-b-hhh") == "hhi----a-thits-a-a-_sentenceleEthisxa3esc-c-----bggagp-b-hhh"
    @test fix_spaces("3pleE") == "3pleE"
    @test fix_spaces("wordss") == "wordss"
    @test fix_spaces("---a-a") == "---a-a"
    @test fix_spaces("Exa3c--i-leEtEhisxa3e") == "Exa3c--i-leEtEhisxa3e"
    @test fix_spaces("EExam  E  ExaExx2ple  1Ex") == "EExam-E-ExaExx2ple-1Ex"
    @test fix_spaces("hhihh") == "hhihh"
    @test fix_spaces("---a---b-b-b-c-c-c---ExampleEtEhisxa3e") == "---a---b-b-b-c-c-c---ExampleEtEhisxa3e"
    @test fix_spaces("plethmple") == "plethmple"
    @test fix_spaces("xalxmamspleEhhhi---a-a-a---b-b-b--c-c-c---sthisxae3es") == "xalxmamspleEhhhi---a-a-a---b-b-b--c-c-c---sthisxae3es"
    @test fix_spaces("g    his    A-B-*_--C   gs") == "g-his-A-B-*_--C-gs"
    @test fix_spaces("hiss") == "hiss"
    @test fix_spaces("n") == "n"
    @test fix_spaces("gsentencele-a---") == "gsentencele-a---"
    @test fix_spaces("PzPPb") == "PzPPb"
    @test fix_spaces("2---sa-ac---c---") == "2---sa-ac---c---"
    @test fix_spaces("3Example") == "3Example"
    @test fix_spaces("  hjnYExample") == "-hjnYExample"
    @test fix_spaces("--CC") == "--CC"
    @test fix_spaces("---a--a-a---b-") == "---a--a-a---b-"
    @test fix_spaces("--CExampleEmtExamplC") == "--CExampleEmtExamplC"
    @test fix_spaces("Examxpbe2   2tw--CeeExasxa3e  1nl") == "Examxpbe2-2tw--CeeExasxa3e-1nl"
    @test fix_spaces("22EExample-C--") == "22EExample-C--"
    @test fix_spaces("     his   Exx1   --C       d") == "-his-Exx1---C-d"
    @test fix_spaces("EExc-c-c---sxeEtlepampl") == "EExc-c-c---sxeEtlepampl"
    @test fix_spaces("ExampleEt  E  Ega psxample   2---sa-ac-c---hisxa3eE") == "ExampleEt-E-Ega_psxample-2---sa-ac-c---hisxa3eE"
    @test fix_spaces("1   Exa 1 2 2\nmple\tExBig gaps    between words    i2---sa-ac-c---n this sentenceample 3aps") == "1-Exa_1_2_2\nmple\tExBig_gaps-between_words-i2---sa-ac-c---n_this_sentenceample_3aps"
    @test fix_spaces("hExampxleEtEhisxa3e") == "hExampxleEtEhisxa3e"
    @test fix_spaces("sentenceleEthicsxa3esc-c---") == "sentenceleEthicsxa3esc-c---"
    @test fix_spaces("mplees") == "mplees"
    @test fix_spaces("   Ex     2\nmple\tExample   ExmampleEi") == "-Ex-2\nmple\tExample-ExmampleEi"
    @test fix_spaces("         Example   2    Example   2   Exa 1ExampleEtEhisxe  1gggaps   3      ") == "-Example-2-Example-2-Exa_1ExampleEtEhisxe-1gggaps-3-"
    @test fix_spaces("gW") == "gW"
    @test fix_spaces("htsExampthitsleEthisxahhi---a-a-a---b-b-bKu-c-c-c---s3es") == "htsExampthitsleEthisxahhi---a-a-a---b-b-bKu-c-c-c---s3es"
    @test fix_spaces("i2---s-a-a-c-c---n") == "i2---s-a-a-c-c---n"
    @test fix_spaces("sentenceleEt3mplehicsxa3esc-c---") == "sentenceleEt3mplehicsxa3esc-c---"
    @test fix_spaces("---a--a-a---b-b-b-c-c----") == "---a--a-a---b-b-b-c-c----"
    @test fix_spaces("  his  h  hismplhsExampleExthi ExampleEi hssxA-B-*_--Ca3eseample     ismpleample ") == "-his-h-hismplhsExampleExthi_ExampleEi_hssxA-B-*_--Ca3eseample-ismpleample_"
    @test fix_spaces("wordrd") == "wordrd"
    @test fix_spaces("thitExampExampleEtles") == "thitExampExampleEtles"
    @test fix_spaces("   A-B-*_-E- C   Ex     2\nmple\t    E  Ega psxample   2---sa-ac-c--- A-B-*_-E-C   Ex     2\nmple\tExample   3ampsenteExamplnce1gggapsle  m 3") == "-A-B-*_-E-_C-Ex-2\nmple\t-E-Ega_psxample-2---sa-ac-c---_A-B-*_-E-C-Ex-2\nmple\tExample-3ampsenteExamplnce1gggapsle-m_3"
    @test fix_spaces("  E  xaExx2") == "-E-xaExx2"
    @test fix_spaces("xaE sentenceleEthisxa3esc-c---") == "xaE_sentenceleEthisxa3esc-c---"
    @test fix_spaces("zP----a-a-a---b-b-b-c-c-c---ExamplceEtEhisxa3e") == "zP----a-a-a---b-b-b-c-c-c---ExamplceEtEhisxa3e"
    @test fix_spaces("tsthitts") == "tsthitts"
    @test fix_spaces("3apswd") == "3apswd"
    @test fix_spaces("ExExamplampleEt  E  Example   2hisxggaa3e") == "ExExamplampleEt-E-Example-2hisxggaa3e"
    @test fix_spaces("thitteEthishts") == "thitteEthishts"
    @test fix_spaces("A-B-*m_-E-C") == "A-B-*m_-E-C"
    @test fix_spaces("sentenceleEthisxaa3es") == "sentenceleEthisxaa3es"
    @test fix_spaces("ExampleEt  E  Ega psxample   2---sa-ac-c---hisxa3e-C") == "ExampleEt-E-Ega_psxample-2---sa-ac-c---hisxa3e-C"
    @test fix_spaces("3thitssx") == "3thitssx"
    @test fix_spaces("---E  c-c-c---sxxample EExb-b-c-c----a-a-a---b-b-b-c-c-c---ExamapleEtEhisxa3e") == "---E-c-c-c---sxxample_EExb-b-c-c----a-a-a---b-b-b-c-c-c---ExamapleEtEhisxa3e"
    @test fix_spaces("    Examp2pleEtEhisxa3eExample   2") == "-Examp2pleEtEhisxa3eExample-2"
    @test fix_spaces("s3thitssxa3eis") == "s3thitssxa3eis"
    @test fix_spaces("    his    A-BA-B-*_  hExampleEthitssxa3eis    EExampple-E-C-*           _--C   ") == "-his-A-BA-B-*_-hExampleEthitssxa3eis-EExampple-E-C-*-_--C-"
    @test fix_spaces("  hExampleEthitssxahsE2xampleEthisxa3es3eis    EExam") == "-hExampleEthitssxahsE2xampleEthisxa3es3eis-EExam"
    @test fix_spaces("1ampleE") == "1ampleE"
    @test fix_spaces("mE3tshitssxa3eisxpample") == "mE3tshitssxa3eisxpample"
    @test fix_spaces("2---sa-ac-c--  Exx1   -h-isxa3e") == "2---sa-ac-c---Exx1--h-isxa3e"
    @test fix_spaces("   shis     ") == "-shis-"
    @test fix_spaces("A-B-*mA_-E-C") == "A-B-*mA_-E-C"
    @test fix_spaces("ExExamplampleEt  E  Example   2hisx") == "ExExamplampleEt-E-Example-2hisx"
    @test fix_spaces("ithits") == "ithits"
    @test fix_spaces("---a--a-a---b-   Ex     2\nmple\tExample   ExmampleEib-b--c-c-c---") == "---a--a-a---b--Ex-2\nmple\tExample-ExmampleEib-b--c-c-c---"
    @test fix_spaces("hismpleamplegapsle") == "hismpleamplegapsle"
    @test fix_spaces("nn") == "nn"
    @test fix_spaces("hsE    his   Exx1   --CE   xmampleEthisxa3es") == "hsE-his-Exx1---CE-xmampleEthisxa3es"
    @test fix_spaces("Exeamggapsle") == "Exeamggapsle"
    @test fix_spaces(" s ExampleeEthisxa3e") == "_s_ExampleeEthisxa3e"
    @test fix_spaces("ExampsenteExamplnce1gggapsle") == "ExampsenteExamplnce1gggapsle"
    @test fix_spaces("bExametweeExasxa3e  1n") == "bExametweeExasxa3e-1n"
    @test fix_spaces("---a--a-a---b-   Ex     2\nmple\tExample   ExmampleEib-b--cc-c-c---") == "---a--a-a---b--Ex-2\nmple\tExample-ExmampleEib-b--cc-c-c---"
    @test fix_spaces("E1ExampleEtEhisxeaEzExmplPbEEE") == "E1ExampleEtEhisxeaEzExmplPbEEE"
    @test fix_spaces("   Exa 1ExampleEtEEhmisxe  ggaps   3") == "-Exa_1ExampleEtEEhmisxe-ggaps-3"
    @test fix_spaces("gaTnYIFZqaAzpshhi---a-a-a---") == "gaTnYIFZqaAzpshhi---a-a-a---"
    @test fix_spaces("2-    his     A-B-*_-E-C   Ex     2\nmple\tExample  m 3thitssxa3eis    EExample-C   --sa-ac---c---") == "2--his-A-B-*_-E-C-Ex-2\nmple\tExample-m_3thitssxa3eis-EExample-C---sa-ac---c---"
    @test fix_spaces("    his    A-BA-B-*_  hEx  hExampleEthitssxa3eis    EExamppleampleEthitssxa3eis    EExampple-E-C-*           _--C   ") == "-his-A-BA-B-*_-hEx-hExampleEthitssxa3eis-EExamppleampleEthitssxa3eis-EExampple-E-C-*-_--C-"
    @test fix_spaces("cc-cggss-c---sxxcgapshhi---a-2---sa-ac-c---hisxa3e----ample") == "cc-cggss-c---sxxcgapshhi---a-2---sa-ac-c---hisxa3e----ample"
    @test fix_spaces("   A-B-*_-E-C   Ex     2\nmple\tExample  E  c-c-c---sx3") == "-A-B-*_-E-C-Ex-2\nmple\tExample-E-c-c-c---sx3"
    @test fix_spaces("ExpampA-B-*_le") == "ExpampA-B-*_le"
    @test fix_spaces("2hsExampleExtEleEasRentenceleEthisxa3esc-c--tE2   2h-is-") == "2hsExampleExtEleEasRentenceleEthisxa3esc-c--tE2-2h-is-"
    @test fix_spaces("sRentenceleEthisxa3esc-c--") == "sRentenceleEthisxa3esc-c--"
    @test fix_spaces("thitExmE3thitssxa3eisxpampleampExampleEtles") == "thitExmE3thitssxa3eisxpampleampExampleEtles"
    @test fix_spaces("hisExampBig gaps    between words    in this sentenceleEthisxa3 es") == "hisExampBig_gaps-between_words-in_this_sentenceleEthisxa3_es"
    @test fix_spaces("   Ex     22\nmple\tExample   3") == "-Ex-22\nmple\tExample-3"
    @test fix_spaces("Exa-E") == "Exa-E"
    @test fix_spaces("hhis2---sa-ac-c---h-isx") == "hhis2---sa-ac-c---h-isx"
    @test fix_spaces("2---sa-ac-c-i--h-isxa3e") == "2---sa-ac-c-i--h-isxa3e"
    @test fix_spaces(" ") == "_"
    @test fix_spaces(" a b c ") == "_a_b_c_"
    @test fix_spaces(" a  b  c ") == "_a-b-c_"
    @test fix_spaces("        ") == "-"
    @test fix_spaces(" a   b c  ") == "_a-b_c-"
    @test fix_spaces("ABC") == "ABC"
    @test fix_spaces("1 2 3") == "1_2_3"
    @test fix_spaces("百度是中国最大的搜索引擎") == "百度是中国最大的搜索引擎"
    @test fix_spaces("Big gaps    between words    in thce") == "Big_gaps-between_words-in_thce"
    @test fix_spaces("Big gaps    between words    in this sen3tence") == "Big_gaps-between_words-in_this_sen3tence"
    @test fix_spaces("  Big gaps    between words    in thce      ") == "-Big_gaps-between_words-in_thce-"
    @test fix_spaces("        mple") == "-mple"
    @test fix_spaces("  Big        ") == "-Big-"
    @test fix_spaces("mple") == "mple"
    @test fix_spaces("  Big gaps    between words    Big gaps    between words    in this sen3tencein thce          ") == "-Big_gaps-between_words-Big_gaps-between_words-in_this_sen3tencein_thce-"
    @test fix_spaces("  Big            Example   2") == "-Big-Example-2"
    @test fix_spaces("Exa 1 2 2 mplle") == "Exa_1_2_2_mplle"
    @test fix_spaces("   gaps") == "-gaps"
    @test fix_spaces("wor  Big gaps    between words    Big gaps    between words    in this sen3tencein thce          ds") == "wor-Big_gaps-between_words-Big_gaps-between_words-in_this_sen3tencein_thce-ds"
    @test fix_spaces("thce") == "thce"
    @test fix_spaces("mmple") == "mmple"
    @test fix_spaces("   Example  1 ") == "-Example-1_"
    @test fix_spaces("    Example 2") == "-Example_2"
    @test fix_spaces("sen3tence") == "sen3tence"
    @test fix_spaces("mmpleExample  1") == "mmpleExample-1"
    @test fix_spaces("  Big            ExamExaple   2") == "-Big-ExamExaple-2"
    @test fix_spaces("Big") == "Big"
    @test fix_spaces("     Example   2   ") == "-Example-2-"
    @test fix_spaces("Exa 1 2 2 mpsen3tencee") == "Exa_1_2_2_mpsen3tencee"
    @test fix_spaces("ExamExaple") == "ExamExaple"
    @test fix_spaces("Exxa") == "Exxa"
    @test fix_spaces("   A-BExample   ") == "-A-BExample-"
    @test fix_spaces(" Big gaps    between words    in thce  ") == "_Big_gaps-between_words-in_thce-"
    @test fix_spaces("Big gap        mples    between words    in thce") == "Big_gap-mples-between_words-in_thce"
    @test fix_spaces("     gaps A-B-*_--C   ") == "-gaps_A-B-*_--C-"
    @test fix_spaces("sen3tencein") == "sen3tencein"
    @test fix_spaces("se3n3tence") == "se3n3tence"
    @test fix_spaces("Big gaps    between words     in this sen3tence") == "Big_gaps-between_words-in_this_sen3tence"
    @test fix_spaces("mmpleExample") == "mmpleExample"
    @test fix_spaces("mplExa 1 2 2 mpsen3tenceees") == "mplExa_1_2_2_mpsen3tenceees"
    @test fix_spaces("Exa 1 2 2 mpl  Big            ExamExaple   2e") == "Exa_1_2_2_mpl-Big-ExamExaple-2e"
    @test fix_spaces("mmpleE1") == "mmpleE1"
    @test fix_spaces("   A-B-*_--C  Big gaps    between words    in this sen3tence- ") == "-A-B-*_--C-Big_gaps-between_words-in_this_sen3tence-_"
    @test fix_spaces("   A-gapsB-*_--C   ") == "-A-gapsB-*_--C-"
    @test fix_spaces("t Big gaps    between words    in thce  his") == "t_Big_gaps-between_words-in_thce-his"
    @test fix_spaces("Exa 1 2 2 mpExample  1sen3tencee") == "Exa_1_2_2_mpExample-1sen3tencee"
    @test fix_spaces("  Big gaps    between words    in thce      fKqrpAGA") == "-Big_gaps-between_words-in_thce-fKqrpAGA"
    @test fix_spaces("EExample  1") == "EExample-1"
    @test fix_spaces("  Big gaps    between words   o in thce      ") == "-Big_gaps-between_words-o_in_thce-"
    @test fix_spaces("th   Exa 1 2 2\nmple\tExample   3s") == "th-Exa_1_2_2\nmple\tExample-3s"
    @test fix_spaces("BiBg") == "BiBg"
    @test fix_spaces("mfKqrpAGApleE1") == "mfKqrpAGApleE1"
    @test fix_spaces("EExampEle  1") == "EExampEle-1"
    @test fix_spaces("BWnXAhX") == "BWnXAhX"
    @test fix_spaces("                    ") == "-"
    @test fix_spaces("sen3tenncein") == "sen3tenncein"
    @test fix_spaces("EExa") == "EExa"
    @test fix_spaces("Ex     mmpleE1   ample  1") == "Ex-mmpleE1-ample-1"
    @test fix_spaces("mpsen3tenceees") == "mpsen3tenceees"
    @test fix_spaces(" Big gap        mples    between words    in thce") == "_Big_gap-mples-between_words-in_thce"
    @test fix_spaces("   A-gaps-B-*_*--C   ") == "-A-gaps-B-*_*--C-"
    @test fix_spaces("  Big gaps    between words   o in thce          ") == "-Big_gaps-between_words-o_in_thce-"
    @test fix_spaces("Ex    Example 2xa") == "Ex-Example_2xa"
    @test fix_spaces("EExample") == "EExample"
    @test fix_spaces("   A-gaps-B-*_*s--C   ") == "-A-gaps-B-*_*s--C-"
    @test fix_spaces("         sen3tenncein") == "-sen3tenncein"
    @test fix_spaces("   le   ") == "-le-"
    @test fix_spaces("Exa 1 2 2 m") == "Exa_1_2_2_m"
    @test fix_spaces("tthhce") == "tthhce"
    @test fix_spaces("Exa 1 2 2 mpsent3tencee") == "Exa_1_2_2_mpsent3tencee"
    @test fix_spaces("Exa 1 2  2 m") == "Exa_1_2-2_m"
    @test fix_spaces("   A-B-*_--C   mplExa") == "-A-B-*_--C-mplExa"
    @test fix_spaces("A-gapsB-*_--C") == "A-gapsB-*_--C"
    @test fix_spaces("BWnXAh") == "BWnXAh"
    @test fix_spaces("fKqrpAGA") == "fKqrpAGA"
    @test fix_spaces("Exa 1 2 2 mp") == "Exa_1_2_2_mp"
    @test fix_spaces("Big gaps    bet ween words    in this sentence") == "Big_gaps-bet_ween_words-in_this_sentence"
    @test fix_spaces("se3n3ntence") == "se3n3ntence"
    @test fix_spaces("EExa 1 2 2 mpsent3tencee2xa") == "EExa_1_2_2_mpsent3tencee2xa"
    @test fix_spaces("    ExampleEx    Example 2xa 2") == "-ExampleEx-Example_2xa_2"
    @test fix_spaces("   A-B--*_--C   mplExa") == "-A-B--*_--C-mplExa"
    @test fix_spaces("se3n           3tence") == "se3n-3tence"
    @test fix_spaces("Exa 1 2 2 mpl  Big            ExamExa 1 2 2 me") == "Exa_1_2_2_mpl-Big-ExamExa_1_2_2_me"
    @test fix_spaces("ample") == "ample"
    @test fix_spaces("th   Exae 1 2 2\nmple\tExample   3s") == "th-Exae_1_2_2\nmple\tExample-3s"
    @test fix_spaces("BBig") == "BBig"
    @test fix_spaces("   A-x   ") == "-A-x-"
    @test fix_spaces("   A-gapsB- ") == "-A-gapsB-_"
    @test fix_spaces("ExxEa") == "ExxEa"
    @test fix_spaces("     gEExampleaps A-B-*_--C   ") == "-gEExampleaps_A-B-*_--C-"
    @test fix_spaces("sen3tence-") == "sen3tence-"
    @test fix_spaces("Bg") == "Bg"
    @test fix_spaces("    2") == "-2"
    @test fix_spaces("ExxA-xEa") == "ExxA-xEa"
    @test fix_spaces("                   ") == "-"
    @test fix_spaces("mplExa") == "mplExa"
    @test fix_spaces(" Big gaps    between words   Big         in thce  ") == "_Big_gaps-between_words-Big-in_thce-"
    @test fix_spaces("ttse3n           3tencehhce") == "ttse3n-3tencehhce"
    @test fix_spaces("EEpxample") == "EEpxample"
    @test fix_spaces("A-gapsB-**_--C") == "A-gapsB-**_--C"
    @test fix_spaces("pBig gap        mples    between wo rds    in thce") == "pBig_gap-mples-between_wo_rds-in_thce"
    @test fix_spaces("  Big            Exaple   2") == "-Big-Exaple-2"
    @test fix_spaces("m") == "m"
    @test fix_spaces("sce") == "sce"
    @test fix_spaces("EEpxampl") == "EEpxampl"
    @test fix_spaces("xExxEA-xEa") == "xExxEA-xEa"
    @test fix_spaces("2xa") == "2xa"
    @test fix_spaces("ExamExaplae") == "ExamExaplae"
    @test fix_spaces("mmpleEmexample  Big gaps    between words   o in thce          1") == "mmpleEmexample-Big_gaps-between_words-o_in_thce-1"
    @test fix_spaces("Big 3tenceds    in thce") == "Big_3tenceds-in_thce"
    @test fix_spaces("gap") == "gap"
    @test fix_spaces("   A-B-*---a-a-a---b-b-b-c-c-c---_--C   ") == "-A-B-*---a-a-a---b-b-b-c-c-c---_--C-"
    @test fix_spaces("ExamEA-gapsB-*_---Caple") == "ExamEA-gapsB-*_---Caple"
    @test fix_spaces("isenn3tenncein ") == "isenn3tenncein_"
    @test fix_spaces("   le    ") == "-le-"
    @test fix_spaces("me") == "me"
    @test fix_spaces("ggasen3tenceinp") == "ggasen3tenceinp"
    @test fix_spaces("Ex    Examplxe 2xa") == "Ex-Examplxe_2xa"
    @test fix_spaces("BWnnX") == "BWnnX"
    @test fix_spaces("EEpxampl     ") == "EEpxampl-"
    @test fix_spaces("tthhcewords") == "tthhcewords"
    @test fix_spaces("A-_B--*_--C") == "A-_B--*_--C"
    @test fix_spaces("    le    ") == "-le-"
    @test fix_spaces("EEx  a") == "EEx-a"
    @test fix_spaces("     gA-B-*---a-a-a---b-b-b-c-c-c---_--CEExampleaps A-B-*_--C   ") == "-gA-B-*---a-a-a---b-b-b-c-c-c---_--CEExampleaps_A-B-*_--C-"
    @test fix_spaces("bet") == "bet"
    @test fix_spaces("  Big   Exa 1 2 2\nmple\tExample   3        ") == "-Big-Exa_1_2_2\nmple\tExample-3-"
    @test fix_spaces("mpl   A-x   ") == "mpl-A-x-"
    @test fix_spaces("thh") == "thh"
    @test fix_spaces("   x Example   2") == "-x_Example-2"
    @test fix_spaces("mplExa 1 2 2 mpsen3tenEExceees") == "mplExa_1_2_2_mpsen3tenEExceees"
    @test fix_spaces("A-gapsB--**_--C") == "A-gapsB--**_--C"
    @test fix_spaces("  Big gaps    between words    A-xin thce      fKqrpAGA") == "-Big_gaps-between_words-A-xin_thce-fKqrpAGA"
    @test fix_spaces("   x Example   2gap") == "-x_Example-2gap"
    @test fix_spaces("A-gapsB-") == "A-gapsB-"
    @test fix_spaces("mm") == "mm"
    @test fix_spaces("Big gaps    bet ween words    in this senbtence") == "Big_gaps-bet_ween_words-in_this_senbtence"
    @test fix_spaces("3tenceds") == "3tenceds"
    @test fix_spaces("2e") == "2e"
    @test fix_spaces("     gaps A-B-*_--C  msen3tenceinp thce") == "-gaps_A-B-*_--C-msen3tenceinp_thce"
    @test fix_spaces("     gaps A-B-*_--C  msen3tenceinp thcae") == "-gaps_A-B-*_--C-msen3tenceinp_thcae"
    @test fix_spaces("mpscelle") == "mpscelle"
    @test fix_spaces("se3n") == "se3n"
    @test fix_spaces("Exaa") == "Exaa"
    @test fix_spaces("    A-gapsB- ") == "-A-gapsB-_"
    @test fix_spaces("EEExa 1 2 2 mpl  Big            ExamExaple   2e") == "EEExa_1_2_2_mpl-Big-ExamExaple-2e"
    @test fix_spaces("ExamExbetweenlae") == "ExamExbetweenlae"
    @test fix_spaces("   Exa 1 2 2\nmple\tE  Big gaps    between words   o in thce          xample   3") == "-Exa_1_2_2\nmple\tE-Big_gaps-between_words-o_in_thce-xample-3"
    @test fix_spaces("isenn3tenncein") == "isenn3tenncein"
    @test fix_spaces("     ExampleEx    Example 2xa 2") == "-ExampleEx-Example_2xa_2"
    @test fix_spaces("BWn  Big        XAh") == "BWn-Big-XAh"
    @test fix_spaces("ExampleEx") == "ExampleEx"
    @test fix_spaces("ggasen3tenceinpsce") == "ggasen3tenceinpsce"
    @test fix_spaces("Big gaps    bet ween words    in this senbtenc   A-gapsB- e") == "Big_gaps-bet_ween_words-in_this_senbtenc-A-gapsB-_e"
    @test fix_spaces("   x ExamEEpxample 2") == "-x_ExamEEpxample_2"
    @test fix_spaces("  in thce          ") == "-in_thce-"
    @test fix_spaces("2Big gaps    between words    in thcee") == "2Big_gaps-between_words-in_thcee"
    @test fix_spaces("tbet") == "tbet"
    @test fix_spaces("sen3tencte") == "sen3tencte"
    @test fix_spaces("A-gapsB--**_--C Big gap        mples    between words    in thce") == "A-gapsB--**_--C_Big_gap-mples-between_words-in_thce"
    @test fix_spaces("Big gaps    between wocrds     in this sen3tence") == "Big_gaps-between_wocrds-in_this_sen3tence"
    @test fix_spaces("  Big   1 2 2\nmple\tExample   3 ") == "-Big-1_2_2\nmple\tExample-3_"
    @test fix_spaces("sen3tenecein") == "sen3tenecein"
    @test fix_spaces("2xExa 1 2 2 mpsen3tenceea") == "2xExa_1_2_2_mpsen3tenceea"
    @test fix_spaces("A-gaps-B-*_*--C") == "A-gaps-B-*_*--C"
    @test fix_spaces("isennmpsen3tencee3tenncein ") == "isennmpsen3tencee3tenncein_"
    @test fix_spaces("mpsen3tenceeees") == "mpsen3tenceeees"
    @test fix_spaces("mpsent3tencee2xa") == "mpsent3tencee2xa"
    @test fix_spaces("A-gapsB--**_--C Big gap        mples    between words    in thceEExample") == "A-gapsB--**_--C_Big_gap-mples-between_words-in_thceEExample"
    @test fix_spaces("betmples") == "betmples"
    @test fix_spaces("  Big ga ps    between words    Big gaps    between words    in this sen3tencein thce          ") == "-Big_ga_ps-between_words-Big_gaps-between_words-in_this_sen3tencein_thce-"
    @test fix_spaces("Exa 1 2 2 mpsen32tencee") == "Exa_1_2_2_mpsen32tencee"
    @test fix_spaces("Big gaps    between words   ") == "Big_gaps-between_words-"
    @test fix_spaces("pBiggap") == "pBiggap"
    @test fix_spaces("mpsen3tenEExceees") == "mpsen3tenEExceees"
    @test fix_spaces("rds") == "rds"
    @test fix_spaces("BiBgg") == "BiBgg"
    @test fix_spaces("mmpleExample  ExampleEx1") == "mmpleExample-ExampleEx1"
    @test fix_spaces("mmpl  Big gaps    between words   o in thce          eExample  1") == "mmpl-Big_gaps-between_words-o_in_thce-eExample-1"
    @test fix_spaces("   ExampExaplele  1 ") == "-ExampExaplele-1_"
    @test fix_spaces("Big gaps  A-gapsB--**_--C Big gap        mples    between words    in thce  between words   ") == "Big_gaps-A-gapsB--**_--C_Big_gap-mples-between_words-in_thce-between_words-"
    @test fix_spaces("Exa 1 2 2  ampsen3tencee") == "Exa_1_2_2-ampsen3tencee"
    @test fix_spaces("mplle") == "mplle"
    @test fix_spaces("se3n   A-gapsB- -C   ") == "se3n-A-gapsB-_-C-"
    @test fix_spaces("Big gaps    between words    in this sen3tenwce") == "Big_gaps-between_words-in_this_sen3tenwce"
    @test fix_spaces("tthhwords") == "tthhwords"
    @test fix_spaces("pBig gap        mples in thce") == "pBig_gap-mples_in_thce"
    @test fix_spaces("am    A-gapsB- ExamExaple") == "am-A-gapsB-_ExamExaple"
    @test fix_spaces("BWnXsenbtenceAhX") == "BWnXsenbtenceAhX"
    @test fix_spaces("CWSrjljyFR") == "CWSrjljyFR"
    @test fix_spaces("Big gaps    bet weens    in this senbtenc   A-gapsBmplExa 1 2 2 mpsen3tenEExceees- e") == "Big_gaps-bet_weens-in_this_senbtenc-A-gapsBmplExa_1_2_2_mpsen3tenEExceees-_e"
    @test fix_spaces("amplmmpleExample  ExampleEx1") == "amplmmpleExample-ExampleEx1"
    @test fix_spaces("ttse3n           3tencehhce    Example   2") == "ttse3n-3tencehhce-Example-2"
    @test fix_spaces("gaa") == "gaa"
    @test fix_spaces("    Ethcele  1 ") == "-Ethcele-1_"
    @test fix_spaces("    Example  2") == "-Example-2"
    @test fix_spaces("th   Exa 1 2 2\nm3s") == "th-Exa_1_2_2\nm3s"
    @test fix_spaces("   Exa 1 2 2\nmple\tE  Big gaps    betwe2Big gaps    between words    in thceeen words   o in thce          xample   3") == "-Exa_1_2_2\nmple\tE-Big_gaps-betwe2Big_gaps-between_words-in_thceeen_words-o_in_thce-xample-3"
    @test fix_spaces("e") == "e"
    @test fix_spaces("   ExampExaplelea  1 ") == "-ExampExaplelea-1_"
    @test fix_spaces("A-gapsB--**_--C Big gap        mples    between words n   in thce") == "A-gapsB--**_--C_Big_gap-mples-between_words_n-in_thce"
    @test fix_spaces("sen3tenc  Big gaps    between words   o in thce          te") == "sen3tenc-Big_gaps-between_words-o_in_thce-te"
    @test fix_spaces("weens") == "weens"
    @test fix_spaces("   A-B--*_--C   mExampleplExa") == "-A-B--*_--C-mExampleplExa"
    @test fix_spaces("mExampleplExa") == "mExampleplExa"
    @test fix_spaces("th   Exa 1 2 2\nmple\tExample   3smp") == "th-Exa_1_2_2\nmple\tExample-3smp"
    @test fix_spaces("wse3n3ntenceor") == "wse3n3ntenceor"
    @test fix_spaces("eExample") == "eExample"
    @test fix_spaces("Exa    ExampExaplele  1 1 2 2  ampsen3tencee") == "Exa-ExampExaplele-1_1_2_2-ampsen3tencee"
    @test fix_spaces("isennmpsen3tencee3tennceinbet") == "isennmpsen3tencee3tennceinbet"
    @test fix_spaces("se3n   A-gap -C 3  ") == "se3n-A-gap_-C_3-"
    @test fix_spaces("mmpleExample gA-B-*---a-a-a---b-b-b-c-c-c---_--CEExampleaps ExampleEx1") == "mmpleExample_gA-B-*---a-a-a---b-b-b-c-c-c---_--CEExampleaps_ExampleEx1"
    @test fix_spaces("bets") == "bets"
    @test fix_spaces("mp") == "mp"
    @test fix_spaces("   A-Bb-c-c-c---_--C   ") == "-A-Bb-c-c-c---_--C-"
    @test fix_spaces("EEpx") == "EEpx"
    @test fix_spaces("   A-B-- *_--C    mplExa") == "-A-B--_*_--C-mplExa"
    @test fix_spaces("ExamEA-gapsB-*_a--m-Cap") == "ExamEA-gapsB-*_a--m-Cap"
    @test fix_spaces("  Bi           Exaple   2") == "-Bi-Exaple-2"
    @test fix_spaces("pBig gap   *_--C     mples    between wo rds    in thce") == "pBig_gap-*_--C-mples-between_wo_rds-in_thce"
    @test fix_spaces("BWnX         Ah") == "BWnX-Ah"
    @test fix_spaces("xExxEA-xEaExae") == "xExxEA-xEaExae"
    @test fix_spaces("sen3tenc") == "sen3tenc"
    @test fix_spaces("mmpleExample p 1") == "mmpleExample_p_1"
    @test fix_spaces("tthh") == "tthh"
    @test fix_spaces("isennmpsen3teEExampEle    Example  2ncee3tennceinbet") == "isennmpsen3teEExampEle-Example-2ncee3tennceinbet"
    @test fix_spaces("  a                 ") == "-a-"
    @test fix_spaces("  Big gaps    between wordae      fKqrpAGA") == "-Big_gaps-between_wordae-fKqrpAGA"
    @test fix_spaces("BWnX         mmpleExample p 1Ah") == "BWnX-mmpleExample_p_1Ah"
    @test fix_spaces("     Ethcele  1 ") == "-Ethcele-1_"
    @test fix_spaces("ebS") == "ebS"
    @test fix_spaces("A-gaps-B-*_*s--C") == "A-gaps-B-*_*s--C"
    @test fix_spaces("eaxa") == "eaxa"
    @test fix_spaces("rrds") == "rrds"
    @test fix_spaces("sece-") == "sece-"
    @test fix_spaces("pBig gap   *_--C     mples    bet   A-gaps-B-*_*--C   ween wo rds    in thce") == "pBig_gap-*_--C-mples-bet-A-gaps-B-*_*--C-ween_wo_rds-in_thce"
    @test fix_spaces("A**_--C Big g ap        mples    bempl   A-x   hce") == "A**_--C_Big_g_ap-mples-bempl-A-x-hce"
    @test fix_spaces("t Biig gaps    between wordshis    in thce  his") == "t_Biig_gaps-between_wordshis-in_thce-his"
    @test fix_spaces("ExamExaEple") == "ExamExaEple"
    @test fix_spaces("     Example   2mpsen3tenceea   ") == "-Example-2mpsen3tenceea-"
    @test fix_spaces("BWnXAxExxEA-xEaExaeX     Ethcele  1 ") == "BWnXAxExxEA-xEaExaeX-Ethcele-1_"
    @test fix_spaces("ps") == "ps"
    @test fix_spaces("a") == "a"
    @test fix_spaces("isennmpsen3tencee3tennceintbet") == "isennmpsen3tencee3tennceintbet"
    @test fix_spaces("ExampExaplelea") == "ExampExaplelea"
    @test fix_spaces("   Exa 1 2 2\nmple\tE  Big gaps    betwe2Big gaps    between words xExxEA-xEaExae   in thceeen words   o in thce          xample   3") == "-Exa_1_2_2\nmple\tE-Big_gaps-betwe2Big_gaps-between_words_xExxEA-xEaExae-in_thceeen_words-o_in_thce-xample-3"
    @test fix_spaces("pmp") == "pmp"
    @test fix_spaces("n           3tencehhce") == "n-3tencehhce"
    @test fix_spaces("rNfUBspa") == "rNfUBspa"
    @test fix_spaces("     Epxample   2   ") == "-Epxample-2-"
    @test fix_spaces("wocrds") == "wocrds"
    @test fix_spaces(" Ex    Examplxe 2xaA-B-*_--C   mplExa") == "_Ex-Examplxe_2xaA-B-*_--C-mplExa"
    @test fix_spaces("rNfteUBspa") == "rNfteUBspa"
    @test fix_spaces("Bigmpsent3tencee    in this sentence") == "Bigmpsent3tencee-in_this_sentence"
    @test fix_spaces("esen3tencempsen3tenEExceee3s-") == "esen3tencempsen3tenEExceee3s-"
    @test fix_spaces("        mpl  Big            ExamExaple   2e") == "-mpl-Big-ExamExaple-2e"
    @test fix_spaces("EEEpx") == "EEEpx"
    @test fix_spaces("t Biig gaps    between wordshis    in thce t his") == "t_Biig_gaps-between_wordshis-in_thce_t_his"
    @test fix_spaces("   x xample 2") == "-x_xample_2"
    @test fix_spaces("betmeples") == "betmeples"
    @test fix_spaces("th   Exa 1 2 2\nm3sBig gaps    between words    in thce") == "th-Exa_1_2_2\nm3sBig_gaps-between_words-in_thce"
    @test fix_spaces("te") == "te"
    @test fix_spaces("  Big            ExamExaple   2ExamExbetweenlae") == "-Big-ExamExaple-2ExamExbetweenlae"
    @test fix_spaces("XRSIx") == "XRSIx"
    @test fix_spaces("BWnXAXhX") == "BWnXAXhX"
    @test fix_spaces("     A-gapsB-    ExamEEpxamplemplExa") == "-A-gapsB--ExamEEpxamplemplExa"
    @test fix_spaces("  Big   1 2 2\nmple\tEx2ample   3 ") == "-Big-1_2_2\nmple\tEx2ample-3_"
    @test fix_spaces("A-gapsB-B*_--C") == "A-gapsB-B*_--C"
    @test fix_spaces("th   Big     gaps    bet ween words    in this senbtenc   A-gapsB- eExa 1 2 2\nmple\tEx  3smp") == "th-Big-gaps-bet_ween_words-in_this_senbtenc-A-gapsB-_eExa_1_2_2\nmple\tEx-3smp"
    @test fix_spaces("mpsece-lExa") == "mpsece-lExa"
    @test fix_spaces("tth") == "tth"
    @test fix_spaces("  mpsent3tencee                 ") == "-mpsent3tencee-"
    @test fix_spaces("ExagmEA-gapsB-*_---Caple") == "ExagmEA-gapsB-*_---Caple"
    @test fix_spaces("ggasen3tenp") == "ggasen3tenp"
    @test fix_spaces("mmpleEsen3tenc  Big gaps    between words   o in thce          temexample  Big gaps    between words   o in thce          1") == "mmpleEsen3tenc-Big_gaps-between_words-o_in_thce-temexample-Big_gaps-between_words-o_in_thce-1"
    @test fix_spaces("m3sBig") == "m3sBig"
    @test fix_spaces("Exa 1 2 ") == "Exa_1_2_"
    @test fix_spaces("BWnXhceAh") == "BWnXhceAh"
    @test fix_spaces("smpl   A---a-a-a---b-b-b-c-c-c----x   ece-") == "smpl-A---a-a-a---b-b-b-c-c-c----x-ece-"
    @test fix_spaces("XBWX") == "XBWX"
    @test fix_spaces("A-B-*_-C") == "A-B-*_-C"
    @test fix_spaces("  Big gaps    betwneen words   o in thce      ") == "-Big_gaps-betwneen_words-o_in_thce-"
    @test fix_spaces("  a                  ") == "-a-"
    @test fix_spaces("sp") == "sp"
    @test fix_spaces("mpsen3tenEExceees-") == "mpsen3tenEExceees-"
    @test fix_spaces("EExampEle") == "EExampEle"
    @test fix_spaces("BWnXAXhEEpxamplX") == "BWnXAXhEEpxamplX"
    @test fix_spaces("3tencehhce") == "3tencehhce"
    @test fix_spaces("   A-B--*mm_--C   mExampleplExa") == "-A-B--*mm_--C-mExampleplExa"
    @test fix_spaces("     gaps-- C  msen3tenceinp thcae") == "-gaps--_C-msen3tenceinp_thcae"
    @test fix_spaces("Exa 1 2 2 m psen3tencee") == "Exa_1_2_2_m_psen3tencee"
    @test fix_spaces("lmmple") == "lmmple"
    @test fix_spaces("secn3tExa 1 2 2 mpsent3tenceeencte") == "secn3tExa_1_2_2_mpsent3tenceeencte"
    @test fix_spaces("Exaisennmpsen3tencee3tennceinbet1 2 ") == "Exaisennmpsen3tencee3tennceinbet1_2_"
    @test fix_spaces("   Exa 1 2 2\nmple\tE  Big gaps    betwe2Big gaps    between words xExxEA-xEaEhxae   in thceeen words   o in thce          xample   3") == "-Exa_1_2_2\nmple\tE-Big_gaps-betwe2Big_gaps-between_words_xExxEA-xEaEhxae-in_thceeen_words-o_in_thce-xample-3"
    @test fix_spaces("    Examaple  2") == "-Examaple-2"
    @test fix_spaces("tben            3tencehhcebt") == "tben-3tencehhcebt"
    @test fix_spaces("betmEx    Example 2xaples") == "betmEx-Example_2xaples"
    @test fix_spaces("ebBig gaps    between words     in this sen3tenceetween") == "ebBig_gaps-between_words-in_this_sen3tenceetween"
    @test fix_spaces("A-B-*---a-a-a---b-b-b-c-c-c---_--C") == "A-B-*---a-a-a---b-b-b-c-c-c---_--C"
    @test fix_spaces("senbtenc") == "senbtenc"
    @test fix_spaces("BWn i Big         XAh") == "BWn_i_Big-XAh"
    @test fix_spaces("mmpleEsen3tenc") == "mmpleEsen3tenc"
    @test fix_spaces("Examplxe") == "Examplxe"
    @test fix_spaces("th   Exa 1 2 2\nmple\tExampale   3smp") == "th-Exa_1_2_2\nmple\tExampale-3smp"
    @test fix_spaces("tthhX") == "tthhX"
    @test fix_spaces("sen3tenwce") == "sen3tenwce"
    @test fix_spaces("EExEampEle") == "EExEampEle"
    @test fix_spaces("mpsen33tenceees") == "mpsen33tenceees"
    @test fix_spaces("  e A-B--*mm_--C   mExampleplExa") == "-e_A-B--*mm_--C-mExampleplExa"
    @test fix_spaces("tthhrwords") == "tthhrwords"
    @test fix_spaces("ebese3n   A-gap -C 3  tsExxEa") == "ebese3n-A-gap_-C_3-tsExxEa"
    @test fix_spaces("Big gaps    between words    in this sebSentencte") == "Big_gaps-between_words-in_this_sebSentencte"
    @test fix_spaces("     x ExamEEpxample 2  Example 2") == "-x_ExamEEpxample_2-Example_2"
    @test fix_spaces("Ex2ample") == "Ex2ample"
    @test fix_spaces("betms") == "betms"
    @test fix_spaces("  Big gaps    betweentthhcewords words   o in thce      ") == "-Big_gaps-betweentthhcewords_words-o_in_thce-"
    @test fix_spaces("smpl   A---a-a-a---b-b-b-c--c-c----x   ece-") == "smpl-A---a-a-a---b-b-b-c--c-c----x-ece-"
    @test fix_spaces("m    le    ple") == "m-le-ple"
    @test fix_spaces("BWnXpAXhEEpxamplX") == "BWnXpAXhEEpxamplX"
    @test fix_spaces("mmpleEsen3tenc  Big gaps    beBWnX         Ahtween words   o in thce          temexample  Big gaps    between words   o in thce          1") == "mmpleEsen3tenc-Big_gaps-beBWnX-Ahtween_words-o_in_thce-temexample-Big_gaps-between_words-o_in_thce-1"
    @test fix_spaces("gga   A-x   sen3tencce") == "gga-A-x-sen3tencce"
    @test fix_spaces("pl   A-B-*_--C  Big gaps    between words    in this sen3tence- ee") == "pl-A-B-*_--C-Big_gaps-between_words-in_this_sen3tence-_ee"
    @test fix_spaces("mpsen3ttenceemmpleExample  1s") == "mpsen3ttenceemmpleExample-1s"
    @test fix_spaces("mpsecmpscellee-lExa") == "mpsecmpscellee-lExa"
    @test fix_spaces("plmmple") == "plmmple"
    @test fix_spaces("lmmpletthhcewords") == "lmmpletthhcewords"
    @test fix_spaces("wo  Big            EEExample  1ds") == "wo-Big-EEExample-1ds"
    @test fix_spaces("Big gaps    between words    in s sentence") == "Big_gaps-between_words-in_s_sentence"
    @test fix_spaces("am") == "am"
    @test fix_spaces("Big gaps    bet ween words    in tsentence") == "Big_gaps-bet_ween_words-in_tsentence"
    @test fix_spaces("epBig gap        mples in thce") == "epBig_gap-mples_in_thce"
    @test fix_spaces("psen3tencee") == "psen3tencee"
    @test fix_spaces("A-gapsB--**_s--C") == "A-gapsB--**_s--C"
    @test fix_spaces("Big gaps    between words    iExaen this sen3tenwce") == "Big_gaps-between_words-iExaen_this_sen3tenwce"
    @test fix_spaces("th   Exa 1 2 2\nmmple\tExampale   3smp") == "th-Exa_1_2_2\nmmple\tExampale-3smp"
    @test fix_spaces("meaxaplle") == "meaxaplle"
    @test fix_spaces("   Exa 1 2 2\nmple\tE  Big gaps    betwe2Big gapmpsen3tenEExceees-between words xExxEA-xEaExae   in thceeen words   o in thce          xample   3") == "-Exa_1_2_2\nmple\tE-Big_gaps-betwe2Big_gapmpsen3tenEExceees-between_words_xExxEA-xEaExae-in_thceeen_words-o_in_thce-xample-3"
    @test fix_spaces("pBgig") == "pBgig"
    @test fix_spaces("A-gap--**_s--C") == "A-gap--**_s--C"
    @test fix_spaces("mmmpleExample") == "mmmpleExample"
    @test fix_spaces("mExa 1 2 2 mpl  Big            ExamExaple   2ee") == "mExa_1_2_2_mpl-Big-ExamExaple-2ee"
    @test fix_spaces("ExampleEx1") == "ExampleEx1"
    @test fix_spaces("ggasenp3tenp") == "ggasenp3tenp"
    @test fix_spaces("XBWXX") == "XBWXX"
    @test fix_spaces("betwneen") == "betwneen"
    @test fix_spaces("2hcee") == "2hcee"
    @test fix_spaces("BWnplX") == "BWnplX"
    @test fix_spaces("2xExa") == "2xExa"
    @test fix_spaces("pBgiBg") == "pBgiBg"
    @test fix_spaces("EA---a-a-a---b-b-b-c-c-c----x2 mpsent3tencee") == "EA---a-a-a---b-b-b-c-c-c----x2_mpsent3tencee"
    @test fix_spaces("t Biig gaps  e  between wordshis    in thce  his") == "t_Biig_gaps-e-between_wordshis-in_thce-his"
    @test fix_spaces("Big  gaps    between words    in this sen3tence") == "Big-gaps-between_words-in_this_sen3tence"
    @test fix_spaces("bteet") == "bteet"
    @test fix_spaces("mpsen33temmpleEmexample  Big gaps    between words   o in thce          1nceees") == "mpsen33temmpleEmexample-Big_gaps-between_words-o_in_thce-1nceees"
    @test fix_spaces("BWnAXAh") == "BWnAXAh"
    @test fix_spaces("BWnXAXhEEpxampllX") == "BWnXAXhEEpxampllX"
    @test fix_spaces("senbtence") == "senbtence"
    @test fix_spaces("ampl3tencehhcele") == "ampl3tencehhcele"
    @test fix_spaces("mfKqrpAGAlpleE1") == "mfKqrpAGAlpleE1"
    @test fix_spaces("   A-gaps-B-*_*Bigmpsent3tencee    in this sentence--C -  ") == "-A-gaps-B-*_*Bigmpsent3tencee-in_this_sentence--C_--"
    @test fix_spaces("  Bigi        ") == "-Bigi-"
    @test fix_spaces("mmpleExA-_B--*_--Cample p 1") == "mmpleExA-_B--*_--Cample_p_1"
    @test fix_spaces("   Exa 1 2 2\nmple\tE  Big gaps    betwe2Big gaps    between words xEx     xEA-xEaExae   in thceeen words   o in thce          xample   3") == "-Exa_1_2_2\nmple\tE-Big_gaps-betwe2Big_gaps-between_words_xEx-xEA-xEaExae-in_thceeen_words-o_in_thce-xample-3"
    @test fix_spaces("smpl   A---a-a-a---bisennmpsen3tencee3tenncein-b-b-c--c-c----x   ece-") == "smpl-A---a-a-a---bisennmpsen3tencee3tenncein-b-b-c--c-c----x-ece-"
    @test fix_spaces("A-Bb-c-c-c---_--C") == "A-Bb-c-c-c---_--C"
    @test fix_spaces("tbsenbtencet") == "tbsenbtencet"
    @test fix_spaces("Big gaps    bet weens    in this senbtenc   A-gapsBmplsExa 1 2 2 mpsen3tenEExceees- e") == "Big_gaps-bet_weens-in_this_senbtenc-A-gapsBmplsExa_1_2_2_mpsen3tenEExceees-_e"
    @test fix_spaces("Exaisennmpsen3tencee3tennceinbet1") == "Exaisennmpsen3tencee3tennceinbet1"
    @test fix_spaces("   xExxEA-xEaExae  Ethcele  1 ") == "-xExxEA-xEaExae-Ethcele-1_"
    @test fix_spaces("Bmpsent3tenceetween words   ") == "Bmpsent3tenceetween_words-"
    @test fix_spaces("A-Bf-*_-mfKqrpAGApleE1C") == "A-Bf-*_-mfKqrpAGApleE1C"
    @test fix_spaces("crdsExamplxe") == "crdsExamplxe"
    @test fix_spaces("betmEx    Epxample 2xaples") == "betmEx-Epxample_2xaples"
    @test fix_spaces("A-gapsBmplsExa") == "A-gapsBmplsExa"
    @test fix_spaces("mmmp") == "mmmp"
    @test fix_spaces(" Big gaps    between words   Big         in ") == "_Big_gaps-between_words-Big-in_"
    @test fix_spaces("   A-B--ExamEA-gapsB-rNfUBspa*_---Caple*_--C   mplEx") == "-A-B--ExamEA-gapsB-rNfUBspa*_---Caple*_--C-mplEx"
    @test fix_spaces("mpsen33temmpleEe          1nceees") == "mpsen33temmpleEe-1nceees"
    @test fix_spaces("senbteenc") == "senbteenc"
    @test fix_spaces("ExapleEx") == "ExapleEx"
    @test fix_spaces("thisebBig") == "thisebBig"
    @test fix_spaces("mpl   A-C-x   ") == "mpl-A-C-x-"
    @test fix_spaces("EamExbetwe    Ethcele  1 enlae") == "EamExbetwe-Ethcele-1_enlae"
    @test fix_spaces("Exa 1 2 2 mpExample  1  Big        sen3tencee") == "Exa_1_2_2_mpExample-1-Big-sen3tencee"
    @test fix_spaces("ebBigmp") == "ebBigmp"
    @test fix_spaces("pBig gap   *_--C     mples    ebSbetween wo rds    in thce") == "pBig_gap-*_--C-mples-ebSbetween_wo_rds-in_thce"
    @test fix_spaces("E   Ethcele  1 enlae") == "E-Ethcele-1_enlae"
    @test fix_spaces("mmmm") == "mmmm"
    @test fix_spaces("mpsen3ttenceemmpple") == "mpsen3ttenceemmpple"
    @test fix_spaces("1nceees") == "1nceees"
end
