@testitem "143_words_in_sentence_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "143_words_in_sentence.jl"))
    @test words_in_sentence("cats and dogs") == "and"
    @test words_in_sentence("I am a developer") == "am"
    @test words_in_sentence("elephants are huge") == "are"
    @test words_in_sentence("the quick brown fox jumps over the lazy dog") == "the quick brown fox jumps the dog"
    @test words_in_sentence("this code challenge is tricky") == "is"
    @test words_in_sentence("Python programming is fun") == "programming is fun"
    @test words_in_sentence("mathematics can be easy") == "mathematics can be"
    @test words_in_sentence("writing clean code is important") == "writing clean is"
    @test words_in_sentence("I love eating pizza") == "pizza"
    @test words_in_sentence("quick sort algorithm is efficient") == "quick is"
    @test words_in_sentence("I am a dquick sort algorithm is efficienteveloper") == "am is efficienteveloper"
    @test words_in_sentence("mathematics can be eacsy") == "mathematics can be eacsy"
    @test words_in_sentence("eleephants are huge") == "are"
    @test words_in_sentence("Python programmingg is fun") == "is fun"
    @test words_in_sentence("this code schallenge is tricky") == "is"
    @test words_in_sentence("this code mathematics can be eacsychalleI love eating pizzangge is tricky") == "mathematics can be is"
    @test words_in_sentence("I athe quick brown fox jumps over the lazy dogm a developer") == "quick brown fox jumps the"
    @test words_in_sentence("Io love eaI love eating pizzaquick sort algorithm is efficientting pizza") == "Io eaI is efficientting pizza"
    @test words_in_sentence("this acode mathematics can be eacsychalleI love eating pizzangge is tricky") == "acode mathematics can be is"
    @test words_in_sentence("Io love eaI love eating pizort algorithm is efficientting pizza") == "Io eaI is efficientting pizza"
    @test words_in_sentence("I athe qurown fox jumps over the lazy dogm a developer") == "fox jumps the"
    @test words_in_sentence("quick sort algoritI love eating pizzahm is efficient") == "quick pizzahm is"
    @test words_in_sentence("this code challenge is triycky") == "is triycky"
    @test words_in_sentence("I am a dquick sort algorithm isp efficientevelope r") == "am isp"
    @test words_in_sentence("eleepnhantselephanpts are huge are huge") == "are are"
    @test words_in_sentence("I am a deper") == "am deper"
    @test words_in_sentence("Pyththe quick brown fox jumps over the lazy dogon programming is fun") == "Pyththe quick brown fox jumps the dogon programming is fun"
    @test words_in_sentence("this code schayllenge is tricky") == "schayllenge is"
    @test words_in_sentence("thse quick brown fox jumps over the lazy dog") == "quick brown fox jumps the dog"
    @test words_in_sentence("I am a dquick sort algorithm is efficientthis code challenge is triyqckyeveloper") == "am is efficientthis is"
    @test words_in_sentence("quick soithm is efficient") == "quick is"
    @test words_in_sentence("eleepnhantselepmathematics can be easyhanpts are huge are huge") == "can be are are"
    @test words_in_sentence("quick sort algoritI love eaating pizzahm is efficient") == "quick eaating pizzahm is"
    @test words_in_sentence("elephants are hugeIo love eaI love eating pizort algorithm is efficientting pizza") == "are eaI is efficientting pizza"
    @test words_in_sentence("this code schayllI am a dquick sort algorithm is efficienteveloperenge is tricky") == "am is is"
    @test words_in_sentence("quick sort algorithm iselephants are hugeIo love eaI love eating pizort icient") == "quick iselephants are eaI"
    @test words_in_sentence("thse q the lazy dog") == "the dog"
    @test words_in_sentence("I am a deveoper") == "am"
    @test words_in_sentence("I athe qurown fox jumps over the lazy dogm a developethse q the lazy dog") == "fox jumps the the dog"
    @test words_in_sentence("this code e is tricky") == "is"
    @test words_in_sentence("mahthematics can be easy") == "can be"
    @test words_in_sentence("I athe quick brown fox jumpthis code e is trickys over the lazy dogm a ddeveloper") == "quick brown fox is trickys the"
    @test words_in_sentence("Io love eaI love eting pizort algorithm is efficientting pizza") == "Io eaI eting is efficientting pizza"
    @test words_in_sentence("I am a deveopthis code mathematics can be eacsychalleI love eating pizzangge is trickyer") == "am mathematics can be is"
    @test words_in_sentence("I am ad deveoper") == "am ad"
    @test words_in_sentence("mahthematics can be e asy") == "can be asy"
    @test words_in_sentence("Pythothis code mathematics can be eacsychalleI love eating pizzangge is trickyprogrammingg is fun") == "mathematics can be is is fun"
    @test words_in_sentence("quick soithmc ihs efficient") == "quick soithmc ihs"
    @test words_in_sentence("I Io love eaI love eating pizort aligorithm is effIicientting pizzaeloper") == "Io eaI is pizzaeloper"
    @test words_in_sentence("I am a dquick sort algorithm is efficienteveloperr") == "am is"
    @test words_in_sentence("I am a dquick sort algorithm is efficienttehis code challenge is triyqckyeveloper") == "am is is"
    @test words_in_sentence("quick sort algoritI love eating pizzahm ist") == "quick pizzahm ist"
    @test words_in_sentence("mahthematics can bI athe qurown fox jumps over the lazy dogm a developethse q the lazy dog asy") == "can bI fox jumps the the dog asy"
    @test words_in_sentence("Pyththe quick brown fox jumps over the lazy dogon proeleephants are hugegramming is fun") == "Pyththe quick brown fox jumps the dogon proeleephants are is fun"
    @test words_in_sentence("I am a develthis code schayllI am a dquick sort algorithm is efficienteveloperenge is trickyoper") == "am am is is"
    @test words_in_sentence("quick sort algoritI love this code schallenge is trickyeating pizzahm is efficient") == "quick is pizzahm is"
    @test words_in_sentence("writing clean code iis rimportant") == "writing clean iis"
    @test words_in_sentence("qu ick sort algoritI love eaating pizzahm is efficzient") == "qu ick eaating pizzahm is"
    @test words_in_sentence("qu ick sort algoritI love eaating pizzvahm is efficzient") == "qu ick eaating is"
    @test words_in_sentence("thisI am a dquick sort algorithm is efficienteveloperchayllenge is tricky") == "thisI am is is"
    @test words_in_sentence("quick sort algoritefficient") == "quick"
    @test words_in_sentence("I Io love eaI love eating pizort aligorithm is efpfIicientting pizzaeloper") == "Io eaI is pizzaeloper"
    @test words_in_sentence("eleepnhantselephanpts are hthis code e is trickyuge are huge") == "are hthis is are"
    @test words_in_sentence("Pyththe quick brown fox jumps over the lazy dogon programmi ng is fun") == "Pyththe quick brown fox jumps the dogon ng is fun"
    @test words_in_sentence("my") == "my"
    @test words_in_sentence("quick soithmc ihs efficientt") == "quick soithmc ihs"
    @test words_in_sentence("eleeeuge") == ""
    @test words_in_sentence("Python ogramming is fun") == "is fun"
    @test words_in_sentence("I am a deveopI Io love eaI love eating pizort aligorithm is efpfIicientting pizzaeloperer") == "am deveopI Io eaI is pizzaeloperer"
    @test words_in_sentence("mahthematics can bI athe qurown fox jumps over the lazy dogm a developeog asy") == "can bI fox jumps the asy"
    @test words_in_sentence("Io love eaI love eatingr pizort palgorithm is efficientting pizza") == "Io eaI eatingr is efficientting pizza"
    @test words_in_sentence("PythothisI am a dquick sort algorithm is efficienteveloperchayllenge is trickyng is fun") == "am is is is fun"
    @test words_in_sentence("Pyththe quick brown fox jumps over the lazy dogonleephants are hugegramming ins fun") == "Pyththe quick brown fox jumps the are ins fun"
    @test words_in_sentence("this code schayllI am a dqk sort algorithm is efficienteveloperenge is tricky") == "am dqk is is"
    @test words_in_sentence("quick sort algoritI love eating phm is efficient") == "quick phm is"
    @test words_in_sentence("Pyththe quick brown fox jumps over the lazy dogonleephants I am a developerare hugegramming ins fun") == "Pyththe quick brown fox jumps the am ins fun"
    @test words_in_sentence("mahthematics can be easty") == "can be easty"
    @test words_in_sentence("qu ick sort algoritI love eaating pizzvahm is efficzeient") == "qu ick eaating is efficzeient"
    @test words_in_sentence("I am a dedveopthis code mathematics can be eacsychalleI love eating pizzangge is trickyer") == "am dedveopthis mathematics can be is"
    @test words_in_sentence("eleepnhantsethis code challenge is triyckyhuge are huge") == "is triyckyhuge are"
    @test words_in_sentence("mathematI love eating pizzaics can be eacsy") == "can be eacsy"
    @test words_in_sentence("thse quick brown fox jumps oover the lazy dog") == "quick brown fox jumps oover the dog"
    @test words_in_sentence("writing tclean code is importamathematI love eating pizzaics can be eacsynt") == "writing is can be eacsynt"
    @test words_in_sentence("quick soithmc ihs efI am a developerficient") == "quick soithmc ihs efI am"
    @test words_in_sentence("I am a depethisI am a dquick sort algorithm is efficienteveloperchayllenge is trickyr") == "am am is is trickyr"
    @test words_in_sentence("quick sI am ad deveopercient") == "quick sI am ad deveopercient"
    @test words_in_sentence("cquick sort algorithm is efficient") == "is"
    @test words_in_sentence("quick soitc ihs uefficient") == "quick soitc ihs"
    @test words_in_sentence("quick sort alsgoritI love this code sct") == "quick sct"
    @test words_in_sentence("I enge is trickyr") == "is trickyr"
    @test words_in_sentence("I am ad deveo per") == "am ad deveo per"
    @test words_in_sentence("quick sort algorithm is efficI am a dquick sort algorithm isp efficientevelope rient") == "quick is am isp rient"
    @test words_in_sentence("thse quick brown fox jumps oover the ladog") == "quick brown fox jumps oover the ladog"
    @test words_in_sentence("quick soithmc ihs effkicientt") == "quick soithmc ihs effkicientt"
    @test words_in_sentence("mat hematics can be eacsy") == "mat can be eacsy"
    @test words_in_sentence("tPython programming is fun") == "tPython programming is fun"
    @test words_in_sentence("I Io love eaI love eating pizort taligorithm is efpfIicientting pizzaeloper") == "Io eaI taligorithm is pizzaeloper"
    @test words_in_sentence("I") == ""
    @test words_in_sentence("Io love eaI love eatingr pizort palgor ithm is efficientting pizza") == "Io eaI eatingr is efficientting pizza"
    @test words_in_sentence("tPython programm ing is fun") == "tPython ing is fun"
    @test words_in_sentence("science some has branches of") == "science has of"
    @test words_in_sentence("one two three four five six seven eight nine") == "one two three six seven eight"
    @test words_in_sentence("abcdefghijklmnopqrstuvwxyz abc defghijklmnopqrstuvwxyz") == "abc defghijklmnopqrstuvwxyz"
    @test words_in_sentence("aa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaa") == "aa"
    @test words_in_sentence("this is a test for prime numbers in words within a sentence") == "is for prime numbers in words"
    @test words_in_sentence("The quick brown fox jumps over the lazy dog") == "The quick brown fox jumps the dog"
    @test words_in_sentence("The cat in the hat sat on the mat") == "The cat in the hat sat on the mat"
    @test words_in_sentence("Peter Piper picked a peck of pickled peppers") == "Peter Piper of pickled peppers"
    @test words_in_sentence("An apple a day keeps the doctor away") == "An apple day keeps the"
    @test words_in_sentence("The cat in tofhe ahat sat on the mat") == "The cat in tofhe sat on the mat"
    @test words_in_sentence("doctor") == ""
    @test words_in_sentence("test") == ""
    @test words_in_sentence("picaaaaaad") == ""
    @test words_in_sentence("eight") == "eight"
    @test words_in_sentence("aa aaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaa") == "aa aaa"
    @test words_in_sentence("abcdefghijklmnopqrstuvwxyz") == ""
    @test words_in_sentence("doctaaaaor") == ""
    @test words_in_sentence("Peter Piper picked a peck of pipers") == "Peter Piper of"
    @test words_in_sentence("The quicdoctorown fox jumps over the lazy dog") == "The quicdoctorown fox jumps the dog"
    @test words_in_sentence("abcpipers") == ""
    @test words_in_sentence("six") == "six"
    @test words_in_sentence("aabcaaaaa") == ""
    @test words_in_sentence("zudeUmy") == "zudeUmy"
    @test words_in_sentence("fox") == "fox"
    @test words_in_sentence("clwFZYzs") == ""
    @test words_in_sentence("aaaaaa") == ""
    @test words_in_sentence("pcicaaaaaad") == "pcicaaaaaad"
    @test words_in_sentence("Peter Piper psomeicked a peck of pickled peppers") == "Peter Piper of pickled peppers"
    @test words_in_sentence("The cat in tofhe ahat asat on thte mat") == "The cat in tofhe on mat"
    @test words_in_sentence("P eter Piper picked a peck of pickled peppers") == "Piper of pickled peppers"
    @test words_in_sentence("clwZFZYzs") == ""
    @test words_in_sentence("aabcaaaaaa") == ""
    @test words_in_sentence("tesst") == "tesst"
    @test words_in_sentence("ELBDOeWCp") == ""
    @test words_in_sentence("fodoctorx") == ""
    @test words_in_sentence("eighpeck") == ""
    @test words_in_sentence("dooctaaaaor") == "dooctaaaaor"
    @test words_in_sentence("Peter Piper picked a peck of picklled peppers") == "Peter Piper of peppers"
    @test words_in_sentence("wFZYzs") == ""
    @test words_in_sentence("The cat in tofhe aha t asat on thte mat") == "The cat in tofhe aha on mat"
    @test words_in_sentence("aa aaaa aaaaaa aaaaaaaa aaaathteaaaaaaaa aaaaaaaaaaaaaaaaaaaa") == "aa"
    @test words_in_sentence("doaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("wFZYs") == "wFZYs"
    @test words_in_sentence("doctaaaaorfoforr") == ""
    @test words_in_sentence("brown") == "brown"
    @test words_in_sentence("doctaaaaorfoftorr") == "doctaaaaorfoftorr"
    @test words_in_sentence("ffox") == ""
    @test words_in_sentence("nine") == ""
    @test words_in_sentence("Pk of pickled peppers") == "Pk of pickled peppers"
    @test words_in_sentence("a") == ""
    @test words_in_sentence("seven") == "seven"
    @test words_in_sentence("psomeicked") == ""
    @test words_in_sentence("aa aaa aaaaaaaa aaaaaaa") == "aa aaa aaaaaaa"
    @test words_in_sentence("this is a test for prime numbers in words wit hin a sentence") == "is for prime numbers in words wit hin"
    @test words_in_sentence("doctthreefooftorr") == "doctthreefooftorr"
    @test words_in_sentence("abcyz") == "abcyz"
    @test words_in_sentence("doaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaAnaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("browrn") == ""
    @test words_in_sentence("Peter Piper pipcked a peck of pickled peppers") == "Peter Piper pipcked of pickled peppers"
    @test words_in_sentence("picked") == ""
    @test words_in_sentence("tofhe") == "tofhe"
    @test words_in_sentence("wit") == "wit"
    @test words_in_sentence("aaa aaa aaaaaaaa aaaaaaa") == "aaa aaa aaaaaaa"
    @test words_in_sentence("aaaaaaa") == "aaaaaaa"
    @test words_in_sentence("aabcnsatumbersaaaaa") == "aabcnsatumbersaaaaa"
    @test words_in_sentence("twnumboneers") == ""
    @test words_in_sentence("doctthrePeter Piper picked a peck of picklled peppersefooftorr") == "doctthrePeter Piper of"
    @test words_in_sentence("hat") == "hat"
    @test words_in_sentence("sciencedoctaaaaor") == "sciencedoctaaaaor"
    @test words_in_sentence("tbwnumboneers") == "tbwnumboneers"
    @test words_in_sentence("aa") == "aa"
    @test words_in_sentence("aa aaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaa") == "aa aaa"
    @test words_in_sentence("three") == "three"
    @test words_in_sentence("lazy") == ""
    @test words_in_sentence("docctor") == "docctor"
    @test words_in_sentence("lazynumbers") == "lazynumbers"
    @test words_in_sentence("jumps") == "jumps"
    @test words_in_sentence("siis") == ""
    @test words_in_sentence("The quicdoctorown fox jumps over thed lazy dog") == "The quicdoctorown fox jumps dog"
    @test words_in_sentence("aha") == "aha"
    @test words_in_sentence("doaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaasixaaaaaaactor") == ""
    @test words_in_sentence("pipcked") == "pipcked"
    @test words_in_sentence("peppersefoofrtorr") == "peppersefoofrtorr"
    @test words_in_sentence("aaaaa") == "aaaaa"
    @test words_in_sentence("The cat in tofhe ahat sat onaabcnsatumbersaaaaa the mat") == "The cat in tofhe sat the mat"
    @test words_in_sentence("P") == ""
    @test words_in_sentence("Peter Piper pickepd a peck of picklled peppers") == "Peter Piper pickepd of peppers"
    @test words_in_sentence("browrnsix") == ""
    @test words_in_sentence("pickedwit") == ""
    @test words_in_sentence("science sofhas branches oaf") == "science oaf"
    @test words_in_sentence("aaaaaaaaaaaaaaaaaaaa") == ""
    @test words_in_sentence("aahin") == "aahin"
    @test words_in_sentence("one") == "one"
    @test words_in_sentence("aaaaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("awordsbc") == ""
    @test words_in_sentence("browrisnsix") == "browrisnsix"
    @test words_in_sentence("science sofhas branches otwoaf") == "science"
    @test words_in_sentence("doaa aaatbwnumboneersa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaasixaaaaaaactor") == "aaatbwnumboneersa"
    @test words_in_sentence("Peter Piper psomeicked a peck of piP eter Piper picked a peck of pickled peppersckled peppers") == "Peter Piper of piP Piper of pickled peppers"
    @test words_in_sentence("abcppipeThears") == ""
    @test words_in_sentence("defghijklmnopqrstuvwxyzbrowrn") == "defghijklmnopqrstuvwxyzbrowrn"
    @test words_in_sentence("ahat") == ""
    @test words_in_sentence("fffopipersx") == "fffopipersx"
    @test words_in_sentence("asatdooctaaaaor") == ""
    @test words_in_sentence("cat") == "cat"
    @test words_in_sentence("thed") == ""
    @test words_in_sentence("abc") == "abc"
    @test words_in_sentence("si") == "si"
    @test words_in_sentence("ssi") == "ssi"
    @test words_in_sentence("piP") == "piP"
    @test words_in_sentence("doctaaaaoraahin") == ""
    @test words_in_sentence("has") == "has"
    @test words_in_sentence("Piper") == "Piper"
    @test words_in_sentence("psoed") == "psoed"
    @test words_in_sentence("jmumps") == ""
    @test words_in_sentence("caaaaaaaaaaaaaasixaaaaaaactor") == "caaaaaaaaaaaaaasixaaaaaaactor"
    @test words_in_sentence("aaaathteaaaaaaaaa") == "aaaathteaaaaaaaaa"
    @test words_in_sentence("aa aahina aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaa") == "aa"
    @test words_in_sentence("aa aaa aaaaaaaa aaaaabrowrnaa") == "aa aaa aaaaabrowrnaa"
    @test words_in_sentence("aa aaaa aaaaaa aaaapiPaaaa aaaathteaaaaaaaa aaaaaaaaaaaaaaaaaaaa") == "aa aaaapiPaaaa"
    @test words_in_sentence("doctaaaaorrfoforor") == ""
    @test words_in_sentence("s") == ""
    @test words_in_sentence("fffox") == "fffox"
    @test words_in_sentence("oaf") == "oaf"
    @test words_in_sentence("doaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaactoar") == ""
    @test words_in_sentence("The quicdoctorown fox jumps over thed layzy dog") == "The quicdoctorown fox jumps layzy dog"
    @test words_in_sentence("browrnjumps") == "browrnjumps"
    @test words_in_sentence("eter") == ""
    @test words_in_sentence("aaaAnaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("iss") == "iss"
    @test words_in_sentence("doaa aaaa aaaaaaa aaaaaaaa aaaaaaaaaaaa aaaAnaaaaaaaaaaaaaaaaactor") == "aaaaaaa"
    @test words_in_sentence("bropickledn") == "bropickledn"
    @test words_in_sentence("PP") == "PP"
    @test words_in_sentence("oabcpipersttwoaf") == ""
    @test words_in_sentence("prime") == "prime"
    @test words_in_sentence("aa aaaa aaaaaajmumps aaaaaaaa aaaathteaaaaaaaa aaaaaaaaaaaaaaaaaaaa") == "aa"
    @test words_in_sentence("doctthrek of picklled peppersefooftorr") == "of"
    @test words_in_sentence("docttThehrek") == ""
    @test words_in_sentence("over") == ""
    @test words_in_sentence("ipicked") == "ipicked"
    @test words_in_sentence("brosiispickledn") == ""
    @test words_in_sentence("ccat") == ""
    @test words_in_sentence("quick") == "quick"
    @test words_in_sentence("Peter Piper psomeicked a epeck of piP eter Piper picked a peck of pickleld peppersckled peppers") == "Peter Piper epeck of piP Piper of peppers"
    @test words_in_sentence("fodoccto") == ""
    @test words_in_sentence("abcy") == ""
    @test words_in_sentence("pThe cat in the hat sat on the matrime") == "cat in the hat sat on the matrime"
    @test words_in_sentence("aassibcnsatumbersaaaaa") == ""
    @test words_in_sentence("uicdoctorown fox jumps over the lazy dog") == "fox jumps the dog"
    @test words_in_sentence("aa aaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaapicklledaaa") == "aa aaa"
    @test words_in_sentence("pickedquick") == "pickedquick"
    @test words_in_sentence("aahina") == ""
    @test words_in_sentence("abcppiapeTheaars") == ""
    @test words_in_sentence("pickeddquick") == ""
    @test words_in_sentence("aahinP eter Piper picked a peck of pickled peppersa") == "Piper of pickled"
    @test words_in_sentence("wiit") == ""
    @test words_in_sentence("doctthreefoolazynumbersftorr") == ""
    @test words_in_sentence("ahhat") == "ahhat"
    @test words_in_sentence("brosiispsickledn") == ""
    @test words_in_sentence("sentence") == ""
    @test words_in_sentence("P eter Piperkeepsrs") == ""
    @test words_in_sentence("pidckedwit") == ""
    @test words_in_sentence("doctoaaaaorfoforr") == "doctoaaaaorfoforr"
    @test words_in_sentence("atwohhat") == ""
    @test words_in_sentence("aahinP etpTheer Piper picked a peck of pickled peppersas") == "Piper of pickled"
    @test words_in_sentence("haas") == ""
    @test words_in_sentence("on") == "on"
    @test words_in_sentence("aaa aaa aaaaaaaa aaaaabrowrnaaaaaaaaaaaaaasixaaaaaaactora") == "aaa aaa"
    @test words_in_sentence("scxdLYL") == "scxdLYL"
    @test words_in_sentence("aahinP") == ""
    @test words_in_sentence("aaaaabrowrnaa") == "aaaaabrowrnaa"
    @test words_in_sentence("The cat min tofhe aha t asat on thte mat") == "The cat min tofhe aha on mat"
    @test words_in_sentence("witscience sofhas branchess oawf") == ""
    @test words_in_sentence("wsFZYzs") == "wsFZYzs"
    @test words_in_sentence("quuick") == ""
    @test words_in_sentence("aaaapiPaaaa") == "aaaapiPaaaa"
    @test words_in_sentence("abcyaabcaaaaaaz") == ""
    @test words_in_sentence("The quicdoctorown fox jumps over the ldog") == "The quicdoctorown fox jumps the"
    @test words_in_sentence("aaa aaa aaaaaaasixaaaaaaactora") == "aaa aaa"
    @test words_in_sentence("aaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaapiPaaaa") == "aaa"
    @test words_in_sentence("aaaaaaaaaaaaaaaaaaaactoar") == ""
    @test words_in_sentence("forx") == ""
    @test words_in_sentence("one two three four five six seven eight peppersnine") == "one two three six seven eight peppersnine"
    @test words_in_sentence("defghiabcpipersjklmnopqrstuvwxyzbrowrn") == ""
    @test words_in_sentence("eeter") == "eeter"
    @test words_in_sentence("aathedaaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("aaaaaaaaaaapipersaaaaaaaaactoar") == "aaaaaaaaaaapipersaaaaaaaaactoar"
    @test words_in_sentence("doaa aaaa aaaaaa aaaaaaaa aaaaar") == ""
    @test words_in_sentence("one two three four five siThe quicdoctorown fox jumps over thed lazy dogx seven eight peppersnine") == "one two three siThe quicdoctorown fox jumps seven eight peppersnine"
    @test words_in_sentence("fffokeepsx") == ""
    @test words_in_sentence("ELBDkeepsOaa aaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaeWCp") == "aaa"
    @test words_in_sentence("t") == ""
    @test words_in_sentence("fffopiprersx") == ""
    @test words_in_sentence("defghijklmnopqrstu") == ""
    @test words_in_sentence("eiPeter Piper picked a peck of picklled peppersghpeck") == "eiPeter Piper of peppersghpeck"
    @test words_in_sentence("quicdoctorown") == "quicdoctorown"
    @test words_in_sentence("acaaaaaaaaaaaaaasixaaaaaaactora") == "acaaaaaaaaaaaaaasixaaaaaaactora"
    @test words_in_sentence("abcppiapeaTheaars") == "abcppiapeaTheaars"
    @test words_in_sentence("ewitscienaa aahina aaaaaaaa aaappleaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaceeter") == "ewitscienaa aaappleaaaaaaaaaa"
    @test words_in_sentence("aaaaaaaaaaaaaaabrowrnaaaactor") == "aaaaaaaaaaaaaaabrowrnaaaactor"
    @test words_in_sentence("Peter Piper pickAn apple a day keeps the doctor awayepd a peck of picklled peppers") == "Peter Piper apple day keeps the awayepd of peppers"
    @test words_in_sentence("bropickpleldn") == "bropickpleldn"
    @test words_in_sentence("pickediwit") == ""
    @test words_in_sentence("defghijkaaaalmnopqrstu") == ""
    @test words_in_sentence("doaa aaatbwnumboneersa aaaaaa aaaaaaaa aaaaaaaatwnumboneersaaaaasixaaaaaaactor") == "aaatbwnumboneersa"
    @test words_in_sentence("quicka") == ""
    @test words_in_sentence("aawfoura") == ""
    @test words_in_sentence("qpThek") == ""
    @test words_in_sentence("doctthrePeter Piper picked a peck of pickllfed peppersefooftorr") == "doctthrePeter Piper of"
    @test words_in_sentence("aaaaaaaaaaaaaaaaaaaaaceeter") == ""
    @test words_in_sentence("pctwoicaaaaaad") == ""
    @test words_in_sentence("ffaaaaaaox") == ""
    @test words_in_sentence("spiP") == ""
    @test words_in_sentence("aaaapiThe cat in tofhe aha t asat on thte matPaaaa") == "cat in tofhe aha on"
    @test words_in_sentence("dtoctaaaaorrfoforor") == "dtoctaaaaorrfoforor"
    @test words_in_sentence("aaaaaaaaaaaaaaaaapicklledaaa") == ""
    @test words_in_sentence("ipipcked") == ""
    @test words_in_sentence("ly") == "ly"
    @test words_in_sentence("The quick broELBDOeWCp") == "The quick"
    @test words_in_sentence("Yzs") == "Yzs"
    @test words_in_sentence("apple") == "apple"
    @test words_in_sentence("aahihhna") == ""
    @test words_in_sentence("aa aaaa aaaaaaaa aaaaaaa") == "aa aaaaaaa"
    @test words_in_sentence("Tat on tmat") == "Tat on"
    @test words_in_sentence("aa aaa aaaaaabrowrnsixa aaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaa") == "aa aaa aaaaaaaaaaaaa"
    @test words_in_sentence("ewitscienaa aahina aaaaaaaa aaappleaaaaaaaaaa aaaaapaaaaaaaaaaaaaaaaceeter") == "ewitscienaa aaappleaaaaaaaaaa"
    @test words_in_sentence("aaa aaaa aaaaaa aaaaaaaa aaaaahatapiPaaaa") == "aaa"
    @test words_in_sentence("quicdoctn") == ""
    @test words_in_sentence("aahinP etpTheer Pipaer picked a peck of picklersas") == "of"
    @test words_in_sentence("asatdooctor") == "asatdooctor"
    @test words_in_sentence("fthteffokeepsx") == ""
    @test words_in_sentence("twnumboeers") == "twnumboeers"
    @test words_in_sentence("ipickeed") == ""
    @test words_in_sentence("aa aahina aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaa") == "aa"
    @test words_in_sentence("aaa aapeppersefooftorra aaaaaaasixaaaaaaactora") == "aaa aapeppersefooftorra"
    @test words_in_sentence("ahhateight") == ""
    @test words_in_sentence("brosiispicklledn") == ""
    @test words_in_sentence("aa aaa aaaaaaaa aaaaa aa") == "aa aaa aaaaa aa"
    @test words_in_sentence("ss") == "ss"
    @test words_in_sentence("docotthrek of picklled peppersefooftorr") == "of"
    @test words_in_sentence("aabcyaabcaaaaaaz") == ""
    @test words_in_sentence("The quicdoct fox jumps over the lazy dsog") == "The fox jumps the"
    @test words_in_sentence("ffaaaaahatapiPaaaaaaaaaaox") == ""
    @test words_in_sentence("quicdoct") == ""
    @test words_in_sentence("peck") == ""
    @test words_in_sentence("docotthrek") == ""
    @test words_in_sentence("aahinP eter Piper picked a peck of pickled peppersaeighpeck") == "Piper of pickled"
    @test words_in_sentence("one two three four five six seforxven eight nine") == "one two three six eight"
    @test words_in_sentence("bropickplpidckedwiteldn") == "bropickplpidckedwiteldn"
    @test words_in_sentence("tbwnumboneoers") == ""
    @test words_in_sentence("aahinP eter Piper piceppersa") == "Piper"
    @test words_in_sentence("doaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaAnaaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("sss") == "sss"
    @test words_in_sentence("etetpTheerest") == "etetpTheerest"
    @test words_in_sentence("aaatbwnumboneersadoctor") == "aaatbwnumboneersadoctor"
    @test words_in_sentence("ewitscienaa aahina aaaaaaaa aaappleaaaaaaaaaa aaaaapaaaaaaaaaaaaaaaaceePeterter") == "ewitscienaa aaappleaaaaaaaaaa"
    @test words_in_sentence("quickaaahinP") == ""
    @test words_in_sentence("aaa aaa aaaaaaaa aixaaaaaaactora") == "aaa aaa"
    @test words_in_sentence("aworddsbc") == ""
    @test words_in_sentence("eTtetpTheerest") == ""
    @test words_in_sentence("wordswsFZYdoctaaaaorrfofororzsaa aaaa aaaaaaaa aaaaaaa") == "aaaaaaa"
    @test words_in_sentence("matrime") == "matrime"
    @test words_in_sentence("faa aaaa aaaaaajmumps aaaaaaaa aaaathteaaaaaaaa aaaaaaaaaaaaaaaaaaaathteffokeepsx") == "faa"
    @test words_in_sentence("abcppipeTheminars") == "abcppipeTheminars"
    @test words_in_sentence("atwohsomehat") == ""
    @test words_in_sentence("wordds") == ""
    @test words_in_sentence("matsix") == ""
    @test words_in_sentence("lzazy") == "lzazy"
    @test words_in_sentence("caaaaaaaaaaaaaasixaor") == ""
    @test words_in_sentence("quuuick") == "quuuick"
    @test words_in_sentence("abcdefghaahinP eter Piper piceppersawxyz") == "Piper"
    @test words_in_sentence("hhin") == ""
    @test words_in_sentence("apbcppieminars") == ""
    @test words_in_sentence("aa aaa a") == "aa aaa"
    @test words_in_sentence("ipipckedapbcppieminars") == ""
    @test words_in_sentence("aaa aaa aaaaaaa a aaaaaaa") == "aaa aaa aaaaaaa aaaaaaa"
    @test words_in_sentence("broELBDOeWCp") == ""
    @test words_in_sentence("ququicdoctorownn") == ""
    @test words_in_sentence("faa") == "faa"
    @test words_in_sentence("aaaaaaaaaaaaaaaaaaaaaeWCp") == ""
    @test words_in_sentence("scxdLYtwnumboeers") == "scxdLYtwnumboeers"
    @test words_in_sentence("fffopipersxeeter") == ""
    @test words_in_sentence("aThe ciat in tofhe aha t asat on thte mattwohhat") == "in tofhe aha on"
    @test words_in_sentence("pekck") == "pekck"
    @test words_in_sentence("doctthrek of picklrled peppersefooftorr") == "of"
    @test words_in_sentence("Anlazynumbers") == "Anlazynumbers"
    @test words_in_sentence("aabcyaabcaaaaaazjumps") == ""
    @test words_in_sentence("doctthrek of picklled peppersefooftorrccat") == "of"
    @test words_in_sentence("aathis is a test for prime numbers in words within a sentencebcaaaa") == "is for prime numbers in words"
    @test words_in_sentence("aaa aaa aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == "aaa aaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
    @test words_in_sentence("aabcaaa") == "aabcaaa"
    @test words_in_sentence("The ocat in tofhe ahat sat on the mat") == "The in tofhe sat on the mat"
    @test words_in_sentence("spiwiit") == "spiwiit"
    @test words_in_sentence("peppersghpecrk") == ""
    @test words_in_sentence("oone") == ""
    @test words_in_sentence("witscience sofhas branchessc oawf") == ""
    @test words_in_sentence("lazynumbrs") == ""
    @test words_in_sentence("abcdefghaahinP eter Pir piceppersawxyz") == "Pir"
    @test words_in_sentence("iPiper") == ""
    @test words_in_sentence("twnumaaawapdoaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaactorhers") == ""
    @test words_in_sentence("doaa aaatbwnumboneersa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaasixaaaaaaacator") == "aaatbwnumboneersa"
    @test words_in_sentence("aaatbwnumboneersa") == "aaatbwnumboneersa"
    @test words_in_sentence("browbn") == ""
    @test words_in_sentence("hin") == "hin"
    @test words_in_sentence("abcdefghijklmnopqrstuvwxabcppipeThearsyz") == ""
    @test words_in_sentence("dooctaaaaorbrowrnjumps") == ""
    @test words_in_sentence("aaa aaa aaaaaaa aa aaaaaaa") == "aaa aaa aaaaaaa aa aaaaaaa"
    @test words_in_sentence("aaaAnaaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("dooctaaaor") == ""
    @test words_in_sentence("sefofrxven") == ""
    @test words_in_sentence("The onaabcnsatumbersaaaaaocat in tofhe ahat sat on the mat") == "The in tofhe sat on the mat"
    @test words_in_sentence("The cat in tofhe ahat saat onaabcnsatumbersaaaaa the mat") == "The cat in tofhe the mat"
    @test words_in_sentence("doctoaapsoedaaorfoforr") == ""
    @test words_in_sentence("Peter Piper pk of pipers") == "Peter Piper pk of"
    @test words_in_sentence("quicdoctorownaaa aaa aaaaaaaa aaaaaaa") == "aaa aaaaaaa"
    @test words_in_sentence("az") == "az"
    @test words_in_sentence("ELquickaaahinPBDOeWCp") == ""
    @test words_in_sentence("one two three four five sieven eight peppersnine") == "one two three eight peppersnine"
    @test words_in_sentence("The quicdoct brosiispsickledn jumps over the lazy dsog") == "The jumps the"
    @test words_in_sentence("pickeduquick") == ""
    @test words_in_sentence("bfffopipersxeeterrown") == ""
    @test words_in_sentence("science sofhas branches oaffodoctorx") == "science"
    @test words_in_sentence("zudeU") == "zudeU"
    @test words_in_sentence("ff") == "ff"
    @test words_in_sentence("picklled") == ""
    @test words_in_sentence("picdoctaaaaorked") == ""
    @test words_in_sentence("twnumaaawapdoaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaatorhers") == ""
    @test words_in_sentence("sstofhe") == "sstofhe"
    @test words_in_sentence("bropipekckckpleldn") == ""
    @test words_in_sentence("aa aahina aaaaaaaa aaaaaaaaaaaa aaaaaaaainaaaaaaaaaaaaaaa") == "aa"
    @test words_in_sentence("sciencedoctaaaeaor") == ""
    @test words_in_sentence("Peter Piper pickAn apple a day keeps the doctor awayepd a peck of paicklled peppers") == "Peter Piper apple day keeps the awayepd of peppers"
    @test words_in_sentence("fodoceiPeter Piper picked a peck of picklled peppersghpeckcto") == "Piper of"
    @test words_in_sentence("aahidooctaaaaorbrowrnjumpsna") == ""
    @test words_in_sentence("aa aaa") == "aa aaa"
    @test words_in_sentence("Pk") == "Pk"
    @test words_in_sentence("peppersghpeck") == "peppersghpeck"
    @test words_in_sentence("cccat") == "cccat"
    @test words_in_sentence("iPithe quick brown fox jumps over the lazy dogper") == "quick brown fox jumps the"
    @test words_in_sentence("Paabcnsatumbersaaaaak") == ""
    @test words_in_sentence("aaaaaascience sofhas branches otwoaf") == "aaaaaascience"
    @test words_in_sentence("tthed") == "tthed"
    @test words_in_sentence("aaaAnaaaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("docttaaa aaa aaaaaaa a aaaaaaahrek of picklled peppersefooftorrccat") == "aaa aaaaaaa aaaaaaahrek of"
    @test words_in_sentence("lazyndooctaaaaorumbers") == ""
    @test words_in_sentence("aaaaaaaaaaaaa") == "aaaaaaaaaaaaa"
    @test words_in_sentence("aahidooctetpTheeraaaaorbrowrnjfodoceiPeter Piper picked a peck of picklled peppersghpeckctoumpsna") == "Piper of"
    @test words_in_sentence("aaaaaaaa") == ""
    @test words_in_sentence("seveen") == ""
    @test words_in_sentence("tbwnumrs") == ""
    @test words_in_sentence("pipP") == ""
    @test words_in_sentence("ascience some has branches ofaaapiPaaaa") == "has"
    @test words_in_sentence("docttaaa") == ""
    @test words_in_sentence("doctthrePetooftorr") == ""
    @test words_in_sentence("doctaaaaaor") == "doctaaaaaor"
    @test words_in_sentence("jmjps") == "jmjps"
    @test words_in_sentence("The cat in tofhe ahat saat onaabcnsatumberaaaaa the mat") == "The cat in tofhe the mat"
    @test words_in_sentence("science some has branchesone two three four five six seven eight peppersnine of") == "science has branchesone two three six seven eight peppersnine of"
    @test words_in_sentence("pepperseffoofrtorr") == ""
    @test words_in_sentence("picaaaad") == ""
    @test words_in_sentence("docotthrek of picklled peppersefThe quicdoctorown fox jumps over the ldogorr") == "of quicdoctorown fox jumps the ldogorr"
    @test words_in_sentence("the quick brown forx jumps over the lazy dog") == "the quick brown jumps the dog"
    @test words_in_sentence("peppersckled") == ""
    @test words_in_sentence("dooctor") == "dooctor"
    @test words_in_sentence("peppersas") == ""
    @test words_in_sentence("aaaaaaaaaaaaaaaaaaaeaaceeter") == ""
    @test words_in_sentence("peppersckleed") == "peppersckleed"
    @test words_in_sentence("within") == ""
    @test words_in_sentence("witscience sofhas branchess owawf") == "owawf"
    @test words_in_sentence("oaaf") == ""
    @test words_in_sentence("fffokeepshinx") == "fffokeepshinx"
    @test words_in_sentence("ahthat") == ""
    @test words_in_sentence("aaaaaaaaaaaaasixaaaaaaactor") == ""
    @test words_in_sentence("abcdefghijklmnopqrsqtuvwxyz abc defghijklmnopqrstuvwxyz") == "abc defghijklmnopqrstuvwxyz"
    @test words_in_sentence("pekkck") == ""
    @test words_in_sentence("awordsbcawf") == "awordsbcawf"
    @test words_in_sentence("apickeduquickaaAnaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("PkPeter Piper pickAn apple a day keeps the doctor awayepd a peck of picklled peppersmattwohhat") == "PkPeter Piper apple day keeps the awayepd of peppersmattwohhat"
    @test words_in_sentence("pepperseffoofrtoorr") == "pepperseffoofrtoorr"
    @test words_in_sentence("aaa aaaa aapaicklleda aaaaaaaa aaaaahatapiPaaaa") == "aaa"
    @test words_in_sentence("quicdone two three four five six seforxven eight nineoctn") == "two three six eight"
    @test words_in_sentence("doaa aaaa aaaaaaa aaaaaaaa aaaaabcaaaaaaaaaaaa aaaAnaaaaaaaaaaaaaaaaactor") == "aaaaaaa aaaaabcaaaaaaaaaaaa"
    @test words_in_sentence("twnusioeers") == "twnusioeers"
    @test words_in_sentence("doaa aaaa aaaaaaa aaaaaaaa aaaaa aaaAnaaaaaaaator") == "aaaaaaa aaaaa"
    @test words_in_sentence("The q brown fox jumps over the lazy dog") == "The brown fox jumps the dog"
    @test words_in_sentence("Peter Piper pipcked a peck of pickled ppeppersghpecrkeppers") == "Peter Piper pipcked of pickled"
    @test words_in_sentence("ayz") == "ayz"
    @test words_in_sentence("aaa") == "aaa"
    @test words_in_sentence("doumbersftorr") == "doumbersftorr"
    @test words_in_sentence("defghijkaaaalmnabcdefghaahinP eter Piper piceppersawxyzpqrstu") == "defghijkaaaalmnabcdefghaahinP Piper"
    @test words_in_sentence("fodtoctaaaaorrfofoaa aahina aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaarorx") == ""
    @test words_in_sentence("tofhhe") == ""
    @test words_in_sentence("abcppiaepeaTheaars") == ""
    @test words_in_sentence("jmjpps") == ""
    @test words_in_sentence("laozyndooctaaaaorumbers") == "laozyndooctaaaaorumbers"
    @test words_in_sentence("aa aaa aaaaaaseforxven aa aaaaaaa") == "aa aaa aa aaaaaaa"
    @test words_in_sentence("ELOeWCp") == "ELOeWCp"
    @test words_in_sentence("the quick breown forx jumps over the lazy dog") == "the quick jumps the dog"
    @test words_in_sentence("aa aaa aaaaaaaa aaaaabrdoaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaAnaaaaaaaaaaaawrnaa") == "aa aaa aaaaabrdoaa"
    @test words_in_sentence("science seome has branches of") == "science seome has of"
    @test words_in_sentence("aaa aaa aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaa") == "aaa aaa"
    @test words_in_sentence("pickeduquickaaAnaaaaaaaaaator") == "pickeduquickaaAnaaaaaaaaaator"
    @test words_in_sentence("science sofhas bran ches otwoaf") == "science"
    @test words_in_sentence("twnipipckedumboneers") == ""
    @test words_in_sentence("piiP") == ""
    @test words_in_sentence("aasciencedoctaaaeaoraaaaaaaaaaa") == "aasciencedoctaaaeaoraaaaaaaaaaa"
    @test words_in_sentence("jmjpp") == "jmjpp"
    @test words_in_sentence("one two three four five six seven eight nineasatdooctaaaaor") == "one two three six seven eight nineasatdooctaaaaor"
    @test words_in_sentence("brownn") == ""
    @test words_in_sentence("quicdoneaaaAnaaaaaaaaaaaawrnaa") == ""
    @test words_in_sentence("aaaaaaaaaaaaaaaaaaaaaaceeter") == ""
    @test words_in_sentence("PaaaAnaaaaaaaatoriper") == ""
    @test words_in_sentence("YYzs") == ""
    @test words_in_sentence("Pk of pickledaa aaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaa peppaers") == "Pk of aaa"
    @test words_in_sentence("defghiabcpipersjklmnopqrstuwn") == "defghiabcpipersjklmnopqrstuwn"
    @test words_in_sentence("ipipckpeppersghpeckctoumpsnaminars") == ""
    @test words_in_sentence("docrek") == ""
    @test words_in_sentence("ahaewitscienaa aahina aaaaaaaa aaappleaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaceeter") == "aaappleaaaaaaaaaa"
    @test words_in_sentence("brownnn") == "brownnn"
    @test words_in_sentence("aawfooura") == ""
    @test words_in_sentence("otwoaf") == ""
    @test words_in_sentence("oceiPeter") == ""
    @test words_in_sentence("doctoaaaaorfdoctthrePetooftorroforr") == ""
    @test words_in_sentence("woaaaaaaaaaaaaaaaaaaaardds") == ""
    @test words_in_sentence("Pet") == "Pet"
    @test words_in_sentence("quicdoctorownaaa aaa aaaaaaaaa aaaaaaa") == "aaa aaaaaaa"
    @test words_in_sentence("caaaaaaaaaaaaaaaaaaaaaaceeteraaaaaaaaaaaaaasixaaaaaaaactor") == ""
    @test words_in_sentence("matrimecat") == ""
    @test words_in_sentence("ssentennce") == ""
    @test words_in_sentence("mkZrwvKDr") == ""
    @test words_in_sentence("ayabcy") == ""
    @test words_in_sentence("Peter Piper psomeicked a ppicklrledeck of pickled peppers") == "Peter Piper ppicklrledeck of pickled peppers"
    @test words_in_sentence("twnumboaaaaabrdoaaneers") == "twnumboaaaaabrdoaaneers"
    @test words_in_sentence("one two threne four five sieven eight peppersnine") == "one two eight peppersnine"
    @test words_in_sentence("Yzzfodoccotos") == "Yzzfodoccotos"
    @test words_in_sentence("aaa aaa aaaaaaaa aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaabrowrnaa") == "aaa aaa"
    @test words_in_sentence("aahinP etpTheer Pipaer pickedeighpecka peck of picklersas") == "of"
    @test words_in_sentence("q") == ""
    @test words_in_sentence("The ceat in tofhe ahat sat on the mat") == "The in tofhe sat on the mat"
    @test words_in_sentence("The quicdoct fox jumps over the") == "The fox jumps the"
    @test words_in_sentence("doaa aaaa aaaaaaa aaaaaaaa aaaaaaaaaaaa aaaAnaaapeppersckleedaaaaaaaaaaaaaactor") == "aaaaaaa"
    @test words_in_sentence("aaaapiatwohsomehatThe cadoctaaaaaort in tofhe aha t asat on thte matPaaaa") == "in tofhe aha on"
    @test words_in_sentence("pieckleld") == ""
    @test words_in_sentence("defghijklmnopqrstruvwxyz") == ""
    @test words_in_sentence("aa aaa aaaaaaseforxven aav aaaaaaa") == "aa aaa aav aaaaaaa"
    @test words_in_sentence("jjmummmps") == ""
    @test words_in_sentence("fodoctorox") == ""
    @test words_in_sentence("pThe cat in the hat saYzst on the matrime") == "cat in the hat on the matrime"
    @test words_in_sentence("clwZFZYz") == ""
    @test words_in_sentence("ZGmkXBsVH") == ""
    @test words_in_sentence("defghijkaaaalmnabcdefghaahinP") == "defghijkaaaalmnabcdefghaahinP"
    @test words_in_sentence("The cat in tofhe ahat sat at") == "The cat in tofhe sat at"
    @test words_in_sentence("ELBDkeepsOaa aaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaaeWCp") == "aaa"
    @test words_in_sentence("ofaaapiPaaaa") == ""
    @test words_in_sentence("onn") == "onn"
    @test words_in_sentence("e") == ""
    @test words_in_sentence("doctaaaaorlly") == "doctaaaaorlly"
    @test words_in_sentence("aabc") == ""
    @test words_in_sentence("aaaaabrdoaa") == "aaaaabrdoaa"
    @test words_in_sentence("quicdoc aaaaaaaaa aaaaaaa") == "quicdoc aaaaaaa"
    @test words_in_sentence("aa aahina aaaaaaaa aaaaaaaaaaaa aaaainaaaaaaaaaaaaaaa") == "aa"
    @test words_in_sentence("ipipckpepperckctoumpsnaminars") == "ipipckpepperckctoumpsnaminars"
    @test words_in_sentence("fodabcppiaepeaTheaarsoccto") == ""
    @test words_in_sentence("pepck") == "pepck"
    @test words_in_sentence("twnusioeeighters") == ""
    @test words_in_sentence("aav") == "aav"
    @test words_in_sentence("aaaaaaaaaaaaaaaaaaaatorhers") == ""
    @test words_in_sentence("piecklpeld") == ""
    @test words_in_sentence("The quiaaa aaa aaaaaaa a aaaaaaacdoctorown fox jumps over the lazy dog") == "The aaa aaaaaaa aaaaaaacdoctorown fox jumps the dog"
    @test words_in_sentence("breown") == ""
    @test words_in_sentence("doaa aaaa aaaaaa aaaahhateightaaaaa aaaaaaaaaaaa aaaAnaaaaaaaaaaaaaaaaactor") == ""
    @test words_in_sentence("aa aaa aThe cat in tofhe ahat sat ataaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaaaa") == "aa aaa cat in tofhe sat"
    @test words_in_sentence("olazynumbersn") == "olazynumbersn"
    @test words_in_sentence("doctthr picked a peck of picklled peppersefooftorr") == "doctthr of"
    @test words_in_sentence("docttaaa aaa aaaaaaa a aaaaaaahreaaa aaa aaaaaaasixaaaaaaactorak of picklled peppersefooftorrccat") == "aaa aaaaaaa aaaaaaahreaaa aaa aaaaaaasixaaaaaaactorak of"
    @test words_in_sentence("twnumaaawapdoaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaatorhers") == "aaaaaaaaaaaaa"
    @test words_in_sentence("this is a test for prime numbers in words wit hhin a sentence") == "is for prime numbers in words wit"
    @test words_in_sentence("pk") == "pk"
    @test words_in_sentence("dogper") == ""
    @test words_in_sentence("quicdoctorownaaa aaa aaaffoxaaaaaa aaaaaaa") == "aaa aaaffoxaaaaaa aaaaaaa"
    @test words_in_sentence("ofaaaaaaaaaaaaaaaaaaaaaaaaaapiPaaaapiPaaaa") == ""
    @test words_in_sentence("aaatbwnuoneersa") == ""
    @test words_in_sentence("aaAnaaaaa") == ""
    @test words_in_sentence("The q brown fox jumps over trhe lazy dog") == "The brown fox jumps dog"
    @test words_in_sentence("qpThekk") == "qpThekk"
    @test words_in_sentence("fodaapaicklledarox") == ""
    @test words_in_sentence("lyazy") == "lyazy"
    @test words_in_sentence("pThe cat in the hat sat on the maetrime") == "cat in the hat sat on the"
    @test words_in_sentence("prbreownime") == "prbreownime"
    @test words_in_sentence("doaa aaaa aaaaaaa aaaaaaaa aaaaa aaaaaator") == "aaaaaaa aaaaa"
    @test words_in_sentence("mecat") == "mecat"
    @test words_in_sentence("science some has branchesone two three four five six seven eightn peppersnine of") == "science has branchesone two three six seven peppersnine of"
    @test words_in_sentence("Peter Piper picked aa aaa aaaaaaaa aaaaa aaa peck of pickled peppers") == "Peter Piper aa aaa aaaaa aaa of pickled peppers"
    @test words_in_sentence("defghijkxlmnopqaaaarstruvwxyz") == "defghijkxlmnopqaaaarstruvwxyz"
    @test words_in_sentence("piawordsbciwit") == ""
    @test words_in_sentence("doctaaaaoorrfoforor") == "doctaaaaoorrfoforor"
    @test words_in_sentence("pseppersghpecrkree") == ""
    @test words_in_sentence("sieven") == ""
    @test words_in_sentence("aaaAnaaaaaaaaahinaaaaaaaaactor") == ""
    @test words_in_sentence("aasciencedocteaaaeaoraaaaaaaaaaa") == ""
    @test words_in_sentence("twnumaaaawapdoaa aaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aars") == ""
    @test words_in_sentence("tpipP") == "tpipP"
    @test words_in_sentence("dooctaaaaorbrowrcnjumps") == "dooctaaaaorbrowrcnjumps"
    @test words_in_sentence("dooctaaaaorbrwornjuwmps") == "dooctaaaaorbrwornjuwmps"
    @test words_in_sentence("aaaaaascience") == "aaaaaascience"
    @test words_in_sentence("aa aaaPkPeter Piper pickAn apple a day keeps the doctor awayepd a peck of picklled peppersmattwohhat") == "aa Piper apple day keeps the awayepd of peppersmattwohhat"
    @test words_in_sentence("witscience sofhas braninchess owawf") == "braninchess owawf"
    @test words_in_sentence("dehrek") == ""
    @test words_in_sentence("doctthrePetowitscience sofhas braoftorr") == ""
    @test words_in_sentence("x y z") == ""
    @test words_in_sentence("numbers") == "numbers"
    @test words_in_sentence("quicninek") == ""
    @test words_in_sentence("the quick brown fox jumps over the lazy twodog") == "the quick brown fox jumps the"
    @test words_in_sentence("this is a test for prime numbers foxin words within a sentence") == "is for prime numbers foxin words"
    @test words_in_sentence("quicniinek") == ""
    @test words_in_sentence("two") == "two"
    @test words_in_sentence("aone two three fou r five six seven eight nine") == "two three fou six seven eight"
    @test words_in_sentence("scPeterience some has branches of") == "has of"
    @test words_in_sentence("this is a test for prime numbers in wodaynce") == "is for prime numbers in"
    @test words_in_sentence("twPetero") == ""
    @test words_in_sentence("numbeonrs") == ""
    @test words_in_sentence("wWFWJpaA") == ""
    @test words_in_sentence("science some has brsentencehes of") == "science has brsentencehes of"
    @test words_in_sentence("pceck") == "pceck"
    @test words_in_sentence("tesnumbeonrs") == ""
    @test words_in_sentence("some") == ""
    @test words_in_sentence("aonePiper two three fou r five six seven eight nine") == "two three fou six seven eight"
    @test words_in_sentence("twPro") == "twPro"
    @test words_in_sentence("aonepple") == ""
    @test words_in_sentence("wWFWJaa aaaa aaaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaakeepsaaaaaaaapaA") == "wWFWJaa aaaaaaa"
    @test words_in_sentence("aaaaaaaaaaaa") == ""
    @test words_in_sentence("The quick brown fox jumps over the lazy dogscPeterience some has branches of") == "The quick brown fox jumps the has of"
    @test words_in_sentence("twProo") == ""
    @test words_in_sentence("wWFWJaa") == "wWFWJaa"
    @test words_in_sentence("f") == ""
    @test words_in_sentence("quik") == ""
    @test words_in_sentence("the quick bazy dog") == "the quick dog"
    @test words_in_sentence("nusmbers") == ""
    @test words_in_sentence("o") == ""
    @test words_in_sentence("fThe cat in the hat sat on the mat") == "cat in the hat sat on the mat"
    @test words_in_sentence("quaoneppleek") == ""
    @test words_in_sentence("priime") == ""
    @test words_in_sentence("quicniscience some has inbrsentencehes ofinek") == "quicniscience has"
    @test words_in_sentence("aaaaaaaaaaaakeepsaaaaaaaapaAf") == "aaaaaaaaaaaakeepsaaaaaaaapaAf"
    @test words_in_sentence("this") == ""
    @test words_in_sentence("wWFWJaa aaaa aaaaaaa aaaaaaaa aaaaaaapsaaaaaonePiperaaaapaA") == "wWFWJaa aaaaaaa aaaaaaapsaaaaaonePiperaaaapaA"
    @test words_in_sentence("peppers") == "peppers"
    @test words_in_sentence("tesAnnumbeonrs") == ""
    @test words_in_sentence("apbcopqrstuvwxyz") == ""
    @test words_in_sentence("words") == "words"
    @test words_in_sentence("science some has brsentenncehes of") == "science has of"
    @test words_in_sentence("in") == "in"
    @test words_in_sentence("aaaaaaaaaaaakeepsatwPeteroapaA") == ""
    @test words_in_sentence("branches") == ""
    @test words_in_sentence("wordcats") == ""
    @test words_in_sentence("The q uick brown fox jumps brsentencehesterience some has branches of") == "The brown fox jumps has of"
    @test words_in_sentence("aaaaaaaaaaaaaa") == ""
    @test words_in_sentence("afThe cat in the hat sat on the mataa") == "afThe cat in the hat sat on the mataa"
    @test words_in_sentence("bazy") == ""
    @test words_in_sentence("r") == ""
    @test words_in_sentence("n") == ""
    @test words_in_sentence("ThAn apple a day keeps the doctor awaye cat in the hat sat on the mat") == "apple day keeps the awaye cat in the hat sat on the mat"
    @test words_in_sentence("Peter") == "Peter"
    @test words_in_sentence("wordcthe quick brown fox jumps over the lazy twodogats") == "quick brown fox jumps the"
    @test words_in_sentence("Ther quick brown fox jumps over the lazy dog") == "quick brown fox jumps the dog"
    @test words_in_sentence("science threesome has brsentencehes of") == "science has brsentencehes of"
    @test words_in_sentence("this is for prime numbers in wodaynce") == "is for prime numbers in"
    @test words_in_sentence("science threesome has bcrsentencehes of") == "science has of"
    @test words_in_sentence("this is a tesninet for prime numbers in words within a sentence") == "is for prime numbers in words"
    @test words_in_sentence("aa aaaaa aaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaaaaaaaaaa") == "aa aaaaa"
    @test words_in_sentence("science threeshas brsentencehes of") == "science brsentencehes of"
    @test words_in_sentence("afThe Ther quick brown fox jumps over the lazy dogt on the mataa") == "afThe quick brown fox jumps the on the mataa"
    @test words_in_sentence("thhree") == ""
    @test words_in_sentence("this is for prime numbers ian wodaynce") == "is for prime numbers ian"
    @test words_in_sentence("quicnibazynek") == "quicnibazynek"
    @test words_in_sentence("mataa") == "mataa"
    @test words_in_sentence("twPettero") == ""
    @test words_in_sentence("aonepplee") == ""
    @test words_in_sentence("eZnNBxOH") == ""
    @test words_in_sentence("quicniscie some has inbrsentencehes ofinek") == "has"
    @test words_in_sentence("quicniscwodaynceience some has inbrsentencehes ofinek") == "has"
    @test words_in_sentence("ofinek") == ""
    @test words_in_sentence("overpceck") == ""
    @test words_in_sentence("nusmbscience some has brsentencehes ofers") == "has brsentencehes ofers"
    @test words_in_sentence("ofers") == "ofers"
    @test words_in_sentence("this is a test for prime numbers in woodaynce") == "is for prime numbers in"
    @test words_in_sentence("wtwo") == ""
    @test words_in_sentence("nusmbscience") == ""
    @test words_in_sentence("aaaatwodogaa") == ""
    @test words_in_sentence("science threesquicniscience some has inbrsentencehes ofinekome has bcrsentencehes of") == "science threesquicniscience has has of"
    @test words_in_sentence("aone") == ""
    @test words_in_sentence("FwWFWJpaA") == ""
    @test words_in_sentence("thisscience threesome has bcrsentencehes of is a tesnappleime numbers in words within a sentence") == "thisscience has of is numbers in words"
    @test words_in_sentence("this is a atest for prime numbers in woodaynce") == "is atest for prime numbers in"
    @test words_in_sentence("Ther quick brown fox jumps over the lazy do g") == "quick brown fox jumps the do"
    @test words_in_sentence("scPeterience some hacs branches of") == "of"
    @test words_in_sentence("priisiimofineke") == ""
    @test words_in_sentence("rtwPetero") == ""
    @test words_in_sentence("Peter Pkled peppers") == "Peter Pkled peppers"
    @test words_in_sentence("quipriisiimofinekek") == "quipriisiimofinekek"
    @test words_in_sentence("ni") == "ni"
    @test words_in_sentence("defghijklmnopqrstuvwxyz") == "defghijklmnopqrstuvwxyz"
    @test words_in_sentence("the quk brown fox jumps over the lazy dog") == "the quk brown fox jumps the dog"
    @test words_in_sentence("peppeers") == ""
    @test words_in_sentence("thisscience threesome has bcrsentencehes of is a tesnappleime numbers in words within a sentenceaoe") == "thisscience has of is numbers in words sentenceaoe"
    @test words_in_sentence("priisiimofinTheke") == "priisiimofinTheke"
    @test words_in_sentence("twodogats") == ""
    @test words_in_sentence("threeshas") == ""
    @test words_in_sentence("eZnNBxOHAn") == ""
    @test words_in_sentence("threesome") == ""
    @test words_in_sentence("keeps") == "keeps"
    @test words_in_sentence("quicniscwodaynceience") == ""
    @test words_in_sentence("this is for prime numbers ian wodaynce o") == "is for prime numbers ian"
    @test words_in_sentence("niaonepplee") == "niaonepplee"
    @test words_in_sentence("this is for prime numbers in wodayabcdefghijklmnopqrstuvwxyz abc defghijklmnopqrstuvwxyznce") == "is for prime numbers in wodayabcdefghijklmnopqrstuvwxyz abc"
    @test words_in_sentence("The") == "The"
    @test words_in_sentence("ofinekome") == ""
    @test words_in_sentence("Peeter") == ""
    @test words_in_sentence("oveAn apple a day keeps the doctor awayr") == "oveAn apple day keeps the awayr"
    @test words_in_sentence("ninee") == "ninee"
    @test words_in_sentence("wWFWJaa aaaa aaaaaaa aaaaaaaa aaaaaaapsaaaaaonePiperaaaawtwopaA") == "wWFWJaa aaaaaaa"
    @test words_in_sentence("lpZlaIbZZ") == ""
    @test words_in_sentence("pickled") == "pickled"
    @test words_in_sentence("uick") == ""
    @test words_in_sentence("eZnNBxOHH") == ""
    @test words_in_sentence("wordscience some has brseentenncehes ofs") == "wordscience has ofs"
    @test words_in_sentence("this is for prime numbers in wodayabcdefghijklmnopqrstuvwxfivec defghijklmnopqrstuvwxyznce") == "is for prime numbers in"
    @test words_in_sentence("this is a test for prime numbers in twodogatswords within a sentence") == "is for prime numbers in"
    @test words_in_sentence("this is a test for prime numbers in inwordsentence") == "is for prime numbers in"
    @test words_in_sentence("ThAn apple a day kweeps the doctor awaye cat in the hat sat on the mat") == "apple day the awaye cat in the hat sat on the mat"
    @test words_in_sentence("quicnibaczynek") == ""
    @test words_in_sentence("ofoveAn apple a day keeps the doctor awayrek") == "ofoveAn apple day keeps the awayrek"
    @test words_in_sentence("ateest") == ""
    @test words_in_sentence("tuickesome") == ""
    @test words_in_sentence("An") == "An"
    @test words_in_sentence("An apple abcdefghijklmnopqrstuvwxyza day keeps thdoctor away") == "An apple day keeps"
    @test words_in_sentence("uithis is for prime numbersofers ian wodayncek") == "is for prime ian"
    @test words_in_sentence("eZnNaonepple") == ""
    @test words_in_sentence("apbcpoxyz") == ""
    @test words_in_sentence("rtwPro") == ""
    @test words_in_sentence("sentenceaoe") == "sentenceaoe"
    @test words_in_sentence("wodayncek") == ""
    @test words_in_sentence("peppeatesters") == "peppeatesters"
    @test words_in_sentence("aaaaaaaaaaaakeepsaaaaaaaaapaAf") == ""
    @test words_in_sentence("ThAn") == ""
    @test words_in_sentence("kekeps") == ""
    @test words_in_sentence("word") == ""
    @test words_in_sentence("aaaaaaaaaaaakeepsaaaaaaaapaA") == ""
    @test words_in_sentence("science") == "science"
    @test words_in_sentence("wWwodayabcdefghijklmnopqrstuvwxyzFWJaaaaaaaapaA") == "wWwodayabcdefghijklmnopqrstuvwxyzFWJaaaaaaaapaA"
    @test words_in_sentence("kweeps") == ""
    @test words_in_sentence("bcrsentencehes") == ""
    @test words_in_sentence("nTThAn") == ""
    @test words_in_sentence("niaonepplquicniscwoodaynceienceee") == ""
    @test words_in_sentence("bcrsentebrseentenncehesnceheafThes") == ""
    @test words_in_sentence("thhreescience some has branches of") == "thhreescience has of"
    @test words_in_sentence("ThAn apple a day kweeps the doctor awaye cat in the ehat sat on the mat") == "apple day the awaye cat in the sat on the mat"
    @test words_in_sentence("scPeterienscience some has branches ofce") == "scPeterienscience has"
    @test words_in_sentence("owodayabcdefghijklmnopqrstuvwxyz") == ""
    @test words_in_sentence("quicniscie some hasthis is for prirs in wodaynce inbrsentencehes ofinek") == "hasthis is for prirs in"
    @test words_in_sentence("threesha") == ""
    @test words_in_sentence("ovrlazy") == "ovrlazy"
    @test words_in_sentence("quicniscience some has inbrsentencehesek") == "quicniscience has inbrsentencehesek"
    @test words_in_sentence("branchers") == ""
    @test words_in_sentence("ovekweeps awayr") == "awayr"
    @test words_in_sentence("wordrs") == ""
    @test words_in_sentence("tesnumbeonrrs") == "tesnumbeonrrs"
    @test words_in_sentence("tukickesome") == "tukickesome"
    @test words_in_sentence("The quick brown fox jumps over the lazyo dog") == "The quick brown fox jumps the lazyo dog"
    @test words_in_sentence("inwordsentence") == ""
    @test words_in_sentence("numbersofers") == ""
    @test words_in_sentence("nusmbscience some has brsentwProtencehess ofers") == "has brsentwProtencehess ofers"
    @test words_in_sentence("doctorover") == ""
    @test words_in_sentence("sat") == "sat"
    @test words_in_sentence("aaaaapeppeatestersaaaaaaaakeepsatwPeteroapaquipriisiimofinekekA") == ""
    @test words_in_sentence("quicniscienthe quick brown fox jumps over the lazy dogce some has inbrsentencehesek") == "quick brown fox jumps the dogce has inbrsentencehesek"
    @test words_in_sentence("the quicik bazy dog") == "the dog"
    @test words_in_sentence("quicniscienthe quick brown fox jutmps over the lazy doegce some has inbrsentencehesek") == "quick brown fox the has inbrsentencehesek"
    @test words_in_sentence("abcdefghijklmnopqrstuvwxyza") == ""
    @test words_in_sentence("ofce") == ""
    @test words_in_sentence("bnusmbers") == ""
    @test words_in_sentence("zYwjhBCYS") == ""
    @test words_in_sentence("dog") == "dog"
    @test words_in_sentence("oveorpceck") == ""
    @test words_in_sentence("woodaynce") == ""
    @test words_in_sentence("bazyover") == ""
    @test words_in_sentence("pkweeps") == "pkweeps"
    @test words_in_sentence("this is for prime numbers in wodayabcdefghijklmnopqrstuvwxyz abdefghijklmnopqrstuvwxyznce") == "is for prime numbers in wodayabcdefghijklmnopqrstuvwxyz"
    @test words_in_sentence("quicniscience") == "quicniscience"
    @test words_in_sentence("oveAn apple a day keeplpZlaIbZZs the doctor awayr") == "oveAn apple day the awayr"
    @test words_in_sentence("aaaaaaaaaaaakeepsatwPaeteroapaA") == "aaaaaaaaaaaakeepsatwPaeteroapaA"
    @test words_in_sentence("ttukickesomeowodog") == ""
    @test words_in_sentence("Ther quick brown fox jumps over the lazydog") == "quick brown fox jumps the lazydog"
    @test words_in_sentence("qnuicniscience") == ""
    @test words_in_sentence("the quick bazdy dog") == "the quick bazdy dog"
    @test words_in_sentence("wWFWJaa aaaa aaaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaTherawithinaaaakeepsaaaaaaaapaA") == "wWFWJaa aaaaaaa"
    @test words_in_sentence("aonePiper") == ""
    @test words_in_sentence("thia tesnappleime numbers in words within a sentenceaoe") == "numbers in words sentenceaoe"
    @test words_in_sentence("niaonepplquicniscwoodaynceiencawayreee") == ""
    @test words_in_sentence("oveAn") == "oveAn"
    @test words_in_sentence("eZnNaonepplThe quick brown fox jumps over the lazy dogscPeterience some has branches ofe") == "quick brown fox jumps the has ofe"
    @test words_in_sentence("scPeterience") == ""
    @test words_in_sentence("ofoveAn apple a day keepsrek") == "ofoveAn apple day"
    @test words_in_sentence("numbeonwithins") == ""
    @test words_in_sentence("ofcfe") == "ofcfe"
    @test words_in_sentence("wodayabcdefghijpklmnopqrstuvwxfivec") == ""
    @test words_in_sentence("this is a atoverest for priquikme numbers in woodaynce") == "is for numbers in"
    @test words_in_sentence("Th") == "Th"
    @test words_in_sentence("owodayabcdefghijklmnopqrstuyz") == "owodayabcdefghijklmnopqrstuyz"
    @test words_in_sentence("threThe quick brown fobranchesx jumps over the lazy doge") == "threThe quick brown fobranchesx jumps the"
    @test words_in_sentence("doge") == ""
    @test words_in_sentence("tesAnnumbe") == ""
    @test words_in_sentence("twPaaaaaaaaaaaakeepsaaaaaaaaapaAfero") == ""
    @test words_in_sentence("TTh") == "TTh"
    @test words_in_sentence("awayr") == "awayr"
    @test words_in_sentence("away") == ""
    @test words_in_sentence("twodogatswords") == ""
    @test words_in_sentence("i") == ""
    @test words_in_sentence("oe") == "oe"
    @test words_in_sentence("one two ht nine") == "one two ht"
    @test words_in_sentence("wWFWJaa aaaa aaaaaaaa aA") == "wWFWJaa aA"
    @test words_in_sentence("quicniscienthe quick brown fox jutmps over the lazy doegcem some has inbrsentencehesek") == "quick brown fox the doegcem has inbrsentencehesek"
    @test words_in_sentence("twPrroo") == "twPrroo"
    @test words_in_sentence("this is for primeu numbers in wodayabcdefghijklmnopqrstuvwxyz abc defghijklmnopqrstuvwxyznce") == "is for numbers in wodayabcdefghijklmnopqrstuvwxyz abc"
    @test words_in_sentence("nusmbeaonePiperrs") == "nusmbeaonePiperrs"
    @test words_in_sentence("aonple") == ""
    @test words_in_sentence("twPPtettero") == "twPPtettero"
    @test words_in_sentence("Pkled") == "Pkled"
    @test words_in_sentence("quicnik") == "quicnik"
    @test words_in_sentence("thpriquikmee quick brown fox jumps over the lazy twodog") == "quick brown fox jumps the"
    @test words_in_sentence("wWFpeppeatestersWJpaA") == ""
    @test words_in_sentence("quicnibathis is a tesninet for prime numbers in words within a sentencezynwordscienceek") == "is for prime numbers in words"
    @test words_in_sentence("abcdefghijklmnopqrstuvwxyz abc defghquicniinekijklmnopqrstuvyz") == "abc defghquicniinekijklmnopqrstuvyz"
    @test words_in_sentence("twPPtetteroaaa") == ""
    @test words_in_sentence("ofe") == "ofe"
    @test words_in_sentence("this is for prime numbers in wodayabcdefghijklmnopqrstuvwxyz abc defghijklmnopqrstuvzwxyznce") == "is for prime numbers in wodayabcdefghijklmnopqrstuvwxyz abc"
    @test words_in_sentence("day") == "day"
    @test words_in_sentence("wodayatbcdefghijpklmnopqrstuvwxfivec") == ""
    @test words_in_sentence("pr") == "pr"
    @test words_in_sentence("brseentenncehesPiper") == ""
    @test words_in_sentence("lpZltwProaIlbbZZZ") == "lpZltwProaIlbbZZZ"
    @test words_in_sentence("inwoovekwnusmbscienceeepbrsentencehesteriencerrdseintence") == ""
    @test words_in_sentence("foxin") == "foxin"
    @test words_in_sentence("numbbeonrs") == ""
    @test words_in_sentence("pecck") == "pecck"
    @test words_in_sentence("thdoctor") == ""
    @test words_in_sentence("thinuquaoneppleekin wooinbrsentencehesekdaynce") == "thinuquaoneppleekin"
    @test words_in_sentence("awaye") == "awaye"
    @test words_in_sentence("this is for prime rnumbers in wodayabcdefghijklmnopqrstuvwxfivec defghijklmnopqrstuvwxyznce") == "is for prime in"
    @test words_in_sentence("The cat in the hat squicniscience some has inbrsentencehes ofinekat on the mat") == "The cat in the hat has on the mat"
    @test words_in_sentence("nin") == "nin"
    @test words_in_sentence("oveAn appTher quick brown fox jumps over the lazy dogle a day keeplpZlaIbZZs the tor awayr") == "oveAn appTher quick brown fox jumps the dogle day the tor awayr"
    @test words_in_sentence("uithis is for prime numbersofers ian wodayncekthdoctor") == "is for prime ian wodayncekthdoctor"
    @test words_in_sentence("keeThekps") == ""
    @test words_in_sentence("overThAn apple a dator awaye cat in the ehat sat on the mat") == "apple dator awaye cat in the sat on the mat"
    @test words_in_sentence("thhtree") == "thhtree"
    @test words_in_sentence("numbeonbcrsentencehess") == ""
    @test words_in_sentence("Ther quick brown fox jumps opriimever the lazy do g") == "quick brown fox jumps the do"
    @test words_in_sentence("eZnNadefghquicniinekijklmnopqrstuvyzple") == ""
    @test words_in_sentence("tpeppeersuickesome") == ""
    @test words_in_sentence("tukicokesome") == ""
    @test words_in_sentence("ovrlazuicky") == "ovrlazuicky"
    @test words_in_sentence("Peter Piper pickernumbersd a peck of pickled peppers") == "Peter Piper of pickled peppers"
    @test words_in_sentence("aaaaaaaaaaaakeepsaaaaainbrsentencehesekaaaapaAf") == "aaaaaaaaaaaakeepsaaaaainbrsentencehesekaaaapaAf"
    @test words_in_sentence("twto") == ""
    @test words_in_sentence("wodaynek") == ""
    @test words_in_sentence("fobranchesx") == "fobranchesx"
    @test words_in_sentence("numbeonfoxbcrsentencehess") == ""
    @test words_in_sentence("wodayne") == "wodayne"
    @test words_in_sentence("quipriistestiimofinekek") == "quipriistestiimofinekek"
    @test words_in_sentence("oveeorpceck") == "oveeorpceck"
    @test words_in_sentence("owhatordsce") == "owhatordsce"
    @test words_in_sentence("Ther quieightx jumps over the lazydog") == "jumps the lazydog"
    @test words_in_sentence("oifinek") == "oifinek"
    @test words_in_sentence("this is aa atest for prime numbers in woodaynce") == "is aa atest for prime numbers in"
    @test words_in_sentence("quicinbrsentencehesekniinek") == ""
    @test words_in_sentence("quicniscienthe") == ""
    @test words_in_sentence("eiginbrsentencehesht") == ""
    @test words_in_sentence("tneesnumbeonrrs") == ""
    @test words_in_sentence("ovrlazcuicky") == ""
    @test words_in_sentence("ovrpceck") == ""
    @test words_in_sentence("quiicniscwodaynceience") == ""
    @test words_in_sentence("sciequipriisiimofinekeknce") == ""
    @test words_in_sentence("brseentenncehesPipwWFWJaa aaaa aaaaaaaa aAer") == ""
    @test words_in_sentence("ffaaaaaaa") == ""
    @test words_in_sentence("peecc") == "peecc"
    @test words_in_sentence("wWFWJaa aaaa aaaaaaa aaaaaaaa aaaaaaaaaaaa aaaaaaaaaaaakeepsaaaaaaaapaaA") == "wWFWJaa aaaaaaa aaaaaaaaaaaakeepsaaaaaaaapaaA"
    @test words_in_sentence("ofinekat") == ""
    @test words_in_sentence("quicniscienthee has inbrsentencehesek") == "has inbrsentencehesek"
    @test words_in_sentence("twwo") == ""
    @test words_in_sentence("primme") == ""
    @test words_in_sentence("thia tes nappleime numbers in words within a sentenceaoe") == "tes numbers in words sentenceaoe"
    @test words_in_sentence("An apple abcdefghijklmnopqrstuvwmxyza day keeps thdoctor away") == "An apple day keeps"
    @test words_in_sentence("nusmnbscience") == "nusmnbscience"
    @test words_in_sentence("Peter Pkled nusmbsciencepeppers") == "Peter Pkled nusmbsciencepeppers"
    @test words_in_sentence("numbeonfoxbcrsseentencehess") == ""
    @test words_in_sentence("owodayabcdefghijklthe quick bazdy dogz") == "quick bazdy"
    @test words_in_sentence("ofnineece") == ""
    @test words_in_sentence("thi test for prime numbers in twodogatswords within a sentence") == "thi for prime numbers in"
    @test words_in_sentence("awthpriquikqmeeayrek") == ""
    @test words_in_sentence("thpriquikmee quick brown fox jumhe lazy twodog") == "quick brown fox jumhe"
    @test words_in_sentence("aoneoverpplee") == "aoneoverpplee"
    @test words_in_sentence("aaaaapeppeatestersaaaaaaaaPeteroapaquipriisiimofinekekA") == ""
    @test words_in_sentence("The qence some has branches of") == "The qence has of"
    @test words_in_sentence("wtowo") == "wtowo"
    @test words_in_sentence("thhreescience") == "thhreescience"
    @test words_in_sentence("Ther quick brown fox jumps mover the lazydog") == "quick brown fox jumps mover the lazydog"
    @test words_in_sentence("qquik") == "qquik"
    @test words_in_sentence("brseentenncwWFWJaaehesPipwWFWJaa") == ""
    @test words_in_sentence("wodayncekthdoctor") == "wodayncekthdoctor"
    @test words_in_sentence("owodayabcdefghiijklmnopqrstuyz") == ""
    @test words_in_sentence("aaaa") == ""
    @test words_in_sentence("nummrbbeonrs") == ""
    @test words_in_sentence("pcpeck") == ""
    @test words_in_sentence("foxina") == ""
    @test words_in_sentence("wordthinuquaoneppleekincats") == ""
    @test words_in_sentence("thpriquikmee") == ""
    @test words_in_sentence("this is a test for prime numbers in twodogatswocrds within athis senthreesquicnisciencetence") == "is for prime numbers in athis"
    @test words_in_sentence("owodayabcdefghijklthe") == ""
    @test words_in_sentence("qone two three four five six seven eight nineuicnibaczynek") == "two three six seven eight nineuicnibaczynek"
    @test words_in_sentence("odogAn apple a day keeps the doctor away") == "apple day keeps the"
    @test words_in_sentence("science threeshas brsentencniaonepplquicniscwoodaynceiencawayreeeehes of") == "science of"
    @test words_in_sentence("quiicniscwoidaynceience") == "quiicniscwoidaynceience"
    @test words_in_sentence("priimme") == "priimme"
    @test words_in_sentence("neZnNBxOHH") == ""
    @test words_in_sentence("wordwodayabcdefghijpklmnopqrstuvwxfivec") == ""
    @test words_in_sentence("fVLkz") == "fVLkz"
    @test words_in_sentence("qf") == "qf"
    @test words_in_sentence("quicnisciencethree some has inbrsentencehes ofinek") == "has"
    @test words_in_sentence("Thhe") == ""
    @test words_in_sentence("abcdefghijklmnopqrstuvbrseenteenncwWFWJaaehesPipwWFWJaawxyza") == ""
    @test words_in_sentence("aaaaquicnissixcience") == ""
    @test words_in_sentence("ofinekpr") == ""
    @test words_in_sentence("aoonpple") == ""
    @test words_in_sentence("science some has branhacses of") == "science has of"
    @test words_in_sentence("science thrseesquicniscience some has inbrsentencehes ofinekome has bcrsentencehes of") == "science has has of"
    @test words_in_sentence("ThAn apple a day keeps the doctor awaye cat inh the hat sat on the mat") == "apple day keeps the awaye cat inh the hat sat on the mat"
    @test words_in_sentence("thhreescience sbrsentennceheses of") == "thhreescience sbrsentennceheses of"
    @test words_in_sentence("bcrsethe quick bazy dogntebrseentenncehesnceheafThees") == "quick"
    @test words_in_sentence("wordors") == "wordors"
    @test words_in_sentence("wWFWJaa aaaa aaaaaaa aaaaaaaa aaaaatpeppeersuickesomeaaaaaaa aaaaaaaTherawithinaaaakeepsaaaaaaaapaA") == "wWFWJaa aaaaaaa"
    @test words_in_sentence("ThAn apple a day kweeps the doctor awaye cat hasin the hat sat on the mawWFWJaat") == "apple day the awaye cat hasin the hat sat on the"
    @test words_in_sentence("ovrlazuy") == ""
    @test words_in_sentence("kekepsrek") == ""
    @test words_in_sentence("ht") == "ht"
    @test words_in_sentence("woodayndce") == ""
    @test words_in_sentence("ovrlazuthia tesnappleime numbers in words within a sentenceaoofcfeeicky") == "ovrlazuthia numbers in words"
    @test words_in_sentence("ovrlazuthia") == "ovrlazuthia"
    @test words_in_sentence("qq") == "qq"
    @test words_in_sentence("thpriquikmeeg") == "thpriquikmeeg"
    @test words_in_sentence("oveeAn") == ""
    @test words_in_sentence("wsords") == ""
    @test words_in_sentence("science threesome has brsscience some has branhacses ofentencehes of") == "science has has of"
    @test words_in_sentence("athis") == "athis"
    @test words_in_sentence("wsds") == ""
    @test words_in_sentence("this is a atest for prisme numbers in woodaynce") == "is atest for numbers in"
    @test words_in_sentence("wWFW") == ""
    @test words_in_sentence("quicniscie some haswodaynek inbrsentencehes ofinbrseentenncehesPipwWFWJaaek") == "haswodaynek ofinbrseentenncehesPipwWFWJaaek"
    @test words_in_sentence("Peetquiker") == ""
    @test words_in_sentence("quicniscienthe qui dogce some has inbrsentencehesek") == "qui dogce has inbrsentencehesek"
    @test words_in_sentence("keepsrek") == ""
    @test words_in_sentence("ThAn apple a dayovrlazy kweeps the doctor awaye cat hasin the hat sat on the mawWFWJaat") == "apple the awaye cat hasin the hat sat on the"
    @test words_in_sentence("ovrlazuthian") == ""
    @test words_in_sentence("Pquicniscienthe quick brown fox jumps over the lazy dogce squicninekas inbrsentencehesekeeter") == "quick brown fox jumps the dogce"
    @test words_in_sentence("ofineat") == "ofineat"
    @test words_in_sentence("An apple a lazyoday keeps the doctor away") == "An apple keeps the"
    @test words_in_sentence("oveAn apple a day keeps the dooctor awayr") == "oveAn apple day keeps the dooctor awayr"
    @test words_in_sentence("gthhtree") == ""
    @test words_in_sentence("aonePiper two three fou r five six seven eight ngine") == "two three fou six seven eight ngine"
    @test words_in_sentence("wcordcats") == ""
    @test words_in_sentence("nusmbscience some has bProtencehess ofers") == "has bProtencehess ofers"
    @test words_in_sentence("owodayabcdefghiijklmnoptwodogatswordsqrstuyz") == ""
    @test words_in_sentence("daywodayabcdefghijklmnopqrstuvwxyz") == ""
    @test words_in_sentence("nusmnbscienquicniscie some hasthis is for prirs in wodaynce inbrsentencehes ofinekce") == "hasthis is for prirs in"
    @test words_in_sentence("tesAnnumbonrs") == "tesAnnumbonrs"
    @test words_in_sentence("ineZnNaoneppleo") == ""
    @test words_in_sentence("thia tes nappleime numbers in words within a sentedogenceaoe") == "tes numbers in words"
    @test words_in_sentence("threeshowodayabcdefghijklmnopqrstuyza") == "threeshowodayabcdefghijklmnopqrstuyza"
    @test words_in_sentence("afThe Ther quick brown fox jumps over the lazy doe mataa") == "afThe quick brown fox jumps the doe mataa"
    @test words_in_sentence("jumhewPro") == ""
    @test words_in_sentence("aone tnwo three fou r five six seven eight nine") == "three fou six seven eight"
    @test words_in_sentence("priisiiomofinTheke") == ""
    @test words_in_sentence("fobrancheovrlazuthiansx") == "fobrancheovrlazuthiansx"
    @test words_in_sentence("wodayatbcdepfghijpklmnopqrstuvwxfivec") == "wodayatbcdepfghijpklmnopqrstuvwxfivec"
    @test words_in_sentence("cdTOCiFqP") == ""
    @test words_in_sentence("uithis ittukickesomeowodogs for prime numbersofers ian wodayncek") == "for prime ian"
    @test words_in_sentence("pe") == "pe"
    @test words_in_sentence("bcrsentenncehes") == ""
    @test words_in_sentence("eofcfe") == ""
    @test words_in_sentence("aa aaaaa aaaaaa aaaaaaaa bcrsentebrseentenncehesnceheafThesaaaaaaaa") == "aa aaaaa"
    @test words_in_sentence("thinuquaoneppleekin") == "thinuquaoneppleekin"
    @test words_in_sentence("qnumbbeonrs") == "qnumbbeonrs"
    @test words_in_sentence("doegcem") == "doegcem"
    @test words_in_sentence("aopneppnle") == ""
    @test words_in_sentence("aaaaaaaaaaaakeepsaaaaaaaaptwPaaaaaaaaaaaakeepsaaaaaaaaapaAferoaA") == ""
    @test words_in_sentence("one two three quicniscie some has inbrsentencehes ofinekfour five six seven eight nine") == "one two three has six seven eight"
    @test words_in_sentence("mat") == "mat"
    @test words_in_sentence("thhreescience sbrsentenncethreeheses of") == "thhreescience of"
    @test words_in_sentence("aaaaapeppeatestersaaaaaaaaPeteroapaqauipriisiimofinekekA") == ""
    @test words_in_sentence("aoonlpple") == ""
end
