@testitem "153_strongest_extension_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "153_strongest_extension.jl"))
    @test strongest_extension("Test1",["UPPERCASE", "uppercase", "1111"]) == "Test1.UPPERCASE"
    @test strongest_extension("Test2",["capitalLETTERS", "lowercaseletters", "mIxEdcAsE"]) == "Test2.capitalLETTERS"
    @test strongest_extension("Test3",["oneUPPERcaseletter", "TWoUPPERcaseletTErs", "threeUppercaseletters", "fourlowercaseletters"]) == "Test3.TWoUPPERcaseletTErs"
    @test strongest_extension("Test4",["ALLUPPERcaseletters", "ALLlowercaseletters", "Nolettersatall123", "12345"]) == "Test4.12345"
    @test strongest_extension("Test5",["ZERO", "one", "Two", "THREE", "four", "FIVE", "six", "seven", "eight", "nine", "10"]) == "Test5.THREE"
    @test strongest_extension("Person",["TEst", "Name", "naMe", "AGE"]) == "Person.AGE"
    @test strongest_extension("Animal",["CAMel", "hOrSE", "DoG"]) == "Animal.CAMel"
    @test strongest_extension("Vehicle",["Automobile", "CAR", "SuPerbIkE", "Z"]) == "Vehicle.CAR"
    @test strongest_extension("Computer",["Laptop", "DEsktop", "TABLET", "MONITOR", "MOUSE", "KEYboard"]) == "Computer.MONITOR"
    @test strongest_extension("Book",["NOVEL", "picturebook", "COOkbook", "Dictionary", "Encyclopedia"]) == "Book.NOVEL"
    @test strongest_extension("Computer",["Laptop", "DEsktop", "TABLET", "MONITOR", "MOUSE", "KEYboard", "KEYeightboard"]) == "Computer.MONITOR"
    @test strongest_extension("Compter",["Laptop", "DEsktop", "TABLET", "MONITOR", "MOUSE", "KEYboard", "KEYeightboard"]) == "Compter.MONITOR"
    @test strongest_extension("Computer",["Laptop", "DEsktop", "TABLET", "MONITOR", "MOUSE", "KEYeightboard"]) == "Computer.MONITOR"
    @test strongest_extension("Vehcice",["Automobile", "CAR", "Vehicle", "SuPerbIkE", ""]) == "Vehcice.CAR"
    @test strongest_extension("VehciceBook",["Automobile", "CAR", "Vehicle", "SuPerbIkE", ""]) == "VehciceBook.CAR"
    @test strongest_extension("Animaal",["CAMel", "hOrSE", "DoG"]) == "Animaal.CAMel"
    @test strongest_extension("Animal",["capitalLETTERS", "lowercaseletters", "mIxEdcAsE"]) == "Animal.capitalLETTERS"
    @test strongest_extension("Test1",["UPPERCASE", "uppercase", "uppercasse", "1111"]) == "Test1.UPPERCASE"
    @test strongest_extension("Test1",["UPPERCASE", "uppercase", "Animal"]) == "Test1.UPPERCASE"
    @test strongest_extension("Vehcice",["Automobile", "CAR", "Vehicele", "SuPerbIkE", ""]) == "Vehcice.CAR"
    @test strongest_extension("T1e1st1",["UPPERCASE", "uppercase", "1111"]) == "T1e1st1.UPPERCASE"
    @test strongest_extension("Test3",["oneUPPERcaseletter", "threeUppercaseletters", "fourlowercaseletters", "threeUppercaseletters"]) == "Test3.oneUPPERcaseletter"
    @test strongest_extension("Vehcice",["bIkE", "Automobile", "CAR", "Vehicle", "SuPerbIkE", ""]) == "Vehcice.CAR"
    @test strongest_extension("eightTeste3",["UPPERCASE", "uppercase", "Animal"]) == "eightTeste3.UPPERCASE"
    @test strongest_extension("AniVehcicemal",["CAMel", "hOrSE", "DoG"]) == "AniVehcicemal.CAMel"
    @test strongest_extension("Test5",["ZERO", "one", "Two", "THREE", "four", "FIVE", "six", "FVIVE", "seven", "eight", "nine", "10"]) == "Test5.THREE"
    @test strongest_extension("VehciceBo",["Automobile", "CAR", "Vehicle", "SuPerbIkE", ""]) == "VehciceBo.CAR"
    @test strongest_extension("Test1",["UPPERSCASE", "uppercase", "Animal"]) == "Test1.UPPERSCASE"
    @test strongest_extension("Test1",["UPPERCASE", "uppercase", "uppercasse", "1Test5111"]) == "Test1.UPPERCASE"
    @test strongest_extension("Animal",["Do", "CAMel", "hOrSE", "ZERO"]) == "Animal.ZERO"
    @test strongest_extension("eightTeste3",["aAnimal", "UPPERCASE", "uppercase", "Animal"]) == "eightTeste3.UPPERCASE"
    @test strongest_extension("TeTst3CTest3omputer",["oneUPPERcaseletter", "TWoUPPERcaseletTErs", "fourlowercaseletteNamers", "threeUppercaseletters", "fourlowercaseletters"]) == "TeTst3CTest3omputer.TWoUPPERcaseletTErs"
    @test strongest_extension("Vehcpicturebccookoobk",["Automobile", "CAR", "Vehicle", "SuPerbIkE", ""]) == "Vehcpicturebccookoobk.CAR"
    @test strongest_extension("Test5",["ZERO", "one", "Two", "THREE", "fur", "four", "FIVE", "six", "FVIVE", "seven", "eight", "nine", "10"]) == "Test5.THREE"
    @test strongest_extension("AnimAnimaonelal",["CAMel", "hOrSE", "DoG"]) == "AnimAnimaonelal.CAMel"
    @test strongest_extension("_",["yolo", "900000000", "s3cr3tK3y", "GIMMETH3L00TZ!"]) == "_.GIMMETH3L00TZ!"
    @test strongest_extension("ClassName",["XXXXXXx", "AAA", "ffffff", "Bbcde", "GHIJKLMN"]) == "ClassName.GHIJKLMN"
    @test strongest_extension("My_class",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH"]) == "My_class.HHHHHH"
    @test strongest_extension("Another_class",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "Z"]) == "Another_class.AbCdEfG"
    @test strongest_extension("MYCLASS",["qwerty", "asdfgh", "zxcvbn", "QWERTY", "ASDFGHJKL", "ZXCVBNM"]) == "MYCLASS.ASDFGHJKL"
    @test strongest_extension("testing1",["TESTING2", "TEST", "test", "tEstin3g"]) == "testing1.TESTING2"
    @test strongest_extension("AnotherClass",["hello", "WORLD", "Python321", "TEST", "Extend"]) == "AnotherClass.WORLD"
    @test strongest_extension("MyClass",["AbcDEFg", "hIjKlmn", "OPqrst", "UVWxYZ"]) == "MyClass.UVWxYZ"
    @test strongest_extension("YetAnotherClass",["1", "BBB", "ccc", "DDDDDD", "EEEeeeE", "ffffff"]) == "YetAnotherClass.DDDDDD"
    @test strongest_extension("OneMoreClass",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "EEE", "FgHiJ", "kLMNop"]) == "OneMoreClass.AAAaA"
    @test strongest_extension("s3cr3tK3y",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "Z"]) == "s3cr3tK3y.AbCdEfG"
    @test strongest_extension("MyCslass",["hIjKlmn", "OPqrst", "UVWxYZ"]) == "MyCslass.UVWxYZ"
    @test strongest_extension("AnotherClass_",["hello", "WORLD", "Python321", "TEST", "Python3yolo21", "Extend"]) == "AnotherClass_.WORLD"
    @test strongest_extension("MExtendy_class",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH"]) == "MExtendy_class.HHHHHH"
    @test strongest_extension("MYCLASS",["qwerty", "asdfgh", "zxcvbn", "QWERTY", "ASDFGHJKL", "qweqrty", "ZXCVBNM"]) == "MYCLASS.ASDFGHJKL"
    @test strongest_extension("My_classMYCLASS",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH", "ZZZZ"]) == "My_classMYCLASS.HHHHHH"
    @test strongest_extension("ClassaName",["XXXXXXx", "AAA", "ffffff", "Bbcde", "GHIJKLMN"]) == "ClassaName.GHIJKLMN"
    @test strongest_extension("ClassaName",["XXXXXXx", "AAA", "ffffff", "Bbcde", "GHIJKLN"]) == "ClassaName.GHIJKLN"
    @test strongest_extension("otherClahellorss",["hello", "WORLD", "Python321", "TEST", "Extend"]) == "otherClahellorss.WORLD"
    @test strongest_extension("s3cr3tK3y",["Hijklmno", "pqrstuvwxy", "Z"]) == "s3cr3tK3y.Z"
    @test strongest_extension("s3cr3tK3y",["Hijklmno", "12345", "pqrstuvwxy", "Z", "Hijklmno"]) == "s3cr3tK3y.Z"
    @test strongest_extension("ClassaName",["GHIHJKLN", "XXXXXXx", "AAA", "ffffff", "Bbcde", "GHIJKLN"]) == "ClassaName.GHIHJKLN"
    @test strongest_extension("otherClahellorss",["hello", "WORLD", "ExtAbCdEfGend", "TEST", "Extend"]) == "otherClahellorss.WORLD"
    @test strongest_extension("My_classMYCLASS",["Aaa", "ZZZZ", "dddd", "E", "HHHHHH", "ZZZZ"]) == "My_classMYCLASS.HHHHHH"
    @test strongest_extension("Python321_",["yolo", "900000000", "s3cr3tK3y", "GIMMETH3L00TZ!"]) == "Python321_.GIMMETH3L00TZ!"
    @test strongest_extension("My_classLMYCLASS",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH", "ZZZZ"]) == "My_classLMYCLASS.HHHHHH"
    @test strongest_extension("s3cr3tK3y",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy"]) == "s3cr3tK3y.AbCdEfG"
    @test strongest_extension("YetAnotherClass",["1", "BBB", "GIMMETH3L00TZ!", "ccc", "DDDDDD", "EEEeeeE", "ffffff"]) == "YetAnotherClass.GIMMETH3L00TZ!"
    @test strongest_extension("Another_class",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "Z", "12345"]) == "Another_class.AbCdEfG"
    @test strongest_extension("MExtendy_class",["Aaa", "ddd", "E", "HHHHHH"]) == "MExtendy_class.HHHHHH"
    @test strongest_extension("My_class",["qwerty", "asdfgh", "zxcvbn", "ASDFGHJKL", "qwewrty", "ZXCVBNM"]) == "My_class.ASDFGHJKL"
    @test strongest_extension("Another_class",["AbCdEfG", "Hijklmno", "12345", "AbCdEfASDFGHJKLG", "pqrstuvwxy", "Z", "12345"]) == "Another_class.AbCdEfASDFGHJKLG"
    @test strongest_extension("dddd",["Hijklmno", "pqrstuvwxy", "Hijklmno"]) == "dddd.Hijklmno"
    @test strongest_extension("ClassaNamse",["XXXXXXx", "AAA", "ffffff", "Bbcde", "GHIJKLMN", "XXXXXXx"]) == "ClassaNamse.GHIJKLMN"
    @test strongest_extension("MyClass",["AbcDEFg", "hIjKlmn", "OPqrst", "UVotherClahellorssWxYZ"]) == "MyClass.AbcDEFg"
    @test strongest_extension("_",["yolo", "900000000", "s3cr3tKK3y", "GIMMETH3L00TZ!"]) == "_.GIMMETH3L00TZ!"
    @test strongest_extension("My_classLMYCLASS_",["yolo", "900000000", "s3cr3tK3y", "GIMMETH3L00TZ!"]) == "My_classLMYCLASS_.GIMMETH3L00TZ!"
    @test strongest_extension("s3cr3tK3y",["AbCdEfG", "Hijklmno", "My__classMYCLASS", "pqrstuvwxy", "Hijklmno"]) == "s3cr3tK3y.My__classMYCLASS"
    @test strongest_extension("_",["yolo", "900000000", "s3cr3tK3y"]) == "_.900000000"
    @test strongest_extension("s3cr3tK3y",["Hijklmno", "pqrstuvwxy", "Z", "pqrstuvwxy"]) == "s3cr3tK3y.Z"
    @test strongest_extension("ClassaName",["XXXXXX", "AAA", "ffffff", "Bbcde", "GHIJKLN"]) == "ClassaName.GHIJKLN"
    @test strongest_extension("MYCLASS",["qwerty", "zxcvbn", "QWERTY", "ASDFGHJKL", "ZXCVBNM"]) == "MYCLASS.ASDFGHJKL"
    @test strongest_extension("MyClasss",["AbcDEFg", "hIjKlmn", "OPqrst", "UVWxYZ"]) == "MyClasss.UVWxYZ"
    @test strongest_extension("s3cr3tK3y",["AbCdEfG", "My__classMYCLASS", "pqrstuvwxy", "Hijklmno"]) == "s3cr3tK3y.My__classMYCLASS"
    @test strongest_extension("otherClahellorss",["ClassaNamse", "WORLD", "ExtAbCdEfGend", "TEST", "Extend"]) == "otherClahellorss.WORLD"
    @test strongest_extension("My_classMYCLASS",["Aaa", "ZZZZ", "dddd", "E", "HHHHHH", "ZZZZ", "ZZZZ"]) == "My_classMYCLASS.HHHHHH"
    @test strongest_extension("MYCLASMyClasssS",["qwerty", "asdfgh", "zxcvbn", "QWERTY", "ASDFGHJKL", "qweqrty", "ZXCVBNM"]) == "MYCLASMyClasssS.ASDFGHJKL"
    @test strongest_extension("Another_class",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "Z", "12345", "AbCdEfG"]) == "Another_class.AbCdEfG"
    @test strongest_extension("AnotherClas_",["hello", "WORLD", "Python321", "TEST", "Python3nyolo21", "Extend", "Python3yolo21"]) == "AnotherClas_.WORLD"
    @test strongest_extension("ClassaNamse",["XXXXXXx", "AAA", "bbBbB", "Bbcde", "MyClasss", "XXXXXXx"]) == "ClassaNamse.XXXXXXx"
    @test strongest_extension("ddGHIHJKLNdd",["Hijklmno", "pqrstuvwxy", "Hijklmno"]) == "ddGHIHJKLNdd.Hijklmno"
    @test strongest_extension("qwewrty",["ylo", "yolo", "900000000", "s3cr3tK3y"]) == "qwewrty.900000000"
    @test strongest_extension("OPqrst",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy"]) == "OPqrst.AbCdEfG"
    @test strongest_extension("MExtendy_class",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH", "ZZZZ"]) == "MExtendy_class.HHHHHH"
    @test strongest_extension("AnotAbCdEfASDFGHJKLGher_class",["AbCdEfG", "Hijklmno", "12345", "AbCdEfASDFGHJKLG", "pqrstuvwxy", "Z", "12345"]) == "AnotAbCdEfASDFGHJKLGher_class.AbCdEfASDFGHJKLG"
    @test strongest_extension("My_class",["Aaa", "ZZZzxcvbnZ", "ddd", "E", "HHHHHH"]) == "My_class.HHHHHH"
    @test strongest_extension("otherClahellorss",["ClassaNamsse", "WORLD", "ExtAbCdEfGend", "TEST", "Extend"]) == "otherClahellorss.WORLD"
    @test strongest_extension("ys3cr3tK3y",["Hijklmno", "pqrstuvwxy", "Z"]) == "ys3cr3tK3y.Z"
    @test strongest_extension("YetAnotherClasUVWxYZs",["1", "BBB", "ccc", "DDDDDD", "EEEeeeE", "ffffff", "EEEeeeE"]) == "YetAnotherClasUVWxYZs.DDDDDD"
    @test strongest_extension("MnYetAnSlaassYCLASS",["qwerty", "zxcvbn", "QWERTY", "ASDFGHJKL", "ZXCVBNM"]) == "MnYetAnSlaassYCLASS.ASDFGHJKL"
    @test strongest_extension("My_class",["ddddDDD", "asdfgh", "zxcvbn", "ASDFGHJKL", "qwewrty", "ZXCVBNM", "asdfgh"]) == "My_class.ASDFGHJKL"
    @test strongest_extension("nYetAnotherCMYCLASSlassnothGIM!METYoetAnoEEErClassH3L00TZ!yoloerClass",["qwerty", "zxcvbn", "QWERTY", "ASDFGHJKL", "ZXCVBNM"]) == "nYetAnotherCMYCLASSlassnothGIM!METYoetAnoEEErClassH3L00TZ!yoloerClass.ASDFGHJKL"
    @test strongest_extension("ClassaName",["XXXXXX", "AAA", "ffffff", "Bbcde", "GHIJKLN", "GHIJKLN"]) == "ClassaName.GHIJKLN"
    @test strongest_extension("Python321_",["yolo", "nYetAnotherCMYCLASSlaass", "s3cr3tK3y", "GIMMETH3L00TZ!"]) == "Python321_.GIMMETH3L00TZ!"
    @test strongest_extension("test",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "Z", "12345", "AbCdEfG"]) == "test.AbCdEfG"
    @test strongest_extension("MMy_classMYCLASS",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH", "ZZZZ"]) == "MMy_classMYCLASS.HHHHHH"
    @test strongest_extension("x1UXXXXXXxVWxYZ",["1", "BBB", "ccc", "DDDDDD", "EEEeeeE", "ffffff", "EEEeeeE"]) == "x1UXXXXXXxVWxYZ.DDDDDD"
    @test strongest_extension("Another_css",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "Z", "12345"]) == "Another_css.AbCdEfG"
    @test strongest_extension("test",["Hijklmno", "12345", "pqrstuvwxy", "Z", "12345", "AbCdEfG"]) == "test.Z"
    @test strongest_extension("My_class",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH", "E"]) == "My_class.HHHHHH"
    @test strongest_extension("MMy_classMYCLASS",["Aaa", "ZZZZ", "ddd", "HHHHHH", "ZZZZ"]) == "MMy_classMYCLASS.HHHHHH"
    @test strongest_extension("My_class",["ddddDDD", "asdfgh", "Aaa", "zxcvbn", "ASDFGHJKL", "qwewrty", "ZXCVBNM", "asdfgh"]) == "My_class.ASDFGHJKL"
    @test strongest_extension("MYCLASS",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH", "ZZZZ"]) == "MYCLASS.HHHHHH"
    @test strongest_extension("My_classMYCLASS",["Aa", "ZZZZ", "HHHHHH", "ZZZZ"]) == "My_classMYCLASS.HHHHHH"
    @test strongest_extension("Another_class",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "Z", "AbCdEfG"]) == "Another_class.AbCdEfG"
    @test strongest_extension("ClassNaMqwertyy_classLMYCLA_e",["XXXXXXx", "AAA", "ffffff", "Bbcde", "GHIJKLMN"]) == "ClassNaMqwertyy_classLMYCLA_e.GHIJKLMN"
    @test strongest_extension("My__classMYCLASS",["ZZZZ", "dddd", "E", "HHHHHH", "ZZZZ", "ZZZZ", "ZZZZ"]) == "My__classMYCLASS.HHHHHH"
    @test strongest_extension("My_class",["Aaa", "ZZZZ", "HHHMeyOneMoreClassClass", "ddd", "E", "HHHHHH", "E", "ZZZZ"]) == "My_class.HHHHHH"
    @test strongest_extension("My_class",["Aaa", "ZZZZ", "ddd", "E", "HHHHH", "HHHHHH"]) == "My_class.HHHHHH"
    @test strongest_extension("ddGHIHJKLNdd",["hello", "WORLD", "Python321", "TEST", "Python3yolo21", "Extend"]) == "ddGHIHJKLNdd.WORLD"
    @test strongest_extension("OPqrst",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "12345"]) == "OPqrst.AbCdEfG"
    @test strongest_extension("ClassaNamse",["XXXXXX", "AAA", "ffffff", "Bbcde", "GHIJKLN", "GHIJKLN"]) == "ClassaNamse.GHIJKLN"
    @test strongest_extension("otherClahellorss",["ClassaNamsse", "WORLD", "ExtAbCdEfGend", "Extend"]) == "otherClahellorss.WORLD"
    @test strongest_extension("ClassaNamse",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH", "ZZZZ"]) == "ClassaNamse.HHHHHH"
    @test strongest_extension("MExty_class",["Aaa", "ddd", "E", "HHYetAnotherClassHHHH"]) == "MExty_class.E"
    @test strongest_extension("MMExtendy_classy_classMYCLASS",["Aaa", "ZZZZ", "dddd", "AAaa", "HHHHHH", "ZZZZ"]) == "MMExtendy_classy_classMYCLASS.HHHHHH"
    @test strongest_extension("s3cr3tKK3y",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "Z", "12345"]) == "s3cr3tKK3y.AbCdEfG"
    @test strongest_extension("MExtendy_clasAnotherClasss",["Aaa", "ZZZZ", "ddd", "E", "HHHHHH", "ZZZZ"]) == "MExtendy_clasAnotherClasss.HHHHHH"
    @test strongest_extension("My_class",["qwerty", "asdfgh", "zxcvbHHHMeyOneMoreClassClassn", "ASDFGHJKL", "qwewrty", "ZXCVBNM"]) == "My_class.ASDFGHJKL"
    @test strongest_extension("JDLRFD",["AbcDEFg", "hIjKlmn", "OPqrst", "UVotherClahellorssWxYZ", "hIjKlmn"]) == "JDLRFD.AbcDEFg"
    @test strongest_extension("test",["AbCdEfG", "Hijklmno", "12345", "pqrstuvwxy", "Z", "12345", "AbCdEfG", "pqrstuvwxy"]) == "test.AbCdEfG"
    @test strongest_extension("My_classLMYCLASS_nnYetAnotherCMYsCLASSUVWxYZlass",["yolo", "900000000", "s3cr3tK3y", "GIMMETH3L00TZ!"]) == "My_classLMYCLASS_nnYetAnotherCMYsCLASSUVWxYZlass.GIMMETH3L00TZ!"
    @test strongest_extension("YoetAnoEEErClasslassaName",["XXXXXXx", "AAA", "ffffff", "Bbcde", "GHIJKLMN"]) == "YoetAnoEEErClasslassaName.GHIJKLMN"
    @test strongest_extension("MExtendyc_class",["Aaa", "ZZZZ", "E", "HHHHHH"]) == "MExtendyc_class.HHHHHH"
    @test strongest_extension("MyClasssnYetAnotherCMYsCLASMqwertyy_classLMYCLASS_",["AbcDEFg", "hIjKlmn", "OPqrst", "UVWxYZ", "OPqrst"]) == "MyClasssnYetAnotherCMYsCLASMqwertyy_classLMYCLASS_.UVWxYZ"
    @test strongest_extension("My_class",["qwerty", "asdfgCcCcC", "zxcvbHHHMeyOneMoreClassClassn", "ASDFGHJKL", "qwewrty", "ZXCVBNM"]) == "My_class.ASDFGHJKL"
    @test strongest_extension("MMy_clasMEAAAaAxtendy_classsMYCLASS",["Aaa", "ZZZZ", "HHHHHH", "ZZZZ"]) == "MMy_clasMEAAAaAxtendy_classsMYCLASS.HHHHHH"
    @test strongest_extension("",["HhAas", "okIWILL123"]) == ".okIWILL123"
    @test strongest_extension("\$pecial_&_Cl@ss_name",["YoUReXt"]) == "\$pecial_&_Cl@ss_name.YoUReXt"
    @test strongest_extension("123ThisIsTheClassName456",["Ex1", "ex2", "ex3", "EX4"]) == "123ThisIsTheClassName456.EX4"
    @test strongest_extension("ThisIsTheClassName",["ThisIsTheExtension"]) == "ThisIsTheClassName.ThisIsTheExtension"
    @test strongest_extension("NoExtensionHasUpperCaseOrLowerCase",["1234", "5678", "9987", "hello"]) == "NoExtensionHasUpperCaseOrLowerCase.1234"
    @test strongest_extension("",["abc", "DEF", "gHi"]) == ".DEF"
    @test strongest_extension("SampleClass",["Abc", "ddD", "eFG"]) == "SampleClass.eFG"
    @test strongest_extension("SampleClass",["AAA", "BBB", "CCC"]) == "SampleClass.AAA"
    @test strongest_extension("SampleClass",["aBc", "dEf", "Ghi"]) == "SampleClass.aBc"
    @test strongest_extension("SampleClass",["AbC", "DeF", "gHI"]) == "SampleClass.AbC"
    @test strongest_extension("UVWxYZ",["hello", "WORLD", "Python321", "Exteasdfghnd", "TEST", "Extend"]) == "UVWxYZ.WORLD"
    @test strongest_extension("AAA",["AbcDEFg", "hIjKlmn", "OPqrst", "UVWxYZ"]) == "AAA.UVWxYZ"
    @test strongest_extension("testing1",["TESTING2", "TOPqrstEST", "test", "tEstin3g"]) == "testing1.TESTING2"
    @test strongest_extension("MyClass",["AbcDEFg", "hIjKlmn", "OPqrst"]) == "MyClass.AbcDEFg"
    @test strongest_extension("AbCdEfG",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "EEE", "FgHiJ", "kLMNop"]) == "AbCdEfG.AAAaA"
    @test strongest_extension("UVWxYZ",["WORLD", "Python321", "Exteasdfghnd", "TEST", "Extend"]) == "UVWxYZ.WORLD"
    @test strongest_extension("YetAnotherClass",["1", "BBB", "ccc", "DDDDDD", "ffffff"]) == "YetAnotherClass.DDDDDD"
    @test strongest_extension("MyClass",["AbcDEFg", "hIjKlmn", "Bbcde", "UVWxYZ"]) == "MyClass.UVWxYZ"
    @test strongest_extension("My_class",["Aaa", "ZZZZ", "ddd", "E"]) == "My_class.ZZZZ"
    @test strongest_extension("AbCdETESTING2fG",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "EEE", "FgHiJ", "kLMNop"]) == "AbCdETESTING2fG.AAAaA"
    @test strongest_extension("AbCdEfG",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "EEE", "FgHiJ", "kLMNop", "ddddDDD"]) == "AbCdEfG.AAAaA"
    @test strongest_extension("MYCLASS",["hello", "WORLD", "Python321", "TEST", "Extend"]) == "MYCLASS.WORLD"
    @test strongest_extension("Tg1",["TESTING2", "TOPqrstEST", "TOPqrsttEST", "test", "tEstin3g"]) == "Tg1.TESTING2"
    @test strongest_extension("fffffBbcdeAaaff",["AAAaA", "bbBbB", "CcCcC", "ass", "EEE", "FgHiJ", "kLMNop", "ddddDDD"]) == "fffffBbcdeAaaff.AAAaA"
    @test strongest_extension("Another_class",["AbCdEfG", "1235", "Hijklmno", "12345", "vpqrstuvwxy", "Z"]) == "Another_class.AbCdEfG"
    @test strongest_extension("Tg",["TESTING2", "TOPqrstEST", "TOPqrsttEST", "test", "tEstin3g"]) == "Tg.TESTING2"
    @test strongest_extension("TESTING2",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "EEE", "FgHiJ", "kLMNop"]) == "TESTING2.AAAaA"
    @test strongest_extension("M1235yClass",["AbcDEFg", "hIjKlmn", "Bbcde", "UVWxYZ"]) == "M1235yClass.UVWxYZ"
    @test strongest_extension("T1",["TESTING2", "TOPqrstESST", "TOPqrsttEST", "test", "tEstin3g"]) == "T1.TESTING2"
    @test strongest_extension("MYCLASS",["qwerty", "asdfgh", "zxcvbn", "QWERTY", "MYCLASS", "ASDFGHJKL", "ZXCVBNM"]) == "MYCLASS.ASDFGHJKL"
    @test strongest_extension("1",["TESTING2", "TOPqrstEST", "TOPqrsttEST", "test", "tEstin3g"]) == "1.TESTING2"
    @test strongest_extension("TESTING2",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "EEE", "hello", "kLMNop"]) == "TESTING2.AAAaA"
    @test strongest_extension("T1",["hello", "WORLD", "Python321", "Exteasdfghnd", "TEST", "Extend"]) == "T1.WORLD"
    @test strongest_extension("TESTING2",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "EEE", "kLMNop"]) == "TESTING2.AAAaA"
    @test strongest_extension("OneMorCassNaame",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "EEE", "FgHiJ", "kLMNop"]) == "OneMorCassNaame.AAAaA"
    @test strongest_extension("testing1",["yolo", "900000000", "s3cr3tK3y", "GIMMETH3L00TZ!"]) == "testing1.GIMMETH3L00TZ!"
    @test strongest_extension("M1235yClas",["AbcDEFg", "hIjKlmn", "Bbcde", "UVWxYZ"]) == "M1235yClas.UVWxYZ"
    @test strongest_extension("T1",["TESTING2", "TOPqrstEST", "TOPqrsttEST", "test", "tEstin3g"]) == "T1.TESTING2"
    @test strongest_extension("T1",["hello", "WORLD", "Python321", "Exteasdfghnd", "TEST", "Extend", "WORLD"]) == "T1.WORLD"
    @test strongest_extension("MCyClass",["AbcDEFg", "hIjKlmn", "OPqrst", "UVWxYZ"]) == "MCyClass.UVWxYZ"
    @test strongest_extension("_",["yolo", "900000000", "s3cr3tK3y", "GIMMETH3L00TZ!", "GIMMETH3L00TZ!"]) == "_.GIMMETH3L00TZ!"
    @test strongest_extension("1234GHIJKLMN5",["TESTING2", "TOPqrstEST", "TOPqrsttEST", "test", "tEstin3g"]) == "1234GHIJKLMN5.TESTING2"
    @test strongest_extension("YetAtEstin3gnotherClass",["1", "BBB", "ccc", "DDDDDD", "EEEeeeE", "ffffff"]) == "YetAtEstin3gnotherClass.DDDDDD"
    @test strongest_extension("Ye1234GHIJKLMN5tAnotherClass",["1", "BBB", "ccc", "DDDDDD", "ffffff"]) == "Ye1234GHIJKLMN5tAnotherClass.DDDDDD"
    @test strongest_extension("M1235yClass",["AbcDEFg", "hIjKlmn", "Bbcde", "UVWxYZ", "AbcDEFg"]) == "M1235yClass.UVWxYZ"
    @test strongest_extension("Tg",["AbcDEFg", "hIjKlmn", "OPqrst", "UVWxYZ", "UVWxYZ"]) == "Tg.UVWxYZ"
    @test strongest_extension("Ye1234GHIJKLMN5tAnotherClass",["HHHHHM1235yClassHExteand1", "BBB", "ccc", "DDDDDD", "ffffff"]) == "Ye1234GHIJKLMN5tAnotherClass.DDDDDD"
    @test strongest_extension("TESTINT2G2",["AAAaA", "bbBbB", "CcCcC", "testiffffffngg1", "EEE", "kLMNop", "bbBbB"]) == "TESTINT2G2.AAAaA"
    @test strongest_extension("_Exteasdfghnd",["yolo", "900000000", "s3cr3tK3y", "GIMMETH3L00TZ!"]) == "_Exteasdfghnd.GIMMETH3L00TZ!"
    @test strongest_extension("T11",["hello", "WORLD", "Python321", "Exteasdfghnd", "TEST", "Extend"]) == "T11.WORLD"
    @test strongest_extension("AbCEdEfG",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "EEE", "FgHiJ", "kLMNop"]) == "AbCEdEfG.AAAaA"
    @test strongest_extension("YetAtEstin3gnotherClass",["1", "BBB", "ccc", "DDDDDD", "bbBbBeeE", "ffffff"]) == "YetAtEstin3gnotherClass.DDDDDD"
    @test strongest_extension("AbCdEfG",["AAAaA", "bbBbB", "CcCcC", "ddddDDD", "xcvbnAAAaA", "EEE", "FgHiJ", "kLMNop", "ddddDDD"]) == "AbCdEfG.AAAaA"
    @test strongest_extension("MyClMasss",["1", "BBB", "ccc", "DDDDDD", "bbBbBeeE", "ffffff"]) == "MyClMasss.DDDDDD"
    @test strongest_extension("TgTg1",["AbcDEFg", "hIjKlmn", "OPqrst", "UVWxYZ", "UVWxYZ"]) == "TgTg1.UVWxYZ"
    @test strongest_extension("Another_class",["AbCdEfG", "1235", "Hijklmno", "12345", "vpqrstuvwxy", "Z", "Hijklmno"]) == "Another_class.AbCdEfG"
    @test strongest_extension("YCBBBLASS",["1", "BBB", "ccc", "DDDDDD", "ffffff"]) == "YCBBBLASS.DDDDDD"
    @test strongest_extension("T1",["hello", "Python321", "Exteasdfghnd", "TEST", "Extend"]) == "T1.TEST"
    @test strongest_extension("M12ss",["AbcDEFg", "hIjKlmn", "Bbcde", "UVWxYZ", "AbcDEFg"]) == "M12ss.UVWxYZ"
    @test strongest_extension("BBBB",["AAAaA", "bbBbB", "CcCcC", "testiffffffngg1", "EEE", "kLMNop", "bbBbB"]) == "BBBB.AAAaA"
    @test strongest_extension("_Exteasdfghnd",["yMCyClassolo", "yolo", "900000000", "s3cr3tK3y", "GIMMETH3L00TZ!"]) == "_Exteasdfghnd.GIMMETH3L00TZ!"
    @test strongest_extension("T1",["hello", "WORLD", "Python321", "Exteasdfghnd", "helHHHHHHEHxteasdkLMNopfBBBghndo", "TEST", "Extend"]) == "T1.WORLD"
end
