@testitem "158_find_max_HumanEvalPlus_v0_1_9_test.jl" tags=[:HumanEvalPlus_v0_1_9] begin
    include(joinpath(ENV["GENERATION_DIR"], "158_find_max.jl"))
    @test find_max(["abcdefg", "hijklmnop", "qrstuvwxyz"]) == "qrstuvwxyz"
    @test find_max(["abacbdce", "edcbacba", "dbcaebda"]) == "abacbdce"
    @test find_max(["aabbcc", "dddeee", "fff"]) == "aabbcc"
    @test find_max(["abc", "bcd", "def", "efg"]) == "abc"
    @test find_max(["abcd", "bcde", "cdef", "defg"]) == "abcd"
    @test find_max(["aaaa", "bbbb", "cccc"]) == "aaaa"
    @test find_max(["hello"]) == "hello"
    @test find_max(["xyz", "pqr"]) == "pqr"
    @test find_max(["abc", "defg"]) == "defg"
    @test find_max(["aaa", "bbb", "ccc", "aaa"]) == "aaa"
    @test find_max(["hellfffo"]) == "hellfffo"
    @test find_max(["aabbcc", "aabbdbabcdcaebdacc", "dddeee", "fff"]) == "aabbdbabcdcaebdacc"
    @test find_max(["aabbdbabcdcaebdacc", "dddeee", "fff"]) == "aabbdbabcdcaebdacc"
    @test find_max(["helloyxyz", "helloxyz"]) == "helloxyz"
    @test find_max(["pqr", "pqr", "pqr"]) == "pqr"
    @test find_max(["abcdefg", "qrstuvwxyz", "qrstuvwxyz"]) == "qrstuvwxyz"
    @test find_max(["xyyyz", "xyyz", "pqr"]) == "pqr"
    @test find_max(["rpqr", "xyz", "pqr"]) == "pqr"
    @test find_max(["hello", "hello"]) == "hello"
    @test find_max(["abc", "aabbcc", "defg"]) == "defg"
    @test find_max(["helloxyz"]) == "helloxyz"
    @test find_max(["helloxyz", "aaaa", "helloxyz"]) == "helloxyz"
    @test find_max(["helloyxyz", "aaaa", "helloxyz"]) == "helloxyz"
    @test find_max(["hellfff", "hellfffo", "hellffbbbfo"]) == "hellffbbbfo"
    @test find_max(["llo"]) == "llo"
    @test find_max(["abc", "aaaaa", "aaaa"]) == "abc"
    @test find_max(["helloxyabcdefgz", "helloxyz"]) == "helloxyabcdefgz"
    @test find_max(["abc", "bcd", "def", "bbcd", "efg"]) == "abc"
    @test find_max(["rpqr", "xyz", "pqr", "pqr"]) == "pqr"
    @test find_max(["abc", "bcd", "bbcd", "efg"]) == "abc"
    @test find_max(["helloyxyz", "haaaaaello", "helloxyz", "helloyxyz"]) == "helloxyz"
    @test find_max(["abc", "aabbcc", "bcd", "def", "xyyyzbcd", "bbcd", "efg"]) == "xyyyzbcd"
    @test find_max(["abcdefg", "qrstuvwxyz", "qrstuedcbacbavwxyz"]) == "qrstuedcbacbavwxyz"
    @test find_max(["abc", "baabbcccd", "def", "efg"]) == "baabbcccd"
    @test find_max(["aaa", "haaaaaello", "bbb", "ccc", "aaa"]) == "haaaaaello"
    @test find_max(["abcdefg", "qrstuvwxbbbyz", "qrstuvwxyz"]) == "qrstuvwxbbbyz"
    @test find_max(["xyyyz", "abcdefg", "qrstuyz", "qrstuvwxyz"]) == "qrstuvwxyz"
    @test find_max(["xyyyzbchelloyxyzd", "abc", "aabbcc", "bcd", "def", "xyyyzbcd", "bbcd", "efqrstuvwxbbbyzg"]) == "efqrstuvwxbbbyzg"
    @test find_max(["abacdbdce", "edcbacba", "dbcaebda"]) == "abacdbdce"
    @test find_max(["helloxyabcdefgz", "helaabbccloxyabcdefgz", "helloxyz"]) == "helaabbccloxyabcdefgz"
    @test find_max(["xyyyz", "xyyz", "efgxyyz", "pqr"]) == "efgxyyz"
    @test find_max(["zxyz", "xyz", "pqr"]) == "pqr"
    @test find_max(["aabbcc", "aabbdbabcdcaebdacc", "dddeee", "fff", "fff", "dddeee", "aabbdbabcdcaebdacc"]) == "aabbdbabcdcaebdacc"
    @test find_max(["abcrpqrdefg", "qrstuvwxyz"]) == "abcrpqrdefg"
    @test find_max(["helloyxyz", "hellffbbbfohelloxyz", "aaaa", "helloxyz"]) == "hellffbbbfohelloxyz"
    @test find_max(["xyz", "pqr", "pqr"]) == "pqr"
    @test find_max(["qpqr", "pqr", "pqr", "pqr"]) == "pqr"
    @test find_max(["abc", "bcd", "bbcd", ""]) == "abc"
    @test find_max(["aabbdbabcdcaebdacc", "abc", "fff"]) == "aabbdbabcdcaebdacc"
    @test find_max(["pqr", "pqr", "qr", "pqr"]) == "pqr"
    @test find_max(["helloyxyz", "haaaaaello", "helloxyz", "helloyxyz", "haaaaaello"]) == "helloxyz"
    @test find_max(["aaaa", "bbbb", "cc"]) == "aaaa"
    @test find_max(["aaa", "haaaaaello", "bbb", "aa", "aaa"]) == "haaaaaello"
    @test find_max(["aabbcc", "aabbdbabcdcaebdacc", "dddeee", "fff", "fff", "dddeee", "aabbdbabcdcaebdaccabcdefg", "dddeee"]) == "aabbdbabcdcaebdaccabcdefg"
    @test find_max(["helloxyabcdefgz", "abacdbdce", "helloxyz"]) == "helloxyabcdefgz"
    @test find_max(["aabbdbabcdcaebdacc", "abc", "ff", "fff"]) == "aabbdbabcdcaebdacc"
    @test find_max(["bbbb", "cc"]) == "bbbb"
    @test find_max(["aaaa", "bbbb", "cc", "bbbb"]) == "aaaa"
    @test find_max(["aaaa", "ccccc", "cccc"]) == "aaaa"
    @test find_max(["abacdbdce", "edcbeacba"]) == "abacdbdce"
    @test find_max(["aabbcc", "aabbdbabcdcaebdacc", "dddeee", "aabbdbabcdcaebdaccdabcdefg", "fff", "fff", "dddeee", "aabbdbabcdcaebdaccabcdefg", "dddeee"]) == "aabbdbabcdcaebdaccabcdefg"
    @test find_max(["zhelloxyz", "helloxyabcdefgz", "helaabbccloxyabcdefgz", "helloxyz"]) == "helaabbccloxyabcdefgz"
    @test find_max(["abcc", "abc", "fff"]) == "abc"
    @test find_max(["xyxz", "pqr", "pqr"]) == "pqr"
    @test find_max(["abcd", "bcde", "cdef", "defg", "abcd"]) == "abcd"
    @test find_max(["abc", "bcd", "dbcaebda", "bbcd", "efg", "bbcd"]) == "dbcaebda"
    @test find_max(["aaaa", "cccc", "cccc"]) == "aaaa"
    @test find_max(["bcde", "cdef", "defg"]) == "bcde"
    @test find_max(["zhelloxyz", "helloxyz", "aaaa", "helloxyz"]) == "helloxyz"
    @test find_max(["zhelloxyz", "helloxyz", "aaaa", "helloxyz", "helloxyz"]) == "helloxyz"
    @test find_max(["helloyxyz", "haaaaaello", "aa", "helloxyz", "helloyxyz"]) == "helloxyz"
    @test find_max(["abc", "baabbcccd", "def"]) == "baabbcccd"
    @test find_max(["qpqr", "pqr", "pqqr", "pqr"]) == "pqqr"
    @test find_max(["dddeee", "aacdcaebdacc", "fff"]) == "aacdcaebdacc"
    @test find_max(["abcdefg", "qrstuvwxyz", "abcdefg"]) == "qrstuvwxyz"
    @test find_max(["pqr", "qr", "pqr"]) == "pqr"
    @test find_max(["defg"]) == "defg"
    @test find_max(["zxyz", "xyz", "pqr", "pqr"]) == "pqr"
    @test find_max(["abcc", "qrstuedcbacbavwxyz", "abc", "fff"]) == "qrstuedcbacbavwxyz"
    @test find_max(["hijklmnop", "qrstuvwxyz", "hijklmnop"]) == "qrstuvwxyz"
    @test find_max(["aabbdbabcdcaebdacc", "ff", "fff"]) == "aabbdbabcdcaebdacc"
    @test find_max(["ef", "abc", "abc", "baabbcccd", "def", "efg"]) == "baabbcccd"
    @test find_max(["aaa", "helaabbccloxyabcdefgz", "bbbb", "ccc", "aaa", "aaa"]) == "helaabbccloxyabcdefgz"
    @test find_max(["helloyxyz", "haaaaaello", "helloxyz", "helloyxyz", "bbcd", "bbcd"]) == "helloxyz"
    @test find_max(["abbbcdc", "aabbcbbbbc", "defdg"]) == "abbbcdc"
    @test find_max(["abcd", "cdef"]) == "abcd"
    @test find_max(["aabbcbbbbc", "defdg"]) == "defdg"
    @test find_max(["aabbdbabcdcaeb", "dddeee", "fff"]) == "aabbdbabcdcaeb"
    @test find_max(["helloxyz", "aaaa", "helloxydbcaebdaz", "helloxyz", "helloxyz"]) == "helloxydbcaebdaz"
    @test find_max(["abc", "abbbcdc", "ff", "fff"]) == "abbbcdc"
    @test find_max(["dddeee", "aacdcaebdac", "fff"]) == "aacdcaebdac"
    @test find_max(["abc", "aaaaa"]) == "abc"
    @test find_max(["zxyz", "xyz", "pqr", "pqr", "pqr"]) == "pqr"
    @test find_max(["qr", "pqr"]) == "pqr"
    @test find_max(["ac", "abc", "bcd", "def", "efg", "abc"]) == "abc"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "HXs9s1Q", "HSSbsh"]) == "75XPBFq19"
    @test find_max(["aaddzz", "qrstuv", "ijklmn", "efghip", "cba"]) == "efghip"
    @test find_max(["xy", "yx", "wyx", "zyx"]) == "wyx"
    @test find_max(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "a"
    @test find_max(["apple", "orange", "grape", "banana", "kiwi", "pear"]) == "orange"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "pear", "xylophone"]) == "supersonic"
    @test find_max(["cat", "tac", "act"]) == "act"
    @test find_max(["Eagle", "eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "wxyz"]) == "hijklmnop"
    @test find_max(["apple", "banana", "cherry", "date", "elderberry", "fig", "grape"]) == "elderberry"
    @test find_max(["xy", "xyx", "wyx", "zyx"]) == "wyx"
    @test find_max(["apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "date"]) == "elderberry"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["wwyx", "xy", "yx", "wyx", "zyx"]) == "wwyx"
    @test find_max(["wwyx", "xy", "yx", "wyx", "zyx", "yx"]) == "wwyx"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["o", "eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["xky", "xyx", "wyx", "xky"]) == "wyx"
    @test find_max(["abcdefg", "abckiwidefg", "hijklmnop", "qrstuv", "wxyz"]) == "abckiwidefg"
    @test find_max(["Eagle", "iHaTethis", "eAgLe"]) == "iHaTethis"
    @test find_max(["xy", "xyx", "zyx"]) == "zyx"
    @test find_max(["wwyx", "m", "yx", "wyx", "zyx"]) == "wwyx"
    @test find_max(["abcdefg", "grape", "hwmnop", "qrstuv"]) == "abcdefg"
    @test find_max(["apple", "orange", "abanana", "grape", "ana", "banana", "kiwi", "pear"]) == "orange"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "pear", "ape", "xylophone"]) == "supersonic"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "wxyz", "wxyz"]) == "hijklmnop"
    @test find_max(["r", "tac", "act"]) == "act"
    @test find_max(["xyx", "wyx", "zyx", "zyx"]) == "wyx"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "j", "v"]) == "cabcdefg"
    @test find_max(["xy", "xyx", "wyx", "zyx", "xyx"]) == "wyx"
    @test find_max(["wwyx", "m", "wyx", "zyx"]) == "wwyx"
    @test find_max(["xky", "xyx", "wyx", "xky", "xky"]) == "wyx"
    @test find_max(["xy", "grape", "xyx"]) == "grape"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "cabcdefg"]) == "cabcdefg"
    @test find_max(["wwyx", "m", "wyx"]) == "wwyx"
    @test find_max(["supersonic", "apple", "orange", "banana", "kiwi", "pear", "ape", "xylophone"]) == "supersonic"
    @test find_max(["abcdefg", "yx", "hijklmnop", "qrstuv", "wxyz"]) == "hijklmnop"
    @test find_max(["xy", "xyx", "wyx"]) == "wyx"
    @test find_max(["r", "tac", "act", "r", "tac"]) == "act"
    @test find_max(["hxy", "xyx", "zyx", "xyx"]) == "hxy"
    @test find_max(["xnyx", "hxy", "xyx", "zyx", "xyx"]) == "hxy"
    @test find_max(["abcdefg", "hijklmnop", "qrsturv", "qrstuv", "wxyz"]) == "hijklmnop"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "titd", "i", "j", "k", "lsupersonic", "m", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "lsupersonic"
    @test find_max(["b", "cabcdefg", "iHaTethis", "aaappleddzz", "e", "f", "g", "h", "titd", "i", "j", "k", "lsupersonic", "mhwmnop", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "lsupersonic"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "gg", "h", "i", "j", "zyxk", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "cabcdefg"]) == "cabcdefg"
    @test find_max(["a", "b", "c", "d", "e", "f", "g", "h", "haaappleddzz", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "u", "z"]) == "haaappleddzz"
    @test find_max(["abcdefg", "cat", "qrstuv", "wxyz"]) == "abcdefg"
    @test find_max(["orange", "grape", "banana", "", "pear"]) == "orange"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "aaappleddzz", "s", "t", "u", "v", "w", "x", "y", "z", "cabcdefg"]) == "cabcdefg"
    @test find_max(["Eagle", "eAgLe", "tit"]) == "Eagle"
    @test find_max(["xy", "xyx", "zyx", "xyx"]) == "zyx"
    @test find_max(["wwyx", "yx", "wyx", "zyx", "yx"]) == "wwyx"
    @test find_max(["Eagle", "j", "eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["abcdefg", "abckiwidefg", "hijklmnop", "qrstuv", "wxyz", "abcdefg"]) == "abckiwidefg"
    @test find_max(["apple", "orange", "abanana", "grape", "ana", "banana", "riwi", "pear", "ana"]) == "orange"
    @test find_max(["xnyx", "hxfigy", "xyx", "zyx"]) == "hxfigy"
    @test find_max(["hiijklmnop", "abcdefg", "hijklmnop", "qrstuv", "wxyz", "wxyz"]) == "hiijklmnop"
    @test find_max(["hiijklmnop", "abcdefg", "hijklmnop", "qrstuv", "wxyz", "qrstuv"]) == "hiijklmnop"
    @test find_max(["yx", "xy", "yx", "wyx", "zyx"]) == "wyx"
    @test find_max(["Eaglce", "eAgLe", "iHaTethis", "Eagle"]) == "iHaTethis"
    @test find_max(["b", "cabcdefg", "", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["xnyx", "hxfigy", "xyx", "zyx", "zyx"]) == "hxfigy"
    @test find_max(["eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "supersonic"]) == "supersonic"
    @test find_max(["apple", "banana", "cherry", "elderberry", "fig", "o", "date"]) == "elderberry"
    @test find_max(["apple", "orange", "abanabna", "HhRQ35", "ana", "banana", "riwi", "pear", "ana"]) == "HhRQ35"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "", "m", "n", "o", "p", "q", "r", "aaappleddzz", "s", "t", "u", "v", "w", "x", "y", "ana", "cabcdefg"]) == "cabcdefg"
    @test find_max(["apple", "orange", "abanabna", "HhRQ35", "ana", "banana", "pear", "ana"]) == "HhRQ35"
    @test find_max(["abcdefg", "cat", "qrstuv", "wxyz", "abcdefg"]) == "abcdefg"
    @test find_max(["xy", "yx", "actyx", "zyx"]) == "actyx"
    @test find_max(["wxyz", "iHaTethis", "eAgLe"]) == "iHaTethis"
    @test find_max(["xy", "yx", "zyx"]) == "zyx"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "", "m", "n", "o", "p", "q", "r", "aaappleddzz", "s", "t", "u", "v", "w", "x", "y", "ana", "cabcdeapefg"]) == "cabcdeapefg"
    @test find_max(["b", "cabcdefg", "cbad", "e", "f", "g", "h", "titd", "i", "j", "k", "lsupersonic", "m", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "lsupersonic"
    @test find_max(["Eagle", "j", "eAgLe", "iHaTethis", "Eagle"]) == "iHaTethis"
    @test find_max(["xy", "xiHaTethisyx", "wyx"]) == "xiHaTethisyx"
    @test find_max(["Eagle", "iHaTethiss", "eAgLe"]) == "iHaTethiss"
    @test find_max(["xyx", "xy", "xyx", "wyx", "xyx"]) == "wyx"
    @test find_max(["Eagle", "iHaTethi", "eAgLe"]) == "iHaTethi"
    @test find_max(["wwyx", "tac", "wyx", "zyx", "yx"]) == "tac"
    @test find_max(["wwyx", "xy", "yx", "wyx", "yx"]) == "wwyx"
    @test find_max(["Eagle", "iHaTethis"]) == "iHaTethis"
    @test find_max(["apple", "orange", "abanabna", "HhRQ35", "ana", "banana", "date", "pear", "ana"]) == "HhRQ35"
    @test find_max(["abcdefg", "abckiwidefg", "hijklmnop", "qrstuv", "abcxkydefg", "wxyz", "abcdefg", "abcdefg"]) == "abckiwidefg"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "cabcdefg", "pear", "ape", "xylophone"]) == "supersonic"
    @test find_max(["tac", "wyx", "zyx", "yx"]) == "tac"
    @test find_max(["xyx", "wyx"]) == "wyx"
    @test find_max(["apple", "orange", "abanabna", "grape", "ana", "banana", "kiwi", "pear"]) == "orange"
    @test find_max(["apple", "banana", "", "cherry", "elderberry", "fig", "o", "date"]) == "elderberry"
    @test find_max(["b", "cabcdHXs9s1Qg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "cabcdefg", "i"]) == "cabcdHXs9s1Qg"
    @test find_max(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "qcabcdHXs9s1Qg", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "qcabcdHXs9s1Qg"
    @test find_max(["xy", "xyx", "zyx", "xy", "xy"]) == "zyx"
    @test find_max(["ta", "wyx", "yzyx", "yxiHaTethisyxx"]) == "yxiHaTethisyxx"
    @test find_max(["xy", "grape", "xyxx"]) == "grape"
    @test find_max(["apple", "banana", "cherry", "date", "datze", "elderberry", "fig", "grape"]) == "elderberry"
    @test find_max(["xy", "xyx", "wyx", "zyx", "xy"]) == "wyx"
    @test find_max(["abcdefg", "yx", "hijklmnop", "qrstuv", "abcgdefg", "wxyz"]) == "hijklmnop"
    @test find_max(["apple", "orange", "abanabna", "grape", "ana", "banana", "bb", "pear"]) == "orange"
    @test find_max(["eAgLe", "iHaTethis", "eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["titd", "yx", "wyx", "zyx", "yx"]) == "titd"
    @test find_max(["abckiwidefg", "hijklmnop", "qrstuv", "wxyz"]) == "abckiwidefg"
    @test find_max(["Eagle", "iHaTethi", "eAgLee"]) == "iHaTethi"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["d", "wxy75XPBFq19", "iHaTethis", "eAgLe"]) == "wxy75XPBFq19"
    @test find_max(["apple", "orange", "abanabna", "grape", "aana", "banana", "kiwi", "pear"]) == "orange"
    @test find_max(["cat", "act"]) == "act"
    @test find_max(["Eadategle", "iHaTethis", "iHaTethis"]) == "iHaTethis"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "abcgdefg", "wxyz"]) == "hijklmnop"
    @test find_max(["apple", "orange", "abanabna", "abcgdefg", "ana", "banana", "pear"]) == "abcgdefg"
    @test find_max(["xy", "supersonic", "xyx"]) == "supersonic"
    @test find_max(["yx", "yxhwmnop", "xy", "yx", "wyx", "yx"]) == "yxhwmnop"
    @test find_max(["Eadategle", "xy", "supersonic", "xyx"]) == "supersonic"
    @test find_max(["abcdefg", "hijklmnop", "qrsturv", "quv", "wxyz"]) == "hijklmnop"
    @test find_max(["Eadategle", "iHaTethis"]) == "iHaTethis"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "pear", "apeAgLee", "xylophone"]) == "supersonic"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "abcgdefg", "wxxyz"]) == "hijklmnop"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "cabcdefg", "pear", "ape", "xylophone", "ape"]) == "supersonic"
    @test find_max(["ha", "b", "c", "d", "e", "f", "g", "h", "haaappleddzz", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "u", "z"]) == "haaappleddzz"
    @test find_max(["Eadategle", "wxxyz", "iHaTethis", "iHaTethis", "iHaTethis"]) == "iHaTethis"
    @test find_max(["mhwmnop", "hijklmnop", "qrsturv", "quv", "wxyz", "b"]) == "hijklmnop"
    @test find_max(["cat"]) == "cat"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "wxyz", "ha"]) == "hijklmnop"
    @test find_max(["wwyx", "wy75XPBFq19", "txy", "wyx", "zyx", "yx"]) == "wy75XPBFq19"
    @test find_max(["apple", "orange", "abanabna", "HhRQ35", "ana", "banana", "riwi", "pear", "ana", "orange"]) == "HhRQ35"
    @test find_max(["eAgLe", "iHaTethis", "pear", "eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "gefghip", "h", "i", "j", "k", "l", "m", "n", "o", "p", "xx", "q", "r", "aaappleddzz", "s", "u", "v", "w", "x", "y", "z", "cabcdefg"]) == "cabcdefg"
    @test find_max(["mhwmnop", "hijklmnop", "qrsturv", "quv", "wxyz", "b", "wxyz"]) == "hijklmnop"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "actyxv", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["Eadategle", "iHaTethiselderberry", "iHaTethis"]) == "iHaTethiselderberry"
    @test find_max(["xnyx", "hxfigy", "zyx", "xyx", "zyx"]) == "hxfigy"
    @test find_max(["xnyx", "hxfigy", "xyx", "zyx", "xnyx", "xnyx"]) == "hxfigy"
    @test find_max(["o", "xyx"]) == "xyx"
    @test find_max(["orange", "grape", "banana", "", "pear", "pear", "pear"]) == "orange"
    @test find_max(["", "apple", "orange", "abanana", "grape", "ana", "banana", "kiwi", "pear"]) == "orange"
    @test find_max(["hijklmnop", "qrsturv", "wxyz", "b"]) == "hijklmnop"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "wu", "v", "w", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["Eagle", "eAgLe", "tit", "eAgLe"]) == "Eagle"
    @test find_max(["b", "cabcdefg", "cbad", "e", "f", "g", "h", "titd", "i", "j", "k", "lsupersonic", "m", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "x"]) == "lsupersonic"
    @test find_max(["yx", "yxhwmnop", "xy", "yx", "wyx", "yx", "yx"]) == "yxhwmnop"
    @test find_max(["wwyx", "s", "wy75XPBFq19", "txy", "wyx", "zyx", "yx"]) == "wy75XPBFq19"
    @test find_max(["arbcdefg", "qrstuv", "wxyz", "wxyz", "arbcdefg"]) == "arbcdefg"
    @test find_max(["cba"]) == "cba"
    @test find_max(["kiwi", "tac", "act", "r", "tac"]) == "act"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "x", "y", "z", "b"]) == "cabcdefg"
    @test find_max(["xy", "wyx", "zyx", "xyx", "xyx", "zyx"]) == "wyx"
    @test find_max(["Eadategle", "xy", "abcxkydefg", "xyx"]) == "abcxkydefg"
    @test find_max(["a", "b", "c", "d", "e", "f", "gg", "h", "i", "j", "k", "l", "m", "n", "o", "p", "qcabcdHXs9s1Qg", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "qcabcdHXs9s1Qg"
    @test find_max(["o", "eAgLe", "iHaTethis", "o"]) == "iHaTethis"
    @test find_max(["apple", "Eadategle", "iHaTethis", "iHaTethis"]) == "iHaTethis"
    @test find_max(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "z"]) == "a"
    @test find_max(["Eagle", "iHaTethi", "eAgLcbadee", "geAgLee", "eAgLee", "eAgLee"]) == "eAgLcbadee"
    @test find_max(["r", "tac", "act", "tac"]) == "act"
    @test find_max(["eAgLe", "xy", "sutpersonic", "xyx"]) == "sutpersonic"
    @test find_max(["b", "cabcdefg", "cbad", "e", "f", "g", "h", "titd", "i", "j", "k", "lsupersonic", "m", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "x", "z"]) == "lsupersonic"
    @test find_max(["b", "cabcdefg", "d", "f", "g", "h", "i", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "wu", "v", "w", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["abcdefg", "qrstuv", "wxyz"]) == "abcdefg"
    @test find_max(["hiijklmnop", "supersonic", "apple", "orange", "grape", "kiwi", "pear", "xylophone"]) == "hiijklmnop"
    @test find_max(["Eagle", "Egle", "iHaTeth", "eAgLe", "eAgLe"]) == "iHaTeth"
    @test find_max(["apple", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "supersonic"]) == "supersonic"
    @test find_max(["abcdefg", "cat", "qrstuv", "abcdef", "wxyz", "abcdefg"]) == "abcdefg"
    @test find_max(["b", "cabcdefg", "cbad", "e", "f", "g", "h", "titd", "i", "j", "k", "lsupersonic", "m", "n", "p", "q", "r", "s", "t", "u", "", "v", "w", "x", "y", "z", "x", "z"]) == "lsupersonic"
    @test find_max(["xky", "xyx", "xky"]) == "xky"
    @test find_max(["lmcnop", "abcdefg", "lmnop", "qrstuv", "wxyz"]) == "abcdefg"
    @test find_max(["hxy", "xyx", "xyx"]) == "hxy"
    @test find_max(["b", "cabcdefg", "cbad", "e", "f", "g", "h", "titd", "zyxkz", "i", "j", "k", "lsupersonic", "m", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "k", "k"]) == "lsupersonic"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "", "m", "n", "o", "p", "q", "r", "aaappleddzz", "s", "t", "u", "ee", "v", "w", "x", "y", "ana", "cabcdeapefg"]) == "cabcdeapefg"
    @test find_max(["a", "b", "c", "abcxkydefg", "e", "f", "g", "h", "i", "j", "k", "l", "m", "o", "p", "q", "r", "s", "t", "tit", "v", "w", "x", "z"]) == "abcxkydefg"
    @test find_max(["Eadategle", "xy", "xy", "supersonic", "xyx"]) == "supersonic"
    @test find_max(["apple", "orange", "grape", "bbanana", "kiwi", "pear"]) == "orange"
    @test find_max(["supersonic", "appe", "orange", "banana", "kiwi", "pear", "ape", "xylophone", "banana"]) == "supersonic"
    @test find_max(["eAgLe", "iHaTethis", "eAgLe", "iqHaTethis"]) == "iqHaTethis"
    @test find_max(["Eaglexyx", "iHaTethiss", "eAgLe"]) == "iHaTethiss"
    @test find_max(["apple", "orange", "abanana", "grape", "banana", "riwi", "pear", "ana", "riwi"]) == "orange"
    @test find_max(["xyx", "xy", "xyx", "wyx", "xyx", "wyx"]) == "wyx"
    @test find_max(["o", "eAgLe", "iHaTethis", "y", "o"]) == "iHaTethis"
    @test find_max(["abcdefg", "grape", "hwmnop", "qcabcdHXs9s1Qg", "qrstuv"]) == "qcabcdHXs9s1Qg"
    @test find_max(["osupersonic", "o", "yzyxo", "eAgLe", "iHaTethis", "y", "o"]) == "osupersonic"
    @test find_max(["a", "b", "c", "titd", "d", "e", "f", "g", "h", "haaappleddzz", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "u", "z"]) == "haaappleddzz"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "pear", "ape", "xylophone", "grape"]) == "supersonic"
    @test find_max(["xy", "xyx", "x", "wyx", "zyx", "xyx", "zyx"]) == "wyx"
    @test find_max(["Eagle", "eAgLe", "Eagle"]) == "Eagle"
    @test find_max(["xky", "xcbaky", "xyx", "wyx", "xky", "xky"]) == "xcbaky"
    @test find_max(["Eadategle", "actyxv", "xy", "abcxkydefg", "xyx"]) == "abcxkydefg"
    @test find_max(["abcdefg", "qrstuv", "wxyz", "abcdefg"]) == "abcdefg"
    @test find_max(["supersonic", "appe", "orange", "banana", "iHaTeth", "kiwi", "pear", "ape", "xylophone", "kiwi"]) == "supersonic"
    @test find_max(["supersonic", "apple", "orange", "xyx", "grape", "banana", "kiwi", "rpear", "xylophone", "datze", "supersonic"]) == "supersonic"
    @test find_max(["b", "cbad", "e", "f", "g", "h", "titd", "i", "j", "k", "lsupersonic", "m", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "lsupersonic"
    @test find_max(["supersonic", "appe", "orange", "banana", "xylophoneiHaTethi", "iHaTeth", "kiwi", "pear", "ape", "xylophone", "kiwi"]) == "xylophoneiHaTethi"
    @test find_max(["xky", "wy75XPBFq19", "xky"]) == "wy75XPBFq19"
    @test find_max(["supersonic", "appe", "orange", "banana", "iHaTeth", "kiwi", "pear", "ape", "xylophone", "supersoniec", "kiwi"]) == "supersonic"
    @test find_max(["a", "b", "c", "d", "e", "actyxf", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "qcabcdHXs9s1Qg", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "qcabcdHXs9s1Qg"
    @test find_max(["apple", "orange", "ee", "banana", "kiwi", "pear", "xylophone", "supersonic"]) == "supersonic"
    @test find_max(["xy", "yx", "e"]) == "xy"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "wxyz", "wxyz", "wxyz"]) == "hijklmnop"
    @test find_max(["abcdefg", "wxyz", "abckiwidefg", "hijklmnop", "qrstuactyxfv", "wxyz", "abcdefg"]) == "qrstuactyxfv"
    @test find_max(["apple", "orange", "abanabna", "abcgdefg", "ana", "banana", "pear", "abcgdefg"]) == "abcgdefg"
    @test find_max(["supersonic"]) == "supersonic"
    @test find_max(["a", "b", "c", "d", "e", "actyxf", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "qcabcdHXs9s1Qg", "r", "s", "t", "u", "w", "x", "y", "z"]) == "qcabcdHXs9s1Qg"
    @test find_max(["xky", "xcbaky", "xyx", "xky", "xky"]) == "xcbaky"
    @test find_max(["orange", "grape", "banana", "date", "pear"]) == "orange"
    @test find_max(["yx", "wyx", "zyx", "yx"]) == "wyx"
    @test find_max(["o", "iHaTaethis", "eAgLe", "o", "o"]) == "iHaTaethis"
    @test find_max(["grape", "xyxx"]) == "grape"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "gg", "h", "i", "j", "zyxk", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "cabcdefg", "w"]) == "cabcdefg"
    @test find_max(["apple", "orange", "abanana", "grape", "banana", "it", "riwi", "pear", "ana", "riwi"]) == "orange"
    @test find_max(["appe", "orange", "banana", "kiwi", "pear", "ape", "xylophone", "banana", "appe"]) == "xylophone"
    @test find_max(["osupersonic", "o", "quv", "eAgLe", "iHaTethis", "y", "o"]) == "osupersonic"
    @test find_max(["Eaglce", "eAgLe", "abanana", "Eagle", "eAgLe"]) == "Eaglce"
    @test find_max(["abcdefg", "date", "qrstuv", "abcgdefg", "wxxyz", "date"]) == "abcdefg"
    @test find_max(["supersonic", "appe", "orange", "banana", "xiHaTethisyx", "kiwi", "pear", "ape", "xylophone", "banana", "kiwi", "kiwi"]) == "xiHaTethisyx"
    @test find_max(["eAgLLe", "iHaTethis", "eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["apple", "orange", "abanabna", "grape", "ana", "banana", "bb", "pear", "bb", "banana"]) == "orange"
    @test find_max(["xnyx", "hxfigy", "zyx", "xyx", "xyx", "zyx"]) == "hxfigy"
    @test find_max(["yx", "yxhwmnop", "xy", "yx", "wyfwyxx", "yx"]) == "yxhwmnop"
    @test find_max(["abcdefg", "wxyz", "wxyyz", "abckiwigdefg", "hijklmnop", "qrstuactyxfv", "wxz", "abcdefg"]) == "qrstuactyxfv"
    @test find_max(["iHaTethiss", "eAgLe"]) == "iHaTethiss"
    @test find_max(["b", "cabcdefg", "d", "f", "g", "h", "i", "ana", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "wu", "v", "w", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["babckiwidefg", "abckiwidefg", "qrstuv", "wxyz"]) == "abckiwidefg"
    @test find_max(["abcdefg", "grape"]) == "abcdefg"
    @test find_max(["a", "b", "c", "d", "e", "actyxf", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "qcabcdHXs9s1Qg", "r", "s", "t", "u", "v", "w", "x", "y", "z", "i"]) == "qcabcdHXs9s1Qg"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "rr", "k", "l", "m", "actyxv", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "v"]) == "cabcdefg"
    @test find_max(["xky", "cbadana", "xyx", "xky", "ana", "xky"]) == "cbadana"
    @test find_max(["apple", "orange", "abanabna", "HhRQ35", "h", "banana", "riwi", "pear", "ana"]) == "HhRQ35"
    @test find_max(["Eaglexyx", "hwmnop", "iHaTethiss", "eAgLe"]) == "iHaTethiss"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "cabcdefg", "peiHaTethissar", "ape"]) == "peiHaTethissar"
    @test find_max(["o", "eAgLe", "iHaTethis", "eAgLe"]) == "iHaTethis"
    @test find_max(["mhwmnop", "hijklmnop", "quv", "wxyz", "b"]) == "hijklmnop"
    @test find_max(["apple", "orange", "abanabna", "abcgdefg", "ana", "Eagle", "banana", "pear", "abcgdefg", "Eagle"]) == "abcgdefg"
    @test find_max(["apple", "orange", "grape", "banana", "kiwi", "pear", "supersonic"]) == "supersonic"
    @test find_max(["hxy", "xyx", "xyx", "xyx"]) == "hxy"
    @test find_max(["Eadategle", "iHaTethis", "Eaadategle", "iHaTethis"]) == "iHaTethis"
    @test find_max(["wxyz", "wxyyz", "abckiwigdefg", "hijklmnop", "qrstuactyxfv", "wxz", "abcdefg"]) == "qrstuactyxfv"
    @test find_max(["eAgLe", "TiHaTethis"]) == "TiHaTethis"
    @test find_max(["wy75XPBFq19", "abckiwidefg", "qrstuv", "abcgdefg", "qrstuuv", "wxyz"]) == "wy75XPBFq19"
    @test find_max(["a", "b", "c", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "z", "b"]) == "a"
    @test find_max(["abcdefg", "grape", "abcdefg", "abcdefg"]) == "abcdefg"
    @test find_max(["Eadategle", "iHaiTethis", "iHaTethiselderberry", "iHaTethis"]) == "iHaTethiselderberry"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "abcgdefg", "wxyz", "wxyz"]) == "hijklmnop"
    @test find_max(["eAgLe", "xy", "sutpersonicyxgrape", "xyx", "xyx"]) == "sutpersonicyxgrape"
    @test find_max(["supersonic", "ale", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "xylophone"]) == "supersonic"
    @test find_max(["Eagle", "iHaTethi", "eAgLcbadee", "geAgLee", "eAgLee"]) == "eAgLcbadee"
    @test find_max(["yx", "wyx", "zyx", "yzyx", "yx"]) == "wyx"
    @test find_max(["abcdefg", "abckiwidefg", "hijklmnop", "qrstuv", "abcxkydefg", "wxyz", "abcdefg", "qrstuv"]) == "abckiwidefg"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "x", "y", "z", "o"]) == "cabcdefg"
    @test find_max(["iHaTethiss", "eAgLe", "eAgLe"]) == "iHaTethiss"
    @test find_max(["apple", "zyx", "z", "orange", "grape", "banana", "kiwi", "pear"]) == "orange"
    @test find_max(["b", "cabcdHXs9s1Qg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "efghip", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "cabcdefg", "i"]) == "cabcdHXs9s1Qg"
    @test find_max(["apple", "orange", "abanana", "grape", "banana", "pear", "ana", "riwi"]) == "orange"
    @test find_max(["yx", "wyx", "zyx", "yzyx"]) == "wyx"
    @test find_max(["dabcxkydefg", "Eadategle", "actyxv", "abcxkydefg", "xyx", "dabcxkydefg"]) == "abcxkydefg"
    @test find_max(["Eacabcdefggle", "Eagle", "eAgLe", "tit", "eAgLe"]) == "Eacabcdefggle"
    @test find_max(["Eagle", "grape", "banana", "", "pear", "pear", "pear"]) == "Eagle"
    @test find_max(["supersonic", "appe", "orange", "banana", "ale", "iHaTeth", "kiwi", "pear", "apee", "xylophone", "supersoniec", "kiwi"]) == "supersonic"
    @test find_max(["supersonic", "apple", "grape", "banana", "cabcdefg", "pear", "ape", "xylophone", "ape"]) == "supersonic"
    @test find_max(["xy", "xyx", "wyx", "zyx", "xyx", "xy"]) == "wyx"
    @test find_max(["arbcdefg", "qrstuv", "iHaiTethis", "wxyz", "wyfwyxx", "arbcdefg"]) == "arbcdefg"
    @test find_max(["datze", "xky", "xcbaky", "xyx", "xky", "xky"]) == "xcbaky"
    @test find_max(["Eaglce", "eAgLe", "Eagle"]) == "Eaglce"
    @test find_max(["xnyx", "hxfigy", "xyx", "zyx", "zyx", "xnyx"]) == "hxfigy"
    @test find_max(["abcdefg", "qqrstuv", "wxyz"]) == "abcdefg"
    @test find_max(["Eaagle", "iHaTethi", "eAgLcbadee", "geAgLee", "eAgLee"]) == "eAgLcbadee"
    @test find_max(["b", "yx", "cabcdefg", "d", "e", "f", "gefghip", "h", "i", "j", "k", "l", "m", "n", "o", "p", "xx", "q", "r", "aaappleddzz", "s", "u", "v", "w", "x", "y", "z", "cabcdefg"]) == "cabcdefg"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "gg", "h", "i", "j", "zyxk", "l", "m", "n", "ziHaTethis", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "cabcdefg"]) == "ziHaTethis"
    @test find_max(["hijklmnactyxvp", "abcdefg", "hijklmnop", "qrstuv", "wxyz"]) == "hijklmnactyxvp"
    @test find_max(["Eadategle", "x", "actyxv", "xy", "abcxkydefg", "xyx"]) == "abcxkydefg"
    @test find_max(["Eaagle", "ixteAgLee", "iHaTethi", "eAgLcbadee", "geAgLee", "eAgLee", "eAgLee", "eAgLee"]) == "eAgLcbadee"
    @test find_max(["apple", "orange", "abanabna", "HhRQ35", "ana", "peaac", "banana", "riwi", "pear", "ana", "orange"]) == "HhRQ35"
    @test find_max(["hxEacabcdefggley", "xyx", "zyx", "xyx"]) == "hxEacabcdefggley"
    @test find_max(["apple", "Eadategle", "iHaTethis", "iHaTethis", "apple"]) == "iHaTethis"
    @test find_max(["supersonic", "apple", "orange", "xyx", "grape", "banana", "kiwi", "rpear", "supersconic", "xylophone", "datze", "supersonic"]) == "supersconic"
    @test find_max(["supersonic", "apple", "orange", "banana", "pear", "ape", "xylophone"]) == "supersonic"
    @test find_max(["abckiwidefg", "hijklmnop", "qrstuv"]) == "abckiwidefg"
    @test find_max(["mhwmnop", "hijklmnop", "qrsturv", "quv", "wxyz", "bhijklmnop", "wxyz", "wxyz"]) == "bhijklmnop"
    @test find_max(["applEaglexyxe", "banana", "cherry", "ee", "datze", "elderberry", "fig", "grape"]) == "applEaglexyxe"
    @test find_max(["supersonic", "abanabna", "orange", "grape", "banana", "kiwi", "pear", "apeAgLee", "xylophone"]) == "supersonic"
    @test find_max(["Eagle", "eAgLe"]) == "Eagle"
    @test find_max(["wwyx", "x", "wyx", "yxwy75XPBFq19", "zyx", "yx", "x"]) == "yxwy75XPBFq19"
    @test find_max(["abcdefg", "grape", "hwmnop", "qrstuv", "abcdefg"]) == "abcdefg"
    @test find_max(["abcdefg", "abcdefgcba", "abckiwidefg", "hijklmnop", "qrstuv", "wxyz"]) == "abckiwidefg"
    @test find_max(["Eagle", "peiHaTethissariHaTethi", "eAgLcbadee", "geAgLee", "eAgLee", "eAgLee"]) == "peiHaTethissariHaTethi"
    @test find_max(["e", "yx", "xy", "sutpersonic", "wyx", "zyx"]) == "sutpersonic"
    @test find_max(["r", "tac", "act", "tac", "tac"]) == "act"
    @test find_max(["Eaagle", "iHaTethi", "eAgLcbadee", "geAgLee", "eAgLee", "eAgLee", "eAgLee"]) == "eAgLcbadee"
    @test find_max(["eAgLLe", "iHaTethis", "eAgLe"]) == "iHaTethis"
    @test find_max(["superbanana", "ale", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "xylophone"]) == "superbanana"
    @test find_max(["f", "xyx", "zx", "xyx"]) == "xyx"
    @test find_max(["supersonic", "apple", "grape", "banana", "cabcdefg", "pear", "ape", "xylophone"]) == "supersonic"
    @test find_max(["abckiwidefg", "hijklmno", "qrstuv", "wxyz"]) == "abckiwidefg"
    @test find_max(["wwyx", "s", "wy75XPBFq19", "txy", "yabcdef", "wyx", "zyx", "yx"]) == "wy75XPBFq19"
    @test find_max(["wwyx", "xy", "yxx", "wyx", "yx"]) == "wwyx"
    @test find_max(["apple", "orange", "abanabna", "HhRQ35", "ana", "banana", "pear", "ana", "ana", "orange"]) == "HhRQ35"
    @test find_max(["eAgLcbadee", "Eagle", "eAgLe"]) == "eAgLcbadee"
    @test find_max(["abcdefg", "grape", "iHaTeth", "abcdefg", "abcdefg"]) == "abcdefg"
    @test find_max(["yx", "wyx", "zyx", "yx", "wyx"]) == "wyx"
    @test find_max(["Eagle", "peiHaTethissariHaTethi", "eAgLcbadee", "geAggrapeLee", "eAgLee", "eAgLee"]) == "peiHaTethissariHaTethi"
    @test find_max(["wwyx", "yx", "wyx", "zyx", "yx", "yxx", "wyx", "yx"]) == "wwyx"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "x", "y", "z", "b"]) == "cabcdefg"
    @test find_max(["abcdefg", "cat", "qrstuv", "wxyz", "cat"]) == "abcdefg"
    @test find_max(["supersonic", "ale", "orange", "h", "banana", "kiwi", "pear", "xylophone", "xylophone"]) == "supersonic"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "gg", "h", "i", "zyxk", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "cabcdefg"]) == "cabcdefg"
    @test find_max(["yx", "wyx", "zyx", "yx", "wyx", "yx"]) == "wyx"
    @test find_max(["Eagle", "Eagl", "eAgLe"]) == "Eagle"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "abcgdefg", "wxyz", "wxyz", "abcgdefg"]) == "hijklmnop"
    @test find_max(["q", "iHaTethiselderberry", "iHaTethis"]) == "iHaTethiselderberry"
    @test find_max(["dabcxkydefg", "Eadagle", "actyxv", "xyx", "dabcxkydefg"]) == "dabcxkydefg"
    @test find_max(["cabcdefg", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "cabcdefg"
    @test find_max(["hxEacabcdefggleyzx", "f", "zx", "xyx"]) == "hxEacabcdefggleyzx"
    @test find_max(["ixteAgLee", "fig", "hxfigy", "xyx", "zyx", "zyx"]) == "ixteAgLee"
    @test find_max(["iHasTethiss", "eAgLeqrstuuv", "eAgLe"]) == "eAgLeqrstuuv"
    @test find_max(["apple", "orange", "grape", "a", "ana", "banana", "kiwi", "pear", "ana"]) == "orange"
    @test find_max(["yx", "yxhwmnop", "xy", "yx", "wyx"]) == "yxhwmnop"
    @test find_max(["rr", "tac", "act", "r", "iHaiTethis"]) == "iHaiTethis"
    @test find_max(["apple", "grape", "bbanana", "kiwi", "pear", "bbanana"]) == "grape"
    @test find_max(["d", "wxy75XPBFq19", "iHaTethis", "iHaTethiis", "eAgLe"]) == "wxy75XPBFq19"
    @test find_max(["xky", "wy75XPBFq19", "xEaglexyx", "wy75XPBFq19"]) == "wy75XPBFq19"
    @test find_max(["wyx", "zyx", "zyx"]) == "wyx"
    @test find_max(["supersonic", "appe", "orange", "banana", "xylophoneiHaTethi", "iHaTeth", "kiwi", "pear", "ape", "xylophone", "p", "kiwi"]) == "xylophoneiHaTethi"
    @test find_max(["Eeagle", "Eagle", "Eagl", "eAgLe"]) == "Eagle"
    @test find_max(["Eagle", "eAgLe", "titv", "eAgLe"]) == "Eagle"
    @test find_max(["wwyx", "hxy", "wyx", "yxwy75XPBFq19", "zyx", "yx", "x", "x"]) == "yxwy75XPBFq19"
    @test find_max(["eAgLLe", "eAgLe"]) == "eAgLLe"
    @test find_max(["tac", "act"]) == "act"
    @test find_max(["xy", "cabcdefg", "zyx"]) == "cabcdefg"
    @test find_max(["d", "wxy75XPBFq19", "iHaTethis", "iHaTethiis", "eAgLe", "iHaTethis"]) == "wxy75XPBFq19"
    @test find_max(["xnyx", "hxfigy", "xyx", "xyx", "zyx"]) == "hxfigy"
    @test find_max(["titv", "actyxv", "xy", "abcxkydefg", "xyx", "titv"]) == "abcxkydefg"
    @test find_max(["eAgLe", "iHaTethis", "eAgLe", "iqHaTethis", "eAgLe"]) == "iqHaTethis"
    @test find_max(["apple", "orange", "abanana", "grape", "ana", "banana", "riwi", "pear", "ana", "pear"]) == "orange"
    @test find_max(["Eagle", "iHaTethi", "eAgLee", "iHaTethi"]) == "iHaTethi"
    @test find_max(["xyx", "xy", "xyx", "wyx", "xyx", "wyx", "xyx"]) == "wyx"
    @test find_max(["oarbcdefg", "o", "eAgLe", "iHaTethis", "o", "eAgLe", "o"]) == "oarbcdefg"
    @test find_max(["abckiwidefg", "hijklmnop", "qrstuv", "hijklmnop"]) == "abckiwidefg"
    @test find_max(["hijklmnactyxvp", "abcdefg", "hijklEaaglemnop", "qrstuv", "wxyz"]) == "hijklmnactyxvp"
    @test find_max(["appe", "orange", "nana", "kiwi", "pear", "ape", "xylophone", "banana", "appe"]) == "xylophone"
    @test find_max(["aana", "cat"]) == "cat"
    @test find_max(["yx", "xy", "ywyx", "wyx", "zyx"]) == "wyx"
    @test find_max(["applEaglexyxe", "banana", "fig", "cherry", "ee", "datze", "elderberry", "t", "grape"]) == "applEaglexyxe"
    @test find_max(["yx", "wyx", "xzyx", "yzyx", "yzyx"]) == "wyx"
    @test find_max(["wwyx", "xy", "yxx", "wyx", "yx", "wyx"]) == "wwyx"
    @test find_max(["supersonic", "appe", "orange", "banana", "iHaTeth", "kiwi", "pear", "appe", "xylophone", "kiwi"]) == "supersonic"
    @test find_max(["apple", "orange", "abanabna", "abcgdefg", "ana", "wxy75XPBFq19", "banana", "pear"]) == "wxy75XPBFq19"
    @test find_max(["applEaglexyxe", "ac", "banana", "fig", "a", "cherry", "ee", "datze", "elderberry", "t", "grape"]) == "applEaglexyxe"
    @test find_max(["hxy", "xyx", "xyx", "abcgdefg", "xyx"]) == "abcgdefg"
    @test find_max(["", "mEagle", "apple", "orange", "abanana", "grape", "ana", "banana", "kiwi", "pear"]) == "mEagle"
    @test find_max(["abcdefg", "cat", "qrstuv", "abcdef", "wxyz"]) == "abcdefg"
    @test find_max(["apple", "orange", "abanabna", "grape", "ana", "banana", "bb", "iHaTethis"]) == "iHaTethis"
    @test find_max(["xy", "xyx", "x", "Eeagle", "wyx", "zyx", "xyx", "zyx"]) == "Eeagle"
    @test find_max(["eLAgLe", "TiHaTethis"]) == "TiHaTethis"
    @test find_max(["r", "tac", "acefghipt", "tac", "tac"]) == "acefghipt"
    @test find_max(["rsonic", "abanabna", "orange", "grape", "banana", "kiwi", "pear", "apeAgLee", "xylophone"]) == "xylophone"
    @test find_max(["apple", "cherry", "elderberry", "fig", "o", "date"]) == "elderberry"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "i", "j", "k", "l", "n", "o", "p", "q", "r", "s", "t", "u", "v", "x", "y", "z", "b"]) == "cabcdefg"
    @test find_max(["apple", "gdrape", "bbanana", "kiwi", "pear", "hxfigytt", "bbanana"]) == "hxfigytt"
    @test find_max(["hxfigy", "zyx", "xyx", "xyx", "zyx"]) == "hxfigy"
    @test find_max(["abcdefg", "wxyz", "wxyyz", "abckiwigdefg", "hijklmnop", "qrstuactyxfv", "wxz", "abcdefg", "abcdefg"]) == "qrstuactyxfv"
    @test find_max(["abcdefg", "qrstuv", "abcgdefg", "wxyz"]) == "abcdefg"
    @test find_max(["Eadategle", "ta", "supersonic", "xyx"]) == "supersonic"
    @test find_max(["mhwmnop", "hijklmnop", "qrsturv", "quv", "wxyz", "qrsturv"]) == "hijklmnop"
    @test find_max(["titd", "yx", "wyx", "zyx", "yx", "yx"]) == "titd"
    @test find_max(["abcdefg", "cat", "qrstuv", "wxyz", "abcdefg", "cat"]) == "abcdefg"
    @test find_max(["abcdefg", "hxy", "xyx", "xyx", "abcgdefg", "xyx", "abcdefg"]) == "abcdefg"
    @test find_max(["supersonic", "apple", "grapeapplEaglexyxe", "apear", "banana", "cabcdefg", "pear", "ape", "xylophone"]) == "grapeapplEaglexyxe"
    @test find_max(["supersonic", "apple", "grapeapplEaglexyxe", "apear", "banana", "cabcdefg", "per", "ape", "xylophone", "supersonic"]) == "grapeapplEaglexyxe"
    @test find_max(["yx", "wyx", "yzyx"]) == "wyx"
    @test find_max(["b", "cabcdefg", "d", "e", "f", "g", "h", "i", "j", "l", "m", "n", "e", "o", "p", "q", "r", "s", "t", "u", "v", "x", "y", "z", "o"]) == "cabcdefg"
    @test find_max(["abmEaecdefg", "hijklmnop", "abcgdefg", "wxxyz"]) == "abmEaecdefg"
    @test find_max(["wy75XPBFq19", "xEaglexyx", "wy75XPBFq19"]) == "wy75XPBFq19"
    @test find_max(["osupersonic", "o", "yzyxo", "eAgLe", "iHaTethis", "y", "o", "o"]) == "osupersonic"
    @test find_max(["bqrstuvb", "xyx", "wyx", "zyx", "xyx"]) == "bqrstuvb"
    @test find_max(["apple", "orange", "ee", "banana", "kiwi", "pear", "xylophone", "supersonic", "ear"]) == "supersonic"
    @test find_max(["titd", "yx", "wyx", "zyx", "yx", "ititd", "wyefghipx", "zyx"]) == "wyefghipx"
    @test find_max(["xy", "yx", "hxyyxhwmnop", "actyx", "zyx"]) == "hxyyxhwmnop"
    @test find_max(["Eagle", "epeiHaTethissariHaTethi", "eAgLcbadee", "geAggrapeLee", "eAgLee", "eAgLee", "eAgLee"]) == "epeiHaTethissariHaTethi"
    @test find_max(["supersonic", "appe", "orange", "banana", "xiHaTethisyx", "kiwi", "pear", "ape", "xylophone", "haaaappleddzzeaappleddezz", "banana", "kiwi", "kiwi"]) == "xiHaTethisyx"
    @test find_max(["abcdefg", "abEadaglecdefg", "grape"]) == "abEadaglecdefg"
    @test find_max(["apple", "orange", "abanabna", "abcgdefg", "ana", "banana", "pear", "abanabna"]) == "abcgdefg"
    @test find_max(["yxiHaTethisyx", "wyx", "zyx", "yx", "wyx"]) == "yxiHaTethisyx"
    @test find_max(["xnyx", "hxy", "xyx", "zyx", "xpxyx", "xpyx"]) == "hxy"
    @test find_max(["xnyx", "zyxx", "hxy", "xyx", "zyx", "xyx", "xeefghiitnyx", "xyx"]) == "xeefghiitnyx"
    @test find_max(["apple", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "supersonic", "grape"]) == "supersonic"
    @test find_max(["apple", "orange", "abanana", "grape", "it", "riwi", "pear", "ana", "riwi"]) == "orange"
    @test find_max(["xy", "xcbakyxyx", "xyx", "zyx", "xyx"]) == "xcbakyxyx"
    @test find_max(["Eagle", "eAgLe", "iHaTethis", "iHaTethis"]) == "iHaTethis"
    @test find_max(["abcdefg", "wxyz", "wxyyz", "abckiwigdefg", "hijklmnop", "wxz", "abcdefg", "abcdefg", "abcdefg"]) == "abckiwigdefg"
    @test find_max(["apple", "banana", "", "cherry", "elderberry", "fig", "wxxyz", "date"]) == "elderberry"
    @test find_max(["abcdefg", "cat", "qrstuv", "wxyz", "gdrape", "cat"]) == "abcdefg"
    @test find_max(["apple", "orange", "grawxyzpe", "bbanana", "kiwi", "pear"]) == "grawxyzpe"
    @test find_max(["eAgLe", "xy", "sutpersonicyxgrape", "xyx", "xyx", "eAgLe"]) == "sutpersonicyxgrape"
    @test find_max(["bbanaa", "apple", "orange", "grpape", "bbanana", "kiwi", "pear"]) == "orange"
    @test find_max(["abcdefg", "qrstuv", "wxyz", "abcdefg", "qrstuv"]) == "abcdefg"
    @test find_max(["yEaaglex", "wwyx", "xy", "yxx", "wyx", "yx"]) == "yEaaglex"
    @test find_max(["Eadategle", "xy", "supersonic", "xyx", "xyx"]) == "supersonic"
    @test find_max(["Eaglexyx", "iHaTethiss", "eAgLe", "eAgLe"]) == "iHaTethiss"
    @test find_max(["yx", "wyx", "zyx", "yzyx", "yx", "zyx"]) == "wyx"
    @test find_max(["wwyx", "tac", "aana", "zyx", "yx"]) == "tac"
    @test find_max(["xnyx", "hxfigy", "zyx", "xyx", "xyx", "yxyx", "zyx"]) == "hxfigy"
    @test find_max(["tacc", "r", "o", "act", "tac", "tac", "tac"]) == "act"
    @test find_max(["xy", "xyx", "appe", "zyx", "xyx"]) == "appe"
    @test find_max(["yxyzyx", "tialetd", "yx", "wyx", "zyx", "yx", "hxyyxhwmnop", "ititd", "wyefghipx", "zyx"]) == "wyefghipx"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "wxyz", "ha", "abcdefg"]) == "hijklmnop"
    @test find_max(["Eagle", "iHaTethi", "eAgLcbadee", "geAgLee", "eAgLee", "Eagle"]) == "eAgLcbadee"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "wxyz", "xylophone", "wxyz", "wxyz"]) == "hijklmnop"
    @test find_max(["abmEaecdefg", "abcdefg", "hijklmnop", "qrstuv", "wxyz", "wxyz"]) == "abmEaecdefg"
    @test find_max(["lmcnop", "abcdefg", "bbanaa", "wxyz"]) == "abcdefg"
    @test find_max(["cat", "acat"]) == "acat"
    @test find_max(["qvuv", "mhwmnop", "hijklmnop", "qrsturv", "quv", "wxyz", "qrsturv"]) == "hijklmnop"
    @test find_max(["yx", "wxz", "wyx", "zyx", "yzyx", "yx"]) == "wxz"
    @test find_max(["aana", "ccat", "aana", "aana"]) == "ccat"
    @test find_max(["b", "cabcdefg", "d", "cacdefg", "e", "f", "g", "h", "i", "j", "l", "m", "n", "e", "o", "p", "q", "r", "s", "t", "u", "v", "x", "y", "z", "o"]) == "cabcdefg"
    @test find_max(["eAgLe", "iqHaititTethis", "iHaTethis", "eAgLe", "iqHaTethis"]) == "iqHaTethis"
    @test find_max(["ppear", "wwyx", "xy", "yx", "wyx", "zyx"]) == "ppear"
    @test find_max(["xy", "xyx", "x", "Eeagle", "wyx", "zyx", "zyx"]) == "Eeagle"
    @test find_max(["xy", "xxxyxiHaTethisyx", "wyx"]) == "xxxyxiHaTethisyx"
    @test find_max(["titv", "actyxv", "xy", "abcxkydefg", "xyx", "titv", "titv"]) == "abcxkydefg"
    @test find_max(["supersonic", "abanabna", "orange", "kiqHaititTethisiwi", "grape", "banana", "kiwi", "pear", "apeAgLee", "xylophone"]) == "kiqHaititTethisiwi"
    @test find_max(["xky", "cbabana", "xyx", "xky", "ana", "xky"]) == "cbabana"
    @test find_max(["yxiHaTethisyx", "wyx", "yx", "wyx"]) == "yxiHaTethisyx"
    @test find_max(["apple", "orange", "abanabna", "abcgdefg", "ana", "wxy75XPBFq19", "baxyxnana", "pear"]) == "wxy75XPBFq19"
    @test find_max(["wwyx", "xwyx", "wyx"]) == "wwyx"
    @test find_max(["xy", "cabcdefg", "zyx", "zyx"]) == "cabcdefg"
    @test find_max(["apple", "oarange", "abanabna", "ana", "banana", "bb", "pear"]) == "oarange"
    @test find_max(["xyx", "xy", "xyx", "wyx", "xyx", "wyx", "wyx"]) == "wyx"
    @test find_max(["a", "b", "c", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "abcdef", "s", "t", "u", "v", "w", "x", "y", "z", "z", "b"]) == "abcdef"
    @test find_max(["yx", "zyx", "yzyx", "yx"]) == "yzyx"
    @test find_max(["xnyx", "xyx", "xyx", "zyx"]) == "xnyx"
    @test find_max(["xy", "xyx", "wyx", "xyx"]) == "wyx"
    @test find_max(["supersonic", "appe", "orange", "banana", "xiHaTethisyx", "kiwi", "pear", "rr", "ape", "xylophone", "haaaappleddzzeaappleddezz", "banana", "kiwi", "kiwi"]) == "xiHaTethisyx"
    @test find_max(["ppear", "wwyx", "xy", "yx", "eAgLee", "wjyx", "zyx"]) == "eAgLee"
    @test find_max(["hiijklm", "apee", "apple", "orange", "grape", "kiwi", "pear", "xylophone"]) == "xylophone"
    @test find_max(["lmcnpop", "abcdefg", "qrmeAgLLeuv", "lmnop", "qrstuv"]) == "qrmeAgLLeuv"
    @test find_max(["abcdef", "ghijkl", "mnopqr", "stuvwx"]) == "abcdef"
    @test find_max(["aaa", "bbb", "ccc", "ddd"]) == "aaa"
    @test find_max(["a", "b", "c", "d"]) == "a"
    @test find_max(["aaaa", "aaaaaa", "aaaaaaaa", "aaaaaaaaaa"]) == "aaaa"
    @test find_max(["apple", "banana", "cherry", "dates"]) == "cherry"
    @test find_max(["abcdefghijklmnopqrstuvwxyz", "a"]) == "abcdefghijklmnopqrstuvwxyz"
    @test find_max(["word", "word", "word"]) == "word"
    @test find_max(["cat", "dog", "pig"]) == "cat"
    @test find_max(["a", "b", "c"]) == "a"
    @test find_max(["supersonic", "apple", "orange", "grape", "kiwi", "pear", "xylophone", "grape"]) == "supersonic"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone"]) == "supersonic"
    @test find_max(["aaddzz", "f", "ijklmn", "efghip", "cba"]) == "efghip"
    @test find_max(["f", "ijklmn"]) == "ijklmn"
    @test find_max(["apple", "banana", "cherry", "l", "elderberry", "fig", "grape"]) == "elderberry"
    @test find_max([""]) == ""
    @test find_max(["saaddzzupersonic", "apple", "xylopthone", "m", "kiwi", "pear", "xylophone"]) == "saaddzzupersonic"
    @test find_max(["aaddzz", "f", "d", "efghip", "cba"]) == "efghip"
    @test find_max(["ijklmn", "efghwxyzip", "cbca"]) == "efghwxyzip"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone", "grape", "xylophone"]) == "supersonic"
    @test find_max(["iHaTethis", "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "dwate", "iHaTethis"]) == "iHaTethis"
    @test find_max(["HhRQ35", "gBFWztts67", "75X1PBFq19", "75XPBFq19", "HXs9s1Q", "HSSbsh", "HSSbsh"]) == "75X1PBFq19"
    @test find_max(["applle", "banana", "cherry", "l", "elderberry", "fig", "grape"]) == "elderberry"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "pear"]) == "supersonic"
    @test find_max(["dwate", "saaddzzupersonic", "xylopthone", "m", "kiwi", "pear", "xylophone"]) == "saaddzzupersonic"
    @test find_max(["f", "ff", ""]) == "f"
    @test find_max(["aaddzz", "qrstuv", "ijklmn", "cb", "efghip", "cba"]) == "efghip"
    @test find_max(["saaaddzzupersonic", "xylophonee", "apple", "xylopthone", "m", "pear", "xylophone", "saaaddzzupersonic"]) == "saaaddzzupersonic"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "kiwi"]) == "supersonic"
    @test find_max(["abcdefg", "hijklmnop", "qrstuvwxyz", "wxyz", "abcdefg"]) == "qrstuvwxyz"
    @test find_max(["applle", "banana", "cherry", "l", "banaapplena", "elderberry", "fig", "grape"]) == "banaapplena"
    @test find_max(["aaddzz", "qrstuv", "ijklmn", "efghip", "cba", "qrstuv"]) == "efghip"
    @test find_max(["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "a"
    @test find_max(["supersonic", "kiw", "apple", "orange", "grape", "banana", "kiwi", "pear", "xylophone"]) == "supersonic"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "HXs9s1Q", "HSSbzyxsh", "HXs9s1Q"]) == "75XPBFq19"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "HXs9s1Q", "HSSbzyxsh", "HXs9s1Q", "gBFWztts67"]) == "75XPBFq19"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "wcbcaxyz"]) == "hijklmnop"
    @test find_max(["applle", "banana", "cherry", "l", "banaapplena", "yelderberry", "fig", "grape"]) == "banaapplena"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "HXs9s1Q", "HSSbzyxsh", "HXs9s1Q", "gBFWztts67", "HXs9s1Q"]) == "75XPBFq19"
    @test find_max(["applle", "banana", "cherry", "l", "elderberry", "fig", "grape", "cherry"]) == "elderberry"
    @test find_max(["ijklmn"]) == "ijklmn"
    @test find_max(["EEaglcbe", "EE", "EEagle", "eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["applle", "y", "banana", "cherry", "l", "banaapplena", "elderberry", "fig", "grape"]) == "banaapplena"
    @test find_max(["Eagle", "eAgLe", "iHaTethis", "Eagle"]) == "iHaTethis"
    @test find_max(["ff", ""]) == "ff"
    @test find_max(["supersonic", "ae", "orange", "grape", "banana", "kiwi", "pear"]) == "supersonic"
    @test find_max(["Eagle", "eAgLe", "u", "iHaTethis", "Eagle"]) == "iHaTethis"
    @test find_max(["appHSSbzyxshle", "banana", "cherry", "l", "elderberry", "fig", "grape"]) == "appHSSbzyxshle"
    @test find_max(["apple", "xylopthone", "m", "kiwi", "pear", "xylophone"]) == "xylopthone"
    @test find_max(["supersonic", "apple", "xylopthone", "epear", "grape", "m", "kiwi", "pear", "grape"]) == "supersonic"
    @test find_max(["aaddzz", "", "HXs9s1Q", "efghip", "cba", "aaddzz"]) == "HXs9s1Q"
    @test find_max(["cat", "act", "tac", "cat"]) == "act"
    @test find_max(["ijklmn", "efghwxyzip"]) == "efghwxyzip"
    @test find_max(["ijklmn", "efghwxyezip", "efghwxyzip"]) == "efghwxyezip"
    @test find_max(["hijklmnop", "wcbcaxyz", "wcbcaxyz"]) == "hijklmnop"
    @test find_max(["cat", "act", "tac", "cat", "cat"]) == "act"
    @test find_max(["f"]) == "f"
    @test find_max(["v", "hijklmnop", "qrstuv", "wxyz"]) == "hijklmnop"
    @test find_max(["apple", "orange", "grape", "banana", "kiwi", "pear", "banana"]) == "orange"
    @test find_max(["banana", "l", "elderberry", "fig", "grape", "cherry"]) == "elderberry"
    @test find_max(["ijklnmn", "efghwxyzip", "cbca"]) == "efghwxyzip"
    @test find_max(["kiw", "abcdefg", "wcbcawxyz", "hijklmnop", "qrstuv", "wcbcaxyz"]) == "hijklmnop"
    @test find_max(["kiw"]) == "kiw"
    @test find_max(["HXs9s1", "HhRQ35", "gBFWztts67", "75XPBFq19", "HXs9s1Q", "HSSbsh"]) == "75XPBFq19"
    @test find_max(["dwate", "saaddzzupersonic", "xylopthone", "m", "kiwi", "perar", "ae"]) == "saaddzzupersonic"
    @test find_max(["applle", "y", "banana", "cherry", "l", "elderberry", "fig", "grape"]) == "elderberry"
    @test find_max(["supersonic", "apple", "orange", "grape", "kiwi", "pear", "xylophone"]) == "supersonic"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "wxyz", "qrstuv"]) == "hijklmnop"
    @test find_max(["aaddzz", "qrstuv", "ijklmn", "efghip", "qrstuv"]) == "efghip"
    @test find_max(["icbajklmn", "efghwzip"]) == "icbajklmn"
    @test find_max(["b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"]) == "b"
    @test find_max(["EwEaglcbe", "EE", "EEagle", "eAgLe", "iHaTethis"]) == "EwEaglcbe"
    @test find_max(["", "ijklmn", "ikjklmn", "efghwxyzip"]) == "efghwxyzip"
    @test find_max(["EEaglcbe", "EE", "eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["wcbcaxyz", "banana", "cherry", "l", "elderberry", "fig", "fg", "grape"]) == "wcbcaxyz"
    @test find_max(["abcdefg", "hijklmnop", "qrstuvwxyz", "wxyz", "abcdefg", "hijklmnop"]) == "qrstuvwxyz"
    @test find_max(["apple", "banana", "cherry", "date", "elderberry", "fig"]) == "elderberry"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone", "grape", "z", "xylophone", "supersonic"]) == "supersonic"
    @test find_max(["Eagle", "eAgLe", "iHaTethis", "Eagle", "Eagle"]) == "iHaTethis"
    @test find_max(["apple", "banana", "cherry", "date", "elderberry", "chery", "efghwxyezip", "grape", "apple"]) == "efghwxyezip"
    @test find_max(["applle", "y", "banana", "cherry", "l", "banaapplena", "fig", "grape"]) == "banaapplena"
    @test find_max(["xy", "ijklmn", "ikjklmn", "efghwxyzip", "ijklmn"]) == "efghwxyzip"
    @test find_max(["abcdefg", "hijklmnop", "qrstuvwxyz", "wxyz", "abcdefg", "abcdefg"]) == "qrstuvwxyz"
    @test find_max(["supersonic", "apple", "xylopthone", "m", "kiwi", "pear", "xylophone"]) == "supersonic"
    @test find_max(["supersonic", "kiw", "apple", "orange", "grape", "banana", "pear", "xylophone"]) == "supersonic"
    @test find_max(["supersonic", "apple", "grape", "banana", "kiwi", "pear"]) == "supersonic"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "tac", "HXs9s1Q", "HXs9s1Q", "gBFWztts67", "HXs9s1Q"]) == "75XPBFq19"
    @test find_max(["c", ""]) == "c"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "xylophoone", "pear", "xylophone", "grape", "z", "xylophone", "supersonic"]) == "supersonic"
    @test find_max(["abcdgefg", "x", "hijklmnop", "qrstuv", "wxyz"]) == "hijklmnop"
    @test find_max(["apple", "banana", "cherry", "l", "elderberry", "fig", "grape", "cherry"]) == "elderberry"
    @test find_max(["xy", "yx", "wyx", "zyx", "yx"]) == "wyx"
    @test find_max(["dwate", "saaddzzupersonic", "m", "kiwi", "t", "xylophone"]) == "saaddzzupersonic"
    @test find_max(["aaddzz", "qrstuv", "ijklmn", "cb", "efgphip", "cba"]) == "efgphip"
    @test find_max(["banana", "elderberry", "fig", "grape", "chehrry"]) == "elderberry"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "dwate", "pear", "xylophone", "kiwi"]) == "supersonic"
    @test find_max(["saaddzzupersonic", "apple", "xylopthone", "m", "kiwi", "pear"]) == "saaddzzupersonic"
    @test find_max(["ijklmn", "ijklmn"]) == "ijklmn"
    @test find_max(["qrstuv", "ijklmn", "efghip", "qrstuv", "ijklmn"]) == "efghip"
    @test find_max(["qrstuv", "ijklmn", "efghip", "qrstuv", "ijklmn", "ijklmn"]) == "efghip"
    @test find_max(["applle", "y", "banana", "cherry", "l", "banaapplena", "elderberry", "fig", "grape", "cherry", "banana"]) == "banaapplena"
    @test find_max(["hijklmnop", "qrstuv", "wxyzs", "wxyz"]) == "hijklmnop"
    @test find_max(["banana", "l", "elderberry", "fig", "grape", "cherry", "cherry", "banana"]) == "elderberry"
    @test find_max(["abcdefg", "hijklmnop", "abcdefg", "wxyz", "qrstuv"]) == "hijklmnop"
    @test find_max(["EEaglcbe", "EE", "eAgLe", "EEaglcbe"]) == "EEaglcbe"
    @test find_max(["aaddzz", "ijklmn", "qrstuv"]) == "ijklmn"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "kiwi", "supersonic"]) == "supersonic"
    @test find_max(["datev", "v", "hijklmnop", "qrstuv", "wxyz"]) == "hijklmnop"
    @test find_max(["apple", "orange", "grape", "banana", "kiwi", "pear", "banana", "banana"]) == "orange"
    @test find_max(["jijklmn", "ijklmn"]) == "ijklmn"
    @test find_max(["ijklnmn", "efghwxyzip", "cbbcca", "cbcca"]) == "efghwxyzip"
    @test find_max(["EEaglcbe", "EE", "EEagle", "eAgLe"]) == "EEaglcbe"
    @test find_max(["Eagle", "eAgL", "iHaaTethis"]) == "iHaaTethis"
    @test find_max(["cc", "c", ""]) == "c"
    @test find_max(["qrsutuv", "aaddzz", "qrstuv", "ijklmn", "efghip", "cba", "qrstuv"]) == "efghip"
    @test find_max(["applle", "y", "banana", "cherry", "l", "elderberry", "fig", "grape", "elderberry"]) == "elderberry"
    @test find_max(["HhRQ35", "75XPBFq19", "HXs9s1Q", "HSSbzyxsh", "HXs9s1Q", "gBFWztts67", "HhRQ35"]) == "75XPBFq19"
    @test find_max(["supersonic", "apple", "gerape", "xylopthone", "epear", "grape", "m", "kiwi", "pear", "grape"]) == "supersonic"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone", "pear"]) == "supersonic"
    @test find_max(["HhRQ35", "gBFWztts67", "75X1PBFq19", "75XPBFq19", "HXs9s1Q", "gBFWzFtts67", "HSSbsh", "HSSbsh"]) == "75X1PBFq19"
    @test find_max(["xy", "yx", "zyx", "xy"]) == "zyx"
    @test find_max(["abcdefg", "hijklmnop", "qrtuv"]) == "hijklmnop"
    @test find_max(["aaddzz", "", "HXs9s1Q", "efghip", "f", "cba", "aaddzz"]) == "HXs9s1Q"
    @test find_max(["jijlklmn"]) == "jijlklmn"
    @test find_max(["abcdefg", "hijklmnop", "wcbz", "qrstuv", "wcbcaxyz"]) == "hijklmnop"
    @test find_max(["hijklmnop", "a", "wcbcaxyz", "wcbcaxyz", "wcbcaxyz", "hijklmnop"]) == "hijklmnop"
    @test find_max(["supersonic", "orange", "grape", "banana", "kiwi", "apear"]) == "supersonic"
    @test find_max(["supersonic", "apple", "gerape", "xylopthone", "epear", "grape", "dwate", "m", "kiwi", "pear", "grape"]) == "supersonic"
    @test find_max(["abcdefg", "hijklmnop", "hijklkmnop", "wxyzz", "qrstuvwxyz", "wxyz", "abcdefg"]) == "qrstuvwxyz"
    @test find_max(["applle", "y", "banana", "cherry", "l", "banaapplena", "fig", "rgrape"]) == "banaapplena"
    @test find_max(["supersonic", "kiw", "apple", "orange", "grape", "banana", "peqrstuvar", "xylophone"]) == "peqrstuvar"
    @test find_max(["ijklmmn", "efghwxyezip", "efghwxyzip"]) == "efghwxyezip"
    @test find_max(["supersonic", "kiw", "apple", "orange", "banana", "kiwi", "pear", "xylophone"]) == "supersonic"
    @test find_max(["supersonic", "apple", "xylopthone", "m", "kiwi", "pear", "Eagle", "xylophone"]) == "supersonic"
    @test find_max(["efghwezip"]) == "efghwezip"
    @test find_max(["applle"]) == "applle"
    @test find_max(["HXs9s1", "HhRQ35", "HhRQ35h", "gcbbccaBFWztts67", "75XPBFq19", "HSSbsh"]) == "gcbbccaBFWztts67"
    @test find_max(["supersonic", "apple", "xylopthone", "epear", "grape", "m", "kiwi", "pear", "gxylophoneerape"]) == "gxylophoneerape"
    @test find_max(["cat", "act", "tac", "catcb", "cat"]) == "catcb"
    @test find_max(["chery", "efghwxyzip", "cbca"]) == "efghwxyzip"
    @test find_max(["ijklnmn", "efghwxyzip", "cbca", "efghwxyzip"]) == "efghwxyzip"
    @test find_max(["l", "elderberry", "fig", "grape", "cherry", "cherry", "banana"]) == "elderberry"
    @test find_max(["xy", "ikjklmn", "efghwxyzip", "ijklmn"]) == "efghwxyzip"
    @test find_max(["jimjlk", "jimjlklmn"]) == "jimjlklmn"
    @test find_max(["fg", "ikjklmn", "efghwxyzip", "ijklmn"]) == "efghwxyzip"
    @test find_max(["banana", "l", "elderberry", "fig", "grape", "cherry", "elderberry"]) == "elderberry"
    @test find_max(["HXs9s1", "HhRQ35", "gcbbccaBFWztts67", "75XPBFq19", "HSSbsh"]) == "gcbbccaBFWztts67"
    @test find_max(["applle", "y", "banana", "cherry", "l", "banaapplena", "elderberry", "fig", "pgrape"]) == "banaapplena"
    @test find_max(["supefgphipersonic", "apple", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "kiwi"]) == "supefgphipersonic"
    @test find_max(["elderberryEEaglcbe", "Echehrry", "EEagle", "eAgLe", "elderberryEEaglcbe"]) == "elderberryEEaglcbe"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone", "grape", "z", "xylophone", "ccff"]) == "supersonic"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "peear", "m", "kiwi", "pear", "xylophone", "grape", "xylophone", "grape"]) == "supersonic"
    @test find_max(["supersonic", "ae", "orange", "grape", "kiwi", "orangchehrrye", "pear"]) == "orangchehrrye"
    @test find_max(["apple", "banana", "cherry", "l", "fig", "grape", "cherry"]) == "cherry"
    @test find_max(["hijklmnop", "wcbca", "wcbcaxyz", "wcbcaxyz", "wcbca"]) == "hijklmnop"
    @test find_max(["apple", "banana", "cherry", "l", "elderberry", "fifg", "grape", "l"]) == "elderberry"
    @test find_max(["ff", "", ""]) == "ff"
    @test find_max(["dwate", "saaddzzupersonic", "mm", "kiwi", "t", "xylophone"]) == "saaddzzupersonic"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "peHXs9s1ear", "kiwi", "pear", "xylophone", "grape", "xylopthone", "xylophone", "qrsutuv"]) == "peHXs9s1ear"
    @test find_max(["applle", "banana", "cherry", "l", "elderberry", "l", "grape", "cherry"]) == "elderberry"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone", "grape", "xylophone", "apple", "xylophone"]) == "supersonic"
    @test find_max(["supersonic", "apple", "orange", "qrsutuv", "ap", "banana", "kiwi", "pear", "orange"]) == "supersonic"
    @test find_max(["supersonic", "apple", "xylopthone", "epear", "grape", "m", "kiwi", "wyx", "pear", "grape"]) == "supersonic"
    @test find_max(["appllle", "y", "banana", "cherry", "l", "elderberry", "fig", "elderberry"]) == "elderberry"
    @test find_max(["iHaTethis", "apple", "banana", "cherry", "elderberry", "fig", "grape", "dwate", "iHaTethis"]) == "iHaTethis"
    @test find_max(["datev", "v", "hijklmnop", "qrstuv", "wxyz", "hijklmnop"]) == "hijklmnop"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "kiwi", "supersonic", "kiwi"]) == "supersonic"
    @test find_max(["abcdgefg", "x", "", "hijklmnop", "qrstuv", "wxyz"]) == "hijklmnop"
    @test find_max(["l", "elderberry", "fig", "grape", "nbanana", "cherry", "cherry", "banana"]) == "elderberry"
    @test find_max(["abcdefg", "banaapplena", "qrstuv", "wcbcaxyz"]) == "abcdefg"
    @test find_max(["elderberryfigEEaglcbe", "Echehrry", "EEagle", "eAgLe", "elderberryEEaglcbe"]) == "elderberryfigEEaglcbe"
    @test find_max(["EEaglcbe", "ueAgL", "EE", "EEagle", "eAgLe"]) == "EEaglcbe"
    @test find_max(["hijklmnop", "a", "wcbcaxyz", "wcbcaxyz", "hijklmjnop", "wcbcaxyz", "hijklmnop"]) == "hijklmjnop"
    @test find_max(["appllle", "y", "banana", "cherry", "l", "elderberry", "fig", "elderberry", "banana"]) == "elderberry"
    @test find_max(["EEaglcbe", "EE", "eAgLe"]) == "EEaglcbe"
    @test find_max(["appll", "banana", "cherry", "l", "banaapplena", "yelderberry", "fig", "grape"]) == "banaapplena"
    @test find_max(["supersonic", "apple", "gerape", "xylopthone", "grape", "rgrape", "kiwi", "grape"]) == "supersonic"
    @test find_max(["EEaglcbe", "EE", "eAgLe", "iHaTethis", "EEaglcbe"]) == "iHaTethis"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "cherry", "HSSbsh", "cherry"]) == "75XPBFq19"
    @test find_max(["applle", "banana", "cherry", "l", "elderberry", "fig", "grrape", "cherry", "b"]) == "elderberry"
    @test find_max(["qrstuv", "ijklmn", "efghip", "qrstuv", "ijklmn", "HXs9s1", "ijklmn"]) == "efghip"
    @test find_max(["datev", "v", "hijklmnop", "qrstuv", "gBFWztts67wxyz"]) == "gBFWztts67wxyz"
    @test find_max(["dwate", "saaddzzupersonic", "mm", "kiwi", "t", "h"]) == "saaddzzupersonic"
    @test find_max(["Eagle", "eAgLe", "Eagele", "iHaTethis"]) == "iHaTethis"
    @test find_max(["v", "hijklmnop", "qrstuv", "hijklmnnop", "wxyz"]) == "hijklmnnop"
    @test find_max(["dwate", "saaddzzupersonic", "xylopthone", "m", "pear", "xylophone"]) == "saaddzzupersonic"
    @test find_max(["EEaglcbe", "EE", "grape", "iHaTethis", "EEaglcbe"]) == "iHaTethis"
    @test find_max(["f", "ff"]) == "f"
    @test find_max(["abcdefg", "wcbcaxyz", "qrtuv"]) == "abcdefg"
    @test find_max(["chehrry"]) == "chehrry"
    @test find_max(["qrstuv", "hijklmnop", "qrstuv", "wxyz", "qrstuv"]) == "hijklmnop"
    @test find_max(["q"]) == "q"
    @test find_max(["aaddzz", "injklmn", "qrstuv"]) == "injklmn"
    @test find_max(["cc", "c", "", "", ""]) == "c"
    @test find_max(["iHaTethis", "apple", "banana", "cherry", "date", "ae", "fig", "grape", "dwate", "iHaTethis", "grape"]) == "iHaTethis"
    @test find_max(["applle", "y", "banana", "chey", "l", "elderberry", "fig", "grape", "elderberry"]) == "elderberry"
    @test find_max(["abcdefg", "hijklmnop", "ijklmn", "wcbcaxyz"]) == "hijklmnop"
    @test find_max(["l", "grape", "cherry", "cherry", "banana"]) == "cherry"
    @test find_max(["elderberryEEaglcbe", "Echehrry", "EEagle", "eAgLe"]) == "elderberryEEaglcbe"
    @test find_max(["EE", "eAgLee", "EEaglcbe"]) == "EEaglcbe"
    @test find_max(["applle", "", "banana", "cherry", "l", "banaapplena", "fig", "grape", "banaapplena", "grape"]) == "banaapplena"
    @test find_max(["qrstuvwxyz", ""]) == "qrstuvwxyz"
    @test find_max(["dwate", "cc", "c", ""]) == "dwate"
    @test find_max(["supersonic", "apple", "kiwefghipi", "orange", "grape", "banana", "kiwi", "pear", "xylophone", "kiwi", "supersonic", "kiwi", "pear"]) == "supersonic"
    @test find_max(["supersonic", "apple", "orange", "grape", "a", "banana", "kiwi", "dwate", "ange", "pear", "xylophone", "kiwi"]) == "supersonic"
    @test find_max(["ijklmn", "ijklmn", "ijklmn"]) == "ijklmn"
    @test find_max(["dwate", "saaddzzupersonic", "xylopthone", "m", "pear"]) == "saaddzzupersonic"
    @test find_max(["hijklmnop", "wcbca", "i", "wcbcaxyz"]) == "hijklmnop"
    @test find_max(["supersonic", "apple", "orange", "grape", "banana", "kiwi", "r", "xylophone", "kiwi", "supersonic", "supersonic"]) == "supersonic"
    @test find_max(["gcbbccaBFWztts67", "act", "tac", "catcb", "cat", "act", "tac"]) == "gcbbccaBFWztts67"
    @test find_max(["q", "q"]) == "q"
    @test find_max(["apple", "xylopthone", "m", "gBFWztts67", "xylophone"]) == "gBFWztts67"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "HSSbzyxsh", "HXs9s1Q", "gBFWztts67"]) == "75XPBFq19"
    @test find_max(["gBFWztts67wxyz", "saaddzzupersonic", "xylopthone", "m", "pear"]) == "gBFWztts67wxyz"
    @test find_max(["abcdefg", "hijklmnop", "qrstuvwxyz", "wxyz", "abcdefg", "jimjllklmn"]) == "qrstuvwxyz"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "xylophoone", "pear", "xylophone", "grape", "zz", "xylophone", "supersonic"]) == "supersonic"
    @test find_max(["y", "banana", "cherry", "l", "banaapplena", "elderberry", "fig", "grape"]) == "banaapplena"
    @test find_max(["supersonic", "ae", "orange", "grape", "kiwi", "pear"]) == "supersonic"
    @test find_max(["hijklmnop", "wcbcaxyz", "hijklmjnop", "wcbcaxyz", "hijklmnop"]) == "hijklmjnop"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "HXs9s1Q", "HXs9s1Q", "gBFWztts67", "HXs9s1Q", "HXs9s1Q", "gBFWztts67"]) == "75XPBFq19"
    @test find_max(["appllle", "banana", "cherry", "l", "elderberry", "elderberry", "banana"]) == "elderberry"
    @test find_max(["qrstuv", "ijkl", "efghip", "ijklmn"]) == "efghip"
    @test find_max(["hijklmnop", "a", "wcbcaxyz", "wcbcaxyz", "hijklmjnop", "wcbcaxyz", "hijklmnop", "hijklmjnop"]) == "hijklmjnop"
    @test find_max(["dwate", "saaddzzupersonic", "mmjijlklmn", "kiwi", "t", "h"]) == "saaddzzupersonic"
    @test find_max(["jijlklmln", "jijlklmn"]) == "jijlklmln"
    @test find_max(["cat", "act", "tac", "catcb", "cat", "cat"]) == "catcb"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "tac", "HXs9s1Q", "qrtuv", "HXs9s1Q", "gBFWztts67", "HXs9s1Q"]) == "75XPBFq19"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone", "grape", "xylophone", "grape"]) == "supersonic"
    @test find_max(["supersonic", "EEaglcbee", "xylopthone", "grape", "m", "kiwi", "xylophoone", "pear", "xylophone", "grape", "z", "xylophone", "supersonic"]) == "supersonic"
    @test find_max(["EEaglcbe", "hijklkmnop", "grape", "iHaTethis", "EEaglcherrycbe"]) == "EEaglcherrycbe"
    @test find_max(["wcbcaxyz", "banana", "HhRQ35fg", "cherry", "l", "elderberry", "kiwefghipifig", "fg", "grape"]) == "HhRQ35fg"
    @test find_max(["dasaaddzzupersonictev", "v", "hijklmnop", "qrstuv", "HSSbzyxsh", "wxyz"]) == "dasaaddzzupersonictev"
    @test find_max(["jimjlk", "elderberryEEaglcbe"]) == "elderberryEEaglcbe"
    @test find_max(["appllle", "y", "banana", "rry", "l", "elderberry", "fig", "elderberry", "banana"]) == "elderberry"
    @test find_max(["ff", "y", "", "", ""]) == "ff"
    @test find_max(["ijklmmn", "efghwxyezip", "immn", "efghwxyzip"]) == "efghwxyezip"
    @test find_max(["applle", "y", "banana", "cherry", "l", "elderberry", "fig", "grape", "elderberry", "elderberry"]) == "elderberry"
    @test find_max(["EEaglcbe", "EE", "EEagl", "eAgLe", "iHaTethis"]) == "iHaTethis"
    @test find_max(["xy", "icbajklmn", "yx", "zyx", "xy"]) == "icbajklmn"
    @test find_max(["applle", "y", "qrstuvl", "banana", "cherry", "l", "banaapplena", "fig", "rgrape"]) == "qrstuvl"
    @test find_max(["supersonic", "apple", "kiwefghipi", "orange", "grape", "banana", "kiwi", "pear", "kiwi", "supersonic", "kiwi", "pear"]) == "supersonic"
    @test find_max(["chery", "efghwxyzip", "cherhy", "cbca"]) == "efghwxyzip"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "HXs9s1Q", "gBFWztts67"]) == "75XPBFq19"
    @test find_max(["apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "elderberry"]) == "elderberry"
    @test find_max(["grrape", "xylopthone", "m", "pear", "xylophone", "m"]) == "xylopthone"
    @test find_max(["supersonic", "apple", "grhijklmjnope", "orange", "grape", "kiwi", "pear", "xylophone", "grape"]) == "grhijklmjnope"
    @test find_max(["ijklnmn", "cbca"]) == "ijklnmn"
    @test find_max(["hchehr"]) == "hchehr"
    @test find_max(["EEaglcbe", "EErgrape", "EE", "eAgLe"]) == "EEaglcbe"
    @test find_max(["hijklmnop", "qrstuvwxyz", "wxyz", "nbanana", "hiEEagljklmnop", "hijklmnop"]) == "hiEEagljklmnop"
    @test find_max(["lijklmn", "abcdefg", "hijklmnop", "ijklmn", "wcbcaxyz"]) == "hijklmnop"
    @test find_max(["appllgcbbccaBFWztts67e", "y", "banana", "cherry", "l", "banaapplena", "elderberry", "fig", "grape"]) == "appllgcbbccaBFWztts67e"
    @test find_max(["gcbbccaBFWztts67", "tac", "catcb", "cat", "act", "tac"]) == "gcbbccaBFWztts67"
    @test find_max(["grrape", "xylopthone", "m", "pear", "xylophone", "m", "m"]) == "xylopthone"
    @test find_max(["hijklmnop", "qrstuvwxyz", "wxyz", "ywxyz", "nbanana", "hiEEagljklmnop", "hijklmnop"]) == "hiEEagljklmnop"
    @test find_max(["supersonic", "apple", "gerape", "xylopthone", "grape", "rgrape", "kiwi", "mm", "grape"]) == "supersonic"
    @test find_max(["supersonic", "apple", "xylopthone", "m", "kiwi", "pear", "xylophone", "m"]) == "supersonic"
    @test find_max(["dwate", "saaddzzupersonic", "xylopthone", "pea", "m", "pear", "m"]) == "saaddzzupersonic"
    @test find_max(["supersonic", "apple", "gerape", "xylopthone", "epear", "m", "kiwi", "pear", "grape"]) == "supersonic"
    @test find_max(["ff", "y", "", "banana", ""]) == "banana"
    @test find_max(["dwate", "ccc", "c", ""]) == "dwate"
    @test find_max(["supersonic", "apple", "gerape", "xylopthone", "grape", "rgrape", "kiwi", "grape", "grape", "supersonic"]) == "supersonic"
    @test find_max(["iHaTethis", "iHaTethiis", "apple", "banana", "cherry", "date", "elderberry", "fig", "grape", "dwate", "iHaTethis"]) == "iHaTethiis"
    @test find_max(["ijklmmn", "efghwxyezip", "immn", "efghwxyzip", "ijklmmn"]) == "efghwxyezip"
    @test find_max(["dwaxylophoneete", "saaddzzupersonic", "xylopthone", "m", "pear", "xylophone", "xylopthone"]) == "dwaxylophoneete"
    @test find_max(["qrsutuv", "aaddzz", "qrstuv", "ijklmn", "efghip", "cba", "qrstuv", "cba"]) == "efghip"
    @test find_max(["abcdgefg", "eAgLe", "hijklmnop", "qrstuv", "wxyz", "eAgLe"]) == "hijklmnop"
    @test find_max(["supersonic", "apple", "grhijklmjnope", "orange", "grape", "pear", "xylophone", "grape"]) == "grhijklmjnope"
    @test find_max(["hchehr", "hchehr"]) == "hchehr"
    @test find_max(["qrstuv", "ijklmn", "efghip", "qrstuv", "HXs9s1", "ijklmn"]) == "efghip"
    @test find_max(["wcbcaxyz", "banana", "cherry", "grappe", "l", "fig", "fg", "grape", "grappe"]) == "wcbcaxyz"
    @test find_max(["abcdefg", "ijklmn", "wcbcaxyz"]) == "abcdefg"
    @test find_max(["aaddzz", "qrstuv", "ijklmn", "cb", "efghip", "cba", "cb"]) == "efghip"
    @test find_max(["dwaefghwxyezipte", "dwate", "datev", "c", ""]) == "dwaefghwxyezipte"
    @test find_max(["apple", "n", "cherry", "date", "elderberry", "fig", "grape"]) == "elderberry"
    @test find_max(["abcdefg", "hijklmnop", "qrstuv", "akiwibcdefg", "wcbcaxyz"]) == "akiwibcdefg"
    @test find_max(["supersonic", "apple", "xylopthone", "m", "kiwi", "pear", "xylophone", "m", "kiwi"]) == "supersonic"
    @test find_max(["iHaTethis", "apple", "banana", "cherry", "date", "ae", "fig", "grape", "dwate", "iHaTethefghwxyezipis", "grape"]) == "iHaTethefghwxyezipis"
    @test find_max(["abcdefg", "hijklmnop", "abcdem", "wxyz", "qrstuv"]) == "hijklmnop"
    @test find_max(["supersonic", "apple", "orange", "grape", "a", "banana", "kiwi", "dwate", "ange", "pear", "xylophone"]) == "supersonic"
    @test find_max(["hijklmnop", "qrstuvwxyz", "wxyz", "nbanana", "hiEEagljklmnop", "hijklmnop", "wxyz"]) == "hiEEagljklmnop"
    @test find_max(["HhRQ35", "75XPBFq19", "HXs9s1Q", "HXs9s1Q", "gBFWztts67", "HXs9s1Q", "HXs9s1Q", "gBFWztts67"]) == "75XPBFq19"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "wcbcawxyz", "HXs9s1Q", "gBFWztts67"]) == "75XPBFq19"
    @test find_max(["mhijklmnop", "wcbbcaxyz", "jijlklmn", "wcbcaxyz"]) == "mhijklmnop"
    @test find_max(["dasaaddzzupersonictev", "v", "hijklmnop", "qrstuv", "HSSbzyxsh"]) == "dasaaddzzupersonictev"
    @test find_max(["dwate", "c", "Eagle"]) == "Eagle"
    @test find_max(["applle", "y", "banana", "cherry", "l", "elderberry", "fig", "grapse", "elderberry", "elderberry"]) == "elderberry"
    @test find_max(["apple", "xylopthone", "m", "gBFgcbbccaBFWztts67Wztts67", "xylophone"]) == "gBFgcbbccaBFWztts67Wztts67"
    @test find_max(["cc", "c", "75XPBFq19", ""]) == "75XPBFq19"
    @test find_max(["injklmn", "qrstuv", "injklmn"]) == "injklmn"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "peHXs9s1ear", "kiwi", "pear", "bananaar", "xylophone", "grape", "xylopthone", "xylophone", "qrsutuv"]) == "peHXs9s1ear"
    @test find_max(["supersonic", "iHaTethiis", "orange", "grape", "banana", "kiwi", "pear", "xylophone"]) == "supersonic"
    @test find_max(["applle", "y", "chey", "l", "elderberry", "fig", "grape", "elderberry"]) == "elderberry"
    @test find_max(["applle", "y", "nbanana", "cherry", "l", "elderberry", "fig", "grape", "elderberry", "elderberry"]) == "elderberry"
    @test find_max(["HhRQ35", "gBFWztts67", "7P5XPBFq19", "75X1PBFq19", "75XPBFq19", "HXs9s1Q", "HSSbsh", "HSSbsh", "75X1PBFq19"]) == "75X1PBFq19"
    @test find_max(["supersonic", "iHaTethiis", "orange", "grape", "banana", "kiwi", "pear", "xlylophone"]) == "supersonic"
    @test find_max(["supersonic", "apple", "orange", "qrsutuv", "ap", "banana", "kiwi", "pear", "orange", "qrsutuv"]) == "supersonic"
    @test find_max(["", "act", "tac", "cat", "cat"]) == "act"
    @test find_max(["iHaTethis", "apple", "banana", "cherry", "elderberry", "fig", "grape", "dwate", "bananaar"]) == "iHaTethis"
    @test find_max(["supersonic", "apple", "gerape", "HhRQ35", "iHaTethis", "m", "kiwi", "pear", "grape"]) == "supersonic"
    @test find_max(["aaddzz", "hijklkmnop", "qrstuv", "ijklmn", "cb", "efghip", "cba", "cbakiwibcdefg"]) == "cbakiwibcdefg"
    @test find_max(["abcdgefg", "eAgLe", "hijklmnop", "qrstuv", "wcbcaxyzyz", "eAgLe"]) == "hijklmnop"
    @test find_max(["iHaTethis", "apple", "banana", "cherry", "elderberry", "fig", "grape", "dbwate", "dwate", "bananaar"]) == "iHaTethis"
    @test find_max(["HhRQ35", "zz", "gBFWztts67", "75XPBFq19", "wcbcawxyz", "HXs9s1Q", "gBFWztts67"]) == "75XPBFq19"
    @test find_max(["aaddzz", "ijklmn"]) == "ijklmn"
    @test find_max(["y", "banana", "cherry", "rry", "yelderberry", "banaapplena", "elderberry", "fig", "grjHIjpape", "banaapplena"]) == "grjHIjpape"
    @test find_max(["abcdefg", "d", "hijklmnop", "abcdem", "wxyz", "qrstuv"]) == "hijklmnop"
    @test find_max(["catcb", "supersonic", "apple", "aaddzz", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone", "grape", "xylophone", "apple", "xylophone"]) == "supersonic"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "m", "kiwi", "xylophoone", "pear", "xylophone", "grape", "z", "xylophone"]) == "supersonic"
    @test find_max(["abcdefg", "d", "hijklmnop", "abcdem", "wxyz", "qrstuv", "abcdem"]) == "hijklmnop"
    @test find_max(["mhijklmnop", "wcbbcaxyz", "jijlklmn", "wcbcaxyz", "jijlklmn"]) == "mhijklmnop"
    @test find_max(["supersonic", "orange", "grape", "banana", "kiwi", "pear", "xylophone"]) == "supersonic"
    @test find_max(["catcb", "supersonic", "apple", "aaddzz", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone", "appapearle", "grape", "xylophone", "appple", "xylophone", "appple"]) == "supersonic"
    @test find_max(["aaddzz", "f", "d"]) == "aaddzz"
    @test find_max(["apear", "c", "75XPBFq19", "", "", ""]) == "75XPBFq19"
    @test find_max(["ikjklmn", "banana", "cherry", "l", "banaapplena", "elderberry", "fig", "grape"]) == "banaapplena"
    @test find_max(["apple", "kiwefghipi", "orange", "grape", "banana", "kiwi", "kiwefghipi", "pear", "orcheyange", "kiwi", "supersonic", "kiwi", "pear"]) == "orcheyange"
    @test find_max(["c"]) == "c"
    @test find_max(["abcdefg", "hijklmnop", "hijklkmnop", "qrstuvwxyz", "wxyz", "abcdefg", "wxyz"]) == "qrstuvwxyz"
    @test find_max(["elderberryEEaglcbe", "Echehrry", "EEagle", "eAgLe", "elderberryEEaglcbe", "elderberryEEaglcbe"]) == "elderberryEEaglcbe"
    @test find_max(["applle", "banana", "cherry", "l", "banaapplena", "elderberry", "fig", "grape", "l"]) == "banaapplena"
    @test find_max(["saaaddzzupersonic", "xylophonee", "apple", "xylopthone", "m", "pear", "saaaddzzupersonic"]) == "saaaddzzupersonic"
    @test find_max(["supersonic", "kiw", "apple", "orange", "grape", "peqrstuvar", "banana", "pear", "xylophone"]) == "peqrstuvar"
    @test find_max(["hijklmnop", "HhRQ35h", "hijklmjnop", "wcbcaxyz", "hijklmnop", "wcbcaxyz"]) == "hijklmjnop"
    @test find_max(["apple", "gerape", "xylopthone", "epear", "grape", "m", "kiwi", "actm", "pear", "grape", "pear"]) == "xylopthone"
    @test find_max(["supersonic", "apple", "gerape", "xylopthone", "peacheyrr", "pearr", "grape", "m", "pgrhijklmjnopeear", "kiwi", "pear", "grape"]) == "pgrhijklmjnopeear"
    @test find_max(["HhRQ35", "gBFWztts67", "75XPBFq19", "tac", "HXs9s1Q", "HXs9s1Q", "gBFWztts67"]) == "75XPBFq19"
    @test find_max(["dwate", "c", "Egagle", "Eagle"]) == "Eagle"
    @test find_max(["applle", "", "banana", "cherry", "l", "banaapplena", "fiig", "grape", "banaapplena", "grape", "banana"]) == "banaapplena"
    @test find_max(["iHaTethis", "apple", "banana", "cherry", "elderberry", "fig", "grape", "w", "iHaTethis"]) == "iHaTethis"
    @test find_max(["gcbbccaBFWztts67", "act", "tac", "catcb", "cat", "act", "tac", "gcbbccaBFWztts67"]) == "gcbbccaBFWztts67"
    @test find_max(["HhRQ35", "75XPBFq19", "HXs9s1Q", "HXs9s1Q", "gBFWztts67", "HXs9ss1Q", "HXs9s1Q", "gBFWztts67"]) == "75XPBFq19"
    @test find_max(["saaddzzupersonic", "oxylopthone", "m", "kwi", "p", "xylophone"]) == "saaddzzupersonic"
    @test find_max(["applle", "y", "banana", "cherry", "l", "dwate", "elderberry", "fig", "grape"]) == "elderberry"
    @test find_max(["saaddzzupersonic", "apple", "x", "xylopthone", "m", "kiwi", "pear", "xylophone", "xylophone"]) == "saaddzzupersonic"
    @test find_max(["apple", "xylopthone", "m", "xe", "gBFWztts67", "xylophone", "xe", "m", "m"]) == "gBFWztts67"
    @test find_max(["supersonic", "apple", "kiwefghipi", "orange", "grape", "banana", "kiwi", "pear", "kiwi", "supersonic", "kiwi", "pear", "grape"]) == "supersonic"
    @test find_max(["supersonic", "ae", "orange", "grape", "kiwi", "orangchehrrye", "c"]) == "orangchehrrye"
    @test find_max(["applle", "y", "chey", "l", "elderberry", "fig", "grape", "elderberry", "l"]) == "elderberry"
    @test find_max(["applle", "banana", "cherry", "ll", "fig", "grape"]) == "cherry"
    @test find_max(["ijklnmn", "efghwxyzip", "cbbcca", "cbccca"]) == "efghwxyzip"
    @test find_max(["gBFkiwtts67", "apple", "m", "gBFWztts67", "appple"]) == "gBFkiwtts67"
    @test find_max(["supersonic", "apple", "xylophonechehrry", "xylopthone", "grape", "m", "kiwi", "pear", "xylophone", "grape", "xylophone"]) == "xylophonechehrry"
    @test find_max(["dwatwe", "ccc", "c", "", "ccc"]) == "dwatwe"
    @test find_max(["applleEEagl", "banana", "cherry", "l", "elderberry", "fig", "grrape", "cherry", "b"]) == "applleEEagl"
    @test find_max(["ijklnmn", "efghwxyzip", "ijklnmn"]) == "efghwxyzip"
    @test find_max(["wcbcaxyzyz", "applle", "chey", "l", "elderberry", "fig", "grape", "elderberry", "l"]) == "wcbcaxyzyz"
    @test find_max(["Eagle", "jijlklmlneAgLe", "eAgLe", "u", "iHaTethis", "Eagle"]) == "jijlklmlneAgLe"
    @test find_max(["supersonic", "apple", "xylopthone", "epear", "grape", "m", "kiwi", "wyx", "pear", "grape", "pear", "supersonic"]) == "supersonic"
    @test find_max(["ijklmmn", "ijklmn", "ijklmn"]) == "ijklmmn"
    @test find_max(["", "ijklmn"]) == "ijklmn"
    @test find_max(["v", "hijklmnop", "qrstuv", "grhijklmjnope"]) == "grhijklmjnope"
    @test find_max(["dwatell", "saaddzzupersonic", "mm", "b", "t", "h"]) == "saaddzzupersonic"
    @test find_max(["qrtuv", "orange", "grape", "banana", "kiwi", "pear", "xylophone"]) == "xylophone"
    @test find_max(["wcbcaxyz", "banana", "mhijklmnop", "cherry", "l", "elderberry", "kiwefghipifig", "fg", "grape", "cherry", "fg"]) == "mhijklmnop"
    @test find_max(["catcb", "supersonic", "apple", "xylopthone", "y", "m", "kiwi", "pear", "xylophone", "grape", "xylophone", "apple", "xylophone"]) == "supersonic"
    @test find_max(["qrstuv", "ijklmn", "efghip", "qrstuv", "ijklmn", "eghip", "HXs9s1", "ijklmn"]) == "efghip"
    @test find_max(["abcdefg", "abcdem", "hijklmnop", "qrstuv", "wcbcaxyz"]) == "hijklmnop"
    @test find_max(["wcbcaxyz", "banana", "cherry", "l", "elderberry", "fg", "grape"]) == "wcbcaxyz"
    @test find_max(["abcdefg", "hijklmnop", "abcdefg", "wxangez", "qrstuv", "abcdefg"]) == "hijklmnop"
    @test find_max(["supersonic", "apple", "orange", "grape", "kiwi", "r", "kiwi", "supersonic", "supersonic", "supersonic", "supersonic", "apple"]) == "supersonic"
    @test find_max(["EE", "eAgLEageleee", "eAgLee", "EEaglcbe"]) == "EEaglcbe"
    @test find_max(["EEaglcbe", "ueAgL", "EEagle", "eAgLe"]) == "EEaglcbe"
    @test find_max(["hijklmnop", "a", "wcbcaxyz", "wcbcaxyz", "wcbcaxyz", "hijklmnop", "hijklmnop"]) == "hijklmnop"
    @test find_max(["oxylopthone", "hijklmnop", "abcdem", "wxyz", "qrstuv"]) == "hijklmnop"
    @test find_max(["apple", "xylopthone", "m", "xe", "gBFWztts67", "xylophone", "xe", "m", "m", "xe"]) == "gBFWztts67"
    @test find_max(["ijklmmn", "efghwxyezip", "efghwxzyezip", "efghwxyzip"]) == "efghwxyezip"
    @test find_max(["qrstuvwxyz", "yx"]) == "qrstuvwxyz"
    @test find_max(["supersonic", "apple", "xylopthone", "grape", "peHXs9s1ear", "kiwi", "pear", "grape", "xylopthone", "xylophone", "qrsutuv"]) == "peHXs9s1ear"
    @test find_max(["hijklmnnop"]) == "hijklmnnop"
    @test find_max(["oxylopthone", "hijklmnop", "abcdem", "hmijklmnop", "wxyz", "qrstuv"]) == "hijklmnop"
    @test find_max(["hijklmnnop", "c", "Egagle", "Eagle"]) == "hijklmnnop"
end
